### ISSUE TITLE
Inconsistency display of Required Fields for each API in Banking Hub

### ISSUE THREAD

**Issue by tsegurajimen** [Fiserv/Support#100]
Hi @acho-fiserv and Team,

We just noticed that there is an inconsistency between the required fields in our APIs and the ones that are display as required in Dev Portal UI.

Please find attached an example of the Add Account Hold Request of the Account Hold Service:

https://dev-developer.fiserv.com/product/BankingHub/api/?type=post&path=/accountHolds

AcctHoldInfo is a required element of the request:

![image](https://user-images.githubusercontent.com/81706748/155567543-ac0ec914-6053-4705-ad8e-990faf46cb2f.png)
 
But in the portal is not displayed as required:

![image](https://user-images.githubusercontent.com/81706748/155567625-2d49084d-9581-4413-9eb8-a617bf7d4491.png)

Then inside of AcctHoldInfo, we have AcctRef, which is not required:

![image](https://user-images.githubusercontent.com/81706748/155567756-c35ea49a-b93d-4fb8-b1fc-c4c8e01221d3.png)

But The portal displays is as required:

![image](https://user-images.githubusercontent.com/81706748/155567832-2df42b59-1f30-4c21-a094-e45cb403c355.png)

Finally inside of AcctRef, AcctKeys object is required:

![image](https://user-images.githubusercontent.com/81706748/155567911-f57e0031-26ce-427c-ae84-10c89c61498c.png)

But the portal doesn't reflect is as required:

![image](https://user-images.githubusercontent.com/81706748/155567955-102f2039-33cc-4d96-8049-16db363dc032.png)

Please let us know if you need any additional detail.

Thanks in advance for your help.

Regards,

cc:

@rahravin @fiservakshay @bobburghardt

**Comment by TaniaSarkar89** [comment]
Opened JIRA issue: https://firstdatateam.atlassian.net/browse/PORT-3606

**Comment by TaniaSarkar89** [comment]
Hi @tsegurajimen this issue has been addressed. Could you please validate it from your end.

Cc: @rajeshb15

**Comment by rajeshb15** [comment]
@TaniaSarkar89 @tsegurajimen 
Please validate in DEV env and changes are up and working as expected.
<img width="1638" alt="image" src="https://user-images.githubusercontent.com/80118847/159939728-f30b147a-f6e3-4c25-b77d-01cc77298a71.png">
