### ISSUE TITLE
Implementation of Account Type Specifications Link inside of Banking Hub APIs

### ISSUE THREAD

**Issue by tsegurajimen** [Fiserv/Support#101]
Hi @acho-fiserv and Team,

As you know, due to the complexity of our APIs, there are some cases where we have different specification (Request/Response) versions of the same endpoint, because of the Account Type is different, so it changes the way that the API works. So that, we need to have the ability to display those different versions of the same API in the same place.

For example in Account Service we have Account Add POST/accounts, the one we are currently displaying in the portal is CDA (Certificate of Deposit) based, but there are four more specifications for the same API for Demand Deposit Account (DDA), Savings Deposit Account (SDA) and Loan Account (LOAN) that needs to be displayed as well. (Is important that all of them are defined using the same API version 11.0.0 that we display as latest)

We were looking for the best way of how to display them and we think that having them as links and when you click on the link, the Request/Response Schemas and Default/Samples can be refreshed according the Account Type selected.

![image](https://user-images.githubusercontent.com/81706748/155585548-d96a3a81-f0aa-4b54-8327-4b0c977b2baa.png)

Please let us know if you have a different idea of how we could handle it or if need any additional detail regarding it.

Thanks in advance!

cc:
@rahravin @fiservakshay @bobburghardt

**Comment by tsegurajimen** [comment]
This ticket is not needed now due to the team will handle this constraint in a different way. Thanks!

**Comment by tsegurajimen** [comment]
Hi @acho-fiserv sure, I just added it to S07.

Thanks a lot!

**Comment by tsegurajimen** [comment]
Now we are handling this ticket internally according the core agnostic specifications approach per endpoint, but hope you could take a look to see how we could represent differences between Account Types in a nice way in our Request/Response schemas.

**Comment by TaniaSarkar89** [comment]
This ticket would be taken care as part of the JIRA ticket: https://firstdatateam.atlassian.net/browse/PORT-4302

**Comment by sfiserv** [comment]
This is an on going implementation so moving this issue to milestone13

**Comment by sfiserv** [comment]
The Jira ticket for this issue has been completed hence closing this issue
https://firstdatateam.atlassian.net/browse/PORT-4302
