### ISSUE TITLE
Commented Content Breaks Markdown

### ISSUE THREAD

**Issue by wwfiserv** [Fiserv/Support#104]
# Reporting new issue for Commerce Hub

**Page**
https://stage-developer.fiserv.com/product/CommerceHub/docs/?path=docs/Resources/Guides/Payment-Sources/Source-Type.md
https://dev-developer.fiserv.com/product/CommerceHub/docs/?path=docs/Resources/Guides/Payment-Sources/Source-Type.md
https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Resources/Guides/Payment-Sources/Source-Type.md

**Describe the bug**
I have noticed in several pages after the new tab implementation that commented sections are breaking the Markdown. This needs to be fixed before being pushed to Main as we have multiple files with commented content that is not production ready.

**To Reproduce**
In the table you will notice a section commented;

`| [SamsungPay]<!--(?path=docs/Online-Mobile-Digital/Wallets-AltPayments/Samsung-Pay/Samsung-Pay.md)--> |`

everything after this is not showing in Stage, and Dev is not rendered correctly after the first table row.

**Expected behavior**
Commented sections should not display but remaining content should display. Do we need to look into modifying commented content to `<!---` with three dashes instead of two, this was a fix when using Stolight?

**Comment by wwfiserv** [comment]
@acho-fiserv the push of the update has made our content on Main unusable

**Comment by wwfiserv** [comment]
Additional page examples found once pushed to main
https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Getting-Started/Getting-Started-Online.md
https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Resources/API-Documents/Use-Our-APIs.md
https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Resources/Master-Data/Device-Fingerprint.md
https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Resources/Master-Data/Gateway-Response.md

https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Resources/Master-Data/Transaction-Details.md - Getting a 404 in all 3 environments

**Comment by TaniaSarkar89** [comment]
Opened JIRA ticket for this issue: https://firstdatateam.atlassian.net/browse/PORT-3707

**Comment by OZ-FS** [comment]
Started working on the issue.

**Comment by OZ-FS** [comment]
The issue is in code review.

**Comment by OZ-FS** [comment]
The issue was tested and closed.
