### ISSUE TITLE
Example Key is not displaying when value is "0" or empty string

### ISSUE THREAD

**Issue by palanikumarfiserv** [Fiserv/Support#105]
Example Key is not displaying when value is "0" or empty string

**Page**
FirstVision APAC >> API Explorer >> Customer Management >> List Customer Cards , List Customer Accounts

**Describe the bug**
Example Key not displaying when the value is "0" or "" empty string

This defect is for all the apis having example value as "0" or "" empty string

**To Reproduce**
FirstVision APAC >> API Explorer >> Customer Management >> List Customer Cards , List Customer Accounts

**Expected behavior**
example: 0  & example: ""

**Screenshots**
![image](https://user-images.githubusercontent.com/91948280/157178915-376a65d4-3dab-4cfc-95f8-1c6b17776318.png)

**Comment by TaniaSarkar89** [comment]
Opened JIRA ticket for this issue: https://firstdatateam.atlassian.net/browse/PORT-3708

**Comment by TaniaSarkar89** [comment]
Hi @AwaneeshSrivastava  @palanikumarfiserv  the example provided in the ticket is showing the correct value for the business unit. Could you please provide an example where this is still an issue.
![image](https://user-images.githubusercontent.com/74629095/159951481-0f566698-93e7-4d64-a1b3-fc4521dc1bf3.png)

**Comment by palanikumarfiserv** [comment]
Issue resolved
