### ISSUE TITLE
InTouch Credit Union Banking app does not load/open

### ISSUE THREAD

**Issue by KarlaGM24** [Fiserv/Support#106]
# Reporting new issue for [InTouch Credit Union Banking app] (Tenant/Product)

**Page**
Open InTouch Credit Union app > Observe

**Describe the bug**
 InTouch Credit Union Banking app does not load/open

**To Reproduce**
Open InTouch Credit Union app > Observe

**Expected behavior**
User should able see app content after launch

**Screenshots**
Screenshot attached

**Smartphone (please complete the following information):**
 App Name: InTouch Credit Union Banking
Device: Galaxy S22+ and Galaxy S22 Ultra
IOS: 12
App Version: 21.2.70
Frequency: Always

@Fiserv/fiserv-developer

My name is Karla Galvan and I am a member of the 3rd Party Applications Team with Samsung from the IT Department. We have received several reports from users that are encountering with an issue with the “InTouch Credit Union Banking” application on Samsung devices.
 
We would like to work directly with your Development team to address this issue and continue to build a future relationship for collaboration. Our goal is to establish mutual relationships with 3rd party app vendors and share issues we find, thus helping each other to improve overall user experience. It is our belief that user experience is the main contributing factor to an app’s popularity, therefore, we aim to improve this experience for our customers by raising the standard of quality on application compatibility on our mobile products.
 
I’m sending this information to share our recent findings and we hope there is an opportunity that we could formally introduce ourselves and the team, we are happy to share more details as needed. 

We look forward to hearing from you soon.

Regards, 
Karla Galvan
karla.galvan@sea.samsung.com
![Screenshot_Bank](https://user-images.githubusercontent.com/101291180/157529382-397d5f0a-1669-44a1-894e-a206663350fb.png)

**Comment by bobburghardt** [comment]
Hi Karla,

    Thank you for contacting us regarding this issue.  I will look into who on our mobile applications team are best to contact for the issue at hand, and establishing a future relationship.  I'll use your e-mail to contact you with that information.

Bob

**Comment by KarlaGM24** [comment]
Hello Bob,


Thank you for your reply. As I mentioned before, we received several reports from users that were encountering with the issue "App does not load/Open" on S22 devices.



The reports we received are from several banks. Please see the list of Banks below.



Out of the 13 banks,  2 banks still have the problem

1. Golden 1

2. Associated Bank Mobile




App Name

Previous App version

New App Version

InTouch Credit Union

21.2.70

21.3.30

International harvester credit union Mobiliti

21.2.70

21.3.30

Bank of Colorado

21.2.70

21.3.30

CSB Simple Banking

21.2.70

21.3.30

HomeTown Community Banks

21.2.110

21.3.30

Domino Federal Credit Union

21.2.70

21.3.30

Farmers Bank Mobile Banking

21.2.70

21.3.30

Home Federal Bank GI Mobile

21.2.70

21.3.30

Pioneer Bank Mobile app

21.2.70

21.3.30

HomeTrust Mobile Banking

21.2.80

21.3.30

TNBank

21.2.70

21.3.40

Associated Bank Mobile

21.2.70

-

Golden 1 banking

21.2.110

-






We believe this is a critical issue that is impacting a lot to users and we would like to connect with the development team to provide any support/technical information and also have a direct contact from the Research and Development team from Samsung to prevent any issue in the feature with new devices and OS releases.



I look forward to hearing from you and again thank you for your assistant.



Best Regards,
Karla Galvan| Sr. Lead 3rd Party Applications
MQL TX – 3rd Party Applications | Samsung Electronics America
Mobile: 972.207.9708 | ***@***.***

SAMSUNG CONFIDENTIAL This e-mail message and any attachments are only for the use of the intended recipient and may contain information that is legally privileged, confidential or exempt from disclosure under applicable law. If you are not the intended recipient, any disclosure, distribution or other use of this e-mail message or attachments is prohibited. If you have received this e-mail message in error, please delete and notify the sender immediately.

**Comment by bobburghardt** [comment]
Sent Karla an e-mail with our Mobile Application team contact

**Comment by tsegurajimen** [comment]
Closing this ticket on behalf of @bobburghardt
