### ISSUE TITLE
IH Credit Union Mobiliti mobile application Critical Issue - The mobile application does not launch

### ISSUE THREAD

**Issue by KarlaGM24** [Fiserv/Support#107]
# Reporting new issue for IH Credit Union Mobiliti mobile 

**Describe the bug**
IH Credit Union Mobiliti mobile application Critical Issue | The mobile application does not launch

**To Reproduce**
Open IH Credit Union Mobiliti app > Observe the app does not load

**Expected behavior**
User should able see app content after launch

**Screenshots**

**Smartphone (please complete the following information):**
App Name: IH Credit Union Mobiliti
Device: Galaxy S22+ and Galaxy S22 Ultra
App Version: 21.2.70
Frequency: Always

- Subscribe to a Team
    Example:  @Fiserv/fiserv-developer)

-->Hello Developer Team,

My name is Karla Galvan and I am a member of the 3rd Party Applications Team with Samsung from the IT Department. We have received several reports from users that are encountering with an issue with the “IH Credit Union Mobiliti” application on Samsung devices.
 
We would like to work directly with your Development team to address this issue and continue to build a future relationship for collaboration. Our goal is to establish mutual relationships with 3rd party app vendors and share issues we find, thus helping each other to improve overall user experience. It is our belief that user experience is the main contributing factor to an app’s popularity, therefore, we aim to improve this experience for our customers by raising the standard of quality on application compatibility on our mobile products.
 
I’m sending this information to share our recent findings and we hope there is an opportunity that we could formally introduce ourselves and the team, we are happy to share more details as needed. 

We look forward to hearing from you soon.

![S2](https://user-images.githubusercontent.com/101291180/157537459-dc9ba995-090b-4b89-a530-ac2d74ea103d.jpg)

**Comment by acho-fiserv** [comment]
Thanks for reaching out @KarlaGM24 .  We'll have someone reachout to you.  cc:  @tsegurajimen

**Comment by bobburghardt** [comment]
This is related to ticket 106.  Provided contact information to Karla

**Comment by tsegurajimen** [comment]
Closing this ticket on behalf of @bobburghardt
