### ISSUE TITLE
Commerce Hub Tags

### ISSUE THREAD

**Issue by wwfiserv** [Fiserv/Support#111]
# Reporting new issue for Commerce Hub

**Page**
Merchant, Product, Search results

**Describe the bug**
Tags for Commerce Hub include SMB and Banking  and is completely missing Merchant in several places (Merchant Home Page > Apple Pay, Tentant > Features, Search Results, etc.), this needs to be removed. I provided an Excel spreadsheet before launch last year with the proper tags for the features.
 
Search for iframe in and it returns results which tags don’t match their actual feature set.

**Expected behavior**

- Bank and SMB need to be removed from all CH tags.
- If Merchant is a valid tag it should be added.
- Individual articles should have tags specific to the article not general tags from the product. https://firstdatateam.atlassian.net/browse/PORT-1763

**Screenshots**
![example1](https://user-images.githubusercontent.com/75692745/157887625-cbfbeb96-51be-4a7e-824b-e4cc3c4b5115.png)
![example3](https://user-images.githubusercontent.com/75692745/157887654-2948ed98-1eeb-4c6b-9040-ad15d43730b2.png)
![example2](https://user-images.githubusercontent.com/75692745/157887671-d0e8ac18-2e3b-4a8f-baf7-7ee5d21d863e.png)

**Comment by wwfiserv** [comment]
@OZ-FS @acho-fiserv @TaniaSarkar89

**Comment by TaniaSarkar89** [comment]
Opened a JIRA ticket : https://firstdatateam.atlassian.net/browse/PORT-4201

**Comment by acho-fiserv** [comment]
i fixed a bug @wwfiserv !  the tags should look better now.  except the dup with "enterprise" because that's the product tag & the markdown tag showing.

let me know.
