### ISSUE TITLE
Linkout Request

### ISSUE THREAD

**Issue by kcaramat** [Fiserv/Support#113]
I'd like to request our Specifications Portal be added as a link out on the left hand side of the Developer Studio. Let me know if anything additional is needed. Link: https://specs.firstdata.com/specs/kb/login/index_enter/

**Comment by sfiserv** [comment]
@kcaramat would you be able to let us know as under what Solution  type will Specifications Portal belong to? Would it be Merchants or Financial institution. Based on the Specification Portal contents I am assuming it will be 'Merchants'
Please confirm
