### ISSUE TITLE
Discrepancies of Merchant Reporting Portal page w.r.t Markdown file in Reporting

### ISSUE THREAD

**Issue by kongaravinatha** [Fiserv/Support#114]
Reporting new issue for [Merchant Reporting Portal] (Reporting)

**Describe the bug**
All the content from .md file is not rendering on the DevPortal Studio page 

**Page**
Below is the linked page on the DevStudio
https://developer.fiserv.com/product/Reporting/docs/?path=/docs/APIs/api-model.md

Link to the markdown file: 
https://github.com/Fiserv/reporting/blob/develop/docs/APIs/api-model.md

- Subscribe to a Team
https://github.com/Fiserv/reporting
@Fiserv/clientlinex)

**Comment by TaniaSarkar89** [comment]
@kongaravinatha The markdown file [api-model.md](https://github.com/Fiserv/reporting/blob/develop/docs/APIs/api-model.md) has been fixed. Below highlighted issues were addressed to fix the issue:

![image](https://user-images.githubusercontent.com/74629095/158512045-6716452d-310b-4e46-8ff9-d5f8e30ab292.png)

For reference the original file has been renamed to [api-model-orig.md](https://github.com/Fiserv/reporting/blob/develop/docs/APIs/api-model-orig.md) which you would be find in the same folder.

Please validate the same and let us know if you still see any concerns.

**Comment by kongaravinatha** [comment]
@TaniaSarkar89  thanks a lot for fixing this issue
