### ISSUE TITLE
Correlation between Sample Objects/Fields and Request/Response Schema in the API Explorer

### ISSUE THREAD

**Issue by tsegurajimen** [Fiserv/Support#116]
Hi Team,

This time we need your help to replicate the behavior we have in the API Explorer when the user is looking at the Default sample, the objects/fields descriptions are reflected Request/Response Schema in correlation with what is displayed in the Default view. We want the same capability can be available when the user is looking at the additional samples per Core, in our case it will help us to guide the user thru the specific fields that are applicable for each core, while we'll be displaying all cores fields in the Default view for that API.

Below is a mockup of how it should look like:

![image](https://user-images.githubusercontent.com/81706748/159580798-c0fdd884-02c5-4220-835a-ff01d3af43b2.png)

Please let us know if any additional detail is needed.

Thanks in advance!

cc:
@fiservakshay @bobburghardt

**Comment by tsegurajimen** [comment]
Hi @acho-fiserv @TaniaSarkar89 do you have any update on this ticket?

**Comment by sfiserv** [comment]
Created a Jira ticket for Sprint 11.
https://firstdatateam.atlassian.net/browse/PORT-4224
cc: @acho-fiserv

**Comment by sfiserv** [comment]
This issue will be resolved as part of our API explorer page redesigning. The implementation of this will be done in the milestone 12. 
https://firstdatateam.atlassian.net/browse/PORT-4302

**Comment by sfiserv** [comment]
Closing this issue as the ticket has been worked on and completed as part of API re-designing.
https://firstdatateam.atlassian.net/browse/PORT-4302

**Comment by TaniaSarkar89** [comment]
We will continue working on this ticket in the next sprint.

**Comment by TaniaSarkar89** [comment]
Opened tracking ticket for this issue : https://firstdatateam.atlassian.net/browse/PORT-5224

**Comment by sfiserv** [comment]
This fix is in Dev env and ready for client verification.

**Comment by tsegurajimen** [comment]
Hi @TaniaSarkar89 @OZ-FS ,

We still not able to see the right correlation btw sample fields and Rq/Rs Schema, totally different fields are highlighted when you pick them in the Rq/Rs schema panel:

![image](https://user-images.githubusercontent.com/81706748/197248961-d1be0d21-6685-40ab-a50a-ae6799bc206b.png)

 Also there is no correlation when you're in the sample panel, fields are not highlighted at all in the Rq/Rs Schema panel:

![image](https://user-images.githubusercontent.com/81706748/197249342-187cc517-1010-4b23-99d3-31218bab5f91.png)

Can you please check?

Thanks a lot!

**Comment by OZ-FS** [comment]
@tsegurajimen, it's being worked on currently. we are aware!

**Comment by tsegurajimen** [comment]
The correlation between samples and Request/Response fields is now working as expected:
![image](https://user-images.githubusercontent.com/81706748/202003421-79081b73-702f-4835-afce-a9778f9945f9.png)

Thanks a lot team!
