### ISSUE TITLE
Error status 400 from /marketplace/v1/pfac/application/signup endpoint

### ISSUE THREAD

**Issue by dsarateanu28** [Fiserv/Support#117]
Hi. Could you please advice, what should I change, how to fix this issue. I try to make a call to "/marketplace/v1/pfac/application/signup" (https://developer.firstdata.com/marketplace/api/pfac.html#post-application-pfac-signup) with provided code (java) and request from example, and I receive error 400 with message "[{"errorType":"BRS","errorCode":"10105","location":"","errorMessage":"Missing Owner isPrimary data"},{"errorType":"BRS","errorCode":"10119","location":"","errorMessage":"One Owner should be Primary"}]". Could you please advice what should I change or what could be the issue reason. Thank you in advance.

**Comment by acho-fiserv** [comment]
Hi @dsarateanu28 , thanks for reaching out.  are you still having issues?
