### ISSUE TITLE
Label per Core added into each field in Request/Response Schema

### ISSUE THREAD

**Issue by tsegurajimen** [Fiserv/Support#118]
Hi Team,

We need the ability to represent the core differences between some fields in our Request/Response Schemas for all Banking Hub APIs, to show in some way those fields that not apply for all cores; we were thinking on the addition of a label per core into those objects/fields. 

Please find a mockup bellow:  

![image](https://user-images.githubusercontent.com/81706748/159797147-f7d7a145-e9a0-4a07-ab95-f03f569e7d0f.png)

Thanks in advance!

cc:
@bobburghardt @fiservakshay

**Comment by tsegurajimen** [comment]
Hi @acho-fiserv @TaniaSarkar89 do you have any update on this ticket?

**Comment by sfiserv** [comment]
https://firstdatateam.atlassian.net/browse/PORT-4230
@TaniaSarkar89 Created a jira to address this enhancement.

**Comment by TaniaSarkar89** [comment]
This feature would be redundant going forward as our team is re-designing the whole API explorer where cores/examples can be filtered out from the request schema itself. 
This is being worked as part of this ticket: https://firstdatateam.atlassian.net/browse/PORT-4302
Hence closing this ticket.
Thanks!
