### ISSUE TITLE
Limit the vertical height of API description section

### ISSUE THREAD

**Issue by fiservakshay** [Fiserv/Support#119]
Hi Team, 

We have noticed that for some APIs the description section is so long that user cannot see the documentation tabs upfront. User need to scroll down to see the documentation tabs which is important part of the portal. Please see the example of such case in the screenshot below:
![image](https://user-images.githubusercontent.com/81968767/159915947-67dcec99-de08-4e20-b6ac-c1caa36e9265.png)

We were thing to limit the API content length (let's say to 200px) and add a button to view all information. Please refer the below screenshot for reference:
![image](https://user-images.githubusercontent.com/81968767/159916111-c0187e07-61ef-4a9e-b7e8-8a9cd0ecaadd.png)

This design approach will still show the description of API, and user can see the tabs which they can use to view the field description documentation. And clicking the "view more" button will expand the complete description and other details if one want to see that.

cc: @tsegurajimen @bobburghardt

**Comment by sfiserv** [comment]
Fix for this is going to be completed as part of https://firstdatateam.atlassian.net/browse/PORT-4302 when API explorer page is getting redesigned and completed in Milestone 13.

**Comment by sfiserv** [comment]
Closing this issue as the ticket has been worked on and completed as part of API  re-designing.
https://firstdatateam.atlassian.net/browse/PORT-4302
