### ISSUE TITLE
Tabs Structure Issues found in Banking Hub Markdown Files for Implementation Notes

### ISSUE THREAD

**Issue by tsegurajimen** [Fiserv/Support#120]
Hi @OZ-FS  and Team,

We hope you can take a look of the following issues we found while using the new Tabs structure available, we tried to create some markdown files to handle the Implementation Notes for Banking Hub APIs.

**Nested Tabs capability is failing:**

In the following example we tried to use nested Tabs into a main Tab, but as you can see only the first Tab (Premier) works fine, also nested Tabs displays the content in a good way but other main tabs are not showing the content:

![image](https://user-images.githubusercontent.com/81706748/160002504-b151a430-399a-4c72-abc7-7e49cbda1356.png)

![image](https://user-images.githubusercontent.com/81706748/160002525-3873be43-13f8-43f6-933f-6e59868de2e7.png)

![image](https://user-images.githubusercontent.com/81706748/160002586-723afb86-7f26-445b-9235-fdc103655b39.png)

**Right side menu is not displaying the right area of the file in other Tabs:**

Please take a look of bellow example where I'm located in the "Premier Tab" where the links highlighted in green are the only ones working because we are in the Premier Tab, but the ones in Red are not working because it doesn't have the capability to move between tabs to look for the content.
 
![image](https://user-images.githubusercontent.com/81706748/160003184-3a8de1fa-dbd4-4950-a738-93d12f84bc8a.png)

https://dev-developer.fiserv.com/product/BankingHub/docs/?path=docs/implementation-notes/AcctHoldMod_Tabs_Test.md#update-account-hold-api

Please let us know if any other detail is needed.

Thanks in advance!

cc:
@bobburghardt @fiservakshay

**Comment by OZ-FS** [comment]
Guide to markdown, it is a subset of html. https://www.markdownguide.org/basic-syntax/
 
Tab containers cannot be nested. https://meta.stoplight.io/docs/studio/ZG9jOjg0-stoplight-flavored-markdown-smd#tabs

<img width="579" alt="Screen Shot 2022-03-24 at 21 58 51" src="https://user-images.githubusercontent.com/92183615/160058013-9534e17d-3348-49d0-94a2-c47e464eeb30.png">

**Comment by tsegurajimen** [comment]
Thanks @OZ-FS for the clarification, now we understand that Tabs can't be nested .

In the other hand regarding the right side menu, so those headers will be recognized only if you are in the Tab where they are defined?

Does the page have the capability to look for the header titles between tabs?

**Comment by tsegurajimen** [comment]
Thanks a lot @OZ-FS we'll close this issue due to according to your explanation the Tabs structure works as expected.
