### ISSUE TITLE
Pages Not Rendering Correctly

### ISSUE THREAD

**Issue by wwfiserv** [Fiserv/Support#122]
# Reporting new issue for Commerce Hub

**Page**
https://stage-developer.fiserv.com/product/CommerceHub/docs/?path=docs/Resources/Guides/Debit/PIN_Debit.md
https://stage-developer.fiserv.com/product/CommerceHub/docs/?path=docs/In-Person/Encrypted-Payments/Track.md
https://stage-developer.fiserv.com/product/CommerceHub/docs/?path=docs/In-Person/Encrypted-Payments/EMV.md

**Describe the bug**
For the PIN Debit article it was displaying correctly once an update was made it no longer shows the Cards
For EMV and Track it was showing correctly once an update was made it is no longer showing tabs

**Expected behavior**
Cards and Tabs should display. Need a way to refresh/regenerate pages that incorrectly render markdown.

**Additional context**
Pages load correctly in Dev branch.

**Comment by sfiserv** [comment]
The above mentioned pages are rendering correctly in stage.
<img width="1399" alt="image" src="https://user-images.githubusercontent.com/87097017/169092436-fad4ef1a-c449-4cb2-8fe3-9302e7b257a2.png">
