### ISSUE TITLE
Collapsible right side navigation pane for selected Markdown files

### ISSUE THREAD

**Issue by tsegurajimen** [Fiserv/Support#123]
Hi Team,

Our team is looking for the best way to display the Implementation Notes related to Banking Hub APIs, so we decided to create a markdown file per API that will be linked into each API in the API Explorer, we're using the new Tabs capability and other markdown features, but due to the amount of content we want to displayed, we want to improve the user experience, so **we need the right side navigation pane can be collapsible,** same as the left side menu is collapsible for example; so the entire page can be used to display all the content of the markdown file.

Please take a look of the mockup displayed bellow:

![image](https://user-images.githubusercontent.com/81706748/161821000-aa2094d4-8040-47eb-970b-7b81689eb536.png)

Thanks in advance!

cc:
@bobburghardt @fiservakshay

**Comment by OZ-FS** [comment]
I've spoken with our design team.
We do not support collapsible (right side) page navigation. On the other hand collapsible left hand navigation affords for more space.

Closing the issue.
