### ISSUE TITLE
Notes added using Md syntax are not getting rendered

### ISSUE THREAD

**Issue by fiservakshay** [Fiserv/Support#124]
# Reporting new issue for Banking Hub

**Page**
API description of any API in the API Explorer section

**Describe the bug**
Notes added using markdown syntax are not getting rendered in the description of API in the the API Explorer section. (refer below screenshot)

![image](https://user-images.githubusercontent.com/81968767/162201041-450704ea-034b-4faf-88ad-88d65ff29574.png)

**Expected behavior**
A text added in markdown syntax should render correctly in API Explorer section as well.

PS:
Presently to add the note in API Explorer I'm using `<blockquote>` tag and inline CSS to render it like a normal note. This is producing the expected output. However, in some cases, adding  `<blockquote>` tag and inline CSS in SwaggerHub showing following error message.

![image](https://user-images.githubusercontent.com/81968767/162201948-2ef7e19c-4219-4dad-98a0-77f9559be016.png)

cc: @tsegurajimen @bobburghardt 
**Additional context**

**Comment by fiservakshay** [comment]
Update: We are able to add the `<blockquote>` tag with inline CSS without any error in SwaggerHub. And the output of same is being rendered as expected in the Dev Studio Portal.


![image](https://user-images.githubusercontent.com/81968767/162381439-c96171b7-943f-45a4-b0b6-04fcc750152a.png)

**Comment by tsegurajimen** [comment]
Add comment...

**Comment by TaniaSarkar89** [comment]
Opened a JIRA ticket: https://firstdatateam.atlassian.net/browse/PORT-3941

**Comment by OZ-FS** [comment]
Looking at the issue

**Comment by OZ-FS** [comment]
api description can be text or html (not markdown) and dev-studio displays it as is.
I've checked github banking-hub repo AcctHoldService.yaml, api description field has text & html in it.
and the api description is being rendered
<img width="834" alt="Screen Shot 2022-04-12 at 11 05 11" src="https://user-images.githubusercontent.com/92183615/163041069-8c9949c7-0993-4cff-88bf-0a3957806edc.png">
.
