### ISSUE TITLE
Option to bypass Olo Shield for Fiserv’s Fraud Detect service

### ISSUE THREAD

**Issue by rahulpawar17** [Fiserv/Support#125]
option to bypass Olo Shield for Fiserv’s Fraud Detect service please suggest

**Comment by acho-fiserv** [comment]
Hi @rahulpawar17 , thanks for reaching out.  What's the official product you are referring to?  Also, which API are you referring to?

**Comment by acho-fiserv** [comment]
closing for now as there is no response
