### ISSUE TITLE
Response for Statement PDF is application/pdf

### ISSUE THREAD

**Issue by kongaravinatha** [Fiserv/Support#127]
**Is your feature request related to a problem? Please describe.**
For One of the APIs (Statement PDF (/v1/statement/pdf) the response should be in application/pdf)

We need this feature in all Envs [(dev,qa,stage,Prod)]([url](<img width="1440" alt="Screen Shot 2022-04-18 at 12 54 03 PM" src="https://user-images.githubusercontent.com/84332702/163843222-8b09d726-a326-4890-9a0d-0971f25fd57e.png">))

**Describe the solution you'd like**
The response of the Url should be application/pdf for v1/statement/pdf

    At the end of your Feature template, please mention team you would like to subscribe for this Issue for future updates. You can mention teams in Github 
    
    Example:  @kongaravinatha

**Comment by acho-fiserv** [comment]
are you expecting the run button to give back a pdf file?

**Comment by kongaravinatha** [comment]
Yes, Run button should display the PDF

**Comment by acho-fiserv** [comment]
that's an interesting ask for it to return a binary object.  do you have a sample postman call i can try?

**Comment by acho-fiserv** [comment]
[PDF.postman_collection.json.zip](https://github.com/Fiserv/Support/files/8523718/PDF.postman_collection.json.zip)

**Comment by TaniaSarkar89** [comment]
@kongaravinatha : This would need some code changes at our end but first we would need some new designs when the response returns a file object. So opened this JIRA ticket for Sprint 9:  https://firstdatateam.atlassian.net/browse/PORT-4007

**Comment by kongaravinatha** [comment]
@TaniaSarkar89 

Can you pls provide me access to view this JIRA ?
https://firstdatateam.atlassian.net/browse/PORT-4007

**Comment by TaniaSarkar89** [comment]
Hi @kongaravinatha unfortunately I don't think we have enough licenses to provide access to cloud JIRA. But our team will keep updating the status here.
As of today, the status is our Design team is re-designing the look of the API explorer when a file object is returned as part of an API response as part of the current sprint 11, which started today.

**Comment by TaniaSarkar89** [comment]
We are working on this as part of the JIRA ticket : https://firstdatateam.atlassian.net/browse/PORT-4302.

**Comment by sfiserv** [comment]
@kongaravinatha as communicated by @TaniaSarkar89 and @Yelena11 this ticket has been fixed and change i now in Dev env. Please verify and let us know for any concerns.

**Comment by sfiserv** [comment]
Closing this issue as no concerns/issues were raised.
