### ISSUE TITLE
404 Article

### ISSUE THREAD

**Issue by wwfiserv** [Fiserv/Support#128]
# Reporting new issue for Commerce Hub

**Page**
https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Resources/Master-Data/Transaction-Details.md

**Describe the bug**
Getting the 404 in all 3 environments, article does display in search but gives no details and 404 when navigated to. Originally notified as part of https://github.com/Fiserv/Support/issues/104 but was not fixed. This is high priority as it impacts production.

![image](https://user-images.githubusercontent.com/75692745/164034764-09714094-b4a5-49b1-93b7-3c3e8424eec8.png)

**Expected behavior**
Page should load

**Comment by wwfiserv** [comment]
@OZ-FS @acho-fiserv @TaniaSarkar89

**Comment by wwfiserv** [comment]
@TaniaSarkar89 ok so it's because somebody did the HTML code element and not the proper markdown link? Not sure why that was done I'll switch it to the markdown link and see if that has the same issue.

**Comment by sfiserv** [comment]
@TaniaSarkar89 verified the serach results fro "Transaction details" in the Production and the link is now redirected to the correct doc
<img width="960" alt="image" src="https://user-images.githubusercontent.com/87097017/168001754-5c14b9a5-cf06-4e9f-b97d-1e84ff3e47a3.png">

<img width="1267" alt="image" src="https://user-images.githubusercontent.com/87097017/168001683-e2faab3b-37e4-4374-9aaf-b7a129592025.png">
