### ISSUE TITLE
Beta Label to be Removed from Banking Hub Tenant Name

### ISSUE THREAD

**Issue by tsegurajimen** [Fiserv/Support#129]
Hi Team, 

We need your help removing the "Beta" label from the Baking Hub Tenant, to be promoted in the April, Thursday 28th PROD Release.

![image](https://user-images.githubusercontent.com/81706748/164102388-64c0864b-d20d-4ad5-95bc-84c6610e8113.png)

Thanks in advance!

cc: @fiservakshay @bobburghardt

**Comment by TaniaSarkar89** [comment]
Opened a JIRA ticket : https://firstdatateam.atlassian.net/browse/PORT-4062 to track this effort.

**Comment by TaniaSarkar89** [comment]
This change has been pushed as part of Sprint 7's QA and Stage HotFix and would be available as part of production release on 04/28.
@tsegurajimen  please validate the changes in the lower environments.

**Comment by tsegurajimen** [comment]
Thank you so much @TaniaSarkar89 ! Changes are reflected now in Dev and Stage:
![image](https://user-images.githubusercontent.com/81706748/165361511-f7b5694a-438d-4168-b32a-414ae035ccbd.png)
![image](https://user-images.githubusercontent.com/81706748/165361715-563a5842-6e13-41be-8deb-1941db98f23a.png)
![image](https://user-images.githubusercontent.com/81706748/165361625-e8394e11-a2a3-4b52-a65c-919c125adb72.png)
![image](https://user-images.githubusercontent.com/81706748/165361676-a929e6dc-9889-4c4f-8f6c-91c2aaa08f85.png)
