### ISSUE TITLE
Fields having example with empty value not displaying in RequestSchema 

### ISSUE THREAD

**Issue by palanikumarfiserv** [Fiserv/Support#130]
Fields having example with empty (example:'') value not displaying in RequestSchema 

**Page**
FirstVision Apac >> API Explorer >> Card Management  >> Board Card

**Describe the bug**
Board Card having the PlasticId field with example ('') empty value not displaying in schema,  some other API's has this issue

**To Reproduce**
FirstVision Apac >> API Explorer >> Card Management  >> Board Card

**Expected behavior**
example: ''   for PlasticId

**Screenshots**
![image](https://user-images.githubusercontent.com/91948280/164388915-18cd1b90-9c30-431f-9d44-8979fbeba513.png)

**Comment by sfiserv** [comment]
https://firstdatateam.atlassian.net/browse/PORT-4232
created a jira for this issue.
cc: @rajeshb15

**Comment by sfiserv** [comment]
This fix is done. hence closing this issue.
https://firstdatateam.atlassian.net/browse/PORT-4232

**Comment by tarunfiserv** [comment]
Hi Team,
You have done the changes only at one place. We need this change for all other places as well. This is a generic issue.

**Comment by TaniaSarkar89** [comment]
Hi @tarunfiserv  kindly add more screenshots for the recurring issue.

**Comment by tarunfiserv** [comment]
Hi Tania,
Attaching additional screenshot
![missing_example2](https://user-images.githubusercontent.com/100914278/175289732-b853b825-22b4-4f28-8d81-fa961dbc8ac3.PNG)
![missing_example1](https://user-images.githubusercontent.com/100914278/175289753-a0508c29-2c94-46ac-8bc9-7fb6d7c4d948.PNG)
.
