### ISSUE TITLE
What API to use to add the merchant to partners RAM

### ISSUE THREAD

**Issue by raimundasas** [Fiserv/Support#131]
Hi, 

we are the partner and we onboard our merchants on the RAM. For this we need to create ne users for the RAM. Instead of manually adding users to the RAM we'd like to add these users automatically through the API. The question is what existing API should be used for that.
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/104146324/164465912-2ca972d9-eb11-40ec-a796-f4e1c4a0696a.png)

**Comment by acho-fiserv** [comment]
what product are you referring to?

**Comment by raimundasas** [comment]
Payment processing

**Comment by raimundasas** [comment]
We need to created merchant access to the The Remote Access Module (RAM)

**Comment by acho-fiserv** [comment]
Hi, you can reach out to vasan.ponnagattijayaraman@Fiserv.com
