### ISSUE TITLE
Ability to filter and generate a different URL Endpoint per Tab in Implementation Notes Section - Banking Hub

### ISSUE THREAD

**Issue by tsegurajimen** [Fiserv/Support#132]
Hi @OZ-FS and Team,

We need your help to have the ability to filter on the top ang generate a different URL according each Tab for Implementation Notes Section in Banking Hub, in each Implementation Notes file we have created a Tab per Core, but the URL endpoint is the same for all the tabs.

_Stripe Sample:_ 

![image](https://user-images.githubusercontent.com/81706748/164774960-8d53f4dc-b08f-43ff-99e0-d518b3ea6530.png)
https://stripe.com/docs/payments/accept-a-payment?integration=checkout

We're requesting this feature request because we need the ability to point to them outside from other places in Banking Hub to direct the user to the right Core Implementation Notes Tab.

![image](https://user-images.githubusercontent.com/81706748/164563051-eda3a310-288e-41b8-a408-103b89843b50.png)

Thanks in advance!

cc: 
@fiservakshay @bobburghardt

**Comment by sfiserv** [comment]
created a jira ticket for sprint11
https://firstdatateam.atlassian.net/browse/PORT-4223
cc: @TaniaSarkar89

**Comment by sfiserv** [comment]
The issue is going to be worked in next sprint hence moving to Milestone 12.
https://firstdatateam.atlassian.net/browse/PORT-4223

**Comment by OZ-FS** [comment]
Extended markdown with collapsible section.

<img width="815" alt="Screen Shot 2022-06-17 at 07 05 22" src="https://user-images.githubusercontent.com/92183615/174320379-4f8e348b-16d6-4cee-ad5a-08ffe5b13566.png">
<img width="898" alt="Screen Shot 2022-06-17 at 07 06 45" src="https://user-images.githubusercontent.com/92183615/174320384-e580b4e2-dada-40f1-ab92-9da5459175aa.png">

Next:
add up/down arrow icon to the right of the title
open section from url

**Comment by sfiserv** [comment]
@OZ-FS would you be able to let us know what will be addressed in the second part of the ticket you are working on
https://firstdatateam.atlassian.net/browse/PORT-4873

**Comment by TaniaSarkar89** [comment]
This would be worked on as part of Sprint 19.

**Comment by OZ-FS** [comment]
@tsegurajimen, Vardan had implemented the changes in dev. Please test 
https://dev-developerstudio.fiserv.com/product/BankingHub/docs/?path=docs/api-glossary.md&branch=develop#tab-account_types
Note: page might have several tab sets. It is possible to specify only one tab via link.
Will it suffice?

**Comment by tsegurajimen** [comment]
Hi @OZ-FS,

For me now it looks good now, in Dev I can see that each tab is generating a different URL that we'll be able to point to: 

![image](https://user-images.githubusercontent.com/81706748/195945750-5e470041-54bd-4437-9f77-4e6405081648.png)

![image](https://user-images.githubusercontent.com/81706748/195945769-91ed0093-9d91-4100-8617-bf01fc351525.png)

![image](https://user-images.githubusercontent.com/81706748/195945792-9bcc8316-90c4-4f34-9a76-f8831ccc443a.png)

@fiservakshay can you please validate if this fix will satisfice our need in terms of Release Notes and other places where we are using Tabs structure?

**Comment by tsegurajimen** [comment]
Thanks a lot @OZ-FS I just confirmed with @fiservakshay that this is enough to full fill our needs in Banking Hub.

**Comment by sfiserv** [comment]
@fiservakshay this issue is fixed and can be verified in the dev env.  https://firstdatateam.atlassian.net/browse/PORT-4438

**Comment by sfiserv** [comment]
Closing this issue as did not receive any response from client
