### ISSUE TITLE
Need a quick deployment feature

### ISSUE THREAD

**Issue by sivabonjour** [Fiserv/Support#133]
It would be good if we can see the results quicker in Dev enviornment at least. I use stoplight but some of the features like examples etc. specifc to dev portal and we can't wait to see the chages and i couldn't find any documentation around how the tags shold be arranged. 

Also, is there a way we can order the examples? I want to show my example first then Default as shown reverse to the attahed image.

![image](https://user-images.githubusercontent.com/100300230/164571352-1d2ee5a2-d40d-4699-9907-46b7e237776d.png)

**Comment by sfiserv** [comment]
created a jira ticket https://firstdatateam.atlassian.net/browse/PORT-4451 to update the tenant doc.

**Comment by TaniaSarkar89** [comment]
Relevant support documents will be added in sprint 14.

**Comment by TaniaSarkar89** [comment]
Moving this ticket to Sprint 16 as we do not have the capacity to handle this at this moment.
cc: @sfiserv

**Comment by sfiserv** [comment]
As of now Devstudio does not provide any deployment to tenant and you can read the Tenant support document for the Syncing and release cyle.
