### ISSUE TITLE
Request for tenant space for BNPL (Buy Now Pay Later) 

### ISSUE THREAD

**Issue by bnplbig2** [Fiserv/Support#136]
This request is for tenant space for BNPL (Buy Now Pay Later) .

Please find the related documents attached:

*Markdown file
*API specification file (yaml)
*Use case 

Github Account Details:
username: bnplbig2
registered email : srinivasan.m@Fiserv.com
[dev-portal.zip](https://github.com/Fiserv/Support/files/8601439/dev-portal.zip)

**Comment by acho-fiserv** [comment]
@bnplbig2 , i don't see any attachments

**Comment by bnplbig2** [comment]
Attached :dev-portal.zip
Please find the required file attached.

**Comment by acho-fiserv** [comment]
your space has been provisioned.  you can follow the instructions and get yourself setup by using github.com/fiserv/tenant-docs

to add your files & make your changes.
