### ISSUE TITLE
Trying to get access to the developer studio

### ISSUE THREAD

**Issue by WorkmanD** [Fiserv/Support#138]
I'm not sure if this is the right place to request this, but I would like to get access to the developer studio so I can investigate the Banking Hub APIs and scope out what an integration would like.

**Comment by acho-fiserv** [comment]
Hi @WorkmanD , you can view the bankinghub apis on [developer.fiserv.com/](https://developer.fiserv.com/product/bankinghub)

**Comment by WorkmanD** [comment]
I was able to see the documentation, but need to register to get an account to test with. https://developer.fiserv.com/product/bankinghub/docs/?path=docs/getting-started/before-you-start.md

So I can see the differences between cores and test APIs as opposed to the try now feature in documentation.

Thanks,

Derick Workman

From: Alvin Cho ***@***.***>
Date: Thursday, May 12, 2022 at 2:03 PM
To: Fiserv/Support ***@***.***>
Cc: Derick Workman ***@***.***>, Mention ***@***.***>
Subject: Re: [Fiserv/Support] Trying to get access to the developer studio (Issue #138)

Hi @WorkmanD<https://urldefense.com/v3/__https:/github.com/WorkmanD__;!!E6kGQnY!LTAz5fSxuWSf7MAY2uL6bA-WIbYBMwpXA7PLuw6H4noA1lW1LCPh-5V7i-SaCYjj52IT_D77oimIBbp0hVKqJTKAMAs$> , you can view the bankinghub apis on https://developer.fiserv.com/product/bankinghub<https://urldefense.com/v3/__https:/developer.fiserv.com/product/bankinghub__;!!E6kGQnY!LTAz5fSxuWSf7MAY2uL6bA-WIbYBMwpXA7PLuw6H4noA1lW1LCPh-5V7i-SaCYjj52IT_D77oimIBbp0hVKqB_X5zxs$>

**Comment by bobburghardt** [comment]
Hi Derek ,
     Please provide us with some more information about your organization so we can properly route your registration request.  For instance, what is your company name, website, your role, and contact information.

Thank you,
Bob Burghardt

**Comment by WorkmanD** [comment]
My company name is nCino.
Website is www.nCino.com<http://www.nCino.com>
I'm the Product Manager over Core Booking Integrations.
We have many customers that use Fiserv Core Banking applications that want us to integrate for booking deposit accounts and loans.

Derick Workman
***@***.***
512.704.3913


________________________________

**Comment by bobburghardt** [comment]
Hi Derick,

     I checked internally and at this point we are not ready to accept registrations.  The website will be updated to reflect that registration is not currently available, and the specifications are for informational purposes at this time.  As we develop features on the Developer Studio, we'll continue to post updates, which includes registration.  So, please continue to monitor the site for the registration capability.

Thank you,
Bob
