### ISSUE TITLE
Example values having double quotes not reflecting in Requests schema

### ISSUE THREAD

**Issue by palanikumarfiserv** [Fiserv/Support#140]
Example values having double quotes not reflecting in Requests schema

**Page**
FirstVision APAC >> Account Management >> Block unblock Account

**Describe the bug**
Example values double quotes not reflecting in Request schema
Block code2 example is empty (no values in request schema) whereas in Request Body quotes is being displayed
Expected requestbody ( blockcode2: " ") should be displayed same in Request schema
![blockunblockaccount](https://user-images.githubusercontent.com/91948280/171341471-1343a5ab-db48-4909-9ef1-511aba215e80.PNG)

**To Reproduce**
1. First Vision Apac >> API Explorer >> Account Management >> Block Unblock Account
2. Click on Request Schema >> Block Code2 
3.  Example without double quotes

**Comment by sfiserv** [comment]
Created jira https://firstdatateam.atlassian.net/browse/PORT-4447 to track this issue

**Comment by sfiserv** [comment]
We could not address this issue as part of milestone S12. However we will prioritize this issue in milestone S13.

**Comment by TaniaSarkar89** [comment]
Prioritizing this as part of Sprint 14.

**Comment by anandrewfiserv** [comment]
Hi @AwaneeshSrivastava, I am working on this fix. We cannot distinguish between double and single quotes that come from the yaml, as it is given to us as a string (regardless of the quote-type used). We can choose to enwrap the whitespace examples in double quotes or single quotes. Which do you prefer?

**Comment by anandrewfiserv** [comment]
Using double quotes for now.

**Comment by anandrewfiserv** [comment]
Issue has been fixed in dev now, please verify!

**Comment by AwaneeshSrivastava** [comment]
Thanks.. double quote is also fine.  Will check and close the issue if working

**Comment by AwaneeshSrivastava** [comment]
![image](https://user-images.githubusercontent.com/91457011/181244296-37d787eb-80ca-43db-af03-bdb5628e08d9.png)

**Comment by AwaneeshSrivastava** [comment]
Can you please check in the above screenshot for field "alternateEmailAddress", the example in the swagger is set to "" but still it is not appearing in the Request Schema?

**Comment by anandrewfiserv** [comment]
I'll fix that as well

**Comment by anandrewfiserv** [comment]
Should be fixed in dev now.

**Comment by palanikumarfiserv** [comment]
Example having double quotes reflecting in Request schema in dev env
