### ISSUE TITLE
Default Examples

### ISSUE THREAD

**Issue by wwfiserv** [Fiserv/Support#141]
# Reporting new issue for Commerce Hub

**Page**
API Explorer

**Describe the bug**
Originally the examples would default to the first example in the schema, however after the new x-default-example was implemented it defaults to the "default" or full YAML example. I asked during a call if nothing was used for the x-default-example would it act the same as before and was told yes. This simple change requires a lot of work on Commerce Hub's side as we will have to have a dev team make updates to each of our endpoints in the API and YAML Generator.

**Expected behavior**
If no x-default-example is found in the YAML it should default to the first example in the schema.

**Comment by sfiserv** [comment]
created this ticket for tracking this issue
https://firstdatateam.atlassian.net/browse/PORT-4450

**Comment by TaniaSarkar89** [comment]
We will be working on this ticket in the next sprint.

**Comment by sfiserv** [comment]
@wwfiserv This issue is ready for you to test.

**Comment by TaniaSarkar89** [comment]
Closing this ticket since no confirmation received from tenant.
