### ISSUE TITLE
Authentication Required in Edge

### ISSUE THREAD

**Issue by wwfiserv** [Fiserv/Support#142]
# Reporting new issue for Dev Studio

**Page**
Stage and Dev

**Describe the bug**
When accessing either environment in Edge it does not prompt for authentication and instead gives a blank screen with Authentication required. Works in Chrome and Firefox.

**Expected behavior**
Should prompt for authentication.

**Screenshots**
![image](https://user-images.githubusercontent.com/75692745/171435808-da052a3b-0652-41ba-b4cf-1c16b7febc24.png)

**Comment by sfiserv** [comment]
@wwfiserv I tried to verify the  Authentication modal issue about Edge browser and the authentication modal is prompted. please see the screenshots. We had this similar issue reported by the overseas Fiserv team where the Fiserv device was blocking the edge browser access. 
![Image from iOS (38)](https://user-images.githubusercontent.com/87097017/171671019-1609af35-ff0f-4fc4-bfc2-9f2669b4e4bd.jpg)
![Image from iOS (39)](https://user-images.githubusercontent.com/87097017/171671049-5dca377d-81ac-466d-9c4f-da6f5f53010c.jpg)
