### ISSUE TITLE
Different major versions for different API Endpoints not Supported

### ISSUE THREAD

**Issue by tsegurajimen** [Fiserv/Support#144]
Hi Team, 

In Baking Hub we have two main groups of APIs, where Group A (Gravis/Heavy APIs) are version 11.0.0 and Group B (Leve/Lightweight APIs) are version 1.0.0., we tried to display them in the portal in that way but we found that the UI doesn't support different Major Versions for different API Endpoints.

For example we changed the tentant.json file as follows: 
![image](https://user-images.githubusercontent.com/81706748/171740720-9b07eca6-b6e4-4e8e-835f-0ba3432b232a.png)

According the changes we where expecting that the APIs called in the version: 1.0.0 only display in the portal the 1.0.0 in the version dropdown and not the 11.0.0, and same case for the APIs called in the version: 11.0.0 only display in the portal the 11.0.0 in the version dropdown and not the 1.0.0.

But that wasn't the case because according to this file the UI always displays both versions for all the endpoints even if the API doesn't have a 1.0.0 version, and in called only in the version 11.0.0 section of the file.

![image](https://user-images.githubusercontent.com/81706748/171741748-1bb050fd-6aed-4c39-ae47-9374d28e4f89.png)

That's why we need to handle the versions of this two main groups of APIs in a separate way to don't create confusion to the user and display the right available version of each endpoint.

Thanks in advance for your help!
 cc. @bobburghardt @fiservakshay

**Comment by sfiserv** [comment]
JIra ticket is created https://firstdatateam.atlassian.net/browse/PORT-4448

**Comment by TaniaSarkar89** [comment]
Please note that we would be addressing this enhancement at a later sprint.
