### ISSUE TITLE
Search Tag Selection Not Filtering

### ISSUE THREAD

**Issue by wwfiserv** [Fiserv/Support#146]
# Reporting new issue for Commerce Hub

**Page**
Search

**Describe the bug**
After searching when clicking a tag it shows all results with the tag name/value if it's found in the article

**To Reproduce**
Search for anything and click a tag related to the search

**Expected behavior**
When you select a tag it should only show articles that also contain that specific tag

**Comment by sfiserv** [comment]
jira ticket is created to track this issues
https://firstdatateam.atlassian.net/browse/PORT-4449

**Comment by sfiserv** [comment]
This is currently worked in in sprint 14

**Comment by jimmychen-fiserv** [comment]
Consider about the severity and priority, this ticket will be moved to the future sprint.

**Comment by jimmychen-fiserv** [comment]
This ticket

**Comment by wwfiserv** [comment]
@jimmychen-fiserv I understand this is not going to be prioritized however the ticket should not be closed as it needs to be tracked, reopening and assigning to you again.

**Comment by sfiserv** [comment]
We are currently researching how to refine our Search functionality. hence issue is in Triage.
