### ISSUE TITLE
Search Needs the Ability to Return to Tenant

### ISSUE THREAD

**Issue by wwfiserv** [Fiserv/Support#147]
**Is your feature request related to a problem? Please describe.**
Need the ability to easily return to a tenant from the search, currently there is no easy way to go back to the tenant and are required to navigate back from the header navigation menu which requires multiple clicks.

**Describe the solution you'd like**
 If search was an overlay pop-over screen you could click x to go back to the article or tenant you were in see Adyen, Stripe and similar.

**Describe alternatives you've considered**
Have search open in a new window (not ideal)
Have the filters on the left nav be selectable links to return to the tenant.

**Additional context**
The overhead for the client can be lessened if the search and filter selection was persistent when you clicked back, so if a client selected an article and realized it was not correct they can click back and maintain their search.

**Comment by sfiserv** [comment]
jira ticket is created to track this issues
https://firstdatateam.atlassian.net/browse/PORT-4449

**Comment by sfiserv** [comment]
This is currently worked in in sprint 14

**Comment by jimmychen-fiserv** [comment]
Consider about the severity and priority, this ticket will not be fixed at this point.

**Comment by jimmychen-fiserv** [comment]
Consider about the severity and priority, this ticket will not be fixed at this point.

**Comment by jimmychen-fiserv** [comment]
Consider about the severity and priority, this ticket will not be fixed at this point.

**Comment by jimmychen-fiserv** [comment]
Consider about the severity and priority, this ticket will not be fixed at this point.

**Comment by wwfiserv** [comment]
@jimmychen-fiserv understand this was not planned but is still a required enhancement so reopening ticket so it can be tracked.

**Comment by sfiserv** [comment]
New tracking ticket is opened for this issue. https://firstdatateam.atlassian.net/browse/PORT-4873

**Comment by bigsauron** [comment]
No sure we have to implement this at all. Search is a global page and not related to any tenant so we can't add a link to go back. 
Customer can click back button several times or push on the button and keep pushing then a menu will be opened with all previous steps.
The other way is to open search page in a new tab.

**Comment by wwfiserv** [comment]
@bigsauron This is a requirement for Commerce Hub. Additionally it is not an ideal situation for the client. We should not expect a client to keep clicking back to get to the page they were at. We should not expect a client to open new tabs to perform tasks. The site should be user friendly as well as intuitive.

Additionally we are very unique in the aspect of combining all APIs and services together, this makes it difficult for a client to know where they are or how to get back to what they were doing. Even if you compare us to our competitors they have the search as an overlay that allows you to search and click out of the search to return to where you were. Similarly if you search and access a page it know what your prior search was and allows you to select a new document. If they don't persist the search terms they automatically  open in a new window. This is why I have the other ticket about not being able to go back to your prior search.

**Comment by wwfiserv** [comment]
flagging for update, we did another demo with an internal from another team and they were confused by the current search as it was not maintaining what tenant they were in and didn't allow them to return to the search easily.
