### ISSUE TITLE
Core Banking Processors that are accessed using your Banking Hub APIs

### ISSUE THREAD

**Issue by PeterBerbee** [Fiserv/Support#149]
Can you tell me which of your Core Banking Platforms can be accessed using your Banking Hub APIs?

**Comment by bobburghardt** [comment]
Hi @PeterBerbee,
    Thank you for your inquiry about the banking cores available with the Banking Hub APIs.  Presently, we are
	focused on our Premier, Precision, DNA, Cleartouch and Signature cores, with plans to expand to our credit union
	cores.  We've added Implementation Notes for the various providers, and you can find those notes in each applicable
	API specification.  You can monitor that Implementation Notes section for progress on each provider. 
	
Thank you,
Banking Hub Team

**Comment by PeterBerbee** [comment]
Thank you for the information.

Can you tell me if you have APIs available to get to your Client Central Card platform?  The same CU that I am working with the is Using DNA is using Client Central.


Peter Berbee
VP Financial Services Product Management
Kore.ai
(904) 412-3566


Kore.ai’s No Code / Low Code platform among Gartner’s Top 5 Conversational AI Platform Providers – See Report <https://share.polymail.io/v1/z/b/NjBlODI2OWVjMjhm/LkR94hAa39NtyDQ-gOd9DajLp-KPbIWCgV_X28ZUjnAj9-DLaXOC1AHEyuu3YqABvIBvaj5Wr2B8UfcoOheFYUJkZ5p9_NIIQHiE3dWLMAXUi2a7qEs259F5dcz-v0yUCJK6M0wsWLhuVUPDHCrT4Py97Svn7JdFfssuLmdltz6VsA1tMgP8oYvEitG24Bul4LFhsiU5_4_2LSETFHav-ijfFXaQGbFxD9RISqhvFij6Zo3gCwtd6-CXq6-K_CetLDLKEiA=>

**Comment by bobburghardt** [comment]
Hi @PeterBerbee ,

     The APIs for the Client Central SSO are not available on Developer Studio.  There is a card portal found at card.developer.fiserv.com that provides access to our EPOC platform's Card Management.  The link to the card portal is on the Developer Studio, under Financial Institutions > Cards.

The Developer Studio Team
