### ISSUE TITLE
Version Branching

### ISSUE THREAD

**Issue by wwfiserv** [Fiserv/Support#150]
**Is your feature request related to a problem? Please describe.**
For Version branching we need the ability to select a branch (Preview, Active, Previous, etc.) from outside of a document. And we need to have the ability to link to the specific branch.

Example A: If we need to link to a security requirement update to our API that will be in our Upcoming release we need to be able to switch to the active branch and/or link to the specific document in this branch as it doesn't exist in the Main branch.

Example B: We are creating new documentation that does not exist in the Main navigation tree, we need to be able to switch to the Preview release to see the new Nav tree and/or provide a link to the specific documentation for review as it doesn't exist in the Main branch.

**Describe the solution you'd like**
As discussed with Alvin the dropdown being in the article (as seen in DEV) doesn't feel like the correct place, normally this is used for documentation history not versioning. It would make more sense to have it as it currently is in STAGE and PROD where it's above the navigation menu this allows you to switch branches and have the navigation structure update accordingly.

Need to have some type of URI that points to the specific branch so it can be directly linked to. If you provide a link as is for a Preview document it will 404 as it doesn't exist in Main.

**Comment by TaniaSarkar89** [comment]
This Issue has been addressed and the fix is now in production.
