### ISSUE TITLE
Access to API to process payments on a clients API.

### ISSUE THREAD

**Issue by maanavpatel24** [Fiserv/Support#151]
**Region** (optional)
USA

**What do you like about the project?**
API docs are very clean.

Can you guys help me out?
I can't find any support information, or account creation information on the website.

Thanks,

**Comment by acho-fiserv** [comment]
Hi @maanavpatel24 , thank you for the compliment!

we have not rolled out account creation.  which company are you with?  do you have a specific api you want to use?

as for support, we are currently using github for the DevStudio.  if you're looking for a specific support of a product that would be separate for now.  which product are you interested in?

**Comment by maanavpatel24** [comment]
Hi!
We are with Glyde (Joinglyde.com), one of our clients is a Fiserv customer and wanted us to transact payments on their Fiserv MID. Wanted to see if we could get access to the Commerce Hub.

Thanks,

**Comment by acho-fiserv** [comment]
Hi @maanavpatel24 , we'll be glad to work with you directly.

@wwfiserv , can you help get them connected to an account rep?

@maanavpatel24 , you might inquire with your customer who their fiserv account rep is.

**Comment by maanavpatel24** [comment]
Hi,
I will get the account rep's name shortly.
Just to confirm, developer.fiserv.com are the correct docs right?
We also found this: https://docs.firstdata.com/org/gateway/docs/api#introduction
Thanks,

**Comment by maanavpatel24** [comment]
stephanie.knutsen@Fiserv.com is their account rep.

**Comment by wwfiserv** [comment]
@maanavpatel24 I have sent an email to the account rep who will work with our team to see if Commerce Hub is the correct product for Glyde. They should be in contact with the client and work with them on understanding the current integration and future solutions based on their needs.

**Comment by wwfiserv** [comment]
@maanavpatel24 I just received a response from Stephanie, she says she doesn't work with Glyde and doesn't see them as an Enterprise client with Fiserv. Is their some additional information you can provide or are they operating under a different legal name that we would have on file? It may be best to have the client contact their account rep directly and verify they are an Enterprise client as Commerce Hub and Carat are specific to those merchants.

**Comment by maanavpatel24** [comment]
Hi,
We are not the Enterprise Client. The Client would be TGI Fridays. I can have them email Stephanie, could you tell me what they need to email Stephanie with?
I work for the company providing online ordering for the Fiserv Client, so we need API access to process payments on their MID.

Thank,

**Comment by wwfiserv** [comment]
@maanavpatel24 thanks, Stephanie is the account rep for TGIF and will reach out to them for more details.

**Comment by maanavpatel24** [comment]
Perfect. Sorry for the confusion, it our first payment process integration besides Stripe.
