### ISSUE TITLE
Constructing Signature for Header HMAC

### ISSUE THREAD

**Issue by dacha93** [Fiserv/Support#153]
Hey Fiserv Support Team, 

I wanted to ask exactly what do I need to create a signature of as stated within the following [page](https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Resources/API-Documents/Authentication-Header.md). 

The page says 'The message data for the signature is the following items concatenated: Api-Key, Client-Request-Id, Timestamp, Signature'. I just don't understand what documentation means by including the 'Signature' as part of items that is needed to create a signature. 

Is it just the request body hashed in SHA256 which is encoded in Base64?

Any help would be greatly appreciated, thanks

**Comment by dacha93** [comment]
Any updates on this would be very helpful

**Comment by acho-fiserv** [comment]
thanks for @dacha93 for reaching out.  @wwfiserv has been assigned to help you.

what company do you work for?

**Comment by wwfiserv** [comment]
@dacha93 We use this for security. The Message-Signature is the Base64 encoded HMAC hash (SHA256 algorithm with the API Secret as the key.) There is a rendering bug that isn't displaying our code snippet, see the following for more information;

```javascript
var key = 'api'Key;
var secret = 'secret';

var ClientRequestId = Math.floor((Math.random() * 10000000) + 1);

//var ClientRequestId = 1000000012;

var time = new Date().getTime();
var method = request.method;

var requestBody = request.data;
var rawSignature = key + ClientRequestId + time + requestBody;

var computedHash = CryptoJS.algo.HMAC.create(CryptoJS.algo.SHA256, secret.toString());
computedHash.update(rawSignature);
computedHash = computedHash.finalize();
var computedHmac = b64encode(computedHash.toString());

postman.setEnvironmentVariable('key', key);
postman.setEnvironmentVariable('time', time);
postman.setEnvironmentVariable('signature', computedHmac);
postman.setEnvironmentVariable('ClientRequestId', ClientRequestId)

function b64encode (input) {
	var swaps = ["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z",  "a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z","0","1","2","3","4","5","6","7","8","9","+","/"],
	tb, ib = "",
	output = "",
	i, L;
	for (i=0, L = input.length; i < L; i++) {
		tb = input.charCodeAt(i).toString(2);
		while (tb.length < 8) {
			tb = "0"+tb;
			}
		ib = ib + tb;
		while (ib.length >= 6) {
			output = output + swaps[parseInt(ib.substring(0,6),2)];
			ib = ib.substring(6);
			}
	}
	if (ib.length == 4) {
		tb = ib + "00";
		output += swaps[parseInt(tb,2)] + "=";
	}
	if (ib.length == 2) {
		tb = ib + "0000";
		output += swaps[parseInt(tb,2)] + "==";
	}
	return output;
}
```

**Comment by dacha93** [comment]
> thanks for @dacha93 for reaching out. @wwfiserv has been assigned to help you.
> 
> what company do you work for?

Hey @acho-fiserv, I really appreciate the help. I current work for Glyde (joinglyde.com) as a lead engineer. I will be utilizing this GitHub to post more questions as my team and I come across more issues. 

Thank y’all

**Comment by wwfiserv** [comment]
@dacha93 we currently have the account manager reaching out to your client about seeing if Commerce Hub is the correct integration for your teams need.

**Comment by dacha93** [comment]
Yes @wwfiserv you are correct, in fact the account manager has gotten back to us with the following docs https://firstdatanp-ucomgateway.apigee.io/index. Though upon looking at both docs (ucom and commerce hub), they both have the same functionality that we were intending on using (auth, capture, pay, and digital wallet). So I guess my next question is which one would you guys suggest we use for our Fiserv integration.

**Comment by dacha93** [comment]
@wwfiserv By any chance do you or your team have experience with Fiserv's uCom api docs? I have bunch of questions regarding that api (we are deciding to go with uCom over Commerce Hub as suggested by David Schwartz). If there is another team within Fiserv that can help me and my team out with uCom api then that would be great. Thank you

**Comment by wwfiserv** [comment]
@dacha93 Ucom is a separate group so David will have to provide a good contact.
