### ISSUE TITLE
oneOf code not rendered correctly in the API Explorer UI

### ISSUE THREAD

**Issue by tsegurajimen** [Fiserv/Support#159]
HI @acho-fiserv and Team,

This week we added some new APIs under Banking Hub Tenant, but we realized some of them has oneOf code in place. This type of definitions are used when there is a need to represent a choice relationship between two different sub-schema objects, then the main purpose of using oneOf is validate the value against exactly one of the subschemas.

Please take a look of the example below:

This is how the Term object is defined in the specification file:

![image](https://user-images.githubusercontent.com/81706748/174171451-8c5588c0-0d84-448b-a67a-20c7c0ed772b.png)

This is how the UI is displaying Term just as object:

![image](https://user-images.githubusercontent.com/81706748/174171577-86aee4c3-5af3-4d2e-a3f0-39be8adb9183.png)

This issue is similar to the one we opened some months ago when the allOf code definitions where not displayed correctly in the portal: https://github.com/Fiserv/Support/issues/99

Thanks in advance for your help!

cc:

@bobburghardt @fiservakshay

**Comment by sfiserv** [comment]
Created Jira https://firstdatateam.atlassian.net/browse/PORT-4445 to track this issue

**Comment by sfiserv** [comment]
Currently the Ticket is being worked on and still in progress.

**Comment by tsegurajimen** [comment]
Hi @TaniaSarkar89  and @sfiserv any update on this ticket? 
Thanks in advance!

**Comment by anandrewfiserv** [comment]
Hi @tsegurajimen, the fix was merged today. Could you take a look?

**Comment by tsegurajimen** [comment]
Great news, thanks a lot @anandrewfiserv, once Dev Env is stable again and the 503 issue is fixed, I'll test it and let you know.

**Comment by tsegurajimen** [comment]
Hi @anandrewfiserv oneOf code is now displayed as expected, thanks a lot!

![image](https://user-images.githubusercontent.com/81706748/178605491-34a63d32-d050-4c57-ba92-a61f9fcc6813.png)

Closing this issue.
