### ISSUE TITLE
Ability to customize content ordering under the API Explorer

### ISSUE THREAD

**Issue by tsegurajimen** [Fiserv/Support#160]
Hi @TaniaSarkar89 and Team,

We need to have the ability to customize the content ordering under the API Explorer, we started adding new groups of APIs from different products so we want to have the capability to organize them by priority, according which are the most commonly consumed  by our users.

We understand that the behavior of the API Explorer is different than the Documentation section where we can control the order using the document-explorer-definition file, but we'd like to have something similar where we can align our API main groups as we explained before.

![image](https://user-images.githubusercontent.com/81706748/174185032-97bafff3-e226-4639-8285-507551670a2d.png)

Thanks in advance for your help!

**Comment by sfiserv** [comment]
Created Jira ticket https://firstdatateam.atlassian.net/browse/PORT-4444 to track this enhancement.
