### ISSUE TITLE
Right Nav Anchor Bug

### ISSUE THREAD

**Issue by wwfiserv** [Fiserv/Support#161]
# Reporting new issue for Commerce Hub

**Page**
Right navigation bar on articles in https://dev-developer.fiserv.com/

**Describe the bug**
The right nav bar should stick to the top of the nav pain, but instead is locked to the center. Upon page load it looks fine but once you scroll it stays in the middle.

**Expected behavior**
 The function in Stage and Prod are the ideal method and common standard for most websites. The right nav should stay at the top of the nav pain.

**Screenshots**
![image](https://user-images.githubusercontent.com/75692745/174318441-06411785-15ce-4b2e-a2cd-87921badddf2.png)

**Comment by sfiserv** [comment]
Jira ticket s created for this issue 
https://firstdatateam.atlassian.net/browse/PORT-4442

**Comment by OZ-FS** [comment]
Inquired about the described behavior of the design team.

**Comment by OZ-FS** [comment]
Design team is re-designing the page header and that should fix right side navigation on doc pages.
It will be addressed by the same Jira PORT-4442 in the next Sprint 14.
