### ISSUE TITLE
Code snippet is giving error for Some of the API

### ISSUE THREAD

**Issue by tarunfiserv** [Fiserv/Support#164]
Code snippet is giving error for below API

1. Update Customer
2. Update direct debit controls
3. Update Spend limits

Page

- for Update Customer: FirstVision APAC >> Customer Management >> Update Customer
- for Update Direct Debit Controls: FirstVision APAC >> Account Management >> Update Direct Debit Controls
- for Update Spend limits: FirstVision APAC >> Card Management >> Update Spend Limits

Describe the bug
In code snippet section, if user selects any other language than 'C-Libcurl', portal gives error **"Unable to generate Code snippet"** in snippet description.
To Reproduce

**Steps to reproduce the behavior:**

1. First Vision Apac >> API Explorer >> Customer Management >> Update Customer
2. In code snippet section, select "HTTP -  HTTP/1.1" language from drop-down.
3. "Unable to generate Code snippet" error displays in snippet description.

NOTE: Similar steps for other 2 API

![code_snippet_error](https://user-images.githubusercontent.com/100914278/177098228-d777679a-8335-4a00-a8ba-3917b4106599.PNG)

**Comment by TaniaSarkar89** [comment]
Tracking JIRA ticket opened : https://github.com/Fiserv/Support/issues/164

**Comment by f2zdirk** [comment]
@tarunfiserv - I am not able to replicate this issue. Are you still able to generate this issue at your end ?

![image](https://user-images.githubusercontent.com/81193958/177648762-fd27ecb8-95df-4f58-b545-426c9a58ca63.png)

**Comment by f2zdirk** [comment]
![image](https://user-images.githubusercontent.com/81193958/178523421-7ecf35e2-ae04-4d6b-8afb-53bcb5ac86b1.png)

**Comment by TaniaSarkar89** [comment]
Hi @tarunfiserv we don't see the issue at our end anymore. please let us know if you have any further concerns on this. 
For now we are closing this issue.
Thanks!

**Comment by palanikumarfiserv** [comment]
Curl command for get access token is not displaying,
Hence reopening this ticket
![access](https://user-images.githubusercontent.com/91948280/195805625-a054d3fa-2dbc-4952-834d-2d03e53b5353.PNG)

**Comment by sfiserv** [comment]
@TaniaSarkar89 would you be able to provide more information on the issue seen in our lower env currently.

**Comment by sfiserv** [comment]
Created a new tracking ticket for this issue https://firstdatateam.atlassian.net/browse/PORT-5452

**Comment by asingh2023** [comment]
Update:

Able to generate code from code snippet. 

![image](https://user-images.githubusercontent.com/81193958/204687991-852a2d7e-1dfd-4e68-a2ba-d70f9cba7eff.png)

**Comment by sfiserv** [comment]
Closing this issue as there was no response from client.
