### ISSUE TITLE
Query parameter is not passing values after space in request

### ISSUE THREAD

**Issue by tarunfiserv** [Fiserv/Support#165]
Query parameter is not passing whole value in request for below API
- Get Access Token

**Page**

FirstVision >> APAC >> API Explorer >> Security >> Get Access Token

**Describe the bug**
In the getAccessToken API, scope query parameter is only passing "accounts" in the request even though the scope field has more values 'acccounts cards users'

To Reproduce
**Steps to reproduce the behavior:**

1. First Vision >> Apac >> API Explorer >> Security >> Get Access Token
2. In scope query field pass the value  **accounts cards customers users products misc** .
**Expected:** Portal should pass the whole value ('accounts cards customers users products misc') as value of scope parameter in the request to the server application. 
**Actual:** It is only passing "accounts" as value of scope parameter in the request.

![image](https://user-images.githubusercontent.com/100914278/177128937-e8fd6a05-b72d-4dfd-b438-04dc2d6ada76.png)

**Comment by AwaneeshSrivastava** [comment]
Hi @TaniaSarkar89 

Can you please try with below curl?   Please note the Authorization for this api is Basic.    
curl -k  --location --request POST 'https://stg34.visionplus.io/sandbox/v1/getAccessToken?scope=accounts cards customers users products misc auth' --header 'Authorization: Basic UE9DX05BQl9EZXY6YkhXTVR6Y0VPQ3I3cXU2WWN5M21jUnV1eXdaRzdmT3VobXNiZWNaNGFOYlVRYU5HYWNqeFY0SkM5c0s5WkR6RQ=='


The output will have the access token (as shown below)
{
  "access_token" : "eyJhbGciOiJSUzI1NiJ9.eyJzY29wZSI6ImFjY291bnRzIiwiY2xpZW50X2lkIjoiUE9DX05BQl9EZXYiLCJmaXJzdFZpc2lvbklkIjoiMDAwMDBBVU5BQiIsImV4cCI6MTc1MDM5MjAwMH0.e0q6vbgUXl9vGi1T7UbVO_6N56r25xvX50-Wf-O4As_pRLFIPhQIcS9DDeI8CqQAIKuyk8bNeg0ubULJ1JomnsCbq2ImCBowEJE_lDDdmPMnicE8Sw3QMIFibN6ZPSEbkE8_DLrytV-IGoEmCO2ZZakXpH49OX4VlYCennctFqfA-6mDQO_F1Hl7xRJuBn15ifR1kwXwzz7OWUgZWtm1dRjlOwaQEYSbevXOMcQrDYv0rK-M0aWBkaEQUBlXWwK46_6mkNlZg40p3HSw50rOGWuowm0uppj61xrB5PMOgfWeUHjk58cHAVwo1s8r4ZDVV4q9PeBMwh3KMJ6J_1_VIw",
  "token_type" : "Bearer",
  "expires_in" : 1750392000
}                                                                                                                                                                                                     ✔

**Comment by sfiserv** [comment]
CLosing this ticket based on the comments in https://firstdatateam.atlassian.net/browse/PORT-4849.

**Comment by AwaneeshSrivastava** [comment]
@sfiserv 

Still on our server side, we are not getting the desired value for scope.  We are only getting the first value of scope only. Please below server log

![image](https://user-images.githubusercontent.com/91457011/187185362-6a2f91bd-6c71-4937-901d-e769bac5b056.png)

**Comment by AwaneeshSrivastava** [comment]
![image](https://user-images.githubusercontent.com/91457011/187185425-9e5536c0-9923-4e50-9299-1a3a86bc1263.png)

Above is the request made from the portal. In the request, scope is populated as "accounts cards customers users products misc auth"

**Comment by TaniaSarkar89** [comment]
This would be worked as part of Sprint 19. Created JIRA ticket: https://firstdatateam.atlassian.net/browse/PORT-5009 to track progress of the same.

**Comment by sfiserv** [comment]
Closing this issue as no further issue from client.
