### ISSUE TITLE
Query parameter is not passing  value in request for below API

### ISSUE THREAD

**Issue by ravibhushan12** [Fiserv/Support#170]
- List Plans

Page

FirstVision >> APAC >> API Explorer >>Account Management >> List Plans

Describe the bug
In the planList API, businessUnit query parameter is only passing "0" in the request even though we pass different value like 700,701,600 etc.

To Reproduce

FirstVision >> APAC >> API Explorer >>Account Management >> List Plans
In businessUnit query field pass the value 700 .
Expected: Portal should pass the whole value as 700 as value of  businessUnit  in the request to the server application.
Actual: It is only passing "0" as value of businessUnit  parameter in the request.
![image](https://user-images.githubusercontent.com/101162417/177745757-25b8420d-c69b-4654-bf99-cca4b7f0c13b.png)

**Comment by sfiserv** [comment]
closing this issue as it is a duplicate
https://github.com/Fiserv/Support/issues/171
