### ISSUE TITLE
Portal is not passing query parameter value in request for List Plan API

### ISSUE THREAD

**Issue by tarunfiserv** [Fiserv/Support#171]
Correct value of **businessUnit** query parameter is not passing in the request for List Plan API

**Page** 

FirstVision >> APAC >> API Explorer >>Account Management >> List Plans

**Describe the bug**
In the List Plans API, businessUnit query parameter is only passing "0" in the request even though we pass different value like 700,701,600 etc in query parameter field. This is happening only for this API.

**To Reproduce**

FirstVision >> APAC >> API Explorer >>Account Management >> List Plans

In **businessUnit** query field, pass the value as 700.

**Expected:** Portal should pass the whole value as 700 as value of businessUnit in the request to the server application and API should throw error but API gives successful response.
**Actual**: It is only passing "0" as value of business Unit parameter in the request.

![image](https://user-images.githubusercontent.com/100914278/178466216-c9b7ffbf-40b0-4e01-b3e0-4d301049ca48.png)

**Comment by sfiserv** [comment]
@TaniaSarkar89 I have created a jira to track these issues
 https://firstdatateam.atlassian.net/browse/PORT-4849

**Comment by TaniaSarkar89** [comment]
Hi @AwaneeshSrivastava  @tarunfiserv,
Please take a look into our server logs, we are sending the updated Business Unit as '700'.

`time="2022/08/23 22:14:32.579920147Z UTC" level=debug msg="Request body: '{\"requestType\":\"GET\",\"requestPath\":\"/v1/accounts/0006000011000000137/planList?continuationToken= &businessUnit=700\",\"requestBody\":{},\"requestHeaders\":{\"Authorization\":\"Bearer eyJhbGciOiJSUzI1NiJ9.eyJzY29wZSI6ImFsbCIsImNsaWVudF9pZCI6IlBPQ19OQUJfRGV2IiwiZmlyc3RWaXNpb25JZCI6IjAwMDAwQVVOQUIiLCJleHAiOjE3NTAzNTc4MDB9.qYzJ5krS5F1shsACN3qcVmpF7zOB8uhE28TvjI37aDAP3ZDMONm0947eRxnWo0AkBdmY6JMDtRH-hYpgEiTg_VrjlkimjeSjdJDEzjLoDgNqVV3bCqY-SuAczan2bJs58L3iXgUWKhj7f9ax9-SUfkFRwX4ELWHrnUA926c4Il-ISoH-g-t-yljLxAzg2Yb9n_8LgYGgvC-1g5ntmzLtpxq6JHCsJM7LCOwhE7tSfeqq9ie5FknUuQuCqFd9wTemDe_-BAzYCVzDLLbq_Ath3HTYoKP-hDRuJAVybizYRQ-YIclAz6OGg9JKrDmZHe3HEOb5U-gKLMf_Mpt4UprW4w\",\"X-Correl-Id\":\"ABC123\"},\"apiFullPath\":\"/v1/accounts/{accountId}/planList\"}'" clientIp=104.129.205.29 requestId=ae8f310d-e83e-44b0-b94a-c4ccbc5b89ef
time="2022/08/23 22:14:32.579989048Z UTC" level=debug msg="Request Path: /v1/accounts/0006000011000000137/planList?continuationToken= &businessUnit=700" clientIp=104.129.205.29 file=live_sandbox.go function=ExecuteLiveSandBox processID=1 requestId=ae8f310d-e83e-44b0-b94a-c4ccbc5b89ef
time="2022/08/23 22:14:32.580045848Z UTC" level=debug msg="Request header 'Accept' = '[*/*]'" clientIp=104.129.205.29 requestId=ae8f310d-e83e-44b0-b94a-c4ccbc5b89ef
time="2022/08/23 22:14:32.580054049Z UTC" level=debug msg="Request header 'Content-Type' = '[application/json]'" clientIp=104.129.205.29 requestId=ae8f310d-e83e-44b0-b94a-c4ccbc5b89ef
time="2022/08/23 22:14:32.580061049Z UTC" level=debug msg="Request header 'X-Correl-Id' = '[ABC123]'" clientIp=104.129.205.29 requestId=ae8f310d-e83e-44b0-b94a-c4ccbc5b89ef
time="2022/08/23 22:14:32.580071249Z UTC" level=debug msg="Request header 'Authorization' = '[Bearer eyJhbGciOiJSUzI1NiJ9.eyJzY29wZSI6ImFsbCIsImNsaWVudF9pZCI6IlBPQ19OQUJfRGV2IiwiZmlyc3RWaXNpb25JZCI6IjAwMDAwQVVOQUIiLCJleHAiOjE3NTAzNTc4MDB9.qYzJ5krS5F1shsACN3qcVmpF7zOB8uhE28TvjI37aDAP3ZDMONm0947eRxnWo0AkBdmY6JMDtRH-hYpgEiTg_VrjlkimjeSjdJDEzjLoDgNqVV3bCqY-SuAczan2bJs58L3iXgUWKhj7f9ax9-SUfkFRwX4ELWHrnUA926c4Il-ISoH-g-t-yljLxAzg2Yb9n_8LgYGgvC-1g5ntmzLtpxq6JHCsJM7LCOwhE7tSfeqq9ie5FknUuQuCqFd9wTemDe_-BAzYCVzDLLbq_Ath3HTYoKP-hDRuJAVybizYRQ-YIclAz6OGg9JKrDmZHe3HEOb5U-gKLMf_Mpt4UprW4w]'" clientIp=104.129.205.29 requestId=ae8f310d-e83e-44b0-b94a-c4ccbc5b89ef
time="2022/08/23 22:14:32.580089549Z UTC" level=info msg="Sending GET request to 'https://stg34.visionplus.io/apidev/v1/accounts/0006000011000000137/planList?continuationToken= &businessUnit=700'" clientIp=104.129.205.29 requestId=ae8f310d-e83e-44b0-b94a-c4ccbc5b89ef
time="2022/08/23 22:14:32.580547155Z UTC" level=info msg="Status code: 200" clientIp=10.130.3.35 requestId=70980762-9868-43d6-8054-2f60143ef8ed`

Also you can confirm it from the code snippet and see the parameter values change, screenshot attached here for reference:
![image](https://user-images.githubusercontent.com/74629095/186452231-ed7ecf47-c473-4c96-a83c-60ef50b3c8da.png)

I also noticed that for this endpoint: **_/v1/accounts/{accountId}/blockUnblock_** , when passing businessUnit as 700 it is throwing a 404 error which means that the rest of the endpoints are working as it is. 
![image](https://user-images.githubusercontent.com/74629095/186454873-d31156da-5e5c-49fc-8c98-8727bbe1f381.png)

At Dev Studio end we do not have any customization at individual end point level. 
So will request you to kindly look at your end.

Thanks!

**Comment by sfiserv** [comment]
Closing this Issue based on the above comments and the explanation in the https://firstdatateam.atlassian.net/browse/PORT-4849.
