### ISSUE TITLE
GET Operation Sample not Supported by the Mock Server

### ISSUE THREAD

**Issue by tsegurajimen** [Fiserv/Support#172]
Hi @TaniaSarkar89, @acho-fiserv and Team,

As you know when an API is defined as a GET according REST standards, it implies that there's no body request structure because all the data will be sent as part of the path, thru headers, path parameters or query parameters. 

If we take this constraint of how a mock server works, there's no way to link a request sample (as we do for POST and PUT APIs) because there is no request body, but samples to each parameter can be defined, and response samples can be easily link because the response body works in the same way as the other two methods.

It means that the Dev Portal should support at least one sample for a GET API, where path parameters and request body are already defined in the OpenAPI specification, so the **"Run" button should work fine for a GET operation** as postman tool does it.

The portal displays the parameters samples in the Code Snipped section but Run button doesn't work for this type of operations:
https://dev-developer.fiserv.com/product/BankingHub/api/?type=get&path=/banking/bsm/v1/accounts/{accountId}/transactions&branch=develop&version=11.0.0
![image](https://user-images.githubusercontent.com/81706748/178602375-84c4a3f2-ce44-4f02-8ba3-b041c5700bb4.png)

Please find bellow a GET Account Details API sample, where we have defined all the header, path and query parameters and response body:

**Swagger openAPI Spec:**

Headers, path and query parameters defined:
![image](https://user-images.githubusercontent.com/81706748/178597850-2c823a7c-2c4b-478c-a26d-7fd06c5f8207.png)

Response Body Defined:
![image](https://user-images.githubusercontent.com/81706748/178599525-b0c8b894-fe58-475e-9544-fead2c46aba3.png)

**Postman Sample:**

Headers, path and query parameters defined:

![image](https://user-images.githubusercontent.com/81706748/178599721-74c7ec35-da2a-4b55-9bd0-2e62f47291b7.png)

![image](https://user-images.githubusercontent.com/81706748/178600933-c4fcb3a2-2f6c-412a-a328-145966ee77d2.png)

Response we got from the local prism mock server:

![image](https://user-images.githubusercontent.com/81706748/178601018-bf8c0e7e-2ffa-45a0-a28e-1e17746cbdf3.png)

![image](https://user-images.githubusercontent.com/81706748/178601168-6d124a77-fa09-4c0d-96e8-945e7b1c3daa.png)

Please find attached the postman collection with the sample above and the entire response we got from the mock server.

[Get Transaction List Postman Sample.zip](https://github.com/Fiserv/Support/files/9097112/Get.Transaction.List.Postman.Sample.zip)

Let us know if you need any other information.

Thanks in advance!!

cc:
@bobburghardt @fiservakshay

**Comment by TaniaSarkar89** [comment]
Opened JIRA ticket to track this issue : https://firstdatateam.atlassian.net/browse/PORT-4664

**Comment by TaniaSarkar89** [comment]
Hi @tsegurajimen this issue is now resolved and you can test it in our DEV env. Please see the screenshot below. 
![image](https://user-images.githubusercontent.com/74629095/180478496-aeb55ea7-3e05-4f34-8e7b-a5b743177832.png)

**Comment by tsegurajimen** [comment]
> Hi @tsegurajimen this issue is now resolved and you can test it in our DEV env. Please see the screenshot below. ![image](https://user-images.githubusercontent.com/74629095/180478496-aeb55ea7-3e05-4f34-8e7b-a5b743177832.png)

Thanks a lot! Issue was solved and now GET APIs are working as expected.

![image](https://user-images.githubusercontent.com/81706748/180486264-653de7af-c3f2-4e40-9203-18d810d3a1b5.png)
