### ISSUE TITLE
Bug report broken link in digital payment

### ISSUE THREAD

**Issue by BLACKJAXXX** [Fiserv/Support#173]
# Reporting new issue for [NAME] (Tenant/Product)

**Region** (if applicable)
The region of a user reporting the bug.

**Page**
Path of the page where the problem exists.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Tablet (please complete the following information):**
 - Device: [e.g. iPad]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by TaniaSarkar89** [comment]
Hi @BLACKJAXXX which product are you looking for on Developer Studio?

**Comment by BLACKJAXXX** [comment]
Hi,
I was just corresponding in regards to the software for FiserV Digital
Payment link. I originally though the link was broken but it was just
delayed. Thank you for the follow up.

-Jeremy
