### ISSUE TITLE
Fiserv Developer Studio

### ISSUE THREAD

**Issue by MWolk-CXI** [Fiserv/Support#174]
I am trying to register for Fiserv Developer Studio and it doesn't appear to be available. Is there a way i can register?

Thanks,

**Comment by TaniaSarkar89** [comment]
Hello @MWolk-CXI ,
At the moment, Registration on Developer Studio ( https://developer.fiserv.com ) is not available in our production environment yet. But we are working towards enabling it soon. 

However would like to know which company you work for and which product are you interested to integrate with, 
so that we can direct you to the appropriate product team if required ?

Thanks!

**Comment by MWolk-CXI** [comment]
Hello, Thank you for the quick response. I work for a publicly traded company called Currency Exchange International (CXI). We are an international services provider to financial institutions in the US. We share a mutual client base and have clients wanting to setup a core integration with Fiserv to our Software platform. We are hoping to plug into the Fiserv api, as we have done with other core software providers to better service our mutual client base, so we are needing to discuss development options for that. Please let me know if i can provide more information.

**Comment by TaniaSarkar89** [comment]
Thanks for the information @MWolk-CXI . 
You can check out the products in our Financial Institution page: https://developer.fiserv.com/financial-institutions 
Additionally, if you could let us know which specific product you're looking to integrate with, we can assist you in getting in touch with that team right away!

**Comment by MWolk-CXI** [comment]
Thank you for the info. We are looking to get in contact with the team responsible for integrating into Fiservs DNA core.

Thanks!

One Provider, One Platform

Mitchell Wolk
Client Support Manager

Currency Exchange International
6675 Westwood Boulevard, Suite 300, Orlando, FL 32821

Email: ***@***.*** | www.ceifx.com<http://www.ceifx.com/>
Direct: 407-536-5493 | Toll Free: 888-998-3948

[CXI Logo]
[LinkedIn]<https://www.linkedin.com/company/currency-exchange-international>
[Facebook]<https://facebook.com/currencyexchangeinternational>
[Twitter]<https://twitter.com/ceifx>

This e-mail, its attachments and any other items transmitted with it are covered by the Electronic Communications Privacy Act, 18 U.S.C. "2520-2521" and are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you are not the intended recipient please notify us at ***@***.******@***.***> and delete this e-mail and any attachments from your system. Thank you.

**Comment by TaniaSarkar89** [comment]
Hi Mitchell (@MWolk-CXI ), thank you for the information!

Bob (@bobburghardt) and his Team can assist you in any feedbacks or concerns you have regarding the Banking Hub [https://developer.fiserv.com/product/BankingHub] product on Developer Studio.

For any other concerns please feel free to reach out to us!

Thanks!

**Comment by bobburghardt** [comment]
@MWolk-CXI - thanks for contacting us regarding the Developer Studio and your interest in integrating to our DNA core.  As Tania indicated, we are in the process of increasing the capabilities of our Developer Studio to help ease fintech integration to cores.  In the meantime, you can have our mutual client that uses DNA to contact their DNA Client Partner.  The Client Partner can engage with the client to determine the integration paths available.

We'll also forward your information on to our Product Team, as they are keeping track of who is interested in integrating.

Thanks again for your information, and your time.

**Comment by MWolk-CXI** [comment]
Thank you! We will coordinate with our client on reaching out to their rep.

One Provider, One Platform

Mitchell Wolk
Client Support Manager

Currency Exchange International
6675 Westwood Boulevard, Suite 300, Orlando, FL 32821

Email: ***@***.*** | www.ceifx.com<http://www.ceifx.com/>
Direct: 407-536-5493 | Toll Free: 888-998-3948

[CXI Logo]
[LinkedIn]<https://www.linkedin.com/company/currency-exchange-international>
[Facebook]<https://facebook.com/currencyexchangeinternational>
[Twitter]<https://twitter.com/ceifx>

This e-mail, its attachments and any other items transmitted with it are covered by the Electronic Communications Privacy Act, 18 U.S.C. "2520-2521" and are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you are not the intended recipient please notify us at ***@***.******@***.***> and delete this e-mail and any attachments from your system. Thank you.
