### ISSUE TITLE
Got 403 fobidden when setup first data payment

### ISSUE THREAD

**Issue by ahtd3** [Fiserv/Support#175]
I'm from VietNam

I was setup the payment follow api https://docs.firstdata.com/org/gateway/docs/api#create-primary-transaction but still get 403 Forbidden errors
Do I make any mistake? Please reply me ASAP. Thanks a lot.
https://user-images.githubusercontent.com/99788113/181467657-9e289583-ca6c-4c6b-9539-357e424d891a.png
https://user-images.githubusercontent.com/99788113/181470145-e33a81b9-3db5-477b-b180-c494f9a4488d.png

**Comment by TaniaSarkar89** [comment]
Hi @ahtd3 thank you for reaching out to us! Could you please let us know which company you work for ? 

@eliascanaza  could you please assist @ahtd3 with his issue.

Thanks!

**Comment by ahtd3** [comment]
Yes, my company is AHT JSC from VietNam and our customers want to use first data payment for their website.

Thanks for reply me!

**Comment by TaniaSarkar89** [comment]
Hi @jslingerland  could you please assist @ahtd3.

**Comment by sfiserv** [comment]
Closing this issue.
