### ISSUE TITLE
Preview Branch Navigation Not Persistent

### ISSUE THREAD

**Issue by wwfiserv** [Fiserv/Support#176]
# Reporting new issue for Commerce Hub

**Page**
All pages while in Preview branch
https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Getting-Started/Getting-Started-General.md&branch=preview

https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Release-Notes-Alerts/Release-Notes.md&branch=preview

**Describe the bug**
When in the Preview branch and you select a link to another location from within a document it doesn't stay in the preview branch and instead takes you to back to the Active branch.

When clicking a link as provided above sometimes it does not load the Preview branch even though it shows Preview is selected in the dropdown and it has to be reselected.

**Expected behavior**
When navigating in the Preview branch and clicking a link it should stay in the preview branch.

**Comment by TaniaSarkar89** [comment]
Opened JIRA ticket: https://firstdatateam.atlassian.net/browse/PORT-4760 to track this issue.

**Comment by sfiserv** [comment]
Created a new jira https://firstdatateam.atlassian.net/browse/PORT-4848 to track this issue

**Comment by sfiserv** [comment]
@wwfiserv the issue has been fixed in the dev env for your verification. 
https://firstdatateam.atlassian.net/browse/PORT-4848.

**Comment by sfiserv** [comment]
@wwfiserv this fix is in dev for your verification. Moving this issue to next milestone to be verified and closed by @wwfiserv

**Comment by wwfiserv** [comment]
@TaniaSarkar89 @sfiserv found two bugs
- When navigating from API Explorer Preview to documents, switches back to Active. Example https://dev-developer.fiserv.com/product/CommerceHub/api/?type=post&path=/payments/v1/charges&branch=preview&version=1.3.0 and clicking "capture" in the last sentence goes back to the Active https://dev-developer.fiserv.com/product/CommerceHub/docs/?path=docs/Resources/API-Documents/Payments/Capture.md
- If you are in a document and switch the branch it doesn't change the API Explorer to the Preview branch, you have to select Preview a second time and it updates.

**Comment by sfiserv** [comment]
New tracking ticket is created to reproduce and verify the new issues found by @wwfiserv 
https://firstdatateam.atlassian.net/browse/PORT-5053

**Comment by sfiserv** [comment]
@wwfiserv please verify the fix for the new issue are fixed please validate it.
https://firstdatateam.atlassian.net/browse/PORT-5053

**Comment by sfiserv** [comment]
closing this issue as no issues reported from client.
