### ISSUE TITLE
Clarification on Various Documentation Sources

### ISSUE THREAD

**Issue by ncalteen** [Fiserv/Support#178]
Hi Fiserv team,

(Firstly, apologies if this is the incorrect place to submit this request)

I'm a Tech Writer with the Google Pay and Google Wallet team, and have been looking over some of the documentation for payment service providers that support merchant integration with Google Pay. I was recently reading the [Payeezy documentation](https://github.com/payeezy/google_pay/blob/master/README.md) and wanted to do the same with [Internet Payment Gateway](https://docs.firstdata.com/org/gateway). At that point, I started finding multiple sources of similar documentation, and wanted to get some clarification on which is the correct information to reference.

Could you please assist in confirming the status of each of the following pages/repos?

* [Payeezy - Select your integration](https://developer.payeezy.com/select-your-integration-method)
  * The Google Pay option links to [payeezy/google_pay](https://github.com/payeezy/google_pay)
* [Fiserv - Internet Payment Gateway](https://docs.firstdata.com/org/gateway)
  * This appears to be from the public archived repo [Fiserv/Internet-Payment-Gateway](https://github.com/Fiserv/Internet-Payment-Gateway)
  * The [Google Pay docs](https://docs.firstdata.com/org/gateway/node/163) appear to be from the [same repo](https://github.com/Fiserv/Internet-Payment-Gateway/blob/develop/docs/Features/GooglePay/GooglePay.md).
* [Fiserv - Commerce Hub](https://developer.fiserv.com/product/CommerceHub)
  * This appears to be from the same repo [https://github.com/Fiserv/Commerce-Hub](https://github.com/Fiserv/Commerce-Hub)
  * The [Google Pay docs](https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Online-Mobile-Digital/Wallets-AltPayments/Google-Pay/Google-Pay.md&branch=main) appear to be from the same repo [https://github.com/Fiserv/Commerce-Hub/tree/develop/docs/Online-Mobile-Digital/Wallets-AltPayments/Google-Pay](https://github.com/Fiserv/Commerce-Hub/tree/develop/docs/Online-Mobile-Digital/Wallets-AltPayments/Google-Pay)
* [Fiserv EMEA Developer Portal](https://fiserv.dev/)

Any guidance would be greatly appreciated!

**Comment by wwfiserv** [comment]
@ncalteen for Commerce Hub we don't use a Git repo, this is only used for maintaining documentation you will want to review the documentation in our Developer Portal (https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Online-Mobile-Digital/Wallets-AltPayments/Google-Pay/Google-Pay.md&branch=main) which is Fiserv's go forward website for our products. Legacy products Payeezy/IPG) however will still be in their old location, and the UK in their website.

**Comment by ncalteen** [comment]
Thank you for the information, this helps clear things up. Going forward, where should developers submit questions/corrections for the following documentation?

* Commerce Hub
* Payeezy
* IPG

**Comment by wwfiserv** [comment]
@ncalteen this Git repository is where a ticket can be opened using the help option on the respective article. For the other products I can not say, I would try the contact forms on each respective site.

**Comment by ncalteen** [comment]
Thank you! I will use the help option for the Commerce Hub docs then. Appreciate the help.
