### ISSUE TITLE
Google Pay: Supported Android Devices Link

### ISSUE THREAD

**Issue by ncalteen** [Fiserv/Support#179]
**Page**
https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Online-Mobile-Digital/Wallets-AltPayments/Google-Pay/Google-Pay.md&branch=main

**Describe the bug**
The link to supported Android devices currently directs to https://support.google.com/android/answer/10248227 (Fix issues with your Play Protect certification status).

**Expected behavior**
This should instead point to https://support.google.com/wallet/answer/12059331?hl=en (Download the Google Wallet app), which lists the device prerequisites.

**Comment by wwfiserv** [comment]
@ncalteen We have made the updates, thanks for your feedback.
