### ISSUE TITLE
Google Pay: Integration Documentation

### ISSUE THREAD

**Issue by ncalteen** [Fiserv/Support#180]
**Page**
* https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Online-Mobile-Digital/Wallets-AltPayments/Google-Pay/Google-Pay-Web-REST.md
* https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Online-Mobile-Digital/Wallets-AltPayments/Google-Pay/Google-Pay-App.md

**Describe the bug**
Several documentation update requests, see below. This would apply to both [Android](https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Online-Mobile-Digital/Wallets-AltPayments/Google-Pay/Google-Pay-App.md) and [Web](https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Online-Mobile-Digital/Wallets-AltPayments/Google-Pay/Google-Pay-Web-REST.md) documentation.

* [How it works](https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Online-Mobile-Digital/Wallets-AltPayments/Google-Pay/Google-Pay-Web-REST.md#how-it-works) - In step 3, "google pay" should be replaced with "Google Pay"
* [Request Variables](https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Online-Mobile-Digital/Wallets-AltPayments/Google-Pay/Google-Pay-Web-REST.md#request-variables) - Clarify where merchants acquire a Google Pay merchant ID. If developers should request their own through Google, direct them to the [Google Pay & Wallet Console](https://pay.google.com/business/console/home). Example instructions can be found in the *Google Pay & Wallet Console* section below.
* [Step 1: Configure Google Pay](https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Online-Mobile-Digital/Wallets-AltPayments/Google-Pay/Google-Pay-Web-REST.md#step-1-configure-google-pay) - Include either links to or example client-side code snippets to instantiate the process below
  * Web ([reference](https://developers.google.com/pay/api/web/guides/tutorial))
  * Android ([reference](https://developers.google.com/pay/api/android/guides/tutorial))
    * Create a `PaymentsClient` object (steps 1 through 5)
    * Determine readiness to pay and load the payment button (steps 6 through 7)
    * Create a `PaymentDataRequest` object and register the button handler (steps 8 through 9)
* [API Explorer - Charges](https://developer.fiserv.com/product/CommerceHub/api/?type=post&path=/payments/v1/charges&branch=main&version=1.2.0) - The payment `source` parameter is listed as a `string` type, but the [payload example](https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Online-Mobile-Digital/Wallets-AltPayments/Google-Pay/Google-Pay-Web-REST.md#payload-example) in the Google Pay documentation shows an hash/dictionary.
* [See Also](https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Online-Mobile-Digital/Wallets-AltPayments/Google-Pay/Google-Pay-Web-REST.md#see-also) - Include a link to the [Google Pay brand guidelines](https://developers.google.com/pay/api/web/guides/brand-guidelines) for button guidelines.
* [See Also](https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Online-Mobile-Digital/Wallets-AltPayments/Google-Pay/Google-Pay-Web-REST.md#see-also) - Include a link to the [Google Pay API sample for Android](https://github.com/google-pay/android-quickstart/tree/master).

**Other**

* Can you add information on what steps are required by the merchant to move to production and handle real transactions? Example information in the *How to begin processing production transactions* section below.

##### Google Pay & Wallet Console

The [Google Pay & Wallet Console](https://pay.google.com/business/console/home) is a one-stop location for merchants to manage Google Pay products and services for their business, change how their business appears to customers in the Google Pay app, and connect business identities to payments profiles.

The Business Profile page holds information about you as a business. To use most Google Pay & Wallet Console products and services, you need a completed and approved Business Profile. More information about business profiles can be found [at this support article](https://support.google.com/google-pay-and-wallet-console/answer/10877772).

To access the Google Pay & Wallet Console, all users must accept the Google Pay [Terms of Service](https://payments.developers.google.com/terms/sellertos) and [Acceptable Use Policy](https://payments.developers.google.com/terms/aup).

**How to obtain a Google merchant ID**

1. Navigate to the [Google Pay & Wallet Console](https://pay.google.com/business/console/home).
1. If the merchant has not done so already, provide the public business name and location and agree to the Google Pay [Terms of Service](https://payments.developers.google.com/terms/sellertos) and [Acceptable Use Policy](https://payments.developers.google.com/terms/aup).
1. Select **Business Profile**.
1. Complete the **Business identity** and **Business information** sections.
1. Once approved, the merchant ID will be displayed in the top right corner of the console, next to the username.

##### How to begin processing production transactions [source](https://developers.google.com/pay/api/android/guides/test-and-deploy/deploy-your-application)

**Android**

To start processing real transactions, verify that your APK is signed with a release key, not a debug key. Then, set the environment to `WalletConstants.ENVIRONMENT_PRODUCTION`. See the [Deploy your application guide](https://developers.google.com/pay/api/android/guides/test-and-deploy/deploy-your-application) for more information.

```java
import com.google.android.gms.wallet.WalletConstants;

public static final int PAYMENTS_ENV = WalletConstants.ENVIRONMENT_PRODUCTION;

Wallet.WalletOptions walletOptions = new
        Wallet.WalletOptions.Builder().setEnvironment(PAYMENTS_ENV).build();
```

**Web and mobile**

To start processing real transactions, set your PaymentsClient instance to use the PRODUCTION environment. See the [Deploy production environment guide](https://developers.google.com/pay/api/web/guides/test-and-deploy/deploy-production-environment) for more information.

```javascript
// PRODUCTION environment
const paymentsClient =
    new google.payments.api.PaymentsClient({environment: 'PRODUCTION'});
```

**Comment by wwfiserv** [comment]
@ncalteen We have made the updates, thanks for your feedback.

- We are trying to limit the "Google" specific steps and information in our documentation and direct them to your tech docs to prevent them from getting outdated so some of the items were not added.
- The payment source will not show in the API Explorer this is currently a limitation of our YAML structure. However both the example in the API Explorer dropdown and the example in the Google Pay documents outline the correct structure `  "source": {
    "sourceType": "GooglePay",`
