### ISSUE TITLE
Unable to Link to Older API Versions/Navigation Doesn't Update

### ISSUE THREAD

**Issue by wwfiserv** [Fiserv/Support#181]
# Reporting new issue for Commerce Hub

**Page**
API Explorer (all environments)

https://dev-developer.fiserv.com/product/CommerceHub/api/?type=post&path=/payments/v1/charges/{transactionId}/refund&branch=develop&version=1.0.0
https://dev-developer.fiserv.com/product/CommerceHub/api/?type=post&path=/payments/v1/charges/{transactionId}/refund&branch=develop&version=1.1.0
https://dev-developer.fiserv.com/product/CommerceHub/api/?type=post&path=/payments/v1/charges/{transactionId}/Cancel&branch=develop&version=1.0.0

**Describe the bug**
Commerce Hub has older endpoints that are not available in newer versions, example in 1.1.0 Cancel was changed to Cancels, and in 1.2.0 Refund was changed to Refunds. These are not deprecated yet and therefore not viable for the Previous branch solution.

Problem 1: When you  navigate to an endpoint and change to a lower version 1.1.0 or 1.0.0 the left navigation does not update to reflect the endpoints applicable to that API file.
Problem 2: Unable to link to the older endpoints by adding a link to the description because the links don't work and redirect to the first API in the list.

**Expected behavior**
Should be able to access the old endpoints from other versions via link or via the left navigation updating to the current APIs endpoints. It appears the left Nav documentation and left Nav API Explorer render separately, and once rendered doesn't change unless the Active/Preview dropdown is selected.

**Comment by sfiserv** [comment]
Tracking ticket for this issue has been created https://firstdatateam.atlassian.net/browse/PORT-4894

**Comment by wwfiserv** [comment]
@TaniaSarkar89 it doesn't appear the left navigation bar is updating when you chance the version. Example go to charges and change to 1.0.0 the left nav stays the same and doesn't show the old refund and cancel endpoints.

**Comment by sfiserv** [comment]
@wwfiserv This ticket is ready for client verification

**Comment by wwfiserv** [comment]
@sfiserv getting an unable to create APIs error when I try to go directly into Commerce Hub, if I use one of the links above it goes to the correct location but when I select any document in the left navigation I'm getting a 404.

**Comment by sfiserv** [comment]
@wwfiserv would you please add some screenshot for the error. I am unable to recreate the issue. I tried using the direct url for commerce hub and also the above links provided.

**Comment by wwfiserv** [comment]
@sfiserv it appears the 404 was resolved with the patch for the bug and the API Explorer is still rendering, however below are my current observations in Dev.

This is Charges 1.3.0 and the left Nav
![image](https://user-images.githubusercontent.com/75692745/197207978-c7e5707f-3f80-42d9-accc-ea4753748256.png)

When switching to 1.2.0 which still hand Capture doesn't display in the Nav
![image](https://user-images.githubusercontent.com/75692745/197208329-b861cf54-52b1-4ae9-9179-f0af2e50a729.png)

Linking does work however allows you to select branches that are not valid (Refund was changed to refunds in 1.3.0 and 1.2.0), similar with Cancel and Capture
![image](https://user-images.githubusercontent.com/75692745/197209136-b3211b74-2111-4d5a-a61b-45775f979242.png)

If you go back to Charges and select a newer version the navigation doesn't update (1.3.0 should not have Capture)
![image](https://user-images.githubusercontent.com/75692745/197209453-5688e9f8-b835-400a-b94f-f947887c6b6b.png)

If you select another endpoint from 1.3.0 Charges that is valid (example Refund) it stays 1.3.0, if you select an invalid branch for the version (example Capture) it goes to 1.0.0. Navigating to another endpoint then keeps you in 1.0.0.

**Comment by acho-fiserv** [comment]
this will be fixed as part of the new left nav work

**Comment by sfiserv** [comment]
@wwfiserv would you be able to please verify if this issue still persisit.

**Comment by wwfiserv** [comment]
@sfiserv it looks like with the new layout it correctly changes the nav bar

**Comment by sfiserv** [comment]
thanks for the update. Closing this issue.
