### ISSUE TITLE
DevStudio is displaying 200 APIs only

### ISSUE THREAD

**Issue by eliascanaza** [Fiserv/Support#183]
**Region** (optional)
EMEA and NA

**Is your feature request related to a problem? Please describe.**
In OPTIS we are migrating all services from DevPortal to DevStudio and we have more services and now many of them are not displaying in Optis because the limit issue is 200 APIs, after that amount the extra services are not displaying in DevStudio.

**Describe the solution you'd like**
We are expecting that DevStudio should display all services that we are uploading, in the future we will have more services and all of them needs to be displayed on DevStudio. 

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by sfiserv** [comment]
@eliascanaza this feature is under development and getting worked on. . We will update you on this once the feature is ready.
tracking ticket https://firstdatateam.atlassian.net/browse/PORT-4973

**Comment by sfiserv** [comment]
Adding a new tracking ticket for this issue.
https://firstdatateam.atlassian.net/browse/PORT-5475

**Comment by sfiserv** [comment]
@eliascanaza  please verify the fix.
<img width="1066" alt="image" src="https://user-images.githubusercontent.com/87097017/213584186-3d6c543a-307e-454c-9f3a-042f547568d2.png">
