### ISSUE TITLE
unable to register my profile

### ISSUE THREAD

**Issue by austinwebdeveloper** [Fiserv/Support#184]
# Reporting new issue for [NAME] (Tenant/Product)

**Region** (if applicable)
The region of a user reporting the bug.

**Page**
[Path of the page where the problem exists.](https://www.fiserv.com/en/account/create-profile.html)

**Describe the bug**
I click on Save -- nothing happens 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Tablet (please complete the following information):**
 - Device: [e.g. iPad]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sfiserv** [comment]
@austinwebdeveloper would you be able to give us the details of this issue you reported.

**Comment by austinwebdeveloper** [comment]
I believe the issue is with captcha. Captcha didn't show up on chrome. (Due to adblocker?) I tried to hit submit but there was no indication that captcha was not working and nothing happens. So, I was unable to register.

**Comment by sfiserv** [comment]
@austinwebdeveloper can u please provide more details/screenshots which env you are facing issue

**Comment by sfiserv** [comment]
closing this issue as no further information/issue reasons provided by the reporter.
