### ISSUE TITLE
Code snippet showing query parameters as headers

### ISSUE THREAD

**Issue by AwaneeshSrivastava** [Fiserv/Support#185]
# Reporting new issue for  FirstVision-APAC

**Region** (if applicable)
APAC

**Page**
Account Management -> List Plans --> Code Snippet

**Describe the bug**
The  parameters that are marked as query parameter in the Swagger are appearing as Header parameter in code snippet

**To Reproduce**
1. Go to 'FirstVision-APAC'
2. Click on 'Account Management'
3. Scroll down to 'List Plans'
4. See Code Snippet

**Expected behavior**
Expectation is parameters defined as query parameters in Swagger file should appear as query parameter in the code-snippet

**Screenshots**
![image](https://user-images.githubusercontent.com/91457011/186568939-832134e4-3989-4316-9b4c-fe42d4a1d3c6.png)

**Comment by sfiserv** [comment]
https://firstdatateam.atlassian.net/browse/PORT-4944  Tracking ticket for this issue

**Comment by sfiserv** [comment]
@AwaneeshSrivastava  This fix is now in dev for client verification.

**Comment by sfiserv** [comment]
Closing this ticket as no issues reported by client on this fix.
