### ISSUE TITLE
AcceptanceSolutionsAPAC- Upload files

### ISSUE THREAD

**Issue by rajendrakumarfiserv** [Fiserv/Support#186]
**Region** (optional)
**GBS APAC**

**Description**
Unable to upload files using below api url in devstudio
**https://dev-developerstudio.fiserv.com/product/AcceptanceSolutionsAPAC/api/?type=post&path=/boardinggateway/externalboarding/secure/document/{appUrn}&branch=develop&version=1.0.2**

we need a new feature for upload files using document upload api in devstudio, Please refer the following swagger's screenshot

![image](https://user-images.githubusercontent.com/100661665/186589504-278d77d4-8f39-4a65-9a4f-f160ee44ce2b.png)

Request Body should be multipart form data

![image](https://user-images.githubusercontent.com/100661665/186590683-aaf27454-c0dd-4e02-9186-345ed22ea12e.png)

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by sfiserv** [comment]
Crated a tracking ticket for triage in future. https://firstdatateam.atlassian.net/browse/PORT-4943
