### ISSUE TITLE
Code Snippet - Path Variable Issue

### ISSUE THREAD

**Issue by rajendrakumarfiserv** [Fiserv/Support#187]
# Reporting new issue for AcceptanceSolutionsAPAC

**Region** (if applicable)
APAC

**Page**
https://dev-developerstudio.fiserv.com/product/AcceptanceSolutionsAPAC/api/?type=post&path=/boardinggateway/externalboarding/secure/document/{appUrn}&branch=develop&version=1.0.2

**Describe the bug**
Path variable should be example value in the code snippet section
Ex:-
https://www.uat.fdmerchantservices.com/Externalboarding/secure/document/10000745

**To Reproduce**
STEP 1: Go to below url
https://dev-developerstudio.fiserv.com/product/AcceptanceSolutionsAPAC/api/?type=post&path=/boardinggateway/externalboarding/secure/document/{appUrn}&branch=develop&version=1.0.2

STEP 2: check in Code snippet for path variable
![image](https://user-images.githubusercontent.com/100661665/186598246-f344a32b-e43c-45b3-b7be-c4d501ddcc17.png)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Tablet (please complete the following information):**
 - Device: [e.g. iPad]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sfiserv** [comment]
@rajendrakumarfiserv this fix is now ready for client verification in Dev environment. please validate.

**Comment by sfiserv** [comment]
Closing this ticket as no issue reported by client on this fix.
