### ISSUE TITLE
AcceptanceSolutionsAPAC - Popular Service - increase characters to 500

### ISSUE THREAD

**Issue by rajendrakumarfiserv** [Fiserv/Support#188]
# Reporting new issue for AcceptanceSolutionsAPAC

**Region** (if applicable) 
APAC

**Page**
https://dev-developerstudio.fiserv.com/product/AcceptanceSolutionsAPAC
![image](https://user-images.githubusercontent.com/100661665/186834491-2b636c5f-0edb-4a92-8449-fead7a5afcf8.png)

**Describe the bug**
Popular service is not allowing more than 288 characters and not accepting html tags like <B>

**To Reproduce**
1. Go to https://dev-developerstudio.fiserv.com/product/AcceptanceSolutionsAPAC/
2. Click on  poplar service
3. Scroll side to  point of sale / card present
![image](https://user-images.githubusercontent.com/100661665/186835567-77224928-3b75-4dab-876d-ad04d3d696a9.png)

**Expected behavior**
it should allows 500 characters and html tages in popular service sections

**Screenshots**

**Desktop (please complete the following information):**

**Tablet (please complete the following information):**
 - Device: [e.g. iPad]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sfiserv** [comment]
Created a tracking ticket https://firstdatateam.atlassian.net/browse/PORT-4942

**Comment by TaniaSarkar89** [comment]
Hi @rajendrakumarfiserv, 

The **Popular Services** card only serves as a placeholder to briefly describe the type of service your product is providing. 
And hence character restriction is 200.

However, if you wish to provide additional information regarding the service, kindly do so in the **Related Docs** that are connected to that Popular service. The related docs must be in markdown format, and you can include html tags in the markdown file.

You can follow the below guidelines to add html tags in markdown files.
1. https://www.markdownguide.org/basic-syntax/
2. https://developer.fiserv.com/support/docs/?path=docs/md/extended-syntax.md

Thank you!

Cc: @sfiserv
