### ISSUE TITLE
Renamed and Deleted Articles Showing In Search

### ISSUE THREAD

**Issue by wwfiserv** [Fiserv/Support#192]
# Reporting new issue for Commerce Hub

**Region** (if applicable)
Main

**Page**
https://developer.fiserv.com/search/?q=soft%20descriptors

**Describe the bug**
Searching for renamed article still shows the original name
https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Resources/Guides/Payeezy/Payeezy-Migration-ExtendedFeaturesSoftD.md
https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Resources/Guides/Payeezy/Payeezy-Migration-FeaturesSoftD.md

**Expected behavior**
Search should return the updated named articles
https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Resources/Guides/Payeezy/Payeezy-UpgradetoCH-FeaturesSoftD.md

**Comment by sfiserv** [comment]
Created a tracking ticket for this issue
https://firstdatateam.atlassian.net/browse/PORT-5003
