### ISSUE TITLE
API execution leads to Sandbox execution error. 

### ISSUE THREAD

**Issue by skranganathan** [Fiserv/Support#194]
# Reporting new issue for SnapPay

**Region** (if applicable)
The region of a user reporting the bug.  Chicago

**Page**
Path of the page where the problem exists.
API Explorer / Get Payment Details 

**Describe the bug**
Execute the API and it returns 

{
  "errorCode": 400,
  "errorType": "SANDBOX_EXECUTION_ERROR",
  "message": "400: Bad Request"
}

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Tablet (please complete the following information):**
 - Device: [e.g. iPad]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sfiserv** [comment]
tracking this issue along with other issue in this ticket. https://firstdatateam.atlassian.net/browse/PORT-5184

**Comment by sfiserv** [comment]
@skranganathan  would you be able to provide more information on this issue.

**Comment by TaniaSarkar89** [comment]
Hi @skranganathan this endpoint **_/api/Interop/GetPaymentDetails_** in Production is returning 200 as can be seen from the below screenshot (https://developer.fiserv.com/product/SnapPay/api/?type=post&path=/api/Interop/GetPaymentDetails&branch=develop&version=3.0.0):

<img width="1696" alt="image" src="https://user-images.githubusercontent.com/74629095/196216000-d544f15b-fca4-4627-a543-67bfc3831fcf.png">

**Comment by sfiserv** [comment]
Closing this issue as did not receive any response from client .
