### ISSUE TITLE
Cannot Access API Documentation in Developer Studio Online

### ISSUE THREAD

**Issue by smangiafico** [Fiserv/Support#195]
# Reporting new issue for Developer Studio

**Region** (if applicable)
The region of a user reporting the bug.
United States

**Page**
Path of the page where the problem exists.
https://developer.fiserv.com/product/BankingHub
https://developer.fiserv.com/product/BankingHub/api/?type=post&path=/parties/secured/list&branch=main&version=11.0.0

**Describe the bug**
BankingHub API documentation is not loading in Developer Studio online

**To Reproduce**
1. Go to 'https://developer.fiserv.com/product/BankingHub'
2. See error:  "We are unable to get the list of apis at the moment. Please try again."
3. Go To 'https://developer.fiserv.com/product/BankingHub/api/?type=post&path=/parties/secured&branch=main&version=11.0.0'
4. No information loads on the page and it is blank

**Expected behavior**
I expect to be able to view the API documentation and not get any error messages.

**Screenshots**
Please find attached

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 103.0.5060.114 (Official Build) (64-bit)

**Tablet (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A
![BlankPage](https://user-images.githubusercontent.com/112976776/188711074-8a409b35-4c10-4d61-8814-b48614236664.png)
![ErrorMessage](https://user-images.githubusercontent.com/112976776/188711079-e3d5b25f-4ed1-462d-b3fe-fe294c0bc4ed.png)

**Additional context**

**Comment by sfiserv** [comment]
@smangiafico thank you for notifying us about the issue. Our team is looking into this issue currently. We will post a status update asap its fixed.
Sorry for the inconvenience.

**Comment by sfiserv** [comment]
@smangiafico the issue for the API is resolved. you can now verify it in Production.
