### ISSUE TITLE
API & Secret key generation

### ISSUE THREAD

**Issue by RajeshKFreelancer** [Fiserv/Support#197]
**Region** (optional)
NA

**Is your feature request related to a problem? Please describe.**
For one of my clients, I am trying to use your "/payments/v1/charges" endpoint.  However, in spite of searching many places I am not able to find a provision to generate Merchant ID, API Key & Secret Key which are required to trial run the Api.  The documentation in Support section suggests to login to get to the dashboard and then generate the keys.  But I do not know where I will login!

**Describe the solution you'd like**
Please guide me to the page where I can generate (or get) Merchant ID, API Key & Secret key.

**Describe alternatives you've considered**

**Additional context**

**Comment by sfiserv** [comment]
@RajeshKFreelancer , DevStudio will be releasing the features/information regarding API key generation and the required MID soon . With this release you will be able to have a trial run for the API.
Thank you for your patience.

**Comment by sfiserv** [comment]
@RajeshKFreelancer DevStudio has released the features and information regarding API key generation. please take a look at our production website .https://developer.fiserv.com/
Let us know if you are need help or facing issue for the same.

**Comment by sfiserv** [comment]
closing this issue as no further issue reported by the issue creator.
