### ISSUE TITLE
Download option, shall take only the service that I am working

### ISSUE THREAD

**Issue by eliascanaza** [Fiserv/Support#198]
**Region** (optional)
EMEA and NA

**Is your feature request related to a problem? Please describe.**
In the page of every endpoint, there is one section **Additional resources**, now those options are downloading all API and Postman Collections from all services, but that option shall download only the services (yaml file) that user is reviewing.

For example: in the image shall download Commercial-Card.yaml only

**Describe the solution you'd like**
After hit download link (API or Postman Collections) shall download the specific yaml (API) or json (Postman Collection) file

**Describe alternatives you've considered**
None

**Additional context**

![image](https://user-images.githubusercontent.com/1819754/190005186-8b932566-b4c0-4468-bca7-77dc30cf9a16.png)

**Comment by sfiserv** [comment]
Tracking ticket has been created for this proposed enhancement.
https://firstdatateam.atlassian.net/browse/PORT-5095

**Comment by eliascanaza** [comment]
Can I know what the status is?  this problem is still happening.
