### ISSUE TITLE
Product Layout Card Linking 404

### ISSUE THREAD

**Issue by wwfiserv** [Fiserv/Support#199]
# Reporting new issue for Commerce Hub

**Region** (if applicable)
All

**Page**
https://dev-developer.fiserv.com/product/CommerceHub

**Describe the bug**
Cards that do not have a link: still add the prefix link of https://dev-developer.fiserv.com/product/CommerceHub/docs/ unlike cards that are made with markdown https://dev-developer.fiserv.com/product/CommerceHub/docs/?path=docs/Getting-Started/Getting-Started-General.md&branch=develop

**To Reproduce**
Click on Digital Wallets and then Samsung Pay
Click on Omnichannel and then Connected Commerce

**Expected behavior**
The cards should display with no link to click similar to how cards in markdown work

**Comment by sfiserv** [comment]
created this ticket for tracking https://firstdatateam.atlassian.net/browse/PORT-5178

**Comment by sfiserv** [comment]
@wwfiserv this issue is fixed in dev env for your verification.

**Comment by wwfiserv** [comment]
@sfiserv appears to be fixed the links no longer display.

**Comment by sfiserv** [comment]
Closing this issue as fixed and verified.
