### ISSUE TITLE
SnapPay - Enable users (sales/ solution engineer) to configure credential.

### ISSUE THREAD

**Issue by skranganathan** [Fiserv/Support#200]
1)	The API should allow the user to configure their request header with Account ID, credential (Basic) and system should generate HMAC and call SnapPay SandBox.

What I think is that we create a user level setup, where they can define parameters that are needed for each merchant. For SnapPay we need Account Id, API Credentials, Merchant ID and HMAC. For Commerce Hub it might be different and they can define their setup. 
If the API request header has same name, then we bring it from the setup than what yaml has. This way each user can use their unique setup and show demos to multiple customers. 
a.	We wanted a way to generate HMAC dynamically as this is what we need to explain to end customer and most of our implementation support is to help them create HMAC programatically. If developer studio can demo this, it would be great. 
  For e.g We provide our code snippet to Developer Studio (a javascript) that needs to be executed with the parameters from the API request and HMAC is generated. This HMAC token is used for the sandbox API call. 
b.	If HMAC is future, at bare minimum we would like the Basic credential to be added to each end point so the customer can change the credential, account Id and run for their environment. This is similar to you give a postman collection and customer change environment variable to their merchant, credentials.

**Comment by sfiserv** [comment]
Created tracking ticket https://firstdatateam.atlassian.net/browse/PORT-5188

**Comment by TaniaSarkar89** [comment]
Hi @skranganathan had few questions on this feature request:
1. So we understand that you want an HMAC generator for SnapPay api requests. And this HMAC would get generated based on '_Account ID_', '_API Credentials_' and '_Merchant ID_'. Now the '_Account Id_' and '_Merchant ID_' are derived from user input provided in the request parameters, but how are the _API credentials_ generated?  I believe the api key and secret would be unique per user. If so, then as per the existing Dev Studio feature we ask the user to register/login to Dev Studio and then generate these api credentials. 
2. Could you provide us a sample code snippet for HMAC generation.

Thanks!

**Comment by skranganathan** [comment]
Tania,  
            Great question. Let me share the document on how we create HMAC on our side if we are consuming SnapPay APIs. The HMAC needs the secret key and it is sensitive and not exposed outside. This sits on our configuration and shared personally with the account holder (not end user). 
            Our ask is that Dev Studio takes this secret key in configuration, not show to any consumers but use it to build the Authentication dynamically for every request. And have some document on how to create the HMAC with dummy Secret key. 

Attachment has apiAuthCode as one parameter, that is the secret key. 

SK
[generateHMACv2.txt](https://github.com/Fiserv/Support/files/10559112/generateHMACv2.txt)

**Comment by TaniaSarkar89** [comment]
Further action would be taken on this ticket once SnapPay team reviews Dev Studio's proposal.

**Comment by sfiserv** [comment]
@TaniaSarkar89  did we get any response from the SnapPay teamregarding this issue?
