### ISSUE TITLE
SnapPay - Production version sometime blanks out all information and display empty page. 

### ISSUE THREAD

**Issue by skranganathan** [Fiserv/Support#201]
# Reporting new issue for [NAME] (Tenant/Product)  SnapPay

**Region** (if applicable) NA
The region of a user reporting the bug.  

**Page**  APIs with User Interaction
Path of the page where the problem exists.

**Describe the bug** - Mozilla/ Fire fox browser displayed an empty page and none of the links worked. Effectively at 2pm central on Sept 26 2022. 

**To Reproduce**
1. Go to '...'  SnapPay 
2. Click on '....' APIs with User Interaction 

**Expected behavior**  Content to show up. 

**Screenshots**

**Desktop (please complete the following information):**

**Tablet (please complete the following information):**
 - Device: [e.g. iPad]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sfiserv** [comment]
@skranganathan would you be able to provide the steps to reproduce this issue or any screenshots/links as when it happens.

**Comment by sfiserv** [comment]
created a bug ticket this issue https://firstdatateam.atlassian.net/browse/PORT-5187

**Comment by anandrewfiserv** [comment]
@skranganathan Is this still happening?
