### ISSUE TITLE
SnapPay - Allow one endpoint to be displayed in multiple features/ Categories.

### ISSUE THREAD

**Issue by skranganathan** [Fiserv/Support#202]
SnapPay  has an endpoint "GetRequestID" which is used by ERP, Ecommerce, Government. Even though the endpoint is 1, the payload differs for each use case. As of today, we listed all use cases as examples and provided it under one category and it is been requested to have this displayed under 3 categories as how we do in PDF document. 

Is there a way to display one API endpoint under multiple categories ?  if so let us know how to restructure the yaml.

**Comment by sfiserv** [comment]
Created a tracking ticket https://firstdatateam.atlassian.net/browse/PORT-5186
