### ISSUE TITLE
SnapPay - Postman collection is not working. 

### ISSUE THREAD

**Issue by skranganathan** [Fiserv/Support#204]
SK can provide the postman collection one more time, if needed.

# Reporting new issue for [NAME] (Tenant/Product)

**Region** (if applicable)
The region of a user reporting the bug.

**Page**
Path of the page where the problem exists.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Tablet (please complete the following information):**
 - Device: [e.g. iPad]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sfiserv** [comment]
Created a tracking ticket https://firstdatateam.atlassian.net/browse/PORT-5184

**Comment by sfiserv** [comment]
This issue will be fixed as part of our future enhancement to Generate Spec zip file and Postman collection. hence moving this issue fro milestone 22 and adding a new tracking ticket for the same.
https://firstdatateam.atlassian.net/browse/PORT-5242

**Comment by skranganathan** [comment]
is the fix available now?
