### ISSUE TITLE
Response code menu is showing duplicate error codes

### ISSUE THREAD

**Issue by nhelaiya** [Fiserv/Support#205]
# Reporting new issue for [NAME] (Tenant/Product)

**Region** (if applicable)
APAC

**Page**
Merchant Onboarding - Submit Application API

**Describe the bug**
Response code menu showing duplicate 'Response Codes'  like '401', '401-401' which needs to be removed. This is happening almost for all the APIs and needs to be corrected. 

Please advise what needs to be fixed? 

**To Reproduce**
1. Go to - 'Submit Application' under 'Merchant Boarding'
2. Click on '- 'Run Request'
3. Go To 'Response Code' Drop down.

**Expected behavior**
It should not list duplicate response codes under 'Response Code' menu.

**Screenshots**
<img width="642" alt="image" src="https://user-images.githubusercontent.com/113433938/192511400-1d2a5901-a8e5-4715-a3ed-a56ae3eb6b40.png">

*

**Comment by TaniaSarkar89** [comment]
Hi @nhelaiya this is an intended feature that we introduced last sprint. These response codes are not duplicated, in fact they are coming from your specification file (boarding-test.yaml). 
An Open API spec can have multiple example requests and  responses. The dropdown under the "Parameters" section lists out all the examples defined in the **requestBody** of an endpoint. Similarly the new response code dropdown underneath the "Response Schema" section lists out all the examples defined in the **responses** defined for an endpoint. Below is the mapping of the same.
So in the screenshot that you provided:

- 200 -> _is the default schema for 200_
- 200 - New merchant ->  _is the 'New merchant' example in response_
- 401 -> _is the default schema for 401_
- 401 - 401 -> _is the '401' example name in response _

![image](https://user-images.githubusercontent.com/74629095/192641759-050995a4-76e1-4308-b3b6-80ba0470857a.png)

Hence it is advisable to provide evocative and qualitative names for all your examples including the ones in the responses.

Thanks!
