### ISSUE TITLE
How to get credentials for AllData Aggregation

### ISSUE THREAD

**Issue by michaelsuro** [Fiserv/Support#206]
My company would like to use your AllData Aggregation product to allow our users to connect their bank accounts so we can provide them their account balances and transaction history. Developer Studio currently only allows you to create a workspace for Commerce Hub. I was wondering how I could acquire the credentials required to use the AllData Add Account Widget and API.

**Comment by michaelsuro** [comment]
@DanielleVictoriaFiserv I can be reached at suro@moneykit.com if you require more information.

**Comment by sfiserv** [comment]
https://teams.microsoft.com/l/message/19:ebe0b524f81940648648865c37a7f0f3@thread.tacv2/1664816222703?tenantId=11873a1f-4c8d-450d-8dfb-e37a2e2557f8&groupId=982cd560-8afd-42fc-bb4c-543e1989b6b1&parentMessageId=1664816222703&teamName=Developer%20Studio%20from%20Fiserv&channelName=AllData%20Aggregation&createdTime=1664816222703&allowXTenantAccess=false
<img width="896" alt="image" src="https://user-images.githubusercontent.com/87097017/197113599-f00bc983-f26a-43e2-bbfd-896bb67800b6.png">
Based on the conversation in the team channel and information provided by @MasonFiserv, @michaelsuro is provided the information needed.

**Comment by michaelsuro** [comment]
Thank you for following up on this issue. I spoke with Jenessa and Brent earlier last week. Brent said he would provide me AllData Sandbox credentials but I never heard back from him. I learned this week that he has left the company so I had assumed that's why I didn't hear back. 

Just so I understand your screenshot correctly, are you saying that you are unable to provide any AllData Sandbox credentials at this time?

**Comment by MasonFiserv** [comment]
FYI: Theresa and I chatted with Jenessa about this. She will get back in touch with client Michael. Since she doesn't have a GitHub account, I've asked her to alert me when resolved so I can update the issue and close it out.

**Comment by sfiserv** [comment]
Marking this issue as done based on @MasonFiserv 's comments.
