### ISSUE TITLE
Additional elements added in Response Samples in PROD***

### ISSUE THREAD

**Issue by tsegurajimen** [Fiserv/Support#207]
Hi Team,

Can you please check why these new elements are being displayed in all the response samples for all Banking APIs in Production when we hit the "Run" button?

https://developer.fiserv.com/product/BankingHub/api/?type=post&path=/accounts&branch=main&version=11.0.0
![image](https://user-images.githubusercontent.com/81706748/193128011-4e572bfe-ff47-409c-b518-b8f68abe8ac9.png)

It seems that they are related to the new elements that are going to be added for the API Explorer redesign, but those shouldn't be displayed yet in PROD.

It is also affecting other Tenants as well:

https://developer.fiserv.com/product/CommerceHub/api/?type=post&path=/daas/v1/returnoptimizer&branch=main&version=1.3.0
![image](https://user-images.githubusercontent.com/81706748/193128296-a6869c81-e406-4df7-8d3a-7cab26a1d2f6.png)

Thanks in advance for your help!

cc:
@fiservakshay @bobburghardt

**Comment by sfiserv** [comment]
Created tracking ticket https://firstdatateam.atlassian.net/browse/PORT-5177
@OZ-FS

**Comment by OZ-FS** [comment]
The fix is in dev for GMS tenants.

**Comment by tsegurajimen** [comment]
Thanks a lot @OZ-FS I've tested it in Dev and sample response looks clean as expected, additional info was successfully removed.

![image](https://user-images.githubusercontent.com/81706748/195889888-8340d650-7110-499a-bb70-eff8a467be35.png)
