### ISSUE TITLE
Cancel my account

### ISSUE THREAD

**Issue by alexandreginez** [Fiserv/Support#208]
[](url)Hello my name is Alexandre Ginez I am the owner of a company called Workout bft llc I have an account with you (374256980888) I have been trying to cancel and return my machine for a long time and I can not. Everywhere I contact they tell me that my account has been blocked but they continue to charge me an amount of $86.67 transaction made in the name of First Data with due date every 15th. I want you to stop charging and I want to return my equipment because I am closing my company and closing my account.

thank you very much and i am waiting for an answer as soon as [possible)

**Comment by sfiserv** [comment]
@alexandreginez This support is not for First Data project. You will need to contact First Data Support team.
Sorry we cannot be much of help.
