### ISSUE TITLE
Tenant Creation

### ISSUE THREAD

**Issue by CinthyaRivera** [Fiserv/Support#210]
**Region** (optional)
LATAM - LAS

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Tenant Creation

**Describe alternatives you've considered**
Use older portal

**Additional context**
Description: Optimice y lleve a otro nivel la experiencia en Medios de Pagos a sus clientes utilizando nuestras APIs, lo cual le permitirá asegurar procesos, mejorar la experiencia de usuarios y satisfacer las expectativas de sus clientes al proporcionar servicios innovadores. Brindamos un servicio de API que respaldarán su negocio, incluidas API de emisión instantánea, activación de tarjetas, denuncias por robo y extravío, cuotificación de saldos y consumos, registros de viajes, servicios On-Off, aumento de límite transitorio y productos digitales, entre otros.
Who Is It For: Silvercore es una aplicación de software financiero utilizada principalmente por bancos/procesadores de tarjetas para emitir tarjetas de crédito, débito, prepago y tarjetas comerciales. 
Product tags Industry: Issuing
Solution Name: Silvercore API para Instituciones Financieras
Product Tags: This would help anyone to search your product on Developer Studio
	· Region: LATAM
	· Channel Type: Card Present
	· Integration Type: Restful
	· Customer Segment: 
 
			o   * Financial Institutions: Bank / Credit Union / Large FI.
	· Industry:  Banking, Financial Institutions
Feature: emisión instantánea, activación de tarjetas, denuncias por robo y extravío, cuotificación de saldos y consumos, registros de viajes, servicios On-Off, aumento de límite transitorio y productos digitales

<!-- ** Recommended ** 

- Assign a Feature 

    On you right hand side, you can set an Assignees by Clicking setting button next to it.

- Subscribe to a Team

    At the end of your Feature template, please mention team you would like to subscribe for this Issue for future updates. You can mention teams in Github 
    
    Example:  cinthya.rivera@fiserv.com/fiserv-developer)

**Comment by TaniaSarkar89** [comment]
@CinthyaRivera this tenant is on dev Studio now
