### ISSUE TITLE
Tenant Creation LATAM Acquiring

### ISSUE THREAD

**Issue by CinthyaRivera** [Fiserv/Support#211]
**Region** (optional)
LATAM

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Tenant creation

**Describe alternatives you've considered**
Use old portal

**Additional context**
Name of your Product: 
”LATAM Acquiring as a Service APIs" 
 
Description: (max 800 chars) 
Expand your business’ reach by taking the acceptance process to a different level. Merchants will expand their service and provide different experiences to their clients by leveraging new features and services at the point-of-sale, in real-time to increase their billing and usage.
 
Who Is It For: Product tags Industry 
Merchants, ISVs (Independent Software Vendors), VAR (Value Added Resellers), Acquiring, Acceptance
 
Solution Name: Where do you want to stay in Merchants solution or Financial Institutions category ( based on the services your product serves) 
Merchant Solution
 
External Link: external link to your site for Linked out tenants. 
URL
 
Product Tags: This would help anyone to search your product on Developer Studio 
•	Region: Your product’s region of operation: LATAM
•	Channel Type: Card Present / Card Not Present / OMNI
•	Integration Type: Restful
•	Customer Segment:
  * Merchants: Small Medium Business (SMB) / Enterprise. 
•	Industry: Which industry(s) does it belongs to? Is it Retail, Banking, Hospitality, Money Transfer, Insurance, Telecommunications, etc
o	Retail
o	Restaurant
o	Lodging
o	etc
 
•	Feature: What kind of features does your product provide? Is it Electronic Payments, Gift Cards, Electronic Funds Transfer (EFT), Authorization, Refunds, Settlements, etc
o	Boarding
o	Logistics
o	Electronic Payments
•	Authorization
•	Refunds 
o	Fraud Control
o	Settlements
o	Reporting
o	Integrations

**Comment by TaniaSarkar89** [comment]
@CinthyaRivera this tenant has been onboarded on Developer Studio.
