### ISSUE TITLE
Multi Language

### ISSUE THREAD

**Issue by CinthyaRivera** [Fiserv/Support#212]
**Region** (optional)
LATAM

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add multi-language option in the portal (for LATAM it's required Spanish, English and Portuguese).
![image](https://user-images.githubusercontent.com/111396588/194099756-7aa332b1-bf0e-41df-9694-d9836fa29b36.png)
Example: https://dev.softwareexpress.com.br/onboarding

**Describe alternatives you've considered**
Use the portal only in one language.

**Additional context**

**Comment by sfiserv** [comment]
created a tracking ticket for this issue 
https://firstdatateam.atlassian.net/browse/PORT-5284

**Comment by CinthyaRivera** [comment]
Can you provide me access to the jira to track my issue?

**Comment by CinthyaRivera** [comment]
Do you have any new for this request?

**Comment by CinthyaRivera** [comment]
Do you have an approximate date to release this feature?

**Comment by sfiserv** [comment]
@CinthyaRivera We have not yet discussed this feature of supporting Multi-languages. We have to take up this as part of our Q2 roadmap discussion.

**Comment by sfiserv** [comment]
Proposed changes by DevStudio, are being reviewed with the Latam team.

**Comment by CinthyaRivera** [comment]
Do you have any update?

**Comment by sfiserv** [comment]
@CinthyaRivera as you see the last message in this issue, we had sent out the proposal to your team. We had started talk with your team, but have not received response from them.
If you have some updates please provide us with the same.
