### ISSUE TITLE
HMAC Header documentation page missing in Developer portal!!!

### ISSUE THREAD

**Issue by RajeshKFreelancer** [Fiserv/Support#213]
# Reporting new issue for [COMMERCEHUB] (Charges end-point)

**Region** (if applicable)
North America

My name is Rajesh and I am working for MTI Commerce as a developer.  We already have MID as Merchant ID: 100008000003683.  The registered email is markm@mticommerce.com (Mr Mark Manesh).  We're trying to access your below end point through Rest-API call.
https://cert.api.fiservapps.com/ch/payments/v1/charges/

**Page**
[Path of the page where the problem exists.](https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Resources/API-Documents/Use-Our-APIs.md&branch=main)

**Describe the bug**
In 'Request Header' explanation section, in the 'Authorisation' parameter, there is link 'HMAC' for one of the allowed encryption method.  However, clicking that gives "404 Page not found" error!

**To Reproduce**
1. Go to page
https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Resources/API-Documents/Use-Our-APIs.md&branch=main
2. Click on HMAC to the right of 'Authorisation' row under the 'Request Header' section.
3. You will land upon the "404 Page not found" page.

**Expected behavior**
Earlier a page containing complete explanation of how to generate the HMAC encrypted string was available.

**Screenshots**
![image](https://user-images.githubusercontent.com/85435668/196259382-8282192c-224f-48fd-9cae-1c5cdf190073.png)
![image](https://user-images.githubusercontent.com/85435668/196259460-c5ec2063-4958-4525-80b4-67b93700956a.png)

**Comment by TaniaSarkar89** [comment]
Hi @RajeshKFreelancer this issue has been fixed today and the changes are live in production. Please let us know if you are still facing this issue.

Thanks!

**Comment by RajeshKFreelancer** [comment]
Thank you Tania,

I will check through my client's developer account and let you know.

In fact, I have seen a few other pages also as gone, showing 404.
Will let you guys know.

regards,

Rajesh Karunakaran

+230-5895-1168  (Mauritius) WhatsApp
+91-85273-53711 (India)

**Comment by RajeshKFreelancer** [comment]
Thank you Tania,

I will check through my client's developer account and let you know.

In fact, I have seen a few other pages also as gone, showing 404.
Will let you guys know.

regards,

Rajesh Karunakaran
Mob: +230-5895-1168
Skype: rajeshk.freelancer

**Comment by sfiserv** [comment]
Closing this issue as did not receive any response from client.
