### ISSUE TITLE
Specification Description Page

### ISSUE THREAD

**Issue by kcaramat** [Fiserv/Support#214]
**Region** (optional)
Test

**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Each document contains a description page outlining version and document details. The PDF, Word, or Excel file is accessible for download on this page along with a Subscribe / Unsubscribe option. The Subscribe option triggers an automated email notification to the user when an updated PDF, Word, or Excel file is uploaded. 
-	The Subscribe option should automatically be turned on when a user downloads the file. User receives pop up stating “You’ve subscribed to receive email notifications of new specification versions.”
-	 User will need to manually Unsubscribe if they don’t want to receive automated email notifications. If user unsubscribes, user receives pop up stating “You’re opting out to receive email notifications of new specification versions.
-	Log email receipt with timestamp when an email notification was sent to a user, or a failed delivery occurs.

**Describe alternatives you've considered**
Functionality is required. 

**Additional context**
N/A

**Comment by sfiserv** [comment]
Tracking this requirement in https://firstdatateam.atlassian.net/browse/PORT-5310
