### ISSUE TITLE
Spec Portal - Reporting Capabilities

### ISSUE THREAD

**Issue by kcaramat** [Fiserv/Support#216]
**Region** (optional)
Test

**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
- Ability to obtain reporting on document usage/downloads, number of views, user activity, and file statistics.
- Report containing owner details (last user to create/update) for each document housed on Specification Portal.

**Describe alternatives you've considered**
Functionality required

**Additional context**
N/A

**Comment by sfiserv** [comment]
Tracking this requirement in https://firstdatateam.atlassian.net/browse/PORT-5308
