### ISSUE TITLE
List of US Banks connected to your API solutions

### ISSUE THREAD

**Issue by WojtekAn** [Fiserv/Support#219]
**Region** (optional)
NA

**Is your feature request related to a problem? Please describe.**
Hello, as we are currently researching your products and solutions, we would like to know which specific US banks are providing data to your database. Is it possible?

**Describe the solution you'd like**
Best solution is to get an excel list of US Banks that are connected with you if that's possible. 

**Describe alternatives you've considered**
For now I have no idea

**Additional context**

We are fintech company building open banking solutions. Currently we are in the discovery process of US open banking solutions. Getting this list would be very helpful for us. Thank you!

**Comment by TaniaSarkar89** [comment]
Hi @WojtekAn thank you for reaching out to our team. 

@bobburghardt @tsegurajimen could you please provide assistance to @WojtekAn here on his request.

**Comment by WojtekAn** [comment]
Thank you @TaniaSarkar89 for fast response

Dear @bobburghardt and @tsegurajimen, to clarify my question to you, I would add that we are interested about US Banks that provides via your database information about accounts and transactions. Payments are other part that of course is also highly appreciated, but current research is focused on accounts and transactions. 

Thanks in advance!

**Comment by bobburghardt** [comment]
Hi @WojtekAn ,

    We are not permitted to publicize our client list, but I can tell you that Fiserv is the leading account processor for banks and credit unions in the United States.  Approximately 1 out of every 3 Financial Institutions uses our account processing platforms as account systems of record and to conduct transactions.

    This high penetration should provide you with the scope of our offerings, and a sense of our influence in the US marketplace.

Thank you for contacting us.
Bob

**Comment by WojtekAn** [comment]
@bobburghardt,

thanks. Of course I understand that. So let me ask one more question - is connecting to your API providing instant access to these banks that are connected with you? 

Thanks in advance

**Comment by bobburghardt** [comment]
@WojtekAn  - Connecting to our API provides access to banks that use some of our account processing solutions.  The developer studio Banking Hub section will indicate which APIs are supported by which of our solutions.  Please note that some of the content on the Banking Hub section is still a work in progress, so the solution list is not yet complete.  However, you can get a sense of which account processing solutions support those APIs.  

This means, if the bank is using that particular account processing solution, those APIs are available.

**Comment by WojtekAn** [comment]
Thank you. Have a great day!
