### ISSUE TITLE
Description Render Issue in API Explorer

### ISSUE THREAD

**Issue by wwfiserv** [Fiserv/Support#220]
# Reporting new issue for Commerce Hub

**Page**
https://dev-developer.fiserv.com/product/CommerceHub/api/?type=post&path=/payments/v1/charges&branch=develop&version=1.4.0

**Describe the bug**
Their should be a break at the end of the sentence similar to descriptions in the schemas when bullet points are used, based on Open API spec, shows correctly in Swagger but not Dev Studio

```
      description: |+
        Use this payload to originate a financial transaction based on the <code>captureFlag</code>
        
        * <a href="../docs?path=docs/Resources/API-Documents/Payments/Charges.md">Pre-Auth</a> = <i>false</i>
        * <a href="../docs?path=docs/Resources/API-Documents/Payments/Charges.md">Sale</a> = <i>true</i>
        * <a href="../docs?path=docs/Resources/API-Documents/Payments/Capture.md">Capture</a> = <i>true</i> with a <a href="../docs?path=docs/Resources/Master-Data/Reference-Transaction-Details.md">transaction identifier</a>
```

**Screenshots**
Swagger
![image](https://user-images.githubusercontent.com/75692745/199272277-131d528e-f22b-45f8-b99b-0c8245955be9.png)

Dev Studio
![image](https://user-images.githubusercontent.com/75692745/199272604-335f925f-a69b-48cf-9ab3-2eb51746b5ab.png)

How it should look like it does in schemas
![image](https://user-images.githubusercontent.com/75692745/199272760-bb4e279f-ab7e-494c-828f-af61564071b1.png)

**Comment by wwfiserv** [comment]
@TaniaSarkar89 any update on this? I already had to reopen it once.

**Comment by TaniaSarkar89** [comment]
Hi @wwfiserv  we would prioritize it next sprint.
Cc: @sfiserv
