### ISSUE TITLE
How to get credentials for AllData Aggregation on live environment? 

### ISSUE THREAD

**Issue by WojtekAn** [Fiserv/Support#222]
Hello support team,

as we are researching possibilities of your service, I would like to ask about some parameters that we are missing:

partnerId
homeId

Without these parameters mentioned above we can't run any tests so it would be great to receive more information about this. 

Thanks in advance!

**Comment by sfiserv** [comment]
@MasonFiserv  I am assigning this issue. @WojtekAn  would need help/support from your team (Jenessa and Brent) to get credentials the AllData Aggregation. 
@WojtekAn please connect with Mason, he will help you to connect with his team members.

**Comment by jenessakastelic** [comment]
@WojtekAn, can we sync up via email or a quick call before setting up the sandbox?

**Comment by jenessakastelic** [comment]
@WojtekAn my email is jenessa.kastelic@fiserv.com if you can ping me. thanks!
