### ISSUE TITLE
Sample API Explorer crashes navigating from `Code Snippet` to `Request`

### ISSUE THREAD

**Issue by cscholle1** [Fiserv/Support#223]
# Reporting new issue for [NAME] (Tenant/Product)

**Region** (if applicable)

**Page**
[Path of the page where the problem exists.](https://developer.fiserv.com/product/Reporting/api/?type=post&path=/v1/authorization/search&branch=main&version=1.0.0)

**Describe the bug**
Site crashes on a certain flow in the Sample API Explorer

**To Reproduce**
1. Go to [Sample API Explorer](https://developer.fiserv.com/product/Reporting/api/?type=post&path=/v1/authorization/search&branch=main&version=1.0.0)
2. Click on `Code Snippet`
3. Click on `Request`
4. Current page turns white
5. See error in console `TypeError: Cannot read properties of undefined (reading 'trim')`

**Expected behavior**
Navigates back to `Request` successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/47984872/199760994-c5f6e06b-3a99-460d-8849-cf7d9b18fafc.png)

**Desktop (please complete the following information):**
 - OS: MacOS Monterey
 - Browser chrome
 - Version 106.0.5249.119 (Official Build) (arm64)

**Comment by sfiserv** [comment]
Thank you @cscholle1 for bringing this issue to our attention. Our team has already observed the same and we have tracked and fixed the issue. https://firstdatateam.atlassian.net/browse/PORT-5371
The fix will be available in soon in production.

**Comment by sfiserv** [comment]
@cscholle1 Would you be able to give more information what company/product you are currently working for and how did you hear about DevStudio?

**Comment by sfiserv** [comment]
Closing this issue as verified and no further issue reported by client.
