### ISSUE TITLE
Fiserv DNACreator access

### ISSUE THREAD

**Issue by Jimbrayfl** [Fiserv/Support#225]
**Region** (optional) Florida
The region of a user submitting the feedback.

-->I am looking to gain access to DNA Creator so that we can integrate our bank fraud cases management platform with DNA. Our client is Lankmark Credit Union. What is the process to gain access to DNA Creator?

Jim Bray
Quinte Financial Technologies
954-495-7317
jim.bray@quinteft.com

**Comment by TaniaSarkar89** [comment]
Hi @bobburghardt could you please provide help @Jimbrayfl with the issue.

**Comment by bobburghardt** [comment]
@Jimbrayfl  - Jim - I sent you off an e-mail requesting information on who you are working with at the credit union.  I'll close this issue and we can communicate via e-mail on the next steps.

**Comment by Jimbrayfl** [comment]
What is your FiServ email address. I will then introduce you to my product manager Swami Bhaskaran to answer all your questions.

**Comment by Jimbrayfl** [comment]
What is your FiServ email address. I will then introduce you to my product manager Swami Bhaskaran to answer all your questions.

> @Jimbrayfl - Jim - I sent you off an e-mail requesting information on who you are working with at the credit union. I'll close this issue and we can communicate via e-mail on the next steps.

Hi Bob, I did not get your email message.

**Comment by bobburghardt** [comment]
@Jimbrayfl  - please add your product manager's e-mail to this chat and I will contact Swami directly.  Thank you.

**Comment by Jimbrayfl** [comment]
Good morning.  Following is what we need:
1.	Ability to obtain account information.
2.	Ability to obtain account holder demographics information
3.	Ability to obtain detailed transaction information
4.	ability to update transaction, account and card details

The interfaces / APIs mentioned in the page here are focused on payments not what we are interested in.  FiServ has a software called DNACreator – I think we need to be able to eval that capability. Swami will provide more detail.

**Comment by bobburghardt** [comment]
@Jimbrayfl  - thanks for the list of what you're seeking.  I sent Swami an e-mail.
