### ISSUE TITLE
Banking Hub Dropdown Issues***

### ISSUE THREAD

**Issue by tsegurajimen** [Fiserv/Support#226]
Hi @jimmychen-fiserv , @TaniaSarkar89, @sfiserv and Team,

Please your help with following issues found regarding the new dropdown available in Banking Hub:

1. Cleartouch yaml is not being rendered correctly: first endpoint POST /partyacctrel (Add Party Account Relationship) is not being displayed at all in dev, it should be under Accountholder/Party Account Relationship Service/Add Party Account Relationship

https://github.com/Fiserv/banking-hub/blob/develop/reference/11.0.0/Dropdown_Test/11.0.0_CT.yaml

Precision yaml also has that endpoint as well and is not being displayed either:

https://github.com/Fiserv/banking-hub/blob/develop/reference/11.0.0/Dropdown_Test/11.0.0_PRC.yaml

![image](https://user-images.githubusercontent.com/81706748/200430777-1f241624-46a4-4057-ad7e-9087a137b4fa.png)

2. While testing Update Party Account Relationship, according Signature yaml in the dropdown, when running the mock server it is returning the 200 Response based on another yaml, seems that is is pointing to the original yaml we had of this API, the one we have in PROD: https://github.com/Fiserv/banking-hub/blob/develop/reference/11.0.0/Accountholder/PartyAcctRelUpdate.yaml

![image](https://user-images.githubusercontent.com/81706748/200428644-55d81eb3-c2a2-4d47-aaac-f015c420df79.png)

And same behavior for other cores in the dropdown, we're getting same response in all of them: 
![image](https://user-images.githubusercontent.com/81706748/200429507-9fd48572-4b64-499b-b47a-3e38b043f794.png)

Thanks in advance for your help!

cc: @fiservakshay @bobburghardt

**Comment by TaniaSarkar89** [comment]
Opened JIRA ticket to track this issue : https://firstdatateam.atlassian.net/browse/PORT-5440

**Comment by TaniaSarkar89** [comment]
**Issue 2** : Fixed
**Issue 1** : Duplicate ticket has been opened for this issue. https://github.com/Fiserv/Support/issues/232
Hence closing this ticket.
