### ISSUE TITLE
.docignore Articles Showing in Search

### ISSUE THREAD

**Issue by wwfiserv** [Fiserv/Support#227]
# Reporting new issue for Commerce Hub

**Region** (if applicable)
Dev

**Page**
https://dev-developer.fiserv.com/search?q=test%20response&p=%5B%22CommerceHub%22%5D

**Describe the bug**
Search results contain articles that are in the .docignore

**Expected behavior**
.docignore articles should not show in search results they result in a 404

**Screenshots**
![image](https://user-images.githubusercontent.com/75692745/200655979-88ff12c9-a5a6-4648-bcb4-b0fe9fbe7f57.png)
![image](https://user-images.githubusercontent.com/75692745/200656057-fb87787f-c3a2-4c90-bd3a-8ba028b2950d.png)

**Comment by sfiserv** [comment]
Tracking this issue in https://firstdatateam.atlassian.net/browse/PORT-5448

**Comment by asingh2023** [comment]
Not able to replicate the issue. 

![image](https://user-images.githubusercontent.com/81193958/202261035-b0650bb4-ec42-4cef-a838-0339f8cf1c33.png)



![image](https://user-images.githubusercontent.com/81193958/202261162-54f95190-c285-43ca-9552-5dc127c80db5.png)

**Comment by wwfiserv** [comment]
It appears a database refresh must have been done after opening the ticket so it has resolved itself.
