### ISSUE TITLE
Error with sandbox/prism mock when the responses has more than 1000 fields

### ISSUE THREAD

**Issue by eliascanaza** [Fiserv/Support#228]
# Reporting new issue for [NAME] (Tenant/Product)

**Region** (if applicable)
EMEA and NA

**Page**
IssuerSolutions:

```
Account & Services
	Account Management
		alphaSearch:
			/account/v4/alphaSearch
		search:
			/account/v4/search
	Customer Records
		inquiry:
			/customer/v4/inquiry
		inquiryWithLSDate:
			/customer/v4/inquiryWithLSDate
Customer Service
	Customer Service Cardholder Tool
		demandDepositAccountSearch:
			/ui/v4/demandDepositAccountSearch
```

**Describe the bug**
we found an issue with sandbox, when the response has more than 1000 fields sandbox is failing, on DevStudio is showing null and using prism mock is showing this error:

{
 "type": "https://stoplight.io/prism/errors#UNKNOWN",
 "title": "Schema size exceeded",
 "status": 500,
 "detail": ""
}

**Expected behavior**
Sandbox should display the complete response, even if response has more than 1500 fields 

**Screenshots**
![image](https://user-images.githubusercontent.com/1819754/201115158-1a9ef830-001f-4e46-adc0-026236278f29.png)
<img width="470" alt="image" src="https://user-images.githubusercontent.com/1819754/201115392-22fc846f-08e5-46d8-a9e6-4c68f7031ba8.png">

**Comment by TaniaSarkar89** [comment]
Opened JIRA ticket: https://firstdatateam.atlassian.net/browse/PORT-5585 to work on this issue.

**Comment by TaniaSarkar89** [comment]
Hi @eliascanaza the issue has been fixed. Below screenshot says the same for [endpoint](https://dev-developerstudio.fiserv.com/product/IssuerSolutions/api/?type=post&path=/ui/v4/demandDepositAccountSearch&branch=develop&version=1.0.0): 
<img width="1688" alt="image" src="https://user-images.githubusercontent.com/74629095/216085774-02874719-b267-4001-8d08-b2eea260de4c.png">

Kindly verify the mock responses for the other endpoints.

Thanks!

**Comment by eliascanaza** [comment]
cool great news, I will validate them

**Comment by eliascanaza** [comment]
@TaniaSarkar89 I already validated, it is working... thank you so much.

**Comment by TaniaSarkar89** [comment]
The issue is being closed since no further action is required.
