### ISSUE TITLE
Add Endpoints have disappeared from Banking Hub Tenant in PROD/Dev/Stage

### ISSUE THREAD

**Issue by tsegurajimen** [Fiserv/Support#232]
Hi Team,

We need your help urgently do to almost all Add endpoints had disappear from the left side nav for Banking Hub in PROD/Dev/Stage instances, as you can see we didn't introduced any change to our code in Stage and PROD since last month, but today we detected they were failing:

![image](https://user-images.githubusercontent.com/81706748/201964195-4468161c-db8f-429f-9767-e42438ac0541.png)
![image](https://user-images.githubusercontent.com/81706748/201966120-3b870e60-c234-467d-8855-76d1e4e333f0.png)

Is seems those Add APIs still there but not displayed in the left side nav, I mean you can access them only having the direct link to them:

https://developer.fiserv.com/product/BankingHub/api/?type=post&path=/accounts&branch=main&version=11.0.0
![image](https://user-images.githubusercontent.com/81706748/201966603-67e807c1-6a58-4f86-b415-89718117a6a2.png)

https://developer.fiserv.com/product/BankingHub/api/?type=post&path=/address&branch=main&version=11.0.0
![image](https://user-images.githubusercontent.com/81706748/201966828-5814dc7d-ac80-4469-adf7-27eb2478ba3e.png)

Can you please check if this is related to the dropdown gap we have reported regarding the Add endpoint was not displayed when we were testing the dropdown initially? We were told that issue was not related to the dropdown code but I'm afraid when your code was merged to PROD and other instances it affected the behavior of almost all Add endpoints: 

https://github.com/Fiserv/Support/issues/226

This is the list of APIs affected by the issue:

![image](https://user-images.githubusercontent.com/81706748/201970644-02785923-7de8-41e8-a82d-8fa9d287ae28.png)

These are the ones not impacted until now:

![image](https://user-images.githubusercontent.com/81706748/201970773-d505321f-262c-45cf-b635-0d5edc2a4763.png)

Please your help.

Thanks in advance!!

cc: @bobburghardt @fiservakshay

**Comment by TaniaSarkar89** [comment]
Opened JIRA ticket for tracking https://firstdatateam.atlassian.net/browse/PORT-5463

**Comment by tsegurajimen** [comment]
Hi @OZ-FS @TaniaSarkar89 @sfiserv and Team,

We have tested the fix and Add/create endpoints are back displayed as expected:

https://dev-developer.fiserv.com/product/BankingHub/api/?type=post&path=/address&branch=develop&version=11.0.0
![image](https://user-images.githubusercontent.com/81706748/202294305-c648b455-c4dd-434a-83ae-edfff11fd73d.png)

https://dev-developer.fiserv.com/product/BankingHub/api/?type=post&path=/accounts&branch=develop&version=11.0.0
![image](https://user-images.githubusercontent.com/81706748/202294394-1d501d92-780e-48f8-a0f1-31636e33cff7.png)

When is the fix going to be promoted to Stage and PROD?

Thanks a lot!

cc: @bobburghardt @fiservakshay

**Comment by sfiserv** [comment]
Moving this issue to close as the client have verified the fix. the fix will be in the Stage env on Dec1 and in Prod by Dec 08.

**Comment by TaniaSarkar89** [comment]
Hi @rahravin missing APIs issue is being being looked into as part of the new GitHub ticket opened by your team
https://github.com/Fiserv/Support/issues/245

Also when you update any markdown file / documentation in any Github branch, GitHub web hooks take care of updating them instantaneously. So if you do not intend to update the documentation in production, please feel free to update them in the GitHub 'main' branch which pertains to our production environment.

Thanks!
