### ISSUE TITLE
API Documentation for First Data

### ISSUE THREAD

**Issue by alvinsewram** [Fiserv/Support#233]
**Is your feature request related to a problem? Please describe.**

Yes, my company uses FirstData and I am trying to locate the API Documentation to pull transactions by date and navigating the documentation has been challenging in finding what I need.

**Describe the solution you'd like**

I did not find a support email or I page that I could reach the right department. This was the closest I could find.

**Describe alternatives you've considered**

Scouring the various webpages for the right department to assist.

**Comment by sfiserv** [comment]
@kongaravinatha  would you be able to help out @alvinsewram  to get the information needed.

**Comment by kongaravinatha** [comment]
@kongaravinatha @garybyfield @alvinsewram 

Hi Alvin
can I know more about your company/application/team to assist you further?

**Comment by sfiserv** [comment]
Closing this issue as no response is received from Alvinsewram
