### ISSUE TITLE
Mailto link not working on contact us page

### ISSUE THREAD

**Issue by vijju007** [Fiserv/Support#235]
# Reporting new issue for [NAME] (Tenant/Product)
Contact us page under Introduction in devstudio
**Region** (if applicable)
The region of a user reporting the bug.
India
**Page**
Path of the page where the problem exists.
https://dev-developerstudio.fiserv.com/product/AcceptanceSolutionsAPAC/docs/?path=docs/introduction/contact-us.md&branch=develop

**Describe the bug**
On contact us page when we click on mailto link its going to 404 page. But it should stay on same page and it should open outlook.

**To Reproduce**
1. Go to https://dev-developerstudio.fiserv.com/product/AcceptanceSolutionsAPAC
2. Click on Contact Us page under introduction which is on left hand side menu.
3. Click on Email Id link.( example:merchantcare@icicims.com)
4. We can see 404 error. 

**Expected behavior**
 1. Go to https://dev-developerstudio.fiserv.com/product/AcceptanceSolutionsAPAC
2. Click on Contact Us page under introduction which is on left hand side menu.
3. Click on Email Id link.( example:merchantcare@icicims.com)
4. it should open outlook on the same page.

**Screenshots**

<img width="934" alt="contactus" src="https://user-images.githubusercontent.com/106581840/203234499-44f194e0-6d33-46ab-be72-607a9a2e9209.PNG">

**Desktop (please complete the following information):**

**Tablet (please complete the following information):**
 - Device: [e.g. iPad]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sfiserv** [comment]
Created tracking ticket in Jira. https://firstdatateam.atlassian.net/browse/PORT-5520

**Comment by OZ-FS** [comment]
Will consider that.

**Comment by sfiserv** [comment]
Our team has decided this a low priority issue and won't be fixed.
