### ISSUE TITLE
Ordering of API's under API Explorer for Merchant Onboarding

### ISSUE THREAD

**Issue by vijju007** [Fiserv/Support#236]
# Reporting new issue for [NAME] (Tenant/Product)
API Explorer
**Region** (if applicable)
India

**Page**
https://dev-developerstudio.fiserv.com/product/AcceptanceSolutionsAPAC/api/?type=get&path=/boardinggateway/Externalboarding/secure/appstatus/{appUrn}&branch=develop&version=1.0.2

**Describe the bug**
API's for Merchant Onboarding under API Explorer section  should be ordered in same manner as it is under features/Merchant Onboarding

**To Reproduce**
1. Go to https://dev-developerstudio.fiserv.com/product/AcceptanceSolutionsAPAC
2. Click on API Explorer section on left hand side menu. 
3. Scroll down to Merchant Onboarding.
4. APIs are not in correct order

**Expected behavior**

1. Go to https://dev-developerstudio.fiserv.com/product/AcceptanceSolutionsAPAC
2. Click on API Explorer section on left hand side menu. 
3. Scroll down to Merchant Onboarding.
4. APIs are not in correct order. They should be in same order as it is under features/Merchant Onboarding.
**Screenshots**
![image](https://user-images.githubusercontent.com/106581840/203236114-77c3798a-6cf5-48ea-9a9a-dabf9288e25d.png)

**Desktop (please complete the following information):**

**Tablet (please complete the following information):**
 - Device: [e.g. iPad]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sfiserv** [comment]
created a tracking ticket for this issue https://firstdatateam.atlassian.net/browse/PORT-5521
