### ISSUE TITLE
 DDP Dev Studio Issues

### ISSUE THREAD

**Issue by srjoshi4** [Fiserv/Support#237]
Below are the DDP Dev Studio Issues

Issues are noted in Recipient Service : https://dev-developerstudio.fiserv.com/product/DigitalDisbursements/api/?type=post&path=/ddp/v1/recipients&branch=develop&version=1.0.0

Example value not showing up. (“Value supplied by Dev Studio”)
![Screen Shot 2022-11-17 at 12 50 34 PM](https://user-images.githubusercontent.com/103455125/203393471-875afed8-e958-4fcb-8778-ac86a3c8a909.png)

Getting JS Error when expanding recipient
![Screen Shot 2022-11-17 at 12 50 40 PM](https://user-images.githubusercontent.com/103455125/203393493-e558ad72-f8fc-4fd9-89a2-d80553b485ac.png)
![Screen Shot 2022-11-17 at 12 52 11 PM](https://user-images.githubusercontent.com/103455125/203393524-f6d13a46-98a6-4dec-8fdd-34ad2012371e.png)

Example for Response Codes not showing up
![Screen Shot 2022-11-17 at 12 51 03 PM](https://user-images.githubusercontent.com/103455125/203393541-af01bb4b-6e63-4ede-871e-ce890408ddda.png)

**Comment by sfiserv** [comment]
Tracking the issue in the https://firstdatateam.atlassian.net/browse/PORT-5501

**Comment by sfiserv** [comment]
Tracking these issues as part of 
https://firstdatateam.atlassian.net/browse/PORT-5560
https://firstdatateam.atlassian.net/browse/PORT-5559
