### ISSUE TITLE
Create an account

### ISSUE THREAD

**Issue by signitystar** [Fiserv/Support#238]
# Reporting new issue for [NAME] (Tenant/Product)

**Region** (if applicable)
PST

**Page**
https://developer.fiserv.com/?_ga=2.242404551.456959925.1669229242-674561002.1661784808

**Describe the bug**
Access denied-Sign in or Create an account

**To Reproduce**
Tried to access payments related information. access Denied. I  tried to create an account.

**Expected behavior**
Create an account before sign in.

**Screenshots**
![snip](https://user-images.githubusercontent.com/100254413/203659626-1b1ed3f7-261f-4104-a170-a0eefe8e7d51.PNG)

**Desktop (please complete the following information):**
 - OS Windows 10 Asus 64 bit
 - Browser chrome
 - Version 107.0.5304.107

**Comment by sfiserv** [comment]
HI Deepthi , @signitystar As mentioned in the error message Devstudio only supports account creation with your organization's/company's emails ( gmail s not supported.) 
Please try creating account with your organization's /company's email . 
In the mean time we would like to know what product/company you work for. How did you come to know about DevStudio.

**Comment by signitystar** [comment]
Hey Supriya,
                    Company which hired me was Dominion Infotech.I'm one of
dominion tech team working for fiserv on Couchbase Capella.

**Comment by sfiserv** [comment]
@signitystar please try creating an account using your  company's email (Dominion Infotech email). 
let us know if you need any more information. Closing this issue.

**Comment by signitystar** [comment]
I did forward the message to kevin on creating an account with company’s
email.I work for the company dominion Infotech.
                 One among dominion tech team at fiserv.(working from home)

Deepthi
