### ISSUE TITLE
email insert is not active in OneNote & Outlook

### ISSUE THREAD

**Issue by signitystar** [Fiserv/Support#239]
**Region** 
PST

**Is your feature request related to a problem? Please describe.**
Unable to share a page from OneNote or email it as attachment

system details
Device: laptop
OS: Windows 10 ASUS 64 bit

**Describe the solution you'd like**
Please update the feature for my system

fiserv-DominionTech Team

**Comment by sfiserv** [comment]
This does not look relevant issue to DevStudio. Hence will be closing the issue.
However if you think is it a relevant issue please provide more information or screenshots.

**Comment by signitystar** [comment]
Let me go through features of OneNote and the present edition we are on for
test environment.
