### ISSUE TITLE
Page loading issue in API Explorer section

### ISSUE THREAD

**Issue by fiservakshay** [Fiserv/Support#240]
# Reporting new issue for Banking Hub tenant (Dev environment)

API Explorer section in dev environment of Banking Hub tenant is not loading properly.

When user selects any API from API explorer section, all additional resources starts downloading automatically. 

![image](https://user-images.githubusercontent.com/81968767/204546622-4b020f36-524b-4b61-88c8-d58cdd869a94.png)

And after few minutes browser throws following error message.

![image](https://user-images.githubusercontent.com/81968767/204546513-96a489f3-5fde-4945-9a67-f27079dba133.png)

**Page**
API Explorer section in Banking Hub

Sample link:
https://dev-developerstudio.fiserv.com/product/BankingHub/api/?type=post&path=/address&branch=develop&version=11.0.0

**Expected behavior**
Additional Resources must not be download automatically. 

cc: @bobburghardt

**Comment by sfiserv** [comment]
@fiservakshay  our team is aware of this issue. As we all understand that the Dev environment is constantly under development and continuously goes through changes hence we are bound to face these kind of issues.
Thank you for all the patience.

**Comment by sfiserv** [comment]
@fiservakshay  DevStudio's dev environment is now restored. Api explorer page is loading properly.
<img width="1353" alt="image" src="https://user-images.githubusercontent.com/87097017/204675125-4cbf306d-7f8e-4083-912f-c864ea1dc00b.png">

hence closing this issue.
