### ISSUE TITLE
Couchbase Capella-widget indentation, alignment

### ISSUE THREAD

**Issue by signitystar** [Fiserv/Support#241]
**Region** (if applicable)
Test Environment

**Page**
https://docs.couchbase.com/couchbase-lite/current/index.html

**Describe the bug**
side widget

**To Reproduce**
Steps to replicate
1. Go to above mentioned path "https://docs.couchbase.com/couchbase-lite/current/index.html"

**Expected behavior**
width of side widget to be alligned and as per requirement

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser chrome
 - Version 3.0

**Comment by sfiserv** [comment]
@signitystar This github support for the issues for DevStudio. Please raise the issue related to couchbase in their support channel.
This issue os not relevant to DevStudio hence closing this issue.
