### ISSUE TITLE
OAuth sandbox user

### ISSUE THREAD

**Issue by renarl** [Fiserv/Support#242]
I'm working on access to financial data through institutions that support OAuth. I'm following [Add Account workflow (OAuth)](https://developer.fiserv.com/product/AllDataAggregation/docs/?path=docs/alldata-ws-api.md#add-account-workflow-oauth) and can successfully call `initiateAddAccounts` and get a response with `OAuthUrl` to follow. However, I need help finding sandbox user account details with which to log in to the test bank. Where can I find it?

PS, here is the OAuthUrl I get https://testbank.wm.cashedge.com/OauthFI/oauth/authorize?response_type=code&client_id=testhome9_50040009&redirect_uri=https://aggqa.alldata.cashedge.com/oauth2/FIAuth&scope=read&state=cUs5UEYxNjY5OTA2NTYwNTY4&external-party-agent=TestHome9

**Comment by sfiserv** [comment]
@MasonFiserv would you/your team be able to help out @renarl to get the required information.

**Comment by MasonFiserv** [comment]
Hi Renars, 
My name is Mason and I will either find a solution for you or connect you with someone who can.
Thanks for your patience in the meantime. 
Cheers,
Mason

**Comment by MasonFiserv** [comment]
Hi again @renarl,

These details should connect you to a working test institution:

- FI ID: 505054
- FI name: Fiserv - Oauth Implementation
- User ID: oauth123
- Password: oauth123
- MFA answer: pet2

Please let me know if you have any further issues.

Lastly, I am curious to know how you received your keys... Did Fiserv staff send them to you directly?

Thank you!
Mason

**Comment by renarl** [comment]
Hi @MasonFiserv, 

Thank you, the credentials you provided work 👍

Regarding your question about keys, I used the ones from the documentation samples, e.g. [initiateAddAccounts](https://agg-uat.api.fiservapps.com/WealthManagementWeb/api/examples.jsp?category=AccountMgmt&service=initiateAddAccounts).

**Comment by renarl** [comment]
Another question about the OAuth flow. When I call the initiateAddAccounts from [Add Account workflow (OAuth)](https://developer.fiserv.com/product/AllDataAggregation/docs/?path=docs/alldata-ws-api.md#add-account-workflow-oauth) I get an OAuthURL to redirect the user to. I redirect the user, and the user authenticates and allows me to access his accounts, but how do I get the user back to my page to view the retrieved accounts? There is no way to provide a redirect link back to my site in the [initiateAddAccounts](https://agg-uat.api.fiservapps.com/WealthManagementWeb/api/index.jsp#/Account%20Management%20Service/initiateAddAccounts) API.

**Comment by MasonFiserv** [comment]
Hi @renarl,

Thank you for the updates about the test credentials and the keys you are using.

I have contacted our technical team about returning users to your application and expect to have an authoritative answer for you soon.

Take care,
Mason

**Comment by sfiserv** [comment]
Closing this issues as Mason has already provided all the required information Renarl

**Comment by MasonFiserv** [comment]
Hi Supriya,

Customer “Renarl” had a follow-up question. I contacted tech resources for an answer but have yet to receive a response.

So I would like to reopen this issue, but I don’t see a way to do this in GitHub.
Would you please reopen it, or show me how I can?

Thank you!
Mason

***@***.***<https://fiserv.benevity.org/news/23876>  Mason Tromblee • 404-559-0574 (texts OK)  ***@***.*** <https://fiserv.benevity.org/news/23876>
