### ISSUE TITLE
Update (PUT) APIs not displaying on Dev environment

### ISSUE THREAD

**Issue by fiservakshay** [Fiserv/Support#245]
# Reporting new issue for Banking Hub tenant

All Update (PUT) APIs are not displaying on the dev instance of Developer Studio.

Example case:
Update operation (PUT /cards) is available in Card service API, but the same is not reflecting in the Developer studio.
Please refer the screenshots below:

Update listed in SwaggerHub:
![image](https://user-images.githubusercontent.com/81968767/205577534-89cfcfe7-bd2d-4b3f-bb9f-a6050aa4bdfd.png)
https://dev-developerstudio.fiserv.com/product/BankingHub/api/?type=post&path=/cards&branch=develop&version=11.0.0

Update not displaying on Dev Studio:
![image](https://user-images.githubusercontent.com/81968767/205577926-5e3d7b6a-622b-4ea0-b53d-61e9a01f039d.png)
https://swaggerhub.onefiserv.net/apis/Bank_Sol_Org/CardService/11.0.0_PRM

The issue is affecting all Update operation APIs of Banking Hub tenant.

**Comment by TaniaSarkar89** [comment]
Created JIRA ticket to track this issue:
https://firstdatateam.atlassian.net/browse/PORT-5586

**Comment by OZ-FS** [comment]
We have set number of documents fetched to 200.
BH has 265.
Increasing the size to 300 will solve the issue of missing endpoints over 200.

<img width="982" alt="Screen Shot 2022-12-06 at 9 47 37 AM" src="https://user-images.githubusercontent.com/92183615/205988906-6ebd6dd3-7cbd-44f8-8d3a-7ccce87b3197.png">
<img width="997" alt="Screen Shot 2022-12-06 at 9 48 05 AM" src="https://user-images.githubusercontent.com/92183615/205988917-7cf0bb9e-3870-49e0-9e79-ba3d105bd2b7.png">

**Comment by fiservakshay** [comment]
Closing the issue as all Update APIs are showing on the portal
Thank you team :)
