### ISSUE TITLE
Tenant for BrazilAPI

### ISSUE THREAD

**Issue by ServicosAPIsBrazil** [Fiserv/Support#248]
## Name of the product / tenant:
BrazilApi
## Type of Tenant:
Full service
## GitHub Essentials:
These are required for Developer Studio team to create the GitHub repository.

### Team members:
ServicosAPIsBrazil - ServicosAPIsBrazilTeam@fiserv.com

### Suppport contacts: 
Provide fiserv email addresses below
   - Bug Reporting:
      Assignees: klinton.daltio@fiserv.com, wilsonhiroshi.hisatomi@fiserv.com,  rafael.nascimentogomesvillaca@fiserv.com, wellerson.ribeiro@fiserv.com, ServicosAPIsBrazilTeam@fiserv.com
  - Feedback Reporting:
      Assignees: klinton.daltio@fiserv.com, wilsonhiroshi.hisatomi@fiserv.com,  rafael.nascimentogomesvillaca@fiserv.com, wellerson.ribeiro@fiserv.com, ServicosAPIsBrazilTeam@fiserv.com
   - Enhancement Reporting:
      Assignees: klinton.daltio@fiserv.com, wilsonhiroshi.hisatomi@fiserv.com,  rafael.nascimentogomesvillaca@fiserv.com, wellerson.ribeiro@fiserv.com, ServicosAPIsBrazilTeam@fiserv.com

## Studio Essentials:
These are required for Developer Studio team to create the GitHub repository.

### External Link:
Provide the external link to your product or developer portal if you chose "Link Out" as the "Type of tenant"
N/A
### Internal: 
NO

### Carat:
NO
### Solution Areas: 
Which Solution would your product fit into? 
- Merchants:
        SMB: No
        Enterprise: No
- Financial instustions:
        Banks: Yes
        Credit Untions: Yes
        Large financial instutitions: Yes
- Fintech: Yes

### Filter Tags:
Specify tags to filter your product
#### Region of Operation:
   - North America: No
   - EMEA: No
   - LATAM: Yes
   - APAC: No
      
#### Integration:
   - restful: Yes
   > Developer Studio needs restful APIs for integration.
   - sdk: No

#### Industry:
What industry sectors does your product target? 
"Banking"

## Runbox Essentials:
Below information is required for the running the APIs on Developer Studio

### Runbox:
Do you want to enable the run box feature? 
Yes

> If the preceding response is "Yes," continue filling out the below sections:

#### Type of Sandbox:
- Mock : No
- Live: Yes 

> Please note that the Live sandbox setting overrules mock setting. Developer Studio team will later connect with you to collect Live server connectivity details.

> If Live sandbox is not ready at your end, Developer Studio will provide a Mock server for your APIs. For that please change the above value of 'Mock' to 'Yes'.

**Comment by sfiserv** [comment]
@ServicosAPIsBrazil  thanks for the request. 
We are tracking this request through https://firstdatateam.atlassian.net/browse/PORT-5598

We will update you once the repo and the product is enabled in our Dev env.
