### ISSUE TITLE
I need complete details of Header fields of Charges API call

### ISSUE THREAD

**Issue by suvarnaashoka** [Fiserv/Support#250]
**Region** (optional)
The region of a user requesting the feature.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sfiserv** [comment]
@wwfiserv  can  you please help @suvarnaashoka for the details asked.

**Comment by suvarnaashoka** [comment]
headers: {
                'Content-Type': 'application/json',
                'Client-Request-Id': clientRequestId,
                'Api-Key': 'appKey',
                'Timestamp': '0',
                'Accept-Language': 'en-US',
                'Auth-Token-Type': 'AccessToken',
                'Authorization': `${await GetFIserveAccessToken()}`,
                'Message-Digest': 'Message-Digest'
            },

**Comment by suvarnaashoka** [comment]
{
    "gatewayResponse": {
        "transactionProcessingDetails": {
            "apiTraceId": "7cfdc3a46e9b41b0b36550c4dd261e6e",
            "clientRequestId": "011FE19B-BA67-452A-9591-8F24A495F481"
        }
    },
    "error": [
        {
            "type": "APIM",
            "message": "Bad request."
        }
    ]
}

**Comment by suvarnaashoka** [comment]
why am getting this error

**Comment by wwfiserv** [comment]
@suvarnaashoka sorry for the delay I was OOO for the holidays, please review https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Resources/API-Documents/Use-Our-APIs.md&branch=main and https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Resources/API-Documents/Authentication-Header.md&branch=main on how to build a header. You will also need to register for Dev Studio to access your credentials https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Getting-Started/Getting-Started-Dev-Portal.md&branch=preview
