### ISSUE TITLE
Documentation section not rendering in Dev Studio

### ISSUE THREAD

**Issue by fiservakshay** [Fiserv/Support#251]
# Reporting new issue for BankingHub tenant

Documentation section of Banking Hub is not displaying in Dev instance of Developer Studio.

https://dev-developerstudio.fiserv.com/product/BankingHub

Please refer the screenshot below.
![image](https://user-images.githubusercontent.com/81968767/206167767-4c2e1d91-289c-4551-96ee-be529d0e3682.png)

cc: @rahravin @bobburghardt

**Comment by TaniaSarkar89** [comment]
Hi @fiservakshay  we do not see any issues in DEV env
![image](https://user-images.githubusercontent.com/74629095/206265588-9f663a99-f91b-4e29-bb34-d853ac8ffa2d.png)
Please clear you browser cache if you are having issues.
