### ISSUE TITLE
Does fiserv need terminal Id as mandatory

### ISSUE THREAD

**Issue by suvarnaashoka** [Fiserv/Support#253]
**Region** (optional)
The region of a user requesting the feature.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sfiserv** [comment]
please provide a bit of more details who need.
And if you are verifying any request  for the Commerce hub product via postman ( eg: charges, payments) you will need a TID

**Comment by suvarnaashoka** [comment]
Yes am verifying the charge request for the Commerce hub product via
postman but its asking for terminal id, later i need to integrate that in
my web application
so my question is to call the charge api from my web app do we need
terminalId ? if yes is that feasible to use fiserv as psp for online payment

**Comment by sfiserv** [comment]
For now you can use the MID and TID for the Default MerchantID provided under the workspace ( you can create an account and workspace where default MID is provided)

**Comment by suvarnaashoka** [comment]
I have already created account and i created MID can i use this as MID and
TID in the Charge API call?

As of now in the sense can it be worked in the production environment?

**Comment by sfiserv** [comment]
yes the default MID and TID should work via post with the charges request.

**Comment by suvarnaashoka** [comment]
Hi,


i have put the default value of MID to MID and TID but again am getting
"error": [
        {
            "type": "GATEWAY",
            "code": "202",
            "message": "Invalid Terminal ID or Setup"
        }
    ]
