### ISSUE TITLE
Onboarding of: Education Platform from Fiserv - Commercial

### ISSUE THREAD

**Issue by cjuhlman21** [Fiserv/Support#255]
## Name of the product / tenant:
Education Platform from Fiserv - Commercial

## Type of Tenant:
Doc Only

## GitHub Essentials:
These are required for Developer Studio team to create the GitHub repository.

### Team members:
cjuhlman21 - caleb.uhlman@fiserv.com
naveenreddycirigiri - naveenreddy.cirigiri@fiserv.com

### Suppport contacts: 
Provide fiserv email addresses below
   - Bug Reporting:
      Assignees: caleb.uhlman@fiserv.com
   - Feedback Reporting:
      Assignees: caleb.uhlman@fiserv.com
   - Enhancement Reporting:
      Assignees: caleb.uhlman@fiserv.com

## Studio Essentials:
These are required for Developer Studio team to create the GitHub repository.

### External Link:
N/A

### Internal: 
No

### Carat:
No

### Solution Areas: 
Which Solution would your product fit into? 
- Merchants:
        SMB: No
        Enterprise: No
- Financial instustions:
        Banks: No
        Credit Untions: No
        Large financial instutitions: No
- Fintech: Yes

### Filter Tags:
Specify tags to filter your product
#### Region of Operation:
   - North America: Yes
   - EMEA: No
   - LATAM: No
   - APAC: No
      
#### Integration:
   - restful: Yes
   > Developer Studio needs restful APIs for integration.
   - sdk: No

#### Industry:
What industry sectors does your product target? 
Education Loans

## Runbox Essentials:
Below information is required for the running the APIs on Developer Studio

### Runbox:
Do you want to enable the run box feature? Answer "Yes". 

> If the preceding response is "Yes," continue filling out the below sections:

#### Type of Sandbox:
- Mock : Yes
- Live: No 

> Please note that the Live sandbox setting overrules mock setting. Developer Studio team will later connect with you to collect Live server connectivity details.

> If Live sandbox is not ready at your end, Developer Studio will provide a Mock server for your APIs. For that please change the above value of 'Mock' to 'Yes'.

**Comment by sfiserv** [comment]
tracking this issue in https://firstdatateam.atlassian.net/browse/PORT-5605

**Comment by TaniaSarkar89** [comment]
Hello @cjuhlman21

1. This product has been added in Developer Studio in develop environment. Please find the below details:
Link to your product: https://dev-developerstudio.fiserv.com/product/EducationPlatformCommercial
Our lower environments are protected with passwords which would be sent separately via email.

2. GitHub repository has been created for this product and given users have been added in this repository as well. Please accept the invite from Github to access & update the repository contents.
Link to repository: https://github.com/Fiserv/education-platform-commercial

3. Please drop your concerns in the Teams channel: https://teams.microsoft.com/l/channel/19%3ac80237f16b73478ab320d5c48d0d80b2%40thread.tacv2/Education%2520Platform%2520(Dept%2520of%2520education%252C%2520commercial)?groupId=982cd560-8afd-42fc-bb4c-543e1989b6b1&tenantId=11873a1f-4c8d-450d-8dfb-e37a2e2557f8

Please give our documentation a read: https://fiserv.github.io/tenants-doc/

Thanks!
