### ISSUE TITLE
Breaking changes documentation

### ISSUE THREAD

**Issue by ubtjspiegel** [Fiserv/Support#262]
**Region** (optional)

**Is your feature request related to a problem? Please describe.**
No.   

**Describe the solution you'd like**
We use ESF/Communicator Advantage on-prem (SOAP api's).  Some day we will migrate to Communicator Open and start using the REST APi's.  Do you have any documentation on breaking changes between these?  Or to ask the question differently, if we are using 50 API's now, are those same 50 API's also supported 1 for 1?  Is there a list of differences or any that will not be supported?

**Describe alternatives you've considered**
Go thru them 1 by 1 and compare, but that would take a long time!

**Additional context**
Not sure if this is the right place for this request, but thought I would try.

**Comment by bobburghardt** [comment]
@ubtjspiegel - Good day!  To help me answer the question better, please let me know the Fiserv core you are using with Communicator Advantage.  

Thank you

**Comment by ubtjspiegel** [comment]
Hi -yes we use the Fiserv Premier core.  Thank you!

**Comment by bobburghardt** [comment]
Great - thank you for that info.  I can contact you outside of this git forum.  Is this Jeff S at UBT in Lincoln?  If so, I will send you an email to continue the conversation.

**Comment by ubtjspiegel** [comment]
Yes – you got it.  Sounds good.  Thank you!

**Comment by bobburghardt** [comment]
Closing issue and will contact via e-mail
