### ISSUE TITLE
Documentation Menu depth is capped at 3.

### ISSUE THREAD

**Issue by sweeneyjay** [Fiserv/Support#264]
# Reporting new issue for Digital Disbursements

**Region** (if applicable)
The region of a user reporting the bug.

**Page**
[Path of the page where the problem exists.](https://dev-developerstudio.fiserv.com/product/DigitalDisbursements/docs/?path=docs/interactive-guide/api-flow/create-recipient.md&branch=develop)

**Describe the bug**
The left hand menu is not showing all the levels that are defined in the associated YAML file. It is missing the 4th level of the Menu

**To Reproduce**
1. Go to https://dev-developerstudio.fiserv.com/product/DigitalDisbursements
2. In the lefthand navigation menu expand 'Interactive guide'
3. then expand 'API Flow'
4. See that 'How to Create, Read and Update Recipient Profiles' is missing the sub-menu.

**Expected behavior**
'How to Create, Read and Update Recipient Profiles' should be showing a sub menu of the following item:
-Create Recipient
-Update Recipient
-Get Recipient

**Screenshots**
![image](https://user-images.githubusercontent.com/121973998/211894930-7d70306a-cf0e-4369-bbe9-68818e7291f7.png)
![image](https://user-images.githubusercontent.com/121973998/211894985-d6bf7839-f903-4ce1-8674-bf0d0e4b374a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 108.0.5359.125 (Official Build) (64-bit)

**Additional context**
NA

**Comment by TaniaSarkar89** [comment]
Opened JIRA ticket https://firstdatateam.atlassian.net/browse/PORT-5658 for internal Dev studio tracking.
