### ISSUE TITLE
Update Workspace Product options

### ISSUE THREAD

**Issue by paulmohljr** [Fiserv/Support#269]
**Region** (optional)
United States

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Requesting UCom and Digital Disbursements as an option under Product when you login for workspaces. 

**Describe alternatives you've considered**
None

**Additional context**
Any Further information I can be reached at paul.mohl@fiserv.com

 ** Recommended ** 

- Login 
- Workspaces
- Select Product (add Digital disbursements and Universal Commerce as product options)

**Comment by acho-fiserv** [comment]
do you have an apigee system we can connect to for API keys?

**Comment by acho-fiserv** [comment]
do you only have API keys in your workspace?  anything else customers need?

**Comment by acho-fiserv** [comment]
how do they go from a test system to PROD?  do they generate new keys?

**Comment by acho-fiserv** [comment]
do you go through any test & cert?  also, do you show non-prod transaction history while the customer is doing their integration.  and that data comes from CLX?

**Comment by paulmohljr** [comment]
Hey..... 
1.  I believe Apigee X needs to be in place to self service the keys. for that so for now no as a migration plan to Apigee needs to be determined. 
2.  Yes we have keys in the interim we would share with the clients separately but when #1 is completed we will utilize that flow
3.  There are different MIDS setup from test to prod. So, yes we would generate separate keys from one environment to the next. 
4. For sandboxes no cert. However, for actual signed clients we do internal certification (TCoE team) and work with the client directly (currently). Some of the data comes from CLX but not all.

**Comment by paulmohljr** [comment]
Would a meeting be better to go over this? We currently use Apigee for both applications. The applications are not moved over currently to Apigee X at this time. But, I would like to speak on the usecase of what we do today with what we refer to as our sandboxes. These sandboxes sit in our client facing environments in both spaces. In our databases we have our partner ID's configured and the clients utilize the apigee keys to access those environments. we ensure setup manually and test manually before giving these over to clients that either have signed a contract with us or a client that is prospective and wants the look and feel before making the decision.

**Comment by hasaanali057** [comment]
I am not getting any digital disbursement Product in drop down when I am creating a workspace. Is it normal? using fisrv developer studio

**Comment by paulmohljr** [comment]
> I am not getting any digital disbursement Product in drop down when I am creating a workspace. Is it normal? using fisrv developer studio

hi @hasaanali057  that functionality for creating a MID for Digital disbursements is not available yet. You would want to work with your Sales lead to have them request one and a member of the team would work with you on that.

**Comment by hasaanali057** [comment]
@paulmohljr well I have tried thrice now to ask for a test environment, but seem to be getting no response. I need one for portal flow.

**Comment by hasaanali057** [comment]
@paulmohljr is there any other way to generate payouts? or any API or method to just send payment to an account. like I provide an account number and amount and payment is sent to that specific account?
