### ISSUE TITLE
Release Merchant Acquiring - LATAM tenant to next environment 

### ISSUE THREAD

**Issue by CinthyaRivera** [Fiserv/Support#271]
**Region** (optional)
Latam

**Is your feature request related to a problem? Please describe.**
Merchant Acquiring - LATAM tenant is ready to move to next environments (QA, Stage and Prod).

**Describe the solution you'd like**
Start tenant release to next environments (QA, Stage and Prod

**Describe alternatives you've considered**
N/A

**Additional context**
(https://github.com/Fiserv/merchant-acquiring-latam

**Comment by TaniaSarkar89** [comment]
Opened JIRA tickets for Developer Studio team's tracking: https://firstdatateam.atlassian.net/browse/PORT-5683

**Comment by sfiserv** [comment]
The changes will be available for verification after our QA deployment at end of Sprint 2.

**Comment by CinthyaRivera** [comment]
In accordance with the deployment schedule, sprint 2 ends 2/16/023, is that correct?
Deployment dates indicates that in that date release will be in prod
@sfiserv

**Comment by sfiserv** [comment]
@CinthyaRivera sprint 2 will end on Jan 27 and we have our QA deployment on the same day. and the sprint 2 code will be deployed to Production on 2/16.
However you have raised the issue only to move the your product to QA. so the product will remain in QA till you confirm and inform us to move to higher environments.

**Comment by CinthyaRivera** [comment]
Yes, the expectation is to have in prod on 2/16. So, please help me to move to higher environments.

**Comment by sfiserv** [comment]
Please update this issue accordingly. as our team has worked on the progression as per your description in this issue ( just to QA env).

**Comment by CinthyaRivera** [comment]
@sfiserv done

**Comment by sfiserv** [comment]
@CinthyaRivera the changes have been done as per your requirement. You should be able to test them as we progress with our deployment cycle.

**Comment by CinthyaRivera** [comment]
@sfiserv I see this issue closed, so I understand it's not necessary to create an additonal ticket to move to production, is that correct?

**Comment by sfiserv** [comment]
Reopening this issue to be expedite the process.
