### ISSUE TITLE
Capture fail after Pre-Auth of all the test card

### ISSUE THREAD

**Issue by tfzxyinhao** [Fiserv/Support#272]
### Operating system

Windows 10

### Laravel Version

not laravel project

### PHP Version

not php project

### Project Location

Local

### Bug description

[Capture](https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Resources/API-Documents/Payments/Capture.md) fail after [Pre-Auth](https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Resources/FAQs-Glossary/Glossary.md#preauth) of all the test card

# reference link
## test card 
https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Resources/Guides/Testing/Test-Scripts/Test-Scripts.md

## api doc
https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Resources/API-Documents/Payments/Charges.md&branch=main#tab-source

## Pre-Auth

![image](https://user-images.githubusercontent.com/444814/212644818-2c51a3b5-24c6-4249-bf6e-5c4a15d4ef1a.png)

## Capture fail
![image](https://user-images.githubusercontent.com/444814/212645419-eaf61d5d-4015-476b-b844-f80a31bdf708.png)

**Comment by wwfiserv** [comment]
This method of capture is being sunset, have you tried using the reference transaction identifier and the charges endpoint?

https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Resources/API-Documents/Payments/Capture.md&branch=main


{
  "amount": {
    "total": 12.04,
    "currency": "USD"
  },
  "transactionDetails": {
    "captureFlag": true,
  },
  "merchantDetails": {
    "merchantId": "100009000000200",
    "terminalId": "00000001"
  },
  "referenceTransactionDetails": {
    "referenceTransactionId": "31a12bba68a44e31b98d27ad37b6b5f4"
  }
}

**Comment by wwfiserv** [comment]
@tfzxyinhao sorry for the delay I needed to verify with our tech team. Currently the simulator does not support secondary transactions. We are working to remedy this in the next major update in March or April.
