### ISSUE TITLE
Link to external sites in explorer 

### ISSUE THREAD

**Issue by CinthyaRivera** [Fiserv/Support#273]
# Reporting new issue for explorer menu Merchant Acquiring - LATAM

**Region** (if applicable)
LATAM

**Page**
[Path of the page where the problem exists.](https://dev-developerstudio.fiserv.com/product/MerchantAcquiringLATAM/docs/?path=%3Chttps://dev.softwareexpress.com.br/%3E&branch=develop)

**Describe the bug**
I want to show as part of menu a link to an external page. 
The option to view Carat is available in the menu, however, attempting to access it results in a 404 error being displayed.

**To Reproduce**
1. Go to '[Main page](https://dev-developerstudio.fiserv.com/product/MerchantAcquiringLATAM)'
2. Click on 'Carat'
3. See error 404

**Expected behavior**
Open external link to carat portal

**Screenshots**
![image](https://user-images.githubusercontent.com/111396588/212783719-8b36e3ea-593d-4d9f-8e11-91089d0a438e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Browser: Chrome

**Additional context**

**Comment by TaniaSarkar89** [comment]
Hi @CinthyaRivera As of today we are not offering this functionality where you can add an external link directly in the documentation tree. But you can always add the external link in a markdown and link that markdown in the documentation tree as usual.

**Comment by CinthyaRivera** [comment]
Thanks Tania, I will be pending of any update
