### ISSUE TITLE
No Result with Partial URL Search

### ISSUE THREAD

**Issue by wwfiserv** [Fiserv/Support#274]
Commerce Hub

**Region** (if applicable)
Production

**Page**
https://developer.fiserv.com/search?q=cert.api.fiservapps.

**Describe the bug**
When searching for a partial of a URL example cert.api or cert.api.fiservapps no results are found. When searching for cert.api.fiservapps.com/ch/{resource}, or cert.api.fiservapps.com with or without https:// results are found.

**Expected behavior**
Users should be able to search for partial URLs

**Comment by sfiserv** [comment]
Tracking this issue in https://firstdatateam.atlassian.net/browse/PORT-5736

**Comment by wwfiserv** [comment]
Any update as this has been marked stale?
