### ISSUE TITLE
Ability to download individual yaml

### ISSUE THREAD

**Issue by drodriguez74** [Fiserv/Support#275]
**Region** (optional)
[Issue Solutions](https://developer.fiserv.com/product/IssuerSolutions)

**Is your feature request related to a problem? Please describe.**
Clicking on Download API Specs download every api listed under API Explorer. What I was expecting was for it to only down the yaml that was initially uploaded into the DevStudio. Also when downloading the zip, all the swagger is json. I want to download just the individual yaml

**Describe the solution you'd like**
Download only the Swagger contain the service that api belongs to.

**Describe alternatives you've considered**
I want to download just the individual yaml

**Comment by drodriguez74** [comment]
The reason we want this is specifically for our other DevPortal. We want to update the location of the resources for each of the cards on the main api browser page.
https://cat-fiapi.firstdata.com/portal/NA/apibrowser

The idea is to be able to link to the DevStudio resources and download them. 

The download link currently just downloads the yaml. Since we are uploading these to the DevStudio, we'd like to be able to download it from there instead. 

Otherwise we're basically uploading them to 2 locations

**Comment by acho-fiserv** [comment]
technically, i don't you need to wait for the studio for this.  in your other site just use the github urls to reference your files.  use the github api & your token to read the files.  you're still pulling from the same source.

**Comment by acho-fiserv** [comment]
you would just use the github urls in your browser
