### ISSUE TITLE
Changes not published

### ISSUE THREAD

**Issue by CinthyaRivera** [Fiserv/Support#276]
# Reporting new issue for Merchant Acquiring - LATAM/Merchant

**Region** (if applicable)
LATAM

**Page**
[Path of the page where the problem exists.](https://dev-developerstudio.fiserv.com/product/MerchantAcquiringLATAM)

**Describe the bug**
I am unable to see the updates I made, it seems that they have not been published. Can you please investigate and let me know if there are any issues or if additional steps are required for the changes to be visible? 

Note: I've validate with no errors
[document-explorer-definition.yaml](https://github.com/Fiserv/merchant-acquiring-latam/blob/develop/config/document-explorer-definition.yaml)
[product-layout.yaml](https://github.com/Fiserv/merchant-acquiring-latam/blob/develop/config/product-layout.yaml)
[tenant.json](https://github.com/Fiserv/merchant-acquiring-latam/blob/develop/config/tenant.json)

**To Reproduce**

**Expected behavior**
Publish my changes to visualize in the developer portal.

**Screenshots**
Left side is the repository / Right side is the tenant

![image](https://user-images.githubusercontent.com/111396588/213037997-9ed3d66a-f385-44fb-976f-814cbcd87b4e.png)

![image](https://user-images.githubusercontent.com/111396588/213038101-bbfe85d7-48c9-43d3-9715-4055551a2abc.png)

![image](https://user-images.githubusercontent.com/111396588/213038214-b37a7591-d2ba-481f-a7ee-dd989550d741.png)

![image](https://user-images.githubusercontent.com/111396588/213038451-4a8fed51-5c9b-4c31-a8bd-a589418cea5b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Browser: Chrome
 - Version: Version 109.0.5414.75 (Official Build) (64-bit)

**Tablet (please complete the following information):**
 - Device: [e.g. iPad]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sfiserv** [comment]
@CinthyaRivera our team verified the issue and seems now the changes are being reflected on the UI.please verify and let us know if you are still facing any problems.
It takes some time to get the changes reflected on UI, it a cron job which runs every few hours.

**Comment by CinthyaRivera** [comment]
@sfiserv I can see the changes updated. Thanks :D

**Comment by sfiserv** [comment]
Closing this issue as resolved.
