### ISSUE TITLE
APAC Acceptance Solutions - Promoting to QA environment

### ISSUE THREAD

**Issue by Eileenqfsv** [Fiserv/Support#277]
**Region** (optional)
APAC

**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Request to promote tenant to QA environment.

**Describe alternatives you've considered**
NA

**Additional context**
@TaniaSarkar89 - This request is to facilitate the ask to promote this feature to QA environment.
PromotingToHigherEnv_18Jan23.pdf…]()

**Comment by TaniaSarkar89** [comment]
Opened JIRA ticket for internal developer studio tracking
https://firstdatateam.atlassian.net/browse/PORT-5683

**Comment by sfiserv** [comment]
The changes will be available for verification after our QA deployment at end of Sprint 2.

**Comment by sfiserv** [comment]
@Eileenqfsv just needed confirmation from you if you are looking to move Acceptance Solution APAC to just QA env for now or you want it to progress up to Production.
This ticket mentions only about QA env. DevStudio team has as already made DB changes so as Acceptance solution APAC will be live in production by 2/27

**Comment by Eileenqfsv** [comment]
Hi @sfiserv , we are not ready to live. There are some minor changes to be completed. Can we move this to QA environment first, let the team complete the minor revisions. The team will be using the QA environment to have a walkthrough and stage gate with the senior management. Once the senior management team has given the go-ahead we will move to prod. Do let me know if this is workable. Thanks, Supriya.

**Comment by sfiserv** [comment]
Thanks @Eileenqfsv  for the clarification. For now we will enable the AS-APAC on QA only.

**Comment by Eileenqfsv** [comment]
Thanks, @sfiserv .  👍
