### ISSUE TITLE
503 error when displaying tenant

### ISSUE THREAD

**Issue by CinthyaRivera** [Fiserv/Support#278]
# Reporting new issue for Silvercore

**Region** (if applicable)
LATAM

**Page**
[Path of the page where the problem exists.](https://dev-developerstudio.fiserv.com/product/SilverCore)

**Describe the bug**
Tenant has not been modified and still unable to display. Shows 503 error. 

**To Reproduce**
1. Go to 'https://dev-developerstudio.fiserv.com/product/SilverCore)'
2. See error 503

**Expected behavior**
Visualize tenant 

**Screenshots**
![image](https://user-images.githubusercontent.com/111396588/213230344-21ba0ec9-bc03-44e7-a8ef-784720de298d.png)

**Desktop (please complete the following information):**
 - OS: Window 10 Enterprise
 - Browser: Chrome

**Tablet (please complete the following information):**
 - Device: [e.g. iPad]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sfiserv** [comment]
@CinthyaRivera our team is reviewing this issue. will update you here or in the teams channel

**Comment by sfiserv** [comment]
@CinthyaRivera the issue is fixed please check the dev environment your product is now loading without any errors.

<img width="1163" alt="image" src="https://user-images.githubusercontent.com/87097017/213578439-95b0a8c1-2740-439c-a11e-2d0bbea02265.png">
