### ISSUE TITLE
Please provide the capability of drop downs and enable <br> tag , so that can make line break in the markdown

### ISSUE THREAD

**Issue by f7292v6** [Fiserv/Support#281]
**Region** (optional)
The region of a user requesting the feature.

**Is your feature request related to a problem? Please describe.**
To implement schemas from IPG Gate Way spec : https://docs.firstdata.com/org/gateway/docs/api#models
we need dropdown capability in markdown.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sfiserv** [comment]
created a tracking ticket https://firstdatateam.atlassian.net/browse/PORT-5733

**Comment by OZ-FS** [comment]
@f7292v6  please comment

**Comment by f7292v6** [comment]
Thanks @OZ-FS  tag br will help a lot in formatting.

**Comment by f7292v6** [comment]
Closing this as verified on tab br and working fine.
