### ISSUE TITLE
Enable sandbox for firstvision-emea

### ISSUE THREAD

**Issue by shubhamKanse99** [Fiserv/Support#282]
**Region** (optional)
EMEA

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Please help in enabling the sandbox environment to consume firstvision APIs

**Describe alternatives you've considered**
N/A

**Additional context**
Hi Team, We would like to have sandbox enabled to consume the APIs
on old portal (https://docs.firstdata.com/org/global/docs/api/UAT) we have 'try out' API option, which points to our sandbox  (host : cert.api.firstdata.com) environment. 
Similarly we would like to have it here on devstudio.

Detail steps on how old portal works for sandbox.
1.Sandbox credentials are created in APIGEE for clients.
2.Based on those credentials client will generate a client_assertion (JWT token) 
3.This client_assertion will then be passed to our existing API (generate cc token) which will create a bearer token
4. This bearer token is then passed in API header to hit the APIs. 
Detailed technical document - https://dev-developerstudio.fiserv.com/product/FirstVisionEMEA/docs/?path=docs/Support/Registration-and-Token.md

The ask from devstudio team is to make the sandbox host available for firstvision emea APIs to point. 

Sandbox Details: 
Host : cert.api.firstdata.com/api/fs
sample API url from postman : https://cert.emea.api.fiservapps.com/api/fs/fv_emea/v1/customerAccountCardAdd

- Subscribe to a Team
@Fiserv/firstvision-emea )

-->

**Comment by sfiserv** [comment]
Tracking issue in https://firstdatateam.atlassian.net/browse/PORT-5734

**Comment by shubhamKanse99** [comment]
Hi @TaniaSarkar89, is there any update on this?

**Comment by TaniaSarkar89** [comment]
Hi @shubhamKanse99 I have dropped you a detailed email on this.

Thanks!

**Comment by TaniaS-fiserv** [comment]
Hi @shubhamKanse99 is there anything pending from Dev Studio end? If not, requesting you to close this ticket.

Cc: @sfiserv

**Comment by shubhamKanse99** [comment]
Hi @TaniaS-fiserv , 

I have replied to you over mail for the issue with the sandbox env. Can you please check that and re-open this issue? 

subject - Discussions for GitHub ticket #282

Thanks!

**Comment by TaniaS-fiserv** [comment]
Hi @shubhamKanse99  could you please share some sample request payloads to test this on Dev & QA environments for this endpoint: 
_**/fv_emea/security/v1/token/jwt/generate**_

**Comment by TaniaS-fiserv** [comment]
Hi @shubhamKanse99 do you have any updates for me ? We are blocked on this until you provide us some test data.

**Comment by shubhamKanse99** [comment]
Hi @TaniaS-fiserv apologies, 

Sample payload request for 

![image](https://github.com/Fiserv/Support/assets/117971606/72667e52-1a35-4a38-810b-ba1066d427aa)


curl --location 'https://qa.emea.api.fiservapps.com/api/fs/fv_emea/security/v1/token/jwt/generate' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'grant_type=client_credentials' \
--data-urlencode 'scope=emea_firstvision' \
--data-urlencode 'client_assertion=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJaY3UzSTBZTU0ybnlkMzNBOHNxcWhBNkdSZVYwRjFlaSIsImF1ZCI6Imh0dHBzOlwvXC9jZXJ0LmVtZWEuYXBpLmZpc2VydmFwcHMuY29tXC9hcGlcL2ZzXC9mdl9lbWVhXC9zZWN1cml0eVwvdjFcL3Rva2VuIiwiaXNzIjoiWmN1M0kwWU1NMm55ZDMzQThzcXFoQTZHUmVWMEYxZWkiLCJleHAiOjE2Mjk3OTg0NjAsImlhdCI6MTYyOTc5NDg2MCwianRpIjoiNThkNjFjMWUtYzIwNi00ZDVkLThmOTQtNDYzMzA2ZGE0ZWZhIn0.bJt3ZbGJ-LYFhohlHwISqFQIi3oUfJbLtP40Jmryx2w' \
--data-urlencode 'client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer' \
--data-urlencode 'client_id=Zcu3I0YMM2nyd33A8sqqhA6GReV0F1ei'



for request 

contentType is - application/x-www-form-urlencoded

for response 

contentType is JSON

**Comment by yoramfor-fiserv** [comment]
Hi,

We implemented the changes in the live sandbox. The changes are undergoing tests in our dev environment (which is not open to you).

We tested with the values you provided us and got back an error message. Please see the attached image. Is it possible that the JWT expired?

Please provide us with a JWT that will work and not expire for a long time so we can continue in our testing.

Thanks,

Tania/Yoram

![image](https://github.com/Fiserv/Support/assets/83249894/42a0dbda-9d91-4b11-ba16-fa453bb082ee)

**Comment by shubhamKanse99** [comment]
Hi @yoramfor-fiserv , 

jwt can be used only once for a request, I will provide you developer API details which can be used to generate jwt from postman. 

curl --location 'https://cert.emea.api.fiservapps.com/api/fs/fv_emea/security/v1/demo_token/buildjwt' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'client_id=fi04ubyaReD8EOPSyMqSV7ByNfH9FxVK'

Please let me know if you face any issues.

**Comment by yoramfor-fiserv** [comment]
Hi,
Thank you for your response. I tried to use curl to build a JWT and then use it in a generate command and here's what I see:

curl --location 'https://cert.emea.api.fiservapps.com/api/fs/fv_emea/security/v1/demo_token/buildjwt' --header 'Content-Type: application/x-www-form-urlencoded' --data-urlencode 'client_id=fi04ubyaReD8EOPSyMqSV7ByNfH9FxVK'

            {
                "client_assertion": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJmaTA0dWJ5YVJlRDhFT1BTeU1xU1Y3QnlOZkg5RnhWSyIsImF1ZCI6Imh0dHBzOlwvXC9jZXJ0LmVtZWEuYXBpLmZpc2VydmFwcHMuY29tXC9hcGlcL2ZzXC9mdl9lbWVhXC9zZWN1cml0eVwvdjFcL3Rva2VuIiwiaXNzIjoiZmkwNHVieWFSZUQ4RU9QU3lNcVNWN0J5TmZIOUZ4VksiLCJleHAiOjE2OTA5OTM2MzgsImlhdCI6MTY5MDk5MDAzOCwianRpIjoiMmJjNDljZTYtOGE5MS00YWM1LWFkMjMtZTMyMzZhOGQ4ODI1In0.FXYXrJfy2gOxtfqtuLFHsnV4Plug_M_LpSi2OA2Tgyw"
            }
        %                                                                                                                                                                  

curl --location 'https://qa.emea.api.fiservapps.com/api/fs/fv_emea/security/v1/token/jwt/generate' --header 'Content-Type: application/x-www-form-urlencoded' --data-urlencode 'grant_type=client_credentials' --data-urlencode 'scope=emea_firstvision' --data-urlencode 'client_assertion=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJmaTA0dWJ5YVJlRDhFT1BTeU1xU1Y3QnlOZkg5RnhWSyIsImF1ZCI6Imh0dHBzOlwvXC9jZXJ0LmVtZWEuYXBpLmZpc2VydmFwcHMuY29tXC9hcGlcL2ZzXC9mdl9lbWVhXC9zZWN1cml0eVwvdjFcL3Rva2VuIiwiaXNzIjoiZmkwNHVieWFSZUQ4RU9QU3lNcVNWN0J5TmZIOUZ4VksiLCJleHAiOjE2OTA5OTM2MzgsImlhdCI6MTY5MDk5MDAzOCwianRpIjoiMmJjNDljZTYtOGE5MS00YWM1LWFkMjMtZTMyMzZhOGQ4ODI1In0.FXYXrJfy2gOxtfqtuLFHsnV4Plug_M_LpSi2OA2Tgyw' --data-urlencode 'client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer' --data-urlencode 'client_id=fi04ubyaReD8EOPSyMqSV7ByNfH9FxVK'

                {
                    "errorMessage": "The client id provided is invalid. Please try with valid client id.",
                    "errorCode": "API-Sec-002"
                }
            %                                                                                                                                                              

Please let us know how to overcome this issue.

Thanks,

Tania/Yoram

**Comment by shubhamKanse99** [comment]
Hi @yoramfor-fiserv , 

Please use host as cert.emea.api.fiservapps.com to generate the token. 

client assertion is generated for "cert" environemnt and token is being asked to generate for qa.

**Comment by yoramfor-fiserv** [comment]
Hi,

I was able to successfully test the generate CCToken function. In order to do that I had to modify the base URL of the live sandbox to: `https://cert.emea.api.fiservapps.com/api/fs`
The previous URL was `https://cert.api.firstdata.com/api/fs`

Please note that this changed the base URL to **all** sandbox requests.

**Comment by yoramfor-fiserv** [comment]
Hi,

Please let us know if this issue is resolved and we can close the ticket.

Thanks,

Yoram

**Comment by shubhamKanse99** [comment]
Hi @yoramfor-fiserv , 

Where can we test the same? and when can this be promoted to the main branch? 

Thanks!

**Comment by shubhamKanse99** [comment]
Hi @yoramfor-fiserv , 

Please help us in testing the same at our side. 

Thanks!

**Comment by yoramfor-fiserv** [comment]
Just to make sure it is clear. We are modifying the live sandbox URL to https://cert.emea.api.fiservapps.com/api/fs

**Comment by sfiserv** [comment]
@shubhamKanse99 the changes are currently in the dev env. Once they are available in QA at end of sprint16, your team should verify it

**Comment by shubhamKanse99** [comment]
Hi @sfiserv, I have verified the changes in QA region. 
Everything is working as expected. 

Please help promote these changes in to prod environment as well thanks!

**Comment by sfiserv** [comment]
Changes are promoted to Production env.

**Comment by shubhamKanse99** [comment]
Hi Team, 

Any update on this issue?

**Comment by shubhamKanse99** [comment]
Hi @sfiserv, 

I have just validated the request and token generation in qa region of DevStudio. Kindly push the changes to production. 

The URL - https://cert.emea.api.fiservapps.com/api/fs is also correct to connect to sandbox. 

Thanks!

**Comment by sfiserv** [comment]
@shubhamKanse99  are there any updates from your team if you have fixed the errors seen during the triaging call.
If its done please verify the changes and close this issue.

**Comment by shubhamKanse99** [comment]
Hi @sfiserv, 
There were no errors to fix, it was the request data issue where it was throwing misleading error, but after internal discussion. it is right to configure that way.
I have provided details with Russell for his queries. 
We are now waiting it to get promoted in production branch, where clients can test.
