### ISSUE TITLE
Anchor links to other Articles Broken

### ISSUE THREAD

**Issue by wwfiserv** [Fiserv/Support#285]
Commerce Hub

**Region** (if applicable)
Production

**Page**
https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Resources/Master-Data/Amount-Components.md **(clicking surcharge or convenience fee link)**
https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Resources/Guides/Dynamic-Descriptor.md **(clicking on amount link in table)**

**Describe the bug**
When clicking on a link that anchors to another page, it does not navigate to the anchor. It appears to be an issue with &branch=main being added to the URL. Clicking the link in the right navbar navigates properly to the anchor.

**Expected behavior**
Link should navigate to the anchored location.

**Comment by sfiserv** [comment]
Tracking this issue in https://firstdatateam.atlassian.net/browse/PORT-5753

**Comment by wwfiserv** [comment]
Reopening as it appears this wasn't fixed, another example https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Resources/Guides/Settlement/Transaction-Capture-Type.md&branch=main when you click on Host capture, Gateway capture or Terminal capture the anchor link to the glossary.md doesn't work.

**Comment by minh-pham1** [comment]
Hello William! Sorry this issue slipped under the radar, both the original assigned developer and product manager left the team. I've reassigned the ticket to a new developer for next sprint.

**Comment by wwfiserv** [comment]
reopening, stalebot closed

**Comment by minh-pham1** [comment]
Quick update: Due to some priotization issues, we'll plan to address this issue next sprint (in another 2-3 weeks from now). Apologies for the delay!

**Comment by OZ-FS** [comment]
[TFDS-1508](https://enterprise-jira.onefiserv.net/browse/TFDS-1508)

The solution to this issue is deployed in DEV.
@wwfiserv please test.

**Comment by OZ-FS** [comment]
[TFDS-1508](https://enterprise-jira.onefiserv.net/browse/TFDS-1508) is DONE
@wwfiserv please re-test.

**Comment by minh-pham1** [comment]
Well, you shouldn't have to test in `dev`. However, the solution has been found and deployed so we'll update the ticket once the code has been deployed to `qa` sometime next week/sprint.

**Comment by minh-pham1** [comment]
Hello William! This issue has been fixed up to `stage`. Thank you for your patience!

**Comment by minh-pham1** [comment]
Closing as there seem to be no issue with the onboarding.
