### ISSUE TITLE
Newly added APIs are not displaying on Dev Studio

### ISSUE THREAD

**Issue by fiservakshay** [Fiserv/Support#287]
# Reporting new issue for Banking Hub 

We have uploaded 105 new YAMLs on GitHub to display implementation-specific documentation on the Developer Studio. This documentation can be accessed from the core dropdown as below:
![image](https://user-images.githubusercontent.com/81968767/215076533-7778e2e7-e872-492b-a7e5-b2f33ae873e8.png)

However, even after successfully testing the funcatanily, the newly uploaded YAMLs are not being displayed on the portal. 

Kindly have a look into this issue and do the needful. Please note that we are planning to roll out this documentation in next release (Feb 3, 2022) and before that we need to perform quality check as well.

cc: @acho-fiserv  @bobburghardt @TaniaSarkar89

**Comment by rahravin** [comment]
We plan to move this documentation to production on Feb 3rd, and it looks to be the max APIs limit issue, and we have exceeded the 300 limit. We would soon have 500+ APIs. Need your attention on this.

**Comment by rahravin** [comment]
Thanks for looking into this. Can we change the limit to 1000? Since we will have ~100 APIs per Core (DNA, Portico, Finxact), and other surround products like Cards, BillPay, Channels.

**Comment by fiservakshay** [comment]
Hi, we are able to see the newly added APIs now. We will confirm the count and close the ticket accordingly. 
Thanks for the prompt support.

**Comment by fiservakshay** [comment]
Hi, we have checked the APIs and all new APIs are started showing up on the portal, hence closing the ticket. 
Thanks for the support.
