### ISSUE TITLE
Request to increase the limit for the APIs to 1200 in order to cater all our services in the application

### ISSUE THREAD

**Issue by sundarbx** [Fiserv/Support#288]
**Region** (optional)
The region of a user requesting the feature - LATAM

**Is your feature request related to a problem? Please describe.**
Currently our existing and potential new clients are requesting to access all the services in the Signature application.

**Describe the solution you'd like**
Increasing the limit of number of APIs up to 1200.

**Describe alternatives you've considered**
None

**Additional context**

**Comment by sfiserv** [comment]
@sundarbx  I am closing this issue since the requirement is fulfilled. The API limit is now increased to 2000.
