### ISSUE TITLE
Unable to view new API in API explorer

### ISSUE THREAD

**Issue by shubhamKanse99** [Fiserv/Support#289]
# Reporting new issue for [NAME] (Tenant/Product)

**Region** (if applicable)
EMEA

**Page**
API explorer

**Describe the bug**
Newely added API in another version of yaml file are not visible. 
yaml file for - 23.02(Major) able to see all updates and new APIs
yaml file for - 23.06(Minor) Partially visible, Only updates are visible, New API are not visible in API explorer (new API for reference added in 23.06 - v1 vulnerability Information Capture) 

**To Reproduce**
We can search it in developerstudio search and we can see new API there. But not in API explorer

**Expected behavior**
Should display all APIs in API explorer 

**Screenshots**
N/A

**Additional context**

**Comment by sfiserv** [comment]
Also could you please elaborate more on this issue. ( if any error message/screenshots of gtihub repo where you have added the files, branch... )
 just needed to know if the API added are exceeding 300 and hence not getting displayed.

**Comment by shubhamKanse99** [comment]
Hi @sfiserv, 
In 23.06 yaml file, we have updates to existing APIs and New APIs, ( ex - vulnerability information capture)
in 23.02 yaml file we have same, new as well as updates to existing APIs -- These are all visible (Both update and new)

but for 23.06 yaml file new APIs added are not displaying in API explorer, but i can search them on top right search bar.
![image](https://user-images.githubusercontent.com/117971606/216268582-c44a5b27-f906-454c-a9f7-5a8a7a325874.png)

Not sure on what "exceeding 300" means.

**Comment by sfiserv** [comment]
@shubhamKanse99 can we close this issue based on the conversation in the teams channel- Tania had looked into this issue and pointed out to be ab issue in the tenant json file
https://teams.microsoft.com/l/message/19:d366d60ce4044de2bcbf1a1f8cc91dbf@thread.tacv2/1675455328220?tenantId=11873a1f-4c8d-450d-8dfb-e37a2e2557f8&groupId=982cd560-8afd-42fc-bb4c-543e1989b6b1&parentMessageId=1674222110374&teamName=Developer%20Studio%20from%20Fiserv&channelName=EMEA%20(FirstVision)&createdTime=1675455328220&allowXTenantAccess=false

**Comment by shubhamKanse99** [comment]
Hi @sfiserv , There is a new error now. 

![image](https://user-images.githubusercontent.com/117971606/216892745-2f4dc577-669e-4629-8a2a-02a3c6f4d202.png)

**Comment by sfiserv** [comment]
@shubhamKanse99 for now we have refreshed and reindexed. you should be able to access the apis in the dev, qa env.

**Comment by sfiserv** [comment]
Closing this as issue has been fixed.no response on client verification.
