### ISSUE TITLE
Changes not published

### ISSUE THREAD

**Issue by CinthyaRivera** [Fiserv/Support#290]
# Reporting new issue for Merchant Acquiring - LATAM

**Region** (if applicable)
LATAM

**Page**
https://dev-developerstudio.fiserv.com/product/MerchantAcquiringLATAM/docs/?path=docs/espa%C3%B1ol/pagos/3-5-3d-secure.md&branch=develop

**Describe the bug**
Made some modifications but not published since yesterday morning. I checked yaml and markdown validator and everything it's correct.

**To Reproduce**

**Expected behavior**
Visualize my changes

**Screenshots**
![image](https://user-images.githubusercontent.com/111396588/216472579-2818724b-29d3-4492-85e7-11d341d8c9c8.png)

**Desktop (please complete the following information):**

**Tablet (please complete the following information):**
 - Device: [e.g. iPad]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sfiserv** [comment]
@CinthyaRivera are these changes you were looking for?

<img width="1421" alt="image" src="https://user-images.githubusercontent.com/87097017/216691231-3d3c0496-2ede-4b23-883e-23935b0b917d.png">

**Comment by sfiserv** [comment]
@CinthyaRivera  I can see the changes in the QA env. please let me know if this is right.
<img width="1298" alt="image" src="https://user-images.githubusercontent.com/87097017/216734273-69f981c8-dd48-415b-8c32-4397f2587d3a.png">

**Comment by sfiserv** [comment]
@CinthyaRivera the issue was resolved in dev env. please verify the changes
