### ISSUE TITLE
IPG NA - Need a horizontal scroll bar on the left panel.

### ISSUE THREAD

**Issue by f7292v6** [Fiserv/Support#291]
### Operating system

WINDOWS 10

### Laravel Version

NA

### PHP Version

NA

### Project Location

Local

### Bug description

IPG NA - Need a horizontal scroll bar on the left panel. When open the schemas , can not read the full API names, better to have horizontal scroll bar on the left panel as the panel with fixed width.

![screenshot](https://user-images.githubusercontent.com/122384599/216499070-d56d3513-4bdc-4dd9-9c5d-2fc7a5f0963f.JPG)

**Comment by f7292v6** [comment]
hi When can we expect this to be included?

**Comment by jimmychen-fiserv** [comment]
Hi, our new left nav is under construction. This problem will be gone once the new version is released.

**Comment by sfiserv** [comment]
@f7292v6  This will be fixed as part of our new left navigation feature upgrade.

**Comment by f7292v6** [comment]
hi, any update on this defect? when this will be available on production?
