### ISSUE TITLE
400 bad request 

### ISSUE THREAD

**Issue by suvarnaashoka** [Fiserv/Support#292]
# Reporting new issue for [NAME] (Tenant/Product)

**Region** (if applicable)
The region of a user reporting the bug.

**Page**
Path of the page where the problem exists.

**Describe the bug**
we are trying to integrate https://cert.api.firstdata.com/gateway/v1/payments API with GPay in our website but we are getting 400 bad request. What's wrong with the following payload and header?
let payload = {
                            "requestType": "WalletSaleTransaction",
                            "walletPaymentMethod": {
                                "walletType": "EncryptedGooglePayWalletPaymentMethod",
                                "encryptedGooglePay": {
                                    "data": {
                                        "encryptedMessage": encryptedSignedmessage.encryptedMessage,
                                        "ephemeralPublicKey": encryptedSignedmessage.ephemeralPublicKey,
                                        "tag": encryptedSignedmessage.tag
                                    },
                                    "signature": tokenobj.signature,
                                    "version": tokenobj.protocolVersion,
                                }
                            },
                            "transactionAmount": {
                                "total": "1",
                                "currency": "USD"
                            }
                        };

 const options = {
                            method: 'POST',
                            headers: {
                                'Content-Type': 'application/json',
                                'Client-Request-Id': clientRequestId,
                                'Api-Key': apiKey,
                                'Timestamp': timestamp,
                                'Message-Signature': messageSignature,
                                'Region': 'US',
                            },
                            body: JSON.stringify(payload)
                        };

                        fetch('https://cert.api.firstdata.com/gateway/v1/payments', options)

**Comment by wwfiserv** [comment]
@suvarnaashoka digital wallets are currently not supported in our Sandbox environment. You will need to have a dedicated MID setup. Please contact your merchant account representative to discuss integrating with Commerce Hub.

**Comment by suvarnaashoka** [comment]
We also tried with the request type PaymentCardSaleTransaction but the response we are getting is 400 bad request and we are passing the dedicated MID to the gpay request in test environment as 
 const tokenizationSpecification = {
        type: 'PAYMENT_GATEWAY',
        parameters: {
            "gateway": "firstdata",
            "gatewayMerchantId": "MID"
        }
    };


First data payment API:
let payload = {
                            "requestType": "PaymentCardSaleTransaction",
                            "paymentMethod": {
                                "paymentCard": {
                                    "encryptedGooglePay": {
                                        "data": {
                                            "encryptedMessage": encryptedSignedmessage.encryptedMessage,
                                            "ephemeralPublicKey": encryptedSignedmessage.ephemeralPublicKey,
                                            "tag": encryptedSignedmessage.tag
                                        },
                                        "signature": tokenobj.signature,
                                        "version": tokenobj.protocolVersion,
                                    }
                                }
                            },
                            "transactionAmount": {
                                "total": "1",
                                "currency": "USD"
                            }
                        };

const options = {
method: 'POST',
headers: {
'Content-Type': 'application/json',
'Client-Request-Id': clientRequestId,
'Api-Key': apiKey,
'Timestamp': timestamp,
'Message-Signature': messageSignature,
'Region': 'US',
},
body: JSON.stringify(payload)
};

fetch('https://cert.api.firstdata.com/gateway/v1/payments', options)

**Comment by suvarnaashoka** [comment]
Thanks for your response, as per your reply you mean, whether we will be able to test everything in sandbox environment?
or can we test only in production?

**Comment by wwfiserv** [comment]
@suvarnaashoka currently you can only test a PaymentCard charges request https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Resources/API-Documents/Payments/Charges.md&branch=main

**Comment by luisgrases** [comment]
I am also getting 400 bad request for the payment charges. This is the  request:

```
const response = await axios.request<object, AxiosResponse<Response>, Body>(
      {
        url: `https://cert.api.fiservapps.com/ch/payments/v1/charges`,
        data: {
          amount: {
            total: '12.04',
            currency: 'USD',
          },
          source: {
            sourceType: 'PaymentCard',
            card: {
              cardData: '4005550000000019',
              expirationMonth: '02',
              expirationYear: '2035',
            },
          },
          transactionDetails: {
            captureFlag: true,
          },
          merchantDetails: {
            merchantId: '100008000033683',
          },
        },
        headers: {
          ...getFiservHeaders(data),
          ...headers,
        },
        ...rest,
      }
    )
```

**Comment by luisgrases** [comment]
ok now I am closer, I am following the docs to generate the correct headers: Now I get a `ApiKey and/or Authentication supplied are invalid.`

Relevant code
```
POST:  https://cert.api.fiservapps.com/ch/payments/v1/charges

const getFiservHeaders = (data: AxiosRequestConfig['data']) => {
  const apiKey = process.env.FISERV_API_KEY
  const secretKey = process.env.FISERV_SECRET_KEY
  const clientRequestId = Math.floor(Math.random() * 10000000 + 1)
  const time = new Date().getTime()
  const requestBody = JSON.stringify(data)

  const messageSignatureString = apiKey + clientRequestId + time + requestBody
  const messageSignature = CryptoJS.HmacSHA256(
    messageSignatureString,
    secretKey
  )
  const messageSignatureBase64 = CryptoJS.enc.Base64.stringify(messageSignature)

  return {
    'Content-Type': 'application/json',
    'Client-Request-Id': clientRequestId,
    'Api-Key': apiKey,
    Timestamp: time.toString(),
    'Accept-Language': 'en-US',
    'Auth-Token-Type': 'HMAC',
    Authorization: messageSignatureBase64,
  }
}

**Comment by wwfiserv** [comment]
@luisgrases just to verify you are using the credentials from the default account inside of your dashboard? Additionally the merchantId and terminalId for that account are also required when submitting the request.

**Comment by luisgrases** [comment]
@wwfiserv I am using my sandbox credentials. 

Another question: What is the difference between the Commerce Hub payments api and the Internet Payment Gateway (IPG) NA API?

**Comment by wwfiserv** [comment]
@luisgrases these are two different Fiserv products, IPG NA is our older gateway for Enterprise clients, Commerce Hub is our newer gateway.

**Comment by luisgrases** [comment]
Perfect, any idea why my sandbox keys are not working for commerce hub? Am
I missing something?

**Comment by wwfiserv** [comment]
@luisgrases are you sending the terminalId, the payload above doesn't appear to include it.

**Comment by luisgrases** [comment]
@wwfiserv yeah I am sending it now:

```
data: {
          amount: {
            total: '12.04',
            currency: 'USD',
          },
          source: {
            sourceType: 'PaymentCard',
            card: {
              cardData: '4005550000000019',
              expirationMonth: '02',
              expirationYear: '2035',
            },
          },
          transactionDetails: {
            captureFlag: true,
          },
          merchantDetails: {
            merchantId: '100008000033683',
            terminalId: '10000001',
          },
        },
```

Still getting a:

```
error: [
    {
      type: 'APIM',
      message: 'ApiKey and/or Authentication supplied are invalid.'
    }
  ]
```

Let me know if there is any other info I can provide.

**Comment by luisgrases** [comment]
@wwfiserv nvm I found the issue, it was a stupid mistake on my said, everything is working fine.
