### ISSUE TITLE
Universal Commerce name change

### ISSUE THREAD

**Issue by rpatel47** [Fiserv/Support#302]
Change Universal Commerce to "Connected Commerce (uCom)"

**Comment by sfiserv** [comment]
https://firstdatateam.atlassian.net/browse/PORT-5826
Tracking ticket for this issue

**Comment by rpatel47** [comment]
It appears this task was addressed, though reference on landing page appears to have it as UCom which should be uCom.
<img width="226" alt="uCom to Connnected Commerce (UCom)" src="https://user-images.githubusercontent.com/106842027/220127094-8c36d833-2cc8-469c-931a-6fde30b7f90e.png">

**Comment by rpatel47** [comment]
Additionally, the same needs to be updated in the following references:
<img width="658" alt="image" src="https://user-images.githubusercontent.com/106842027/220444882-985002ea-40c2-4918-817b-567bb0d0f7c9.png">
![image](https://user-images.githubusercontent.com/106842027/220445218-ba1981cc-cbe4-4724-a154-99a0cae7a9ef.png)

**Comment by sfiserv** [comment]
@rpatel47 please verify the changes in dev env.

**Comment by rpatel47** [comment]
@sfiserv Waiting for the site to be up and running properly so I can view all the pages. Thank you for following up!
