### ISSUE TITLE
Is this channel a right place to communicate with FiServ support during API integration

### ISSUE THREAD

**Issue by AlexanderNikiforovLineate** [Fiserv/Support#303]
**Region** (optional)
The region of a user requesting the feature.
USA

Hello.
I'm working on an integration my customer product with FiServ DNA. 
I'm looking for a communication channel where I can ask questions about FiServ API parameters.
Is this place a right place to ask such questions or FiServ has a different ticket system where I can request help. 
Thank you.

Regards, Alexander Nikiforov.

**Comment by sfiserv** [comment]
@AlexanderNikiforovLineate  this is the support channel for the Fiserv Developer studio ( https://developer.fiserv.com/) 
If you have any questions regarding this please let us know
