### ISSUE TITLE
Which endpoint to use to fetch a relationship manager details (name, email, mobileNumber)?

### ISSUE THREAD

**Issue by AlexanderNikiforovLineate** [Fiserv/Support#307]
Hello.
[Get Party ](https://developer.fiserv.com/product/BankingHub/api/?type=post&path=/parties/secured&branch=main&version=11.0.0) endpoint returns a response that has a RelationshipMgrIdentEn parameter - Information about the financial institution officers who have management-related responsibilities of the account. Unique identifier of a relationship manager.

Which endpoint I can use to fetch relationship manager's name, email, mobileNumber by id (RelationshipMgrIdentEn).

Thank you

**Comment by AlexanderNikiforovLineate** [comment]
@sfiserv may I expect any help regarding my question?

**Comment by bobburghardt** [comment]
Hi @AlexanderNikiforovLineate ,

    That particular information is not returned from the DNA core processor.  Our BankingHub site will reflect that when DNA schemas are loaded into the environment.  Per our previous conversations, since you'll be engaging with the client's Client Partner for the specifications, you'll see what is returned for DNA.
