### ISSUE TITLE
In production we have observed all old content (instead recent version of .md file) were pulled when do a search.

### ISSUE THREAD

**Issue by f7292v6** [Fiserv/Support#308]
### Operating system

WINDOWS 10

### Laravel Version

NA

### PHP Version

NA

### Project Location

Local

### Bug description

when we do search, instead the recent version , all old versions of the .md files were pulled and when click they were showing wrong content. 
Expectation is to remove/block the old content and show only the recent version of the .md file on search.

### Steps to reproduce

Search for IPG on the landing page of https://developer.fiserv.com/ 
The below shouldn't be shown on search, as this has been removed.
![issue1](https://user-images.githubusercontent.com/122384599/218469349-3a71a671-414b-406d-99a6-a215df39b659.JPG)
Also we are seeing old version of below for example:
![isssue2](https://user-images.githubusercontent.com/122384599/218469610-e1ba51e7-6593-43d2-bc02-749bdeb39f0f.JPG)

### Relevant log output

```shell
Attached the jpg's which explains the issue.
```

**Comment by sfiserv** [comment]
@f7292v6 this issue should be now fixed please verify and let us know
