### ISSUE TITLE
Which products DNA Platform includes?

### ISSUE THREAD

**Issue by AlexanderNikiforovLineate** [Fiserv/Support#309]
Hello.

My team and I need to integrate our customer product with FiServ DNA Platform.
On developer studio, we see multiple products - Banking Hub, AllData Aggregation, Issuer Solutions...
It is not clear which products can we use for integration with DNA, which products are part of DNA platform.

For example, we need to provide a way to fetch a set of parameters by customerId or by social security number (SSN). 
We can fetch most of the parameters we need by customerId via [Get Party](https://developer.fiserv.com/product/BankingHub/api/?type=post&path=/parties/secured&branch=main&version=11.0.0) endpoint which is part of Banking Hub. But Get Party endpoint doesn't provide a way to fetch the same parameters by SSN.
Can we use [customerAccountSearch](https://developer.fiserv.com/product/IssuerSolutions/api/?type=post&path=/customer/v4/customerAccountSearch&branch=main&version=1.0.0) which is part of Issuer Solutions product?
Is Issuer Solutions product a part of DNA Platform? 

Thank you.

**Comment by sfiserv** [comment]
@eliascanaza  can you please help out @AlexanderNikiforovLineate for his queries.

**Comment by AlexanderNikiforovLineate** [comment]
@sfiserv @eliascanaza may I expect any help regarding my question?

**Comment by bobburghardt** [comment]
Hi @AlexanderNikiforovLineate ,

  The products available to a DNA client vary based upon what each client uses.  For DNA core application information, the BankingHub APIs are appropriate.  If the DNA client uses our Issuer solution, then those would be available.  Therefore the answer varies.  The client's Client Partner will be able to assist in provide the appropriate context.

Thanks.
