### ISSUE TITLE
How to set up a sandbox for Banking Hub, AllData Aggregation, Issuer Solution to be able to send requests from Postman and see demo data in responses?

### ISSUE THREAD

**Issue by AlexanderNikiforovLineate** [Fiserv/Support#310]
Hello.

My team and I are working on integrating our customer product with FiServ DNA.

We need to find some specific endpoints and parameters in FiServ API, and transform parameter values to build responses our client product will send.
To do so we need the following things:

1.  We need to be able to send requests to FiServ API (Banking Hub, AllData Aggregation, Issuer Solutions) from third-party applications (for example from Postman). For now, we cannot do so, because we don't have any URLs and other parameters to send requests. 

1.1 Code snippets show URL as localhost: 
![image](https://user-images.githubusercontent.com/124882232/218738747-64a622c9-d009-42cc-9d40-863010d397f2.png)

1.2 [Make Your First API Call](https://developer.fiserv.com/product/BankingHub/docs/?path=docs/getting-started/make-your-first-api-call.md&branch=main) manuals say that after registration we would get **API Key, Username/Password, OrgId, AppId, VendorId, ChannelId**.
Some of these credentials are required to be passed as header parameters under the EFXHeader parameter.

After registration, we didn't receive most of these credentials.

1.3 When we try to create a workspace we see that only workspace for Commerce Hub is available. We need a workspace for Banking Hub, AllData Aggregation and Issuer Solutions.

![image](https://user-images.githubusercontent.com/124882232/218740217-91374e54-3d90-4602-a6a9-23f6e40cc7dd.png)

After creating a workspace for Commerce Hub we have received an API key, but it doesn't look to work for Banking Hub and other API we need.  Even after creating a workspace for Commerce Hub we didn't receive **OrgId, AppId, VendorId, ChannelId**.

1.4 [Make Your First API Call](https://developer.fiserv.com/product/BankingHub/docs/?path=docs/getting-started/make-your-first-api-call.md&branch=main) manuals say that we need to generate an Access Token. The manual says that we can find UI for generation an Access Token on the Dashboard section. The Dashboard section is not available for us. If it is the Workspaces section, it doesn't have 
"Generate access Token" button/link. Also, workspaces may be created only for Commerce Hub.

2. To map some parameters we need to see test data in responses that looks like real. For now most of the parameters have values "string", so it is not always clear which data can be stored in which parameter. We expect that demo data that looks like real will be available after creating a sandbox for BankingHub, AllData Aggregation and Issuer Solutions. 

Thank you.

Regards, 
Alex

**Comment by sfiserv** [comment]
@bobburghardt  can you please help out @AlexanderNikiforovLineate for his queries.

**Comment by AlexanderNikiforovLineate** [comment]
@sfiserv @bobburghardt may I expect any help regarding my question?

**Comment by bobburghardt** [comment]
@AlexanderNikiforovLineate  - over the next few weeks we will update the portal with the ability to create a workspace, and obtain API keys and credentials for our developer free plan.  The portal is evolving, and over time we will expand it's capabilities.  The DNA environment will not be included in the upcoming release.

You mentioned you are working for a particular DNA client.  At this point your best approach is to work with your DNA client and have them engage with their Client Partner.  That Client Partner can work out the agreement with the client and your company to obtain access to the appropriate client-specific environment.
