### ISSUE TITLE
Get Card List endpoint

### ISSUE THREAD

**Issue by AlexanderNikiforovLineate** [Fiserv/Support#311]
Hello.

I need to fetch cards by account id and consider to use [Get Card List](https://developer.fiserv.com/product/BankingHub/api/?type=post&path=/cards/secured/list&branch=main&version=11.0.0) endpoint.
Please help me to understand two things about this endpoint.

1. Do I understand that right that I can set AcctId and AccType in request body and ignore other parameters -  CardKeys.CardId, PartyKeys.PartyId and Name? So, can I use this endpoint to search cards only by accountId?

2. I noticed that Get Card List is available only for Signature Core.
![image](https://user-images.githubusercontent.com/124882232/218772312-93b4f030-2839-441d-887c-44163f753281.png)

What does it mean? Do I need to ask my client which core they use? Does it mean that the same endpoint is not available for Premier Core? 
Maybe I can fetch the same card information using another endpoint available in Premier Core?

Thank you.

**Comment by sfiserv** [comment]
@bobburghardt  can you please help out @AlexanderNikiforovLineate for his queries.

**Comment by AlexanderNikiforovLineate** [comment]
@sfiserv @bobburghardt may I expect any help regarding my question?

**Comment by bobburghardt** [comment]
@AlexanderNikiforovLineate  - You can send the AcctId and AcctType across to receive a list of cards tied to that account.  Other search criteria are by PartyId, which will provide a list of cards assigned to that Party.  You don't need to send both in the same request.

With respect to the core availability - yes, at this time we have the Signature core information published.  Over time we will publish the schemas for the other cores.  You will need to know which core your client uses to obtain the proper schema.  The endpoint will remain the same, but the schema may vary slightly.  For example, Signature may send you 40 fields and DNA may send you 45.

**Comment by AlexanderNikiforovLineate** [comment]
@bobburghardt Thank you for your answer. We know that our client uses DNA core. You mentioned that DNA schema is not published in the developer studio now. Is it possible to get any documentation for the DNA core, maybe in the form of a JSON file? Thank you.

Regards, 
Alex

**Comment by bobburghardt** [comment]
Yes, the Fiserv Client Partner will be able to get the documentation via the client.

**Comment by AlexanderNikiforovLineate** [comment]
@bobburghardt we have access to Fiserv's Client360 portal but didn't manage to find DNA documentation there. Is there any chance that we can find DNA API documentation on Client360 portal? Thank you

**Comment by bobburghardt** [comment]
@AlexanderNikiforovLineate  - my understanding is that the Client Partner will be able to secure the APIs, or point you to the correct individual who can provide that information.

**Comment by AlexanderNikiforovLineate** [comment]
@bobburghardt Thank you, your answers give a lot of clarity. We requested documentation from a Client Partner. 

For now, we are trying to find DNA documentation on resources we have access. 
The search on the Client360 knowledge base with DNA filtered selected gave us results with Corillian Online API documentation, but we are not sure that this documentation is related to DNA.

I would be very grateful if you help me to understand if Corillian Online and DNA are related or if they are completely different products. 
Thank you.

**Comment by bobburghardt** [comment]
@AlexanderNikiforovLineate  - Corillian Online is a different product.
