### ISSUE TITLE
Which EFX Status Code indicates that transfer was deleted successfully?

### ISSUE THREAD

**Issue by AlexanderNikiforovLineate** [Fiserv/Support#313]
Hello.

May you clarify which EFX Status Code indicates that Transfer was successfully deleted when [Delete Transfer](https://developer.fiserv.com/product/BankingHub/api/?type=put&path=/transfers/secured&branch=main&version=11.0.0) endpoint was called?

[Response Codes](https://developer.fiserv.com/product/BankingHub/docs/?path=docs/response-codes.md) page describes 3 EFX code that matches with 200 OK HTTP code:

- 1080 Warning - Unchanged
- 1120 Info - No records match the selection criteria
- 1140 Warning - details not available.

It is not clear which of these codes means that the transfer was deleted.

Status code "0 Info - Success" matches with 201 Created HTTP code which doesn't look like a successful deletion operation result. 

Please clarify which status code means the success of deletion without any errors and warnings.

Thank you

**Comment by sfiserv** [comment]
@bobburghardt  can you please help out @AlexanderNikiforovLineate for his queries.

**Comment by AlexanderNikiforovLineate** [comment]
@sfiserv @bobburghardt may I expect any help regarding my question?

**Comment by bobburghardt** [comment]
@AlexanderNikiforovLineate - you will receive a HTTP 200, with a EFX status code of 0.
