### ISSUE TITLE
Resolution on sharing custom swagger with clients for UAT testing

### ISSUE THREAD

**Issue by shubhamKanse99** [Fiserv/Support#316]
**Region** (optional)
EMEA

**Is your feature request related to a problem? Please describe.**

Yes, We need to share future release swagger or custom swagger for clients who are testing in UAT, as new updates to the existing APIs or new APIs introduced will not be available in the production portal of devStudio. 
and since we work on multiple releases simultaneously, we have to keep separate swagger's. as copybooks differ with each release.

Please help us in resolving this issue, as this is already impacting existing clients. 

**Describe the solution you'd like**

In the old global portal, we had an API "Upload_Swagger" with which we would upload swagger with a unique URL id,
for ex - _docs.firstdata.com/global/api/Sentry, docs.firstdata.com/global/api/BNPL_  
Here Sentry and BNPL being the URL id for those particular projects/clients swagger. and we would just share these links with clients to refer. 

Considering the existing functionality with devStudio, 
Dev-region refreshes its API explorer every 1 hour. 
So can we create a separate set of credentials for clients only with limited access to view the API explorer in dev-region of devStudio?
Then we can upload custom swagger as a version here- 
![image](https://user-images.githubusercontent.com/117971606/219569125-41e8ee0a-ee4d-4037-ba47-3f652fc19d81.png)
and we will refer this link to them while they are in UAT testing? 

Only purpose of suggesting dev-region is that its fast compared to other regions. 

Please suggest if there is any other way we can share the custom swagger for clients even faster. 

**Describe alternatives you've considered**
n/a

**Additional context**

**Comment by shubhamKanse99** [comment]
Hi Team, 
is there any update on this? We need to provide a resolution for this asap. 
Thanks!

**Comment by acho-fiserv** [comment]
we don't officially support this today.

you can setup a preview mode with mulitple API versions.  but it will all be public.

https://fiserv.gitbook.io/tenant-docs/product-versions

**Comment by shubhamKanse99** [comment]
Hi Alvin, 

Even if we add all of the required swagger in preview mode, we won't be able to share that immediately right? 
We have to follow production deployment cycle for DevStudio. 

We are looking for a solution with which we can share the swagger document for clients who are testing in UAT for future releases. And also, there are regular changes to the swagger for different projects. so need to re-deploy the swagger again and again and share the latest version to them What should we do in such case?

**Comment by shubhamKanse99** [comment]
Hi Alvin,

can you please advice here. Thanks!

**Comment by shubhamKanse99** [comment]
Okay Alvin, I will try this. 

We follow the release calendar, But when it comes to UAT and SIT. 
We have to update as in when required by the client or tcoe team. 

Thank you!
