### ISSUE TITLE
Promote Connected Commerce into Staging & Production

### ISSUE THREAD

**Issue by f7wau03** [Fiserv/Support#317]
Request to promote the dev studio changes into QA, Staging & Production

QA deployment: 2/24/23
Stage Deployment: 3/9/23
Production: 3/16/23

We will be ready with our release branches

Kindly reach to us if any clarifications

Thanks

**Comment by sfiserv** [comment]
@f7wau03 We are in middle of our current sprint ( second half of sprint 4) the ticket being created today will be picked for development in the next sprint. We will be following our deployment schedule to fulfil this requirement.

**Comment by f7wau03** [comment]
Thank you for the update. Can you please confirm the dates for the upcoming sprint?

**Comment by sfiserv** [comment]
https://firstdatateam.atlassian.net/browse/PORT-5915
tracking ticket
