### ISSUE TITLE
Promote Digital Disbursement into Staging & Production

### ISSUE THREAD

**Issue by f7wau03** [Fiserv/Support#318]
Requesting to promote the Digital Disbursement into Staging & Production 

timeline

****

QA deployment: 2/24/23
Stage Deployment: 3/9/23
Production: 3/16/23

Kindly reach to us for any information

**Comment by sfiserv** [comment]
@f7wau03 We are in middle of our current sprint ( second half of sprint 4) the ticket being created today will be picked for development in the next sprint. We will be following our deployment schedule to fulfil this requirement.

**Comment by f7wau03** [comment]
Thank you for the update. is the dates going to be same or different?

**Comment by sfiserv** [comment]
https://firstdatateam.atlassian.net/browse/PORT-5916 
tracking ticket
