### ISSUE TITLE
LATAM Landing Page

### ISSUE THREAD

**Issue by CinthyaRivera** [Fiserv/Support#319]
**Region** (optional)
LATAM

**Is your feature request related to a problem? Please describe.**
No, It's related to a new feature for LATAM

**Describe the solution you'd like**
Create a landing page for LATAM solutions such as: Brazil, API's , FirstVision, Merchant Acquiring, Signature and Silvercore

**Describe alternatives you've considered**
N/A

**Additional context**
Similar to Carat Landing page
https://developer.fiserv.com/carat

**Comment by CinthyaRivera** [comment]
This landing page adds a lot of value for the UX in LATAM tenants and it's a priority to us have this feature.
Please let me know if there's any new.

**Comment by sfiserv** [comment]
@CinthyaRivera I can bring this up in the our Q2 roadmap planning for. discussion

**Comment by CinthyaRivera** [comment]
@sfiserv Let me know if you have any update

**Comment by CinthyaRivera** [comment]
@sfiserv this issue has been auto close, but please keep in mind the value that it's going to bring to LATAM to re-open and keep planned as discussed before
