### ISSUE TITLE
Parties segments support (based on demographics or any other criteria set by Bank) (DNA)

### ISSUE THREAD

**Issue by AlexanderNikiforovLineate** [Fiserv/Support#320]
Hi.
I'm looking for a party (user) property that describes a segment identifier (or group / category id) of a party.
This identifier needs to be in a numeric format.
Do FiServ Banking Hub (DNA core) supports setting any numeric segment/group/category id to a Party?

Thank you.

Regards, 
Alex

**Comment by bobburghardt** [comment]
@AlexanderNikiforovLineate - from what I can see there is no such field available.  As an aside, if that field is available, it typically is alphanumeric.
