### ISSUE TITLE
Search list doesn't redirect correctly

### ISSUE THREAD

**Issue by CinthyaRivera** [Fiserv/Support#321]
# Search list doesn't redirect correctly in FirstVision - LATAM

**Region** (if applicable)
LATAM

**Page**
[Search](https://developer.fiserv.com/search)

**Describe the bug**

**To Reproduce**
1. Go to 'Search' page
2. Search an API in a version that is not the default 
3. Select the API needed
4. It redirects to the first API in the default version

**Expected behavior**
Redirect to the API needed

**Screenshots**
**Screenshot 1. Selecting the correct result**
![image](https://user-images.githubusercontent.com/111396588/220744924-fb6922b0-d938-43d2-8db4-50b833c623c6.png)
**Screenshot 2. Showing the first API in the last version**
![image](https://user-images.githubusercontent.com/111396588/220745236-29360e83-a113-458c-b76c-7c82a461bedc.png)
**Screenshot 3. Showing the expected result**
![image](https://user-images.githubusercontent.com/111396588/220745816-7673c78d-7813-49f8-ad9b-981805e84bc7.png)

**Desktop (please complete the following information):**

**Tablet (please complete the following information):**
 - Device: [e.g. iPad]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by CinthyaRivera** [comment]
@Yelena11 Let me know if you have any update

**Comment by CinthyaRivera** [comment]
@sfiserv Do you have an estimate to release this ticket?

**Comment by CinthyaRivera** [comment]
@sfiserv Do you have an estimate to release this ticket?

**Comment by sfiserv** [comment]
@CinthyaRivera we have refined the search where are pulling the results per the version number and the version number is displayed in the results.
 Would this be helpful.
 
![image](https://github.com/Fiserv/Support/assets/87097017/83afb8c1-44be-49b6-a8e4-b21f29c19a79)

**Comment by CinthyaRivera** [comment]
Great @sfiserv . Thanks for the support :D
