### ISSUE TITLE
Download Postman Collection

### ISSUE THREAD

**Issue by CinthyaRivera** [Fiserv/Support#323]
# Reporting new issue for Download Postman Collection FirstVision LATAM

**Region** (if applicable)
LATAM

**Page**
All tenant

**Describe the bug**
When try to download postman collection, shows error 

**To Reproduce**
1. Go to any endpoint, for example: https://developer.fiserv.com/product/FirstVisionLATAM/api/?type=post&path=/customer/accountNumber&branch=main&version=1.2.0
2. Click on Download Postman Collection
3. See error

**Expected behavior**
Download Postman Collection

**Screenshots**
![image](https://user-images.githubusercontent.com/111396588/221243003-7407e526-0231-4798-a2fa-654963f5c130.png)

**Desktop (please complete the following information):**

**Tablet (please complete the following information):**
 - Device: [e.g. iPad]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sfiserv** [comment]
https://firstdatateam.atlassian.net/browse/PORT-5970

**Comment by CinthyaRivera** [comment]
@sfiserv Do you have an estimate to release this ticket?

**Comment by CinthyaRivera** [comment]
@sfiserv Hello, I just validated and still getting same issue from prod env.

![image](https://github.com/Fiserv/Support/assets/111396588/258b4d47-d712-4852-a930-b41909357293)

**Comment by CinthyaRivera** [comment]
Hello team, any update?

**Comment by sfiserv** [comment]
The issue has been foxed and deployed to production.

**Comment by sfiserv** [comment]
The issue has been foxed and deployed to production.

**Comment by CinthyaRivera** [comment]
@sfiserv Thanks for your support
