### ISSUE TITLE
API to get BIN data using 8 first digits

### ISSUE THREAD

**Issue by yurimarx** [Fiserv/Support#326]
**Region**: Brazil

**Solution you'd like**
API to get BIN data using 8 first digits, like https://www.bincodes.com/bin-checker/

**Comment by sfiserv** [comment]
@yurimarx can you please elaborate what is the issue you need help with.

**Comment by CinthyaRivera** [comment]
@sfiserv Hello, what it's required from my side?

**Comment by sfiserv** [comment]
@CinthyaRivera I have tagged you since this query is regarding LATAM products. I have tagged Brazil api team too. 
Seems @yurimarx needs help using the API for the Brazil product which you or @ServicosAPIsBrazil can help with.

**Comment by yurimarx** [comment]
Business need in detail:
1. I need to consume an API where I send to the API the 6 or 8 first number (BIN number) of a card and the API returns to me the name of the issuer of the card.
2. Example (I sent the first 6 numbers of my credit card): 
![image](https://user-images.githubusercontent.com/12038326/222145762-508fb4e9-0dc5-498d-8728-d94188e84ac9.png)

**Comment by yurimarx** [comment]
The available service did not have all bin list, but is functional
