### ISSUE TITLE
Change tenant name to SilverCore and enable product in QA env.

### ISSUE THREAD

**Issue by CinthyaRivera** [Fiserv/Support#329]
**Region** (optional)
LAS

**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
This tenant only applies to LAS not LATAM, so it's required to change the tenant name to SilverCore

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by sfiserv** [comment]
Change name from  silvercore - latam to silvercore.

Tracking this issue in https://firstdatateam.atlassian.net/browse/PORT-5992

**Comment by sfiserv** [comment]
@CinthyaRivera our team had some queries regarding this product. would be able to help us out to understand why the tenant needs to have a name change and and also you mentioned that the product is only used in LAS region.

**Comment by sfiserv** [comment]
@CinthyaRivera Our team worked on enabling your product Silver core on QA env. You can now use DevStudio QA env to test your changes.  (https://qa-developer.fiserv.com/product/SilverCore) 

Please verify and close this request.

**Comment by CinthyaRivera** [comment]
@sfiserv Thanks for your support
