### ISSUE TITLE
APIs not available in API explorer

### ISSUE THREAD

**Issue by shubhamKanse99** [Fiserv/Support#331]
# Reporting new issue for [NAME] (Tenant/Product)
firstvision-EMEA

**Region** (if applicable)
EMEA

**Page**
Home page, API explorer

**Describe the bug**
API explorer unavailable after latest swagger update

**To Reproduce**
1. Go to 'firstvision-EMEA'
2. See error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/117971606/223739353-ebd2bb8a-32cc-4fe9-a0b1-f62195e1bd36.png)

**Desktop (please complete the following information):**

**Tablet (please complete the following information):**
 - Device: [e.g. iPad]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by shubhamKanse99** [comment]
Hi Team, 
I have recently updated the swagger document and facing this error. 
Please help in fixing it. 
Thanks!

**Comment by sfiserv** [comment]
<img width="740" alt="image" src="https://user-images.githubusercontent.com/87097017/223879459-d215d26e-7365-420a-a1ff-d48d901261da.png">
Please verify the issue is resolved now in Production. 
Please Close the issue once verified.

**Comment by shubhamKanse99** [comment]
Thank you, APIs are visible now.
