### ISSUE TITLE
Images not showing in the portal

### ISSUE THREAD

**Issue by CinthyaRivera** [Fiserv/Support#332]
# Reporting new issue for images FirstVision - LATAM

**Region** (if applicable)
LATAM

**Page**
FirstVision - LATAM

**Describe the bug**
Images not showing in the portal (all environments have the same issue)

**To Reproduce**
1. Go to 'Getting Started'
2. See error

**Expected behavior**
Visualize images

**Screenshots**
![image](https://user-images.githubusercontent.com/111396588/223769042-effb5960-cce6-4bf0-8345-d84fb8868256.png)

**Desktop (please complete the following information):**

**Tablet (please complete the following information):**
 - Device: [e.g. iPad]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sfiserv** [comment]
@CinthyaRivera since your issue is resolved I am closing this ticket.
