### ISSUE TITLE
Bad Request Response

### ISSUE THREAD

**Issue by hrnoguz27** [Fiserv/Support#334]
# Reporting new issue for Fiserv - Commerce Hub

**Region** (if applicable)
Turkey

**Page**
[Path of the page where the problem exists.
](https://developer.fiserv.com/product/CommerceHub/api/?type=post&path=/payments/v1/charges&branch=main&version=1.4.0)
**Describe the bug**
When I try to send post request by using postman, I am always getting Bad request error. I need to setup commerce hub for .net environment. 
Usage: 
HTTP METHOD: POST
URL:  https://cert.api.fiservapps.com/ch/payments/v1/charges
Body: 
{
    "amount": {
        "total": "12.04",
        "currency": "USD"
    },
    "source": {
        "sourceType": "PaymentCard",
        "card": {
            "cardData": "4005550000000019",
            "securityCode": "123",
            "expirationMonth": "02",
            "expirationYear": "2035"
        }
    },
    "transactionDetails": {
        "captureFlag": true
    },
    "transactionInteraction": {
        "origin": "ECOM",
        "eciIndicator": "CHANNEL_ENCRYPTED",
        "posConditionCode": "CARD_NOT_PRESENT_ECOM"
    },
    "merchantDetails": {
         "terminalId": "{my-terminal-id}",
         "merchantId": "{my=merchant-id}"
    }
}

Headers: 
{
    "Content-Type": "application/json",
    "Client-Request-Id": "{Sample UUID}",
    "Api-Key": "{my-api-key}",
    "Timestamp": "{current-timestamp}"
}

**To Reproduce**
1. Create a post request in postman.
2. Use given endpoint url for request.
3. Use given body as raw-json and replace terminal and merchant id with yours.
4. Use given headers and replace api-key with yours.
5. Use auto generated UUID for client-request-id
6. Use current timestamp such as 1678017104 for current-timestamp
7. Send Request
9. See error says Bad Request

**Expected behavior**
Need to get success response like below which is example response from fiserv developer studio.
{
  "statusCode": 201,
  "responseCode": "Success",
  "responseHeaders": {
    "Connection": "keep-alive",
    "Content-Type": "application/json",
    "Date": "Thu, 09 Mar 2023 17:45:12 GMT",
    "Keep-Alive": "timeout=5",
    "X-Powered-By": "Express"
  },
  "responseBody": {
    "responseBody": {
      "gatewayResponse": {
        "transactionOrigin": "ECOM",
        "transactionProcessingDetails": {
          "apiTraceId": "362866ac81864d7c9d1ff8b5aa6e98db",
          "clientRequestId": "4345791",
          "orderId": "RKOrdID-525133851837",
          "transactionId": "84356531338",
          "transactionTimestamp": "2021-06-20T23:42:48Z"
        },
        "transactionState": "AUTHORIZED",
        "transactionType": "CHARGE"
      },
      "paymentReceipt": {
        "approvedAmount": {
          "currency": "USD",
          "total": 12.04
        },
        "merchantAddress": "123 Peach Ave",
        "merchantCity": "Atlanta",
        "merchantCountry": "US",
        "merchantName": "Merchant Name",
        "merchantPostalCode": "12345",
        "merchantStateOrProvince": "GA",
        "merchantURL": "https://www.somedomain.com",
        "processorResponseDetails": {
          "approvalCode": "OK5882",
          "approvalStatus": "APPROVED",
          "bankAssociationDetails": {
            "associationResponseCode": "000",
            "transactionTimestamp": "2021-06-20T23:42:48Z"
          },
          "host": "NASHVILLE",
          "hostResponseCode": "00",
          "hostResponseMessage": "APPROVAL",
          "localTimestamp": "2021-06-20T23:42:48Z",
          "processor": "FISERV",
          "responseCode": "000",
          "responseMessage": "APPROVAL",
          "schemeTransactionId": "0225MCC625628"
        }
      },
      "source": {
        "card": {
          "bin": "40055500",
          "expirationMonth": "10",
          "expirationYear": "2030",
          "last4": "0019",
          "scheme": "VISA"
        },
        "sourceType": "PaymentCard"
      },
      "transactionDetails": {
        "captureFlag": true,
        "merchantInvoiceNumber": "123456789012"
      }
    },
    "responseHeaders": {
      "Content-type": "application/json"
    },
    "statusCode": 201
  }
}

**Screenshots**
![image](https://user-images.githubusercontent.com/34753013/224115236-b10fc8ab-2cc7-4811-8830-6815c9a03bb9.png)
![image](https://user-images.githubusercontent.com/34753013/224115427-b832ffb9-d5f2-45ff-b9cd-23696f76e2b7.png)
![image](https://user-images.githubusercontent.com/34753013/224115841-158e29b1-c7c5-4151-a8bc-a8b7b1186a8b.png)
![image](https://user-images.githubusercontent.com/34753013/224115946-639a9278-a888-46d1-9af2-e4c94b74fbfe.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser [chrome, postman]

**Additional context**
I also tried to do same endpoint call in c# console app and I got the same error. I even try to hash api-secret with HMACSHA256 but it did not work at all.

![c# error](https://user-images.githubusercontent.com/34753013/224116943-07cb3427-d0b1-45b8-b8ba-11c40467280d.PNG)
![c# error1](https://user-images.githubusercontent.com/34753013/224116949-d85fdd93-dc4d-4c0a-9de8-2f08ae42dcd6.PNG)

@sfiserv

**Comment by wwfiserv** [comment]
@hrnoguz27 Are you using the default MID/TID and API credentials or did you create a dedicated MID/TID and new API creds?

**Comment by hrnoguz27** [comment]
By default there was no API creds and I just created that one. For the
MID/TID created automatically when I was creating workspace in dev studio.

**Comment by hrnoguz27** [comment]
@wwfiserv Hey, any progress about the problem? Do you have any idea why I am getting the bad request all the time? I tried everything you said but still not working.
