### ISSUE TITLE
Import/Embed YAML in Markdown

### ISSUE THREAD

**Issue by wwfiserv** [Fiserv/Support#336]
**Is your feature request related to a problem? Please describe.**
Currently to document examples or the Schema from the YAML it requires a manual process.

**Describe the solution you'd like**
We previously had a ticket requesting the option to import/embed the YAML information in a Markdown file. This would mean as the YAML is updated documentation would render the updated info without manually having to update it.

**Additional context**
Object/Field Example: should be able to reference a single object to have it display formatted in the markdown file with the relevant information. 

Payload Request/Response Example: should be able to reference an endpoint definition to have it display the default example with a dropdown to change the example similar to API explorer.

**Comment by wwfiserv** [comment]
@TaniaS-fiserv any update

**Comment by wwfiserv** [comment]
I found something that supports YAML to markdown as long as it can be rendered, it's called Markdown YAML Preamble, which loads the YAML front matter render as a table.

Example format;

```
---
name: John Doe
age: 30
gender: Male
---
```

**Comment by sfiserv** [comment]
Assuming there was a work-around found. Hence closing this issue.

**Comment by wwfiserv** [comment]
reopening ticket was out on leave
