### ISSUE TITLE
Ability to download Postman collection from Developer Studio

### ISSUE THREAD

**Issue by fiservakshay** [Fiserv/Support#342]
**Region** 
API Explorer section and markdown file in Documentation section

**Is your feature request related to a problem? Please describe.**
Developers should able to download the JSON file of Postman collection from the Developer studio. 

**Describe the solution you'd like**
Developers should be able to download a JSON file of postman collection from Resources section of Dev Studio. This collection will help developers to view saved request for all APIs and test the same.
![image](https://user-images.githubusercontent.com/81968767/225367069-c7fb99db-d2aa-49e6-81fc-44e9948501c8.png)

cc:  @bobburghardt @TaniaSarkar89  @acho-fiserv

**Comment by fiservakshay** [comment]
Attached is the sample Postman Collection for reference

[Banking Hub - Premier - Trial Plan Postman Collection.postman_collection.zip](https://github.com/Fiserv/Support/files/10982157/Banking.Hub.-.Premier.-.Trial.Plan.Postman.Collection.postman_collection.zip)

**Comment by fiservakshay** [comment]
@rahravin

**Comment by rahravin** [comment]
** Please note that, we have a requirement to have a custom built postman collection we would like for developers who are signing up for the Banking Hub Free Keys to download and instantly can run them by replacing the key and secret in the variables section of the collection. Dev Studio collating and bundling samples and calling it a postman collection would not work. If you have questions please reach out. cc: @sfiserv @acho-fiserv

**Comment by sfiserv** [comment]
This issue has been fixed and deployed to Production.
