### ISSUE TITLE
Document explorer not showing more than 3 levels

### ISSUE THREAD

**Issue by CinthyaRivera** [Fiserv/Support#346]
# Reporting new issue for First Vision LATAM

**Region** (if applicable)
LATAM

**Page**
Document explorer

**Describe the bug**
When document explorer contain more than 3 levels, Portal doesn't show next levels and in products when are needed to add more than one product or region reduces the possibility to show the information as the solution requires.

**To Reproduce**
1. Add more than 3 levels to show in document explorer
2. Go to Documentation Explorer 
3. See error, Only first 3 levels are shown.

**Expected behavior**
That Portal supports more than 3 levels in documentation and

**Screenshots**
![image](https://user-images.githubusercontent.com/111396588/225451184-e2584606-6035-4638-820c-eb191704eea1.png)

**Desktop (please complete the following information):**

**Tablet (please complete the following information):**
 - Device: [e.g. iPad]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sfiserv** [comment]
We already have issue created for this and is prioritized to be worked on.
This is an enhancement not a bug.

**Comment by sfiserv** [comment]
@CinthyaRivera please verify the changes for the 3 tiers.

**Comment by CinthyaRivera** [comment]
In validation

**Comment by CinthyaRivera** [comment]
@sfiserv Validated and works correctly with 3 tiers

**Comment by sfiserv** [comment]
Closing this issue as the changes are validated and working as expected.
