### ISSUE TITLE
Page navigation not working 

### ISSUE THREAD

**Issue by CinthyaRivera** [Fiserv/Support#347]
# Reporting new issue for First Vision LATAM

**Region** (if applicable)
LATAM

**Page**
Documentation in Spanish

**Describe the bug**
This product requires solution to be show in other languages apart from English so languages were implemented as part of groups in document explorer as follow:
![image](https://user-images.githubusercontent.com/111396588/225451815-44ebf450-78b1-4468-8578-90d4cd2e1f8e.png)
 In Español section the navigation doesn't work 
![image](https://user-images.githubusercontent.com/111396588/225451983-a58a4345-744f-4b95-84d6-8aa96b8bb2aa.png)
As you can see in picture, even I select section 7 the page is still in section 1.

**To Reproduce**
1. Go to https://dev-developerstudio.fiserv.com/product/FirstVisionLATAM/docs/?path=docs/spanish/empezando.md&branch=develop&tab=documentation&collapse=collapsed#7-ejemplo-de-la-seccion-de-prueba
2. Click on the navigation, such as section 7
3. See error that the cursor is in same place

**Expected behavior**
Navigate to selected section

**Screenshots**
![image](https://user-images.githubusercontent.com/111396588/225451793-e7811a7d-102b-4eaa-bb92-46faba02d5a1.png)

**Desktop (please complete the following information):**

**Tablet (please complete the following information):**
 - Device: [e.g. iPad]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sfiserv** [comment]
@CinthyaRivera is this happening in any other environments. The screenshot shows you are testing in Dev env. As mentioned earlier you can start testing your changes in QA env. if the navigation issue is left nav, it is still work in progress. Hence we ask you to move to QA for testing and close this ticket.

**Comment by minh-pham1** [comment]
Hello! This issue is actually related to the issue found with #338 and I just left a comment on there.

**Comment by CinthyaRivera** [comment]
Thanks, checking comment

**Comment by sfiserv** [comment]
closing this ticket since this is smilar to #338 and we are tracking that issue in
https://firstdatateam.atlassian.net/browse/PORT-6076
