### ISSUE TITLE
Refresh API list when change version

### ISSUE THREAD

**Issue by CinthyaRivera** [Fiserv/Support#348]
# Reporting new issue for First Vision LATAM

**Region** (if applicable)
LATAM

**Page**
API explorer

**Describe the bug**
API explorer doesn't refresh API list when select another version

**To Reproduce**
1. Go to API explorer
2. Click on any API. This API will be in default version.
3. Click on version and select another version.
4. See error, the list doesn't update.

**Expected behavior**
Update the API list related with the version without click on refresh page

**Screenshots**
1. Select any API in default version
![image](https://user-images.githubusercontent.com/111396588/225706544-0cdcfc99-bc9a-4c72-9e2a-69889037ad42.png)
2. Select another version
![image](https://user-images.githubusercontent.com/111396588/225706758-c41dc43d-631d-447e-97be-e7167d437a73.png)
3. Expected behaviour
![image](https://user-images.githubusercontent.com/111396588/225707019-1c25221a-5bc5-4c80-84c2-a990c7d04d05.png)

**Desktop (please complete the following information):**

**Tablet (please complete the following information):**
 - Device: [e.g. iPad]

**Smartphone (please complete the following information):**

**Additional context**
This is issue has been reported by customers and difficult the day to day work for them. Adds a lot of value for customer have this working correctly.

**Comment by CinthyaRivera** [comment]
@sfiserv  Do you have an estimate to release this ticket?

**Comment by CinthyaRivera** [comment]
@sfiserv Do you have any update for this issue?

**Comment by sfiserv** [comment]
@CinthyaRivera can you please verify if this issue still exists in the new left nav ( currently on the QA env)

**Comment by CinthyaRivera** [comment]
Hello, so far QA it's working great. Thanks @sfiserv
