### ISSUE TITLE
Promote Card Developer tenant to QA environment

### ISSUE THREAD

**Issue by ebyrd-fiserv** [Fiserv/Support#349]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Request that the Card Developer tenant be promoted to QA.

**Describe alternatives you've considered**
N/A

**Additional context**
As Dev Studio team has announced intention for tenants to use the QA environment to test content, we cannot stay in the dev environment.

**Comment by sfiserv** [comment]
https://firstdatateam.atlassian.net/browse/PORT-6078

Tracking ticket for this request.

**Comment by sfiserv** [comment]
This request is already covered as part of moving all the active tenants from dev to QA.
This will be ready for verification after sprint 6 deployment.

**Comment by sfiserv** [comment]
Card Developer tenant is now in QA environment as requested in this issue.

If your team needs the product to move to higher env you will have to raise a request.
