### ISSUE TITLE
Section not visible in page

### ISSUE THREAD

**Issue by CinthyaRivera** [Fiserv/Support#350]
# Reporting new issue for FirstVision LATAM

**Region** (if applicable)
LATAM

**Page**
https://qa-developerstudio.fiserv.com/product/FirstVisionLATAM/docs/?path=docs/portugu%C3%AAs/refer%C3%AAncia-api/5-notifica%C3%A7%C3%B5es.md&branch=develop

**Describe the bug**
Section "Veja também" it's not visible in QA portal.
Markdown contain section.
https://github.com/Fiserv/firstvision-latam/blob/develop/docs/portugu%C3%AAs/refer%C3%AAncia-api/5-notifica%C3%A7%C3%B5es.md

**To Reproduce**
1. Go to ['...'](https://qa-developerstudio.fiserv.com/product/FirstVisionLATAM/docs/?path=docs/portugu%C3%AAs/refer%C3%AAncia-api/5-notifica%C3%A7%C3%B5es.md&branch=develop)
2. Scroll down to 'Veja também'
4. See error. Section it's not visible.

**Expected behavior**
Visualize section.

**Screenshots**

![image](https://user-images.githubusercontent.com/111396588/225961858-4cffca77-81e7-47e3-899e-9dd0ab4cb45b.png)
![image](https://user-images.githubusercontent.com/111396588/225961901-58d15346-5a3f-47d3-b38c-35f717bb76a4.png)

**Desktop (please complete the following information):**

**Tablet (please complete the following information):**
 - Device: [e.g. iPad]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by CinthyaRivera** [comment]
Thanks, @minh-pham1. I changed it but it looks like it doesn't update.
https://github.com/Fiserv/firstvision-latam/blob/develop/docs/portugu%C3%AAs/refer%C3%AAncia-api/5-notifica%C3%A7%C3%B5es.md

![image](https://user-images.githubusercontent.com/111396588/226047197-b3169027-d4bc-49d5-9910-cee5d0e36ab6.png)

Can you help me to verify if there's an issue with publications.

**Comment by minh-pham1** [comment]
Our environments automatically run an indexing job which fetches all docs and apis from Github once every ~2 hours. I do see the change you made on QA so you might have caught that environment at a good time. If the other environments where this document has this issue still doesn't update to reflect the new changes after 2 hours, please let me know.

**Comment by CinthyaRivera** [comment]
Hello @minh-pham1 Change visible in QA but still not in Dev.

**Comment by minh-pham1** [comment]
Hi @CinthyaRivera ! Just wanted to check in to see whether this is still an issue. I believe I do see it on dev now but I might be missing it elsewhere. Please let me know if you have noticed this issue since then, otherwise we can close this issue and reopen it as needed in the future.

**Comment by CinthyaRivera** [comment]
@sfiserv fixed :D
