### ISSUE TITLE
Text rendering issue in the core dropdown

### ISSUE THREAD

**Issue by fiservakshay** [Fiserv/Support#351]
# Reporting new issue for Banking Hub tenant

Longer core names are exceeding the boundary of core dropdown box, and looks asymmetric.  
Please refer the screenshot below.

![image](https://user-images.githubusercontent.com/81968767/226283207-23f4ba21-ec14-4161-8aae-8028b5c1bd56.png)

**Expected behaviour:**
Width of core dropdown box should fit the name of core if it exceeds the default width. 

cc: @rahravin @acho-fiserv @sfiserv

**Comment by minh-pham1** [comment]
Hello @fiservakshay! This issue has been fixed on dev and will be moving up to QA for testing this week! Thank you for your patience.

**Comment by tsegurajimen** [comment]
Core dropdown looks good now, then closing this ticket.
![image](https://github.com/Fiserv/Support/assets/81706748/f1bb1e09-076b-419a-9b62-779c41a49926)
