### ISSUE TITLE
TENANT-NAME

### ISSUE THREAD

**Issue by fs-rich-tilt** [Fiserv/Support#353]
### Name of your product / tenant

TapToPay

### Type of Tenant

- [X] Full service
- [ ] Doc only
- [ ] Link out

### Team Members

richtilt, tomeck

### Bug Reporting

richtilt, tomeck

### Feedback Reporting

richtilt, tomeck

### Enhancement Reporting

richtilt, tomeck

### Internal tenant

No

### Product of Carat

No

### Merchants solution area

Yes

### Customer Segments for Merchants

- [X] SMB
- [ ] Enterprise

### Financial Institutions solution area

Yes

### Customer Segments for Financial Instituitions

- [X] Bank
- [ ] Credit Union
- [ ] Large Financial Institution

### Fintech solution area

Yes

### Region of Operation

- [X] North America
- [ ] EMEA
- [ ] LATAM
- [ ] APAC

### RESTful

Yes

### SDK

Yes

### Industry

Retail

### Runbox

Yes

### Mock Sandbox

Yes

### Live Server

Yes

**Comment by fs-rich-tilt** [comment]
Fiserv TapToPay

**Comment by sfiserv** [comment]
Tracking this request in jira https://firstdatateam.atlassian.net/browse/PORT-6077

**Comment by sfiserv** [comment]
Jira is marked as won't fix and hence closing this issue.
