### ISSUE TITLE
Acceptance Solution (APAC) -move to Stage and Production.

### ISSUE THREAD

**Issue by vijju007** [Fiserv/Support#354]
**Region** (optional)
India

**Is your feature request related to a problem? Please describe.**
We want to move our product to staging environment.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by vijju007** [comment]
Product name: devstudio 
 [Acceptance Solutions - APAC](https://dev-developerstudio.fiserv.com/product/AcceptanceSolutionsAPAC)
![image](https://user-images.githubusercontent.com/106581840/226430845-ba874f37-8b34-4783-90bb-d7fca03d1fe8.png)

**Comment by sfiserv** [comment]
Tracking this issue in : https://firstdatateam.atlassian.net/browse/PORT-6085

**Comment by sfiserv** [comment]
The product is now enabled in Production env. Please let us know if you have any issue for production.
Create a new github issue for any bugs found.
For now the request has been completed and marking this ticket as done and closing it.
