### ISSUE TITLE
DevStudio - Dev env - Error API Explorer option, bad screen overlay

### ISSUE THREAD

**Issue by eliascanaza** [Fiserv/Support#356]
# API Explorer option, bad screen overlay in Issuer Solutions

**Region** (if applicable)
EMEA and NA

**Page**
https://dev-developerstudio.fiserv.com/product/IssuerSolutions

**Describe the bug**
When you clicked in **API Explorer** option in left side, 

**To Reproduce**
1. Go to https://dev-developerstudio.fiserv.com/product/IssuerSolutions
2. Click on API Explorer option
3. Scroll down to last api

**Expected behavior**
We are expecting the **API Explorer** page will have same background for the long list of APIs.

**Screenshots**
![image](https://user-images.githubusercontent.com/1819754/227565418-034d3f2d-cb2c-4b48-abfb-d2d103999dfa.png)

**Desktop (please complete the following information):**
 - OS: All
 - Browser chrome
 - Version 111.0.5563.110

**Comment by sfiserv** [comment]
@eliascanaza  as mentioned in the playback tenants need to test their application in QA and upper env. The features in the dev env are still under development phase.
Hence closing this issue.
