### ISSUE TITLE
Sandbox is displaying ERROR for some APIs in QA, but Dev env are working

### ISSUE THREAD

**Issue by eliascanaza** [Fiserv/Support#357]
# Issuer Solutions

**Region** (if applicable)
EMEA and NA

**Page**
**_/creDispute/v1/processDisputeData_**
Dev: https://dev-developerstudio.fiserv.com/product/IssuerSolutions/api/?type=post&path=/creDispute/v1/processDisputeData&branch=develop&version=1.0.0
QA: https://qa-developerstudio.fiserv.com/product/IssuerSolutions/api/?type=post&path=/creDispute/v1/processDisputeData&branch=develop&version=1.0.0

**_/caseManagement/v1/clientInfoGetList_**
Dev: https://dev-developerstudio.fiserv.com/product/IssuerSolutions/api/?type=post&path=/caseManagement/v1/clientInfoGetList&branch=develop&version=1.0.0
QA: https://qa-developerstudio.fiserv.com/product/IssuerSolutions/api/?type=post&path=/caseManagement/v1/clientInfoGetList&branch=develop&version=1.0.0

**Describe the bug**
The sandbox is working for those APIs in DEV environment but not in QA.

**To Reproduce**
1. Go to the links above in QA environment
2. Click in **Run Request** button
4. See error in response

**Expected behavior**
Sandbox has to work for those APIs in DEV, QA, Stage and Prod environment.

**Screenshots**
DEV:
<img width="1210" alt="image" src="https://user-images.githubusercontent.com/1819754/227572155-78420c49-582c-4d00-8aa2-35f8d85ba630.png">

QA:
<img width="1368" alt="image" src="https://user-images.githubusercontent.com/1819754/227572041-aed03b30-47e8-4752-a455-531e87c9eede.png">

**Additional context**
Both APIs have **application/json** as type of response and **/creDispute/v1/processDisputeData** we already have that change in Stage and Prod with same error.

**Comment by sfiserv** [comment]
@eliascanaza both the request are showing 200 response in QA env, 
please verify

<img width="1523" alt="image" src="https://user-images.githubusercontent.com/87097017/228326590-1b48eb76-7922-41c2-b9f5-4132147c66e7.png">
<img width="1661" alt="image" src="https://user-images.githubusercontent.com/87097017/228326659-d4fdc6ce-4e0d-406a-af06-213a5b616c16.png">

**Comment by eliascanaza** [comment]
@sfiserv now both are working in Dev-QA environments, I am closing this ticket... thanks.
