### ISSUE TITLE
DevStudio in Dev env, Issue with APIs with same name

### ISSUE THREAD

**Issue by eliascanaza** [Fiserv/Support#358]
# Issuer Solutions

**Region** (if applicable)
EMEA and NA

**Page**
https://dev-developerstudio.fiserv.com/product/IssuerSolutions/api/?type=post&path=/memos/v1/cisAdd&branch=develop&version=1.0.0

**Describe the bug**
DevStudio with new design is not displaying API with same name in DEV environment, in old design those are appearing in QA environment.

/cisMemos/v1/cisAdd
/memos/v1/cisAdd
/cisMemos/v1/cisDelete
/memos/v1/cisDelete
/memos/v1/cisLookup
/cisMemos/v1/cisLookup
/memos/v1/cisUpdate
/cisMemos/v1/cisUpdate

**Github:**
https://github.com/Fiserv/issuer-solutions/blob/develop/reference/1.0.0/AccountServices/Memos.yaml
https://github.com/Fiserv/issuer-solutions/blob/develop/reference/1.0.0/CollectionsCaseManagement/CollectionsMemos.yaml

**To Reproduce**
1. Go to https://dev-developerstudio.fiserv.com/product/IssuerSolutions
2. Click on API Explorer option
3. Write in Search option any of above APIs
4. See error, you will see only 1 API

**Expected behavior**
In search option we have to see those 2 APIs with same name, has to appear all APIs mentioned before.

**Screenshots**
<img width="1362" alt="image" src="https://user-images.githubusercontent.com/1819754/227584271-9bb3213d-9d7b-499e-9636-3ecd9453a8e0.png">
<img width="1490" alt="image" src="https://user-images.githubusercontent.com/1819754/227585247-7c3c3075-a4f2-43a3-bdf3-18d70d1b50ec.png">

**Comment by sfiserv** [comment]
@eliascanaza the feature is not completely developed. and as mentioned in the playbacks we need all the tenants to test their changes on QA env only.
If you see this issue in QA env then please let us know. else I am closing this issue.
