### ISSUE TITLE
Enable Preview Branch in QA Environment

### ISSUE THREAD

**Issue by fiservakshay** [Fiserv/Support#359]
Preview branch is not available in QA environment. 

![image](https://user-images.githubusercontent.com/81968767/227942726-b74882b8-9c3c-42e7-9c13-c3d10ba8e209.png)

Please enable Preview branch is QA as we use this branch to test/validate APIs and Documentation. Preview branch in Dev environment 
 has the updated UI hence we are unable to test and validate the required changes. 

cc: @rahravin @bobburghardt  @sfiserv

**Comment by sfiserv** [comment]
tracking this issues in https://firstdatateam.atlassian.net/browse/PORT-6198

**Comment by TaniaS-fiserv** [comment]
Hi @fiservakshay the Preview branch for Banking Hub is now available in [QA environment](https://qa-developerstudio.fiserv.com/product/BankingHub?branch=preview). Please validate the changes.

<img width="1677" alt="image" src="https://user-images.githubusercontent.com/74629095/234999121-c7b15ac5-8c29-4966-af20-ca67f6f329d1.png">


Thanks!

Cc: @sfiserv

**Comment by fiservakshay** [comment]
Yes, able to see the Preview branch now. Thanks so much @TaniaS-fiserv :) .
