### ISSUE TITLE
New product-layout changes are missing

### ISSUE THREAD

**Issue by shubhamKanse99** [Fiserv/Support#363]
# Reporting new issue for [NAME] (Tenant/Product)

**Region** (if applicable)
EMEA

**Page**
firstvision-EMEA product layout page

**Describe the bug**
Missing correct description and product offerings added. 

**To Reproduce**
can be seen on product home page. 

**Expected behavior**
Should display correct description of product and display missing features

**Screenshots**
Incorrect description - 
![image](https://user-images.githubusercontent.com/117971606/228459123-c3f1273f-bc0c-41a0-b429-8c50f8c03d15.png)

Missing sections under product offereing's only 4 visible on home page.
![image](https://user-images.githubusercontent.com/117971606/228459457-aa483eb0-0df5-4579-903f-a00f041aa0f2.png)

**Additional context**
Hi Team, I have updated the product-layout.yaml file as per the new updates provided on https://fiserv.gitbook.io/tenant-docs/update-productpage-content, 
After update, 
1. Correct product description is missing 
2. Under product offerings section only 4 pages are visible.

**Comment by shubhamKanse99** [comment]
Hi @sfiserv , 
Yes, description is now visible after I changed the word from "product" to "production" in product-layout.yml file. 
But second issue is still present.

**Comment by sfiserv** [comment]
@shubhamKanse99 we are fixing the number of card to be displayed in this sprint.
The max cards to be displayed will be 3.
