### ISSUE TITLE
Bad Request error from Payment API Call https://cert.api.firstdata.com/gateway/v1/payments

### ISSUE THREAD

**Issue by suvarnaashoka** [Fiserv/Support#364]
Hi,

We are integrating Fiserv as PSP in our website for Gpay and ApplePay wallets
When we tried to integrate we are receiving the 400 error

Here is the request object,

let payload = {
                            "requestType": "WalletPreAuthTransaction",
                            "walletPaymentMethod": {
                                "walletType": "EncryptedGooglePayWalletPaymentMethod",
                                "encryptedGooglePay": {
                                    "data": {
                                        "encryptedMessage": encryptedSignedmessage.encryptedMessage,
                                        "ephemeralPublicKey": encryptedSignedmessage.ephemeralPublicKey,
                                        "tag": encryptedSignedmessage.tag
                                    },
                                    "signature": tokenobj.signature,
                                    "version": tokenobj.protocolVersion,
                                }
                            },
                            "transactionAmount": {
                                "total": "1",
                                "currency": "USD"
                            }
                    }
                      
                    
 var apiKey = 'string';
                        var clientRequestId = '1178045C-A683-4639-BAD0-0C43A0D62F32';
                        var timestamp = new Date().valueOf().toString();
                        var apiSceret = 'string';

                        let msg = apiKey + clientRequestId + timestamp + JSON.stringify(payload);

                        console.log("msg", msg);

                        const hmac = CryptoJS.algo.HMAC.create(CryptoJS.algo.SHA256, apiSceret);
                        console.log("hmac", hmac);

                        hmac.update(msg);
                        console.log("hmac2", hmac);

                        const messageSignature = window.btoa(hmac.finalize().toString());
                        console.log("messageSignature", messageSignature);

                        const options = {
                            method: 'POST',
                            headers: {
                                'Content-Type': 'application/json',
                                'Client-Request-Id': clientRequestId,
                                'Api-Key': apiKey,
                                'Timestamp': timestamp,
                                'Message-Signature': messageSignature,
                                'Region': 'US',
                            },
                            body: JSON.stringify(payload)
                        };

                        console.log(options);
                        fetch('https://cert.api.firstdata.com/gateway/v1/payments', options)
                            .then(response => response.json())
                            .then(response => console.log(response))
                            .catch(err => console.error(err));
                        console.log(options);
                        const result = {
                            "status": "SUCCESS"
                        };
                        session.completePayment(result);
                    })
                    

      Please let us know if we are missing any properties.
    
     Thanks,
     Suvarna

**Comment by wwfiserv** [comment]
We apologize for the inconvenience, we currently only support PaymentCard in our sandbox. We are only allowing ApplePay and other Wallet integration if you have an existing merchant relationship with Fiserv. Please have the merchant contact their account representative for more details on getting a dedicated testing MID for wallets.

**Comment by suvarnaashoka** [comment]
Based on your response, may we confirm that FirstData supports integration with GPay wallet?

**Comment by wwfiserv** [comment]
@suvarnaashoka yes Fiserv supports Google Pay with multiple gateways. Commerce Hub also supports Google Pay. One thing to note is Commerce Hub is for large volume and Enterprise clients, you may want to reach out to your merchant account representative to ensure Commerce Hub is the correct product offering from Fiserv.

**Comment by gandalf113** [comment]
@suvarnaashoka @wwfiserv Please tell me, where can I obtain the API keys? I'm trying to use this API as well, but I'm unable to authenticate.

**Comment by wwfiserv** [comment]
@gandalf113 in the future please create a separate ticket unless you are part of the team associated with this request. You can get the default Commerce Hub keys by registering for Dev Studio https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Getting-Started/Getting-Started-Dev-Portal.md

**Comment by gandalf113** [comment]
@wwfiserv I apologize for posting here and will delete this comment later. However, it's urgent that we get keys for IPGNA instead of Commerce Hub. I would greatly appreciate it if you could take a look at issue [367](https://github.com/Fiserv/Support/issues/367) and help us resolve this matter. Thank you in advance.
