### ISSUE TITLE
Activate version branches

### ISSUE THREAD

**Issue by CinthyaRivera** [Fiserv/Support#365]
**Region** (optional)
First Vision LATAM

**Is your feature request related to a problem? Please describe.**
I require to show Preview and Previous branches

**Describe the solution you'd like**
Activate Previous and Preview branches in DB

**Describe alternatives you've considered**
N/A

**Additional context**
I would like to have support for implementation because so far documentation it's not clear in how to proceed (implementation flow)

**I have two scenarios of how version works, Can you clarify which scenario applies, please?**
	
1. Version works for documentation and APIs (Documentation it's not clear if this works for API's and documentation or only APIs)
		
If this also works for documentation and I don't require to have "Previous" and "Preview" documentation, Do I have to maintain same documentation in preview, previous and develop branches? or Is it possible to only have my documentation in develop and APIs in preview, previous and develop branches? Is it necessary to add something in config files?
	
	
2. Version works only for APIs. Is it possible to only have my documentation in develop and APIs in preview, previous and develop branches? Is it necessary to add something in config files?

**Comment by CinthyaRivera** [comment]
@sfiserv Do you have an estimate to release this ticket?

**Comment by sfiserv** [comment]
@CinthyaRivera it will be worked on in this sprint and I will update once preview branch is enabled.
Our team was focused on production issue resolution.
thanks for your patience.

**Comment by sfiserv** [comment]
@CinthyaRivera it will be worked on in this sprint and I will update once preview branch is enabled.
Our team was focused on production issue resolution.
thanks for your patience.

**Comment by sfiserv** [comment]
https://firstdatateam.atlassian.net/browse/PORT-6287

**Comment by TaniaS-fiserv** [comment]
Hi @CinthyaRivera answered you questions below:

The overall structure of the "Preview" & "Previous" branches are quite similar to the "Active" branch. You can choose or not choose to have the API explorer for the "Preview" & "Previous" branches. But it's imperative that you have the documentation for them. 

However, please note that we are not supporting the concept of "Previous" branches anymore. You can maintain the "ACTIVE" and "PREVIEW" branches. If you choose to have decommissioned apis then you can add them as an older version. 

You can refer the CommerceHub product and how they maintain different API versions like below: 

![image](https://github.com/Fiserv/Support/assets/74629095/14b07e63-d34b-4186-9857-cae1f1aeccc1)

There is a separate "Preview" branch in GitHub which has an exactly similar structure like develop /stage /main GitHub branches. So once we enable the "Preview" branch for your product you would be able to see a separate Preview branch like below:
![image](https://github.com/Fiserv/Support/assets/74629095/d688fb8a-88e6-4821-aa5f-f88443d6a7b1)

You could also choose to have Dev Studio Mock service enabled or Live sandbox enabled for this "Preview" branch. You could also choose not to have any sandbox enabled at all. 

This brings me to the below questions, 

1. Do you need to have the same live server enabled for the "Preview" branch ? As of today, you have a live server enabled for the "Active" branch. If yes, then please let us know configurations for them in all environments. 
2. Also do you need the "Preview" branch in all environments : QA, Stage and Prod ?

Based on your confirmation, we would start working on this ticket.

Cc: @sfiserv

**Comment by TaniaS-fiserv** [comment]
Hi @CinthyaRivera  I'm still waiting for your responses to the questions I requested above.

Cc: @sfiserv

**Comment by CinthyaRivera** [comment]
Hello,
I understood that versioning works for documentation and API's but it's required to have documentation for preview and active.
My remaining question is: Do I required to change something in config files?

Related to your questions:
-No, we don't require activate sandbox for preview branch.
-Yes, we expect to activate Preview branch, for all environments.

Thanks @TaniaS-fiserv

**Comment by TaniaS-fiserv** [comment]
Hi @CinthyaRivera to answer your question, as I have mentioned in my earlier response 

> There is a separate "Preview" branch in GitHub which has an exactly similar structure like develop /stage /main GitHub branches.

So similar to the "develop" branch, the "preview" branch is a standalone branch with its own set of config files. You need to make updates to the ded.yaml/ tenant.config files if you want to make modifications to the Docs/ APIs in the "preview" branch.

Please check out your "preview" branch here: https://github.com/Fiserv/firstvision-latam/tree/preview

Also based on your responses on SandBox activation, I would require another clarification from you:
Should we enable the Dev Studio Mock server for "Preview" branch or would you like to keep the "Run Request" button disabled for "Preview" branch? 

Thanks!
