### ISSUE TITLE
Access code

### ISSUE THREAD

**Issue by wesleyc9931** [Fiserv/Support#366]
**Region** (optional)
United States

**Is your feature request related to a problem? Please describe.**
An access code is required when "access a merchant ID", have contacted PAYEEZY, and could not provide us with the access code. related MID: 529808650134588

**Describe the solution you'd like**
n/a

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by wwfiserv** [comment]
We are currently not migrating Enterprise Payeezy clients. Once we begin the migration the merchant will be able to access Merchant Configuration and Boarding to obtain an Access Code. Until then if you are wanting to integrate with Commerce Hub please use the shared MID and credentials or request a dedicated MID and credentials. However before beginning integration I would have the client contact their account representative to ensure that Payeezy is the go forward for them, as Commerce Hub is for high volume and large business Enterprise accounts, Small and Medium size businesses are being migrated to Fiserv's Clover solution.
