### ISSUE TITLE
ConnectPay

### ISSUE THREAD

**Issue by aanoopfiserv** [Fiserv/Support#370]
### Name of your product / tenant

ConnectPay

### Type of Tenant

- [X] Full service
- [X] Doc only
- [ ] Link out

### Team Members

aanoopfiserv

### Bug Reporting

aanoopfiserv

### Feedback Reporting

aanoopfiserv

### Enhancement Reporting

aanoopfiserv

### Internal tenant

No

### Product of Carat

Yes

### Merchants solution area

Yes

### Customer Segments for Merchants

- [ ] SMB
- [X] Enterprise

### Financial Institutions solution area

No

### Customer Segments for Financial Instituitions

- [ ] Bank
- [ ] Credit Union
- [ ] Large Financial Institution

### Fintech solution area

Yes

### Region of Operation

- [X] North America
- [ ] EMEA
- [ ] LATAM
- [ ] APAC

### RESTful

Yes

### SDK

Yes

### Runbox

Yes

### Mock Sandbox

Yes

### Live Server

No

**Comment by aanoopfiserv** [comment]
@acho-fiserv This is for ConnectPay application that we discussed yesterday

**Comment by sfiserv** [comment]
https://firstdatateam.atlassian.net/browse/PORT-6319
Tracking this issue in the above jira

**Comment by sfiserv** [comment]
@aanoopfiserv please verify that this github request has been fulfilled so that we can close this issue.

**Comment by aanoopfiserv** [comment]
@sfiserv APIs from the yaml file are not showing up on QA DevStudio even though yaml file is loading properly on the swagger editor. screenshot attached

Can you pls look into this?

<img width="1432" alt="Screen Shot 2023-05-24 at 10 08 16 AM" src="https://github.com/Fiserv/Support/assets/129788925/f5f46b20-eb70-40aa-afa9-8d9e962bb597">

**Comment by sfiserv** [comment]
<img width="888" alt="image" src="https://github.com/Fiserv/Support/assets/87097017/ac14734c-4316-43f9-bc24-f36eaab02612">
@aanoopfiserv  Please verify now. apis are displaying.

**Comment by aanoopfiserv** [comment]
Thanks. Looks good now. Feel free to close the issue.

Thanks,
Anoop

From: Supriya Nirmale ***@***.***>
Date: Wednesday, May 24, 2023 at 4:32 PM
To: Fiserv/Support ***@***.***>
Cc: Agarwal, Anoop (Berkeley Heights) ***@***.***>, Mention ***@***.***>
Subject: Re: [Fiserv/Support] ConnectPay (Issue #370)

  ⚠ EXTERNAL MESSAGE – Think Before You Click

***@***.***<https://urldefense.com/v3/__https:/github.com/aanoopfiserv__;!!P9vvK-4S!lVhCrGzYiIOCha5KJbF3l0RR6Ch7b2vxKpNkRyzdpfGMXHEGBLgtC-4O2cHDusKUJYpomJs9HBf1buQmUbk25TnbR2a6$> Please verify now. apis are displaying.
