### ISSUE TITLE
"Prologe.exe": List of Error Codes

### ISSUE THREAD

**Issue by LDawggieWAB** [Fiserv/Support#371]
Hi Fiserv (Prologue.exe) Support Team!

Our company is still using the executable version of "Prologue..exe" (v10.20.77.426) and are looking for a list of error codes that are generated by the process.

For example:
On an _assumed_ successful run, we might see an error code of **0x146EC10** or **0x153EC10** in the Windows Task Scheduler after running this command:
`"C:\Program Files (x86)\Fiserv\Prologue\prologue.exe" OpenWindow[30062,*********, YESTERDAY] Authentication [W] AppUserID[*****] DBProfile[*****] Domain [*****] AutoLogin[] OVERRIDE_WOE`

I tried to look on [https://docs.fiserv.com/](https://docs.fiserv.com/) and [https://developer.fiserv.com](https://developer.fiserv.com), however it seems that all of the current documentation provided is for the fancy new APIs and not the legacy "Prologue.exe".

Would you be able to direct me towards any documentation (hopefully including a list of error codes) available for this legacy executable application "prologue.exe"? 

Thank you!

**Comment by sfiserv** [comment]
@LDawggieWAB  this github support is meant for https://developer.fiserv.com only.  
Please reach out to the EMEA Developer Support Team.
If you have any questions regarding Developer Studio please let us know.

**Comment by LDawggieWAB** [comment]
Hi Supriya,

Thank you for letting me know.

Do you have a contact or email address over on the EMEA Developer Support Team?

Thanks!

Lawrence Pawson
WAB Corporate Application Support
Phoenix, Arizona
+1 (623) 256-1212

From: Supriya Nirmale ***@***.***>
Sent: Thursday, April 6, 2023 12:22 PM
To: Fiserv/Support ***@***.***>
Cc: Lawrence Pawson ***@***.***>; Assign ***@***.***>
Subject: *** EXTERNAL *** Re: [Fiserv/Support] "Prologe.exe": List of Error Codes (Issue #371)


CAUTION EXTERNAL EMAIL: Do not click on any links or open attachments if sender is unknown!

________________________________

@LDawggieWAB<https://urldefense.com/v3/__https:/github.com/LDawggieWAB__;!!FVxzmgxCivIWb2dl0Q!pWPa1OefJaH17W-IWgrCvYDqEwff0n2gn9QNyS1rJP1fw5PrRtFofB3zKikYY2HrV3pE69ZbOUuZgjz4prg4n1y8vycWrk6W-bsLQX0$> this github support is meant for https://developer.fiserv.com<https://urldefense.com/v3/__https:/developer.fiserv.com__;!!FVxzmgxCivIWb2dl0Q!pWPa1OefJaH17W-IWgrCvYDqEwff0n2gn9QNyS1rJP1fw5PrRtFofB3zKikYY2HrV3pE69ZbOUuZgjz4prg4n1y8vycWrk6WG7HhcBA$> only.
Please reach out to the EMEA Developer Support Team.
If you have any questions regarding Developer Studio please let us know.

**Comment by sfiserv** [comment]
I am not completely sure. However I found https://fiserv.dev/support
to contact them else there is a chatbot available on their site.
Hope this helps.

**Comment by LDawggieWAB** [comment]
Hi Supriya,

Thanks for letting me know! – I found the same page.

I’ve filled out the form and am now awaiting a reply.

Please go ahead and close my Issue request #371.

Thank you for your help.

Lawrence Pawson
WAB Corporate Application Support
Phoenix, Arizona
+1 (623) 256-1212

From: Supriya Nirmale ***@***.***>
Sent: Thursday, April 6, 2023 12:35 PM
To: Fiserv/Support ***@***.***>
Cc: Lawrence Pawson ***@***.***>; Mention ***@***.***>
Subject: *** EXTERNAL *** Re: [Fiserv/Support] "Prologe.exe": List of Error Codes (Issue #371)


CAUTION EXTERNAL EMAIL: Do not click on any links or open attachments if sender is unknown!

________________________________

I am not completely sure. However I found https://fiserv.dev/support<https://urldefense.com/v3/__https:/fiserv.dev/support__;!!FVxzmgxCivIWb2dl0Q!oeCpC4NvVa6h84Y2GwXhs4VyJv1PBWF3WfAx4pNLtidoRMZpLGBA31jl_0u2PWLNJX9mL0xVc9nMLbZQuCfHPHekxNWuWstGAeg5jdc$>
to contact them else there is a chatbot available on their site.
Hope this helps.

**Comment by sfiserv** [comment]
Thank you for the update. I 'll close this issue.
