### ISSUE TITLE
Inconsistency in value of "example" field.

### ISSUE THREAD

**Issue by tarunfiserv** [Fiserv/Support#372]
“example:” is not consistent in portal when value given in yaml as space (“ “ or “” ) across APIs. 

**Region** (if applicable)
STAGE-PORTAL

**Page**
Home >> Financial Institutions >> FirstVision - APAC >> API Explorer >> Customer Management >> Inquire customer

Home >> Financial Institutions >> FirstVision - APAC >> API Explorer >> Customer Management >> Board customer

**Describe the bug**
In Board_Customer API, example for “middleName” field is mentioned in swagger file as “ “, and the same value is displaying correctly in portal. (Please check below screenshot) 

![image](https://user-images.githubusercontent.com/100914278/230846099-27b9c0ef-3a41-4ace-87a1-25e488a5c0f9.png)

However, In Inquire Customer API, when example for “nameLine3” field is mentioned in swagger file as space “ “.

**Expected:** On portal, value of example should display as " ".
**Actual:** On portal, value of example is displaying blank space without any quotes. (please check screenshot below).

![image](https://user-images.githubusercontent.com/100914278/230850007-b97c4833-0f0e-48f5-b3a9-becbec178717.png)

**NOTE: This issue is in many API so it is a generic issue.**

**To Reproduce**
1. Go to Home >> Financial Institutions >> FirstVision - APAC >> API Explorer >> Customer Management >> Inquire customer
2. Scroll down to 'parameters' section 
3. Click on 'Response Schema' section
4. Scroll down and check for 'namesDetails' field in response schema.
5. Expand the 'namesDetails' field
6. scroll down to 'nameLine3' field and check for the example property on right side.

**Additional context**

**Comment by sfiserv** [comment]
@minh-pham1 please update if this issues is already fixed.

**Comment by minh-pham1** [comment]
Hello @tarunfiserv! This issue is now fixed on dev and will move up to QA env next week where you can test it.
