### ISSUE TITLE
fiserve studio api functionality on video to see?

### ISSUE THREAD

**Issue by AERomecpa23** [Fiserv/Support#375]
**Region** (optional)
The region of a user submitting the feedback.

**What do you like about the project?**
A clear and concise description of what you like about the project.

**Comment by sfiserv** [comment]
@AERomecpa23  can you please provide more information as what you are looking for?
Would you be able to provide us information about your product/organization and how you came to know about us?

**Comment by sfiserv** [comment]
closing this issue as No response for the reporter.
