### ISSUE TITLE
401 Unauthenticated

### ISSUE THREAD

**Issue by suvarnaashoka** [Fiserv/Support#376]
Hi,

We are integrating FirstData as PSP in our website for Gpay wallets, when we tried to integrate we are receiving the 401 Unauthenticated error. Here is the request 

let payload = {
"requestType": "WalletPreAuthTransaction",
"walletPaymentMethod": {
"walletType": "EncryptedGooglePayWalletPaymentMethod",
"encryptedGooglePay": {
"data": {
"encryptedMessage": encryptedSignedmessage.encryptedMessage,
"ephemeralPublicKey": encryptedSignedmessage.ephemeralPublicKey,
"tag": encryptedSignedmessage.tag
},
"signature": tokenobj.signature,
"version": tokenobj.protocolVersion,
}
},
"transactionAmount": {
"total": "1",
"currency": "USD"
}
};

const options = {
method: 'POST',
headers: {
'Content-Type': 'application/json',
'Client-Request-Id': clientRequestId,
'Api-Key': apiKey,
'Timestamp': timestamp,
'Message-Signature': messageSignature,
'Region': 'US',
},
body: JSON.stringify(payload)
};

fetch('https://cert.api.firstdata.com/gateway/v1/payments', options)

Thank you in advance for your time and help. I appreciate your efforts in assisting me with this matter.

**Comment by wwfiserv** [comment]
@suvarnaashoka Commerce Hub Sandbox does not support digital wallet integrations. As you mention First Data, we no longer utilize that integration terminology with Commerce Hub it would be Fiserv. The other gateways would be IPG, uCom, or Payeezy. What gateway are you trying to integrate with as it appears that isn't our payload?
