### ISSUE TITLE
Please give sample data with api documentation

### ISSUE THREAD

**Issue by amcmike3** [Fiserv/Support#377]
**Region** (optional)
The region of a user requesting the feature.
United States

**Is your feature request related to a problem? Please describe.**
I am constantly frustated trying to integrate your API's because the documentation is not great but a lot of the difficulties could be overcome by giving real sample data and giving actual error response codes and what they mean in the documentation for each api.

This is in reference to this api: https://developer.fiserv.com/product/IssuerSolutions/api/?type=post&path=/maintenance/v2/miscfieldupdate&branch=main&version=1.0.0
what does real data in the miscElement look like?

**Comment by sfiserv** [comment]
@eliascanaza can you please help out with the docs/data that @amcmike3 is looking for?
