### ISSUE TITLE
Same Name Tabs Changing

### ISSUE THREAD

**Issue by wwfiserv** [Fiserv/Support#378]
# Reporting new issue for Commerce Hub

**Page**
[Path of the page where the problem exists.](https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/In-Person/Encrypted-Payments/EMV.md#tab-source)

**Describe the bug**
When selecting a tab under Pinless Transaction > Request Variables it also changes to the same named tab under PIN Based Transaction > Request Variables

**Expected behavior**
Tabs should only changed when clicked

**Additional context**
This occurs because the anchor for the tabs are derived from the tab name and doesn't reference the specific header anchor groups, or define a second anchor when the same term is used more than once.

**Comment by minh-pham1** [comment]
The fix is now live on QA, please validate when convenient.
