### ISSUE TITLE
Download Postman Collection Option functionality issue, Server Error when downloading Postman Collection

### ISSUE THREAD

**Issue by cameronveitFiserv** [Fiserv/Support#379]
**Region (optional)**
EMEA and NA

**Is your feature request related to a problem? Please describe.**
In the page of every endpoint is a section called **Additional resources**, this section includes the "Download Postman collection" option. When this option is clicked, the download bar shows up, but the zip file containing the Postman Collection has the message "Failed - Server problem"

**Describe the solution you'd like**
After the download link is clicked, the Postman Collection link should download the json file relating to the postman Collection that the API endpoint is contained within.

For example: In the image below, the Postman Collection link should only download the Postman Collection for Account.yaml.

**Describe alternatives you've considered**
None

**Additional context**
<img width="1439" alt="Screenshot 2023-04-19 at 1 23 21 PM" src="https://user-images.githubusercontent.com/108832813/233152743-fa6ebf40-a3dd-4eef-9dad-5b2216b7c2be.png">

**Comment by sfiserv** [comment]
@cameronveitFiserv  We are aware of this issue and our team has prioritized to work on it.
Tracking ticket.
https://firstdatateam.atlassian.net/browse/PORT-5970

**Comment by sfiserv** [comment]
@CinthyaRivera we have prioritized this for this sprint and I will update once ready for verification.
Our team was focused on production issue resolution.
thanks for your patience.
