### ISSUE TITLE
PaymentJS script tag is not working

### ISSUE THREAD

**Issue by luisgrases** [Fiserv/Support#380]
### Operating system

OSX Ventura 13.0

### Laravel Version

NA

### PHP Version

NA

### Project Location

Local

### Bug description

I am following the documentation to use Payment JS: https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Online-Mobile-Digital/Secure-Data-Capture/Payment-JS/JS-Request.md&branch=main

I added the script tag as suggested:
`<script id="commercehub" src="https://prod.api.fiservapps.com/ch/js/commercehub-client-sdk.js"></script>`

I am getting a 401 response in localhost. Is there something I am missing?

**Comment by wwfiserv** [comment]
@luisgrases please change the src to our cert instead of prod.
