### ISSUE TITLE
Reporting new issue for [String fields] (First Vision Latam)

### ISSUE THREAD

**Issue by OliveiraESilva** [Fiserv/Support#382]
**Region** (if applicable)
First Vision LATAM

**Page**
All site

**Describe the bug**
The portal is **not** showing the minLength for String fields

**To Reproduce**
Example of steps to reproduce the behavior:
1. Go to API Explorer 
2. Go to Cards
3. Go to PIN
4. Click on PIN Validate
5.  Click on Request
6. Scroll down to cardNumber field
7. See error

**Expected behavior**

Show maxLength, minLength, example:
Screenshot from Swagger Editor:

![image](https://user-images.githubusercontent.com/131810830/234377491-b86b1f37-a0a4-483f-b62d-e78e2106d360.png)

**Screenshots**

![image](https://user-images.githubusercontent.com/131810830/234377614-007a40d4-0167-4649-a031-899a5d8f06e6.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome

**Additional context**

**Comment by CinthyaRivera** [comment]
@sfiserv  Do you have any update on this?

**Comment by minh-pham1** [comment]
Hi @CinthyaRivera! Sorry for the late response. The fix is now live on QA, please feel free to validate it!

**Comment by OliveiraESilva** [comment]
Thank you! We are checking it!

**Comment by OliveiraESilva** [comment]
> Hi @CinthyaRivera! Sorry for the late response. The fix is now live on QA, please feel free to validate it!


Hi @minh-pham1! We checked and it looks good for min length different than zero! 

However, for the fields with min length equals '0', only the number appears placed by the side of the field type:

Portal:
![image](https://github.com/Fiserv/Support/assets/131810830/99b0e7cc-ec74-4cd5-bce4-4df8141cd4ed)
YAML:
![image](https://github.com/Fiserv/Support/assets/131810830/2d6c08a4-8ac0-408a-8ed5-7602ecccb731)

In case you need, this example is from the endpoint: [/account/add-L8V3](https://qa-developerstudio.fiserv.com/product/FirstVisionLATAM/api/?type=post&path=/account/add-L8V3&branch=develop&version=1.2.0)

**Comment by minh-pham1** [comment]
Good catch! I've made the change on dev and it'll move up to QA soon. Thank you for spotting it.

**Comment by OliveiraESilva** [comment]
> Good catch! I've made the change on dev and it'll move up to QA soon. Thank you for spotting it.

Thank you!

**Comment by CinthyaRivera** [comment]
@sfiserv @minh-pham1  Let us know if you have any new about this issue

**Comment by minh-pham1** [comment]
Hi @CinthyaRivera! I think that fix went to QA some time in May and is actually already on prod as of the current moment! Please let me know if there's anything else related to this issue that you'd like me to look at.

**Comment by CinthyaRivera** [comment]
Thanks @minh-pham1
