### ISSUE TITLE
Sandbox Enablement for Billpay Space

### ISSUE THREAD

**Issue by DHunnewell** [Fiserv/Support#384]
I would like to enable the sandbox mode for the Billpay space please.

**Comment by sfiserv** [comment]
@DHunnewell is this request to enable Live sand box or Mock?

If its for a Live Sandbox please also provide the other data listed in the https://fiserv.gitbook.io/tenant-docs/enable-sandbox

Else if you have other requirements please provide more details what your product is looking as part of this feature.

**Comment by sfiserv** [comment]
Tracking this request in  https://firstdatateam.atlassian.net/browse/PORT-6286

**Comment by TaniaS-fiserv** [comment]
Hi @DHunnewell Could you kindly respond to the questions above? Based on your response we would start working on this ticket.

> @DHunnewell is this request to enable Live sand box or Mock?
> 
> If its for a Live Sandbox please also provide the other data listed in the https://fiserv.gitbook.io/tenant-docs/enable-sandbox
> 
> Else if you have other requirements please provide more details what your product is looking as part of this feature.
