### ISSUE TITLE
Enable VerifyNow tenant in lower environments

### ISSUE THREAD

**Issue by PurnimaBala** [Fiserv/Support#386]
Hi 
VerifyNow is an existing tenant in dev studio and is currently disabled in QA and DEV env.  This request is to enable VerifyNow tenant so that we can add API documentation for VerifyNow as part of Q4 release. 

Thanks

**Comment by sfiserv** [comment]
Thanks @PurnimaBala  we will priortize this in the upcoming sprint since our work for this sprint is already slotted out.

**Comment by sfiserv** [comment]
Tracking this request in https://firstdatateam.atlassian.net/browse/PORT-6319
priortized for sprint11

**Comment by sfiserv** [comment]
@PurnimaBala please check that your product is enabled in Devstudio QA env. here are the credentials for the QA env

URL: https://qa-developerstudio.fiserv.com/
Username:   devstudio  
Password:     UTvw6-1eAzM
