### ISSUE TITLE
Not able to download API Specification

### ISSUE THREAD

**Issue by ngopir** [Fiserv/Support#387]
# Reporting new issue for Naveen (Product)

**US** (if applicable)
The region of a user reporting the bug.

**Page**
product/IssuerSolutions/api/?type=post&path=/offers/v1/retrieveOffers&branch=main&version=1.0.0

**Describe the bug**
There are links to download API specifications and PostMan collection but it does not download

**To Reproduce**
1. Go to 'https://developer.fiserv.com/product/IssuerSolutions/api/?type=post&path=/offers/v1/retrieveOffers&branch=main&version=1.0.0"
2. Click on '..Download API specifications.'

**Expected behavior**
Zip file the API specs

**Screenshots**

**Desktop (please complete the following information):**

**Tablet (please complete the following information):**
 - Device: [e.g. iPad]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sfiserv** [comment]
DevStudio is aware of this issue and raised as part of another Github issue. This is being addressed as part of current sprint.
We will update this issue once the bug is fixed and ready for validation.

**Comment by sfiserv** [comment]
this is issue is fixed and can be verified on Lower and Production env.
