### ISSUE TITLE
CardPointe

### ISSUE THREAD

**Issue by KGroninger** [Fiserv/Support#392]
### Name of your product / tenant

CardPointe

### Type of Tenant

- [X] Full service
- [ ] Doc only
- [ ] Link out

### Team Members

KGroninger

### Bug Reporting

KGroninger

### Feedback Reporting

KGroninger

### Enhancement Reporting

KGroninger

### Internal tenant

No

### Product of Carat

No

### Merchants solution area

No

### Customer Segments for Merchants

- [ ] SMB
- [ ] Enterprise

### Financial Institutions solution area

No

### Customer Segments for Financial Instituitions

- [ ] Bank
- [ ] Credit Union
- [ ] Large Financial Institution

### Fintech solution area

No

### Region of Operation

- [X] North America
- [ ] EMEA
- [ ] LATAM
- [ ] APAC

### RESTful

Yes

### SDK

Yes

### Runbox

Yes

### Mock Sandbox

Yes

### Live Server

No

**Comment by KGroninger** [comment]
I selected No for each Solution Area, as we will require our own Solution Area (currently in discussion). If one is required to onboard, please place us in Merchant > SMB or Enterprise for now, and we can migrate to a new Solution Area and Customer Segment at a later date.

**Comment by sfiserv** [comment]
@KGroninger  your product does not have any Solution area selected.
Can you please update the requirements as which solution area your product should be set to.

**Comment by sfiserv** [comment]
Tracking this issue in Jira https://firstdatateam.atlassian.net/browse/PORT-6359.

KGroninger please update the Solution area for your product. let us know.

**Comment by KGroninger** [comment]
@sfiserv, It doesn't look like I can edit that detail. Are you able to edit the request to specify Solution Area = Merchant and Customer Segment SMB for now.
