### ISSUE TITLE
Security Tracking and Reporting Tool

### ISSUE THREAD

**Issue by alok-kumar2** [Fiserv/Support#393]
### Name of your product / tenant

PCI Compliance -API

### Type of Tenant

- [X] Full service
- [ ] Doc only
- [ ] Link out

### Team Members

alok-kumar2/alok.kumar2@fiserv.com

### Bug Reporting

alok-kumar2/alok.kumar2@fiserv.com

### Feedback Reporting

alok-kumar2/alok.kumar2@fiserv.com

### Enhancement Reporting

alok-kumar2/alok.kumar2@fiserv.com

### Internal tenant

No

### Product of Carat

No

### Merchants solution area

Yes

### Customer Segments for Merchants

- [X] SMB
- [ ] Enterprise

### Financial Institutions solution area

No

### Customer Segments for Financial Instituitions

- [ ] Bank
- [ ] Credit Union
- [ ] Large Financial Institution

### Fintech solution area

Yes

### Region of Operation

- [X] North America
- [ ] EMEA
- [ ] LATAM
- [ ] APAC

### RESTful

Yes

### SDK

Yes

### Runbox

Yes

### Mock Sandbox

Yes

### Live Server

Yes

**Comment by alok-kumar2** [comment]
What is Mock? I can go with life in that case.

**Comment by sfiserv** [comment]
@alok-kumar2  please go through this section from the Tenant doc https://fiserv.gitbook.io/tenant-docs/enable-sandbox
Check what can be applicable for your product and update the requirement

**Comment by alok-kumar2** [comment]
Please remove Mock Sandbox. We just need Runbox and live server.

**Comment by sfiserv** [comment]
@asingh2023  Can you please look into this tenant on boarding job. the task are stuck at some point.

**Comment by sfiserv** [comment]
@alok-kumar2 your product should be available on our QA env for you to work on. 
Please verify and close this ticket if no issues found.
