### ISSUE TITLE
Exchange Version 2.0.0 API not showing in Explorer

### ISSUE THREAD

**Issue by up-t-j** [Fiserv/Support#394]
# Reporting new issue for Exchange

**Region** (if applicable)
TAPI Explorer 

**Page**
API Explorer
**Describe the bug**
Version 2.0.0 APIs that do not exist in Version 3.0.0 do not show up on the API explorer for Exchange currently. We would expect that the V2 Api should still be viewable
(These are still APIs we Support, just that there were no changes)

**To Reproduce**
Viewable on the API explorer

**Expected behavior**
Version 2.0.0 to be visible at the same time as 
**Screenshots**

**Desktop (please complete the following information):**
 - Chrome

**Additional context**
Appears to be similar to the first issue we raised 

https://github.com/Fiserv/Support/issues/383
-->

**Comment by up-t-j** [comment]
List of Endpoints affected from Version 2.0.0

@TaniaS-fiserv 

/account/settlement-info 

/account/bank-details 

/oauth/token 

/monitoring/overwrite_monitoring_report 

/monitoring/retrieve_hits 

/monitoring/retrieve_report 

/intelligence/overwrite_aml_reports 

/intelligence/overwrite_risk_reports

/intelligence/retrieve_intelligence

/intelligence/retrieve_report

/intelligence/decision 

/split/transaction-details

/split/status

**Comment by TaniaS-fiserv** [comment]
Creating [JIRA ticket](https://firstdatateam.atlassian.net/browse/PORT-6328) for internal Dev Studio tracking purposes.

**Comment by TaniaS-fiserv** [comment]
Hi @up-t-j closing this ticket as I don't think any action is required on this. Kindly re-open a new ticket in case you are still facing similar issues.
Thanks!
