### ISSUE TITLE
Fiserv virtual terminal id, pass and store number

### ISSUE THREAD

**Issue by Markm-mti** [Fiserv/Support#396]
**Region** (optional)
The region of a user requesting the feature.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Markm-mti** [comment]
we are developing integration with Fiserv virtual terminal.need test info for on-boarding such as store number, terminal number, user name and Pass word

**Comment by wwfiserv** [comment]
@Markm-mti Commerce Hub does not have an integration with our VPOS. What gateway are you working with so we can properly direct your inquiry?

@sfiserv
