### ISSUE TITLE
Precision errors

### ISSUE THREAD

**Issue by NeilPre** [Fiserv/Support#399]
# Reporting new issue for [Neil Pre] (Chesapeake Bank & Trust/Precision)

**Region** (if applicable)
The region of a user reporting the bug.

**Page**
Path of the page where the problem exists.

**Describe the bug**
When Shamika Queen logs into Precision via Citrix, she encounters 2 errors (see screenshots)

**To Reproduce**

**Expected behavior**

**Screenshots**
![SQueen Precision error2](https://github.com/Fiserv/Support/assets/134635225/e5a92420-31a3-4cac-be80-97b025985195)
![SQueen restriction error message](https://github.com/Fiserv/Support/assets/134635225/5774521f-2f50-4f3b-b1c4-c00ce3473d75)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win 10
 - Browser [e.g. chrome, safari] Citrix

**Tablet (please complete the following information):**
 - Device: [e.g. iPad]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sfiserv** [comment]
@NeilPre  I am not sure which application you are referring to. 
This github support is meant for reporting bugs/issues on the Fiserv Developer Studio (https://developer.fiserv.com/).

**Comment by NeilPre** [comment]
Supriya,

I apologize for the confusion. I’m trying to get support for errors reported in the Fiserv application Precision to assist a banking customer.

[http://s26.postimg.org/fwxyt2695/blue_line.png]
***@***.***
NEIL PRESSER
RSC Tier 2 Engineer
4035 Tampa Road, Oldsmar, FL  34677
Desk:  (727) 622-6582
Visit us: All Covered <http://www.allcovered.com/>
[http://s26.postimg.org/twql262lh/Facebook.png]<https://www.facebook.com/KonicaMinoltaUS>[http://s26.postimg.org/uq36us8md/Twitter.png]<http://www.twitter.com/allcovered>[http://s26.postimg.org/j6hdx702t/google.png]<https://plus.google.com/u/0/101069343240482341568/about>[http://s26.postimg.org/b5ons0811/Linkedin.png]<http://www.linkedin.com/company/all-covered>[http://s26.postimg.org/p9yyh3qcl/You_Tube.png]<https://www.youtube.com/user/AllCoveredInc>[http://s26.postimg.org/560wocn8l/Pinterest.png]<https://www.pinterest.com/konicaminoltaus/>
Disclaimer<https://kmbs.konicaminolta.us/signature/KMBSUS-Disclaimer%20.png>
[http://s26.postimg.org/fwxyt2695/blue_line.png]
[cid:1727f20b303692e333]<https://kmbs.konicaminolta.us/kmbs/about/awards>

**Comment by sfiserv** [comment]
Maybe you already know this link, you can contact them here
 https://www.fiserv.com/en/about-fiserv/contact-us.html
 Hope this helps.
