### ISSUE TITLE
Enable Preview Branch in Stage and PROD Env for Banking Hub

### ISSUE THREAD

**Issue by tsegurajimen** [Fiserv/Support#400]
Hi Team, 

We need your help to enable Preview branch in Stage and PROD by June 2nd, as we're going to use this branch to showcase a new set of APIs and Documentation for Fiserv Forum.

![image](https://github.com/Fiserv/Support/assets/81706748/27fab25e-6bf4-4e0a-ba45-7243730a7b09)

Thanks in advance!

cc: @rahravin @bobburghardt @sfiserv @fiservakshay

**Comment by TaniaS-fiserv** [comment]
Hi @tsegurajimen this change has been completed from Dev Studio end. The changes however will be reflected in Stage and Production environments as per Sprint 12's release cycle.

Thanks!

**Comment by sfiserv** [comment]
Hi @tsegurajimen this change has been completed from Dev Studio end. The changes however will be reflected in Stage and Production environments as per Sprint 13's release cycle.

Thanks!

**Comment by sfiserv** [comment]
@tsegurajimen The changes are deployed to Stage env and will progress to Production as per the deployment schedule.
<img width="1087" alt="image" src="https://github.com/Fiserv/Support/assets/87097017/3e54e411-24dc-46f4-94f3-dd4f2454d406">

**Comment by tsegurajimen** [comment]
Thanks a lot @sfiserv Preview Branch is now displayed in Stage as expected:
![image](https://github.com/Fiserv/Support/assets/81706748/e1f8a995-be09-42c7-b723-6fdab03d5f5d)
We only still facing the issue reported in the ticket: [API Explorer in Preview Branch is redirecting us to Active Branch · Issue #402 · Fiserv/Support (github.com)](https://github.com/Fiserv/Support/issues/402)

**Comment by tsegurajimen** [comment]
Preview Branch is now displayed as expected in PROD and Stage environments.

![image](https://github.com/Fiserv/Support/assets/81706748/338685bb-bfa7-4bec-ac0c-4121e46be31e)

Then closing this ticket.
