### ISSUE TITLE
Request headers

### ISSUE THREAD

**Issue by CinthyaRivera** [Fiserv/Support#401]
# Reporting new issue for First Vision LATAM

**Region** (if applicable)
LATAM

**Page**
[First Vision LATAM](https://developer.fiserv.com/product/FirstVisionLATAM)

**Describe the bug**
In API explorer, when **any method** (POST, PATCH, PUT, GET) it's selected and in request it's selected "Show Headers" it **doesn't show headers** in Json even though **it has headers to show** in request.

I've realized that it's also in other portals:
https://developer.fiserv.com/product/AccessOne/api/?type=get&path=/v1/api/accountmaintenance/unmask&branch=main&version=1.0.0
https://developer.fiserv.com/product/IPGNA/api/?type=get&path=/store/availableIsoCountries&branch=main&version=1.0.0

**To Reproduce**
1. Go to API Explorer
2. Click on any endpoint
3. Select "Show Headers"

**Expected behavior**
Show Headers in Response json

**Screenshots**
![image](https://github.com/Fiserv/Support/assets/111396588/b2c13162-1df0-46a6-92cf-6ad203f3d541)

![image](https://github.com/Fiserv/Support/assets/111396588/27260c85-e128-4736-a8cc-708308e91eaa)

**Desktop (please complete the following information):**

**Tablet (please complete the following information):**
 - Device: [e.g. iPad]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by CinthyaRivera** [comment]
@sfiserv Do you have an estimate to release this ticket?

**Comment by sfiserv** [comment]
@minh-pham1 can you please verify the issue.

**Comment by minh-pham1** [comment]
Hi Cinthya! We've created a ticket for us to investigate and hopefully fix the issue within the next sprint. I'll post more updates here as we progress!

**Comment by sfiserv** [comment]
this issue should be in QA for you to test by Monday OCt23
https://firstdatateam.atlassian.net/browse/PORT-7360

**Comment by sfiserv** [comment]
@CinthyaRivera  can you please verify if this issue is fixed. It should be in QA env for you to test.

**Comment by sfiserv** [comment]
Closing this ticket as no issues were reported by reportee.
