### ISSUE TITLE
I am trying to create new account in stage-devstudio.fiserv.com, sometimes temporary password email is not triggered and sometimes email is delayed by 20 to 30 mins

### ISSUE THREAD

**Issue by pavansgithubjksahdfjs** [Fiserv/Support#405]
### Product

devstudio

### Page

Create account

### Description

Steps:
Navigate to following URL : stage-developerstudio.fiserv.com 
Click on create account button.
Enter all the details and click on continue
Observe that temporary email is not triggered / it is getting delayed by 20 to 30 mins.

### Expected Behaviour

User should be getting temporary password email

### Operating system

mac od

### Browser

Google chrome

### Region

India

**Comment by sfiserv** [comment]
@pavansgithubjksahdfjs  The logins/emails for OTP are triggered by Ping and not controlled by DevStudio. 
We can keep an eye on this issue and check with Ping however at this point we cannot do much.
