### ISSUE TITLE
Product Title Change

### ISSUE THREAD

**Issue by gowtham-fiserv** [Fiserv/Support#407]
We would like to rename our product from "Zelle Turnkey Solutions" to "Zelle® Mobile SDK". The (®) should be the copyright symbol. Please do the needful ASAP.

**Comment by TaniaS-fiserv** [comment]
Tracking JIRA ticket has been opened for Dev Studio tracking purposes.
https://firstdatateam.atlassian.net/browse/PORT-6588

Further updates would be posted in this GitHub ticket once the changes are implemented.

**Comment by sfiserv** [comment]
@gowtham-fiserv please verify that your product's name has been changed. the changes are in QA env
<img width="672" alt="image" src="https://github.com/Fiserv/Support/assets/87097017/f8bcca7a-13bd-44ea-a172-1cb8dd437a3f">
Close this issue once all verifications are completed.
