### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by formanb17** [Fiserv/Support#408]
### Feedback

Hi,
My name is Ben and I'm the founder of a fintech SaaS company. We are a robust financial management and literacy solution. Our target customers are community and regional banks in New England, many of whom use FiServ for their core and online banking. We would like to partner with FiServ to ease the technical lift for our prospective customers. Thank you and I look forward to hearing back from you.

**Comment by fiservsodas** [comment]
Thank you for the question. Looks like you may be looking at engagement. If you are a fintech please have your developer register and open a banking Hub workspace and request to upgrade. Your fintech Admin persona could then register your company in fiserv's Appmarket and once approved you could get into next steps.

**Comment by formanb17** [comment]
Hi,
Thank you for getting back to me. This is really helpful - one thing that's not clear is how we would request to upgrade our Banking Hub workspace. Could you elaborate on how that would work so we can register to the app market? Thank you again.
