### ISSUE TITLE
Data Commerce Solutions

### ISSUE THREAD

**Issue by f6re97v** [Fiserv/Support#409]
### Name of your product / tenant

Data Commerce Solutions

### Type of Tenant

- [X] Full service
- [ ] Doc only
- [ ] Link out

### Team Members

f6re97v,namanifiserv

### Bug Reporting

f6re97v,namanifiserv

### Feedback Reporting

f6re97v,namanifiserv

### Enhancement Reporting

f6re97v,namanifiserv

### Internal tenant

Yes

### Product of Carat

No

### Merchants solution area

No

### Customer Segments for Merchants

- [X] SMB
- [X] Enterprise

### Financial Institutions solution area

Yes

### Customer Segments for Financial Instituitions

- [X] Bank
- [X] Credit Union
- [X] Large Financial Institution

### Fintech solution area

Yes

### Region of Operation

- [X] North America
- [ ] EMEA
- [ ] LATAM
- [ ] APAC

### RESTful

Yes

### SDK

No

### Industry

Banking , Credit Bureau 

### Runbox

Yes

### Mock Sandbox

Yes

### Live Server

Yes

**Comment by sfiserv** [comment]
@asingh2023  Can you please look into this tenant on boarding job. the task are stuck at some point.

**Comment by sfiserv** [comment]
@f6re97v  please verify your product is now visible in our QA env and you can start using the repo.
