### ISSUE TITLE
API Explorer Missing Expansion Icons on Nested Objects

### ISSUE THREAD

**Issue by wwfiserv** [Fiserv/Support#412]
### Product

Commerce Hub

### Page

https://developer.fiserv.com/product/CommerceHub/api/?type=post&path=/payments/v1/charges

### Description

When going to a nested object the expansion icon is missing

![image](https://github.com/Fiserv/Support/assets/75692745/2aa9425d-1d8b-4837-a869-6b1faa8e996f)
![image](https://github.com/Fiserv/Support/assets/75692745/6ed09f53-3919-48e7-a2d3-72f245e389a3)

### Expected Behaviour

There should be some type of identifier (black arrow) that a nested object can be expanded.

### Operating system

Windows

### Browser

Chrome, Edge

### Region

All

**Comment by tsegurajimen** [comment]
@TaniaS-fiserv @sfiserv can you please look into this issue?

This issue is also affecting all APIs under Banking Hub Tenant.

![image](https://github.com/Fiserv/Support/assets/81706748/a3e3b309-879e-4ff1-8b45-7dcb20a521b9)

cc:
@bobburghardt @fiservakshay

**Comment by sfiserv** [comment]
tracking this issue as part of https://firstdatateam.atlassian.net/browse/PORT-7163 in sprint 17

**Comment by prakashthakuri** [comment]
![image](https://github.com/Fiserv/Support/assets/19219657/2849e3a2-f807-4f19-a8a1-b254ae851ff9)

this issue is fixed and has been merged to the develop branch.

**Comment by wwfiserv** [comment]
shows fixed in QA
