### ISSUE TITLE
Examples of PostAddr format, including CountryCode

### ISSUE THREAD

**Issue by AlexanderNikiforovLineate** [Fiserv/Support#414]
### Product

BankingHub

### Page

https://developer.fiserv.com/product/BankingHub/api/?type=post&path=/partyservice/parties/parties/secured&branch=main&version=11.0.0

### Description

Please provide examples of PostAddr object in GetParty Response. In particular, it is not clear how CountryCode object values look like.

Please give an example of CountryCodeSource,  CountryCodeValue, and CountryCodeEnumDesc.

Several examples in Banking Hub sandbox doesn't have Address information.

Thank you

### Expected Behaviour

Value examples for PostAddr  are provided

### Operating system

Linux Ubuntu

### Browser

Chrome

**Comment by fiservsodas** [comment]
Dear User,
Please take your time to follow this Getting Started Page and details in it to help you better in your engagement in the APIs in Banking Hub - 
**Getting Started Details**: https://developer.fiserv.com/product/BankingHub/docs/?path=docs/getting-started/before-you-start.md&branch=main
**Making your First API Call**: https://developer.fiserv.com/product/BankingHub/docs/?path=docs/getting-started/make-your-first-api-call.md&branch=main#resources

If you need dedicated consulting help, you may look to upgrade your workspace by having your company admin register in our appmarket - https://appmarket.fiservapps.com/

Thank you.

**Comment by bobburghardt** [comment]
@AlexanderNikiforovLineate  - let us take a look in the database for an account or party that has an address.  Are you using the Premier or Signature environments?

**Comment by AlexanderNikiforovLineate** [comment]
@bobburghardt , we are using Premier
