### ISSUE TITLE
Download links to be updated with a different source files for Banking Hub

### ISSUE THREAD

**Issue by tsegurajimen** [Fiserv/Support#415]
### Context

Hi @sfiserv @TaniaS-fiserv and Team,

We need your help because of the nature of Banking Hub APIs and the complexity involved regarding each core documentation, our Download links displayed in each API should point to the following locations in our assets folder, where we have API Specifications files approved to download/distribute and postman collections available per core.

API Specification files: https://github.com/Fiserv/banking-hub/tree/develop/assets/APISpecsToDistribute 
Postman Collections: https://github.com/Fiserv/banking-hub/tree/develop/assets/BH_Postman_Collections

Thanks!

cc: @bobburghardt @fiservakshay 

### Solution

Update Download links in each API in the API Explorer pointing to the right source files accordingly:

![image](https://github.com/Fiserv/Support/assets/81706748/50790ddc-19fa-4a8c-8b59-1e786a183231)

Download API specifications --> https://github.com/Fiserv/banking-hub/tree/develop/assets/APISpecsToDistribute
Download Postman collection --> https://github.com/Fiserv/banking-hub/tree/develop/assets/BH_Postman_Collections

Thanks!

### Alternatives

Not Apply

**Comment by sfiserv** [comment]
tracking this issue as part of https://firstdatateam.atlassian.net/browse/PORT-7021

**Comment by sfiserv** [comment]
Changes are ready to be verified in QA env.

**Comment by sfiserv** [comment]
Changes are ready to be verified in QA env.

**Comment by tsegurajimen** [comment]
Thanks a lot @sfiserv and team, changes were verified according to the demo in the last Playback meeting.
