### ISSUE TITLE
Update Workspaces - Summary Tab for Banking Hub

### ISSUE THREAD

**Issue by tsegurajimen** [Fiserv/Support#416]
### Context

Hi @sfiserv , @TaniaS-fiserv and Team

Please your help updating this paragraph located in Workspaces, Summary Tab, Get Started section; according to this new information:

Current paragraph:

![image](https://github.com/Fiserv/Support/assets/81706748/818ff586-330c-45d5-8fd8-8e5769c58198)

Updated paragraph:

"UPGRADE NOW to a Banking Hub Connection which will give you a dedicated test environment, a monthly quota of 500,000 API transactions, with up to 60 API transactions per minute, and access to optional, ancillary services, including dedicated technical consulting services, and more."

Please note that the UPGRADE NOW should be a hyperlink to this page:

![image](https://github.com/Fiserv/Support/assets/81706748/c6ba5688-df3a-43d9-b88b-5effd13f042f)

Thanks in advance!

cc @bobburghardt @fiservakshay 

### Solution

Update text accordingly.

### Alternatives

Not Apply

**Comment by sfiserv** [comment]
There is a duplicate issue created for this request. hence closing this issue and https://github.com/Fiserv/Support/issues/418
