### ISSUE TITLE
Request for HELP - Issue with party end point in developers hub

### ISSUE THREAD

**Issue by pg06881** [Fiserv/Support#417]
### Product

Banking Hub

### Page

Calling an API

### Description

When issueing an API call to create a new party I receive an error

**Error**
{
    "Status": {
        "StatusCode": "999",
        "StatusDesc": "General Error",
        "Severity": "Error",
        "SvcProviderName": "Signature",
        "ServerStatusCode": "01023.040.000028",
        "ServerStatusDesc": "Failed to retrieve XTE Template"
    }
}

**Payload initially sent**
curl --location 'https://cert.api.fiservapps.com/banking/efx/v1//partyservice/parties/parties/secured/list' \
--header 'EFXHeader: {"OrganizationId":"999980101"}' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjEiLCJwaS5hdG0iOiJhYXVxIn0.eyJzY29wZSI6IiIsImF1dGhvcml6YXRpb25fZGV0YWlscyI6W10sImNsaWVudF9pZCI6Ik9PcW5wVmQ2aWlrM2twcFl3UUkxbHZHSExFWGVKTjk4IiwiaXNzIjoiaHR0cHM6Ly9mZGMtZmVkc3NvLWNhdC5maXJzdGRhdGEuY29tIiwiY2hhbm5lbCI6Im9ubGluZSIsInZlbmRvcklkIjoiOTk5OTkwMzAxIiwiYXBwbGljYXRpb25JZCI6Ijk5OTk5MDMwMSIsImFwcGxpY2F0aW9uTmFtZSI6IkJIVFJJQUxBUFAiLCJmc0ZyaWVuZGx5SWQiOiJEZm5sdGhldnIuT09xbnBWZDZpaWsza3BwWXdRSTFsdkdITEVYZUpOOTgiLCJleHAiOjE2ODc3ODI5MzV9.msYp_sEUHvjfQ_E2UkXpuGQR0_CYtVeueB8aagt836qYxS-4VaijV8oGdf7wdUg-zUGto01P08ewGNaIBksDEDQFemkh93DQfMuSlfBWrNsQFbxsrn-TbwGQOTbc80YKget1G2VEFcpSTUVGyjtOEfsVrX-0KeTqLNcVzQtNCWWay4kce7nCrn-BJHatq0iQNThXY5VGR2mq4fm5-KJ-T0opEkQ8FkygVO86K3r77dclL_IpIJ-VwuTQCk2PBhPf3FA6aq3lqM0yFr8zR3Dw5mwLtl-WQhFav4xAxHbsHL0_uDnJX5Ok3abHFuFkQu6_a_kTXfgbotoMvcrc86MFakFaVb7Mt-hAUW_xYW-kChH5XoSuyDOWBOQBEqBe6oo85t7gXgDHmP6we3xCpZlgAghThzb62a_sj5Weafqk1JSUOr6DIGp9nsrrJx1rN8qXlyNJ4M37ThqZ-JUr3R7-knYkxIPRIMQjL4c9AvXAeDI3xiwruSKHDcYiI7j5csLTtNmboXubd3zntGw0YzUs2MR5grWnvvXXIxH14JjSMXLtwLbVvONCA4MR0yZaacHIbtNHUCtWKnkIL2n4zrUqi8iVjyb_hWdrhobt7LRC9TlUPsfwqGYU3Y7WSJqeO1iqeILIo5_8MAkupublJ-CdnpoeuMZedWS-Rtjnm-j-7rw' \
--data-raw '{
  "PersonPartyInfo": {
    "PartyPref": {
      "Language": "EN"
    },
    "EstablishedDt": "2023-06-22",
    "ServiceLevelOption": "Manual",
    "OriginatingBranch": "Online",
    "ResidenceCountry": {
      "CountryCodeSource": "US",
      "CountryCodeValue": "US"
    },
    "ResidenceCode": "USA",
    "PartyType": "Customer",
    "PersonData": {
      "Contact": [
        {
          "PhoneNum": {
            "PhoneType": "Mobile",
            "Phone": "724-272-8117",
            "PreferredPhone": true,
            "DoNotContactInd": true
          },
          "PostAddr": {
            "Addr1": "812 Brookfield Dr",
            "HouseNum": "812",
            "Street": "Freedom Road",
            "City": "Cranberry TWP",
            "County": "Butler",
            "StateProv": "PA",
            "PostalCode": "16066"
          },
          "Email": {
            "EmailType": "Work",
            "EmailAddr": "TheRealEricDonnelly@tscbank.com"
          }
        }
      ],
      "PersonName": [
        {
          "NameType": "Perhaps long and lengthy",
          "FamilyName": "Smith",
          "GivenName": "John",
          "MiddleName": "J"
        }
      ]
    },
    "BirthDt": "2000-02-08",
    "Gender": "Depends",
    "MaritalStat": "Mostly"
  }
}'

### Expected Behaviour

umm - not an error code :-)

### Operating system

windows

### Browser

portman

**Comment by bobburghardt** [comment]
@pg06881  - thank you for reporting this item.  We are researching and will get back to you with the results of our analysis.

**Comment by bobburghardt** [comment]
@pg06881 - the reason why you received that message is that the system rejected the add due to invalid data.  Generally, that XTE error means that invalid data or a violation of the properties of a field occurred (ex. numeric field expected, but alpha numeric passed over)

In the payload above, there is invalid data in the request - such as the Originating Branch, Marital Status and Gender

You'll want to look at the request schema for the Signature environment to identify the proper data values and types.  That schema is available on the developer studio.

Thank you
