### ISSUE TITLE
Update static content for Developer Studio Free Trial plan in Banking Hub 

### ISSUE THREAD

**Issue by AjitR01** [Fiserv/Support#418]
As a Fintech Developer, when I am in signed into fiserv's Developer Studio

Also, when I create a workspace and navigate to my Banking Hub Workspace,

Then I must see the following details:

For Trial Free Plan - 
![image](https://github.com/Fiserv/Support/assets/137955475/2652ac81-f65a-420f-b6be-2c02676eaa87)

The Marked Content in the Image should be updated to below 

UPGRADE NOW to a Banking Hub Connection which will give you a dedicated test environment, a monthly quota of 500,000 API transactions, with up to 60 API transactions per minute, and access to optional, ancillary services, including dedicated technical consulting services, and more.

Please note that the UPGRADE NOW is a hyperlink to this 
![image](https://github.com/Fiserv/Support/assets/137955475/60ac8db2-a438-4870-928e-d2e75b4daae7)

**Comment by sfiserv** [comment]
@anandrewfiserv  Tracking this issue as part of  milestone 14 in jira: https://firstdatateam.atlassian.net/browse/PORT-6654

**Comment by sfiserv** [comment]
@AjitR01 this issue has been implemented. Please verify and close the issue.

**Comment by AjitR01** [comment]
This is Implemented and validated, Hence closing this ticket.
