### ISSUE TITLE
Large File Upload

### ISSUE THREAD

**Issue by gowtham-fiserv** [Fiserv/Support#420]
We have been facing issues with large file uploads. After doing some R&D work, we found a solution to upload large files, but we need your confirmation to use the [GLFS](https://git-lfs.com/) method to upload larger files inside our repo.

**Comment by TaniaS-fiserv** [comment]
Tracking [JIRA ticket ](https://firstdatateam.atlassian.net/browse/PORT-6672)has been created for tracking purposes of the Dev Studio team.

Further updates would be provided here in this ticket.

Thanks!

**Comment by sfiserv** [comment]
@gowtham-fiserv we have conveyed our view on this issue via email. please take a look.
Hence I am closing this ticket.
