### ISSUE TITLE
DNA

### ISSUE THREAD

**Issue by nseth25** [Fiserv/Support#422]
### Name of your product / tenant

DNA

### Type of Tenant

- [ ] Full service
- [ ] Doc only
- [x] Link out

### Team Members

nseth

### Bug Reporting

nseth

### Feedback Reporting

nseth

### Enhancement Reporting

nseth

### External link

https://dnadeveloper.fiservapps.com/apidocs/

### Internal tenant

No

### Product of Carat

No

### Merchants solution area

Yes

### Customer Segments for Merchants

- [ ] SMB
- [X] Enterprise

### Financial Institutions solution area

Yes

### Customer Segments for Financial Instituitions

- [X] Bank
- [x] Credit Union
- [ ] Large Financial Institution

### Fintech solution area

Yes

### Region of Operation

- [X] North America
- [ ] EMEA
- [ ] LATAM
- [ ] APAC

### RESTful

Yes

### SDK

Yes

### Industry

Banking

### Runbox

No

### Mock Sandbox

No

### Live Server

No

**Comment by sfiserv** [comment]
@nseth25 Can you please resubmit the form with the valid choices. Your product can be on boarded either as a Linkout tenant or Full service tenant. It cannot be both as you have chosen. 
Also the the external link which you have provided needs credentials to access the website. So how can the user access the product.

**Comment by sfiserv** [comment]
@nseth25 we see the Merchant solution area Region, customer segments... are all marked and selected. hence we were not sure exactly what you were looking for.

**Comment by nseth25** [comment]
Is it correct now?

**Comment by nseth25** [comment]
WIll open a new one.
