### ISSUE TITLE
DNA

### ISSUE THREAD

**Issue by nseth25** [Fiserv/Support#424]
### Name of your product / tenant

DNA

### Type of Tenant

- [ ] Full service
- [ ] Doc only
- [X] Link out

### Team Members

nseth

### Bug Reporting

nseth

### Feedback Reporting

nseth

### Enhancement Reporting

nseth

### External link

https://dnadeveloper.fiservapps.com/apidocs/

### Internal tenant

No

### Product of Carat

No

### Merchants solution area

No

### Customer Segments for Merchants

- [ ] SMB
- [ ] Enterprise

### Financial Institutions solution area

Yes

### Customer Segments for Financial Instituitions

- [X] Bank
- [X] Credit Union
- [X] Large Financial Institution

### Fintech solution area

Yes

### Region of Operation

- [X] North America
- [ ] EMEA
- [ ] LATAM
- [ ] APAC

### RESTful

Yes

### SDK

No

### Industry

Banking

### Runbox

No

### Mock Sandbox

No

### Live Server

No

**Comment by sfiserv** [comment]
@nseth25 As mentioned in our earlier conversations, the link provided by you as linkout needs user name and password. 
Is this the correct link you have provided?

**Comment by sfiserv** [comment]
On boarding the tenant is completed. Repo access is granted to the team members.
