### ISSUE TITLE
Dev-QA UI Issue

### ISSUE THREAD

**Issue by GulrukhNaaz** [Fiserv/Support#425]
### Product

Dev-QA

### Page

Active and Preview Branch

### Description

Get Started and Documentation sections on Dev-QA are not working properly. Get Started section is giving 404 error.  At first, Documentation section is not getting expanded, after switching to Preview branch, it expands. Again switching to Active branch, it remains expanded, but after refresh, same issue persists.

### Expected Behaviour

The sections should redirect and expand correctly.

### Operating system

Windows

### Browser

Google Chrome

**Comment by sfiserv** [comment]
@tsegurajimen as mentioned and demoed in the playback, please add the link to the getting started document to the Product yaml file.

@GulrukhNaaz please check with @tsegurajimen for this issue.

**Comment by tsegurajimen** [comment]
Sure @sfiserv, we've fixed it from BH side.

**Comment by tsegurajimen** [comment]
New Getting Started Section in the new Letf side nav is now working as expected.

![image](https://github.com/Fiserv/Support/assets/81706748/dfba92b4-eefc-47c9-9c28-c7cce842ff12)
