### ISSUE TITLE
Cannot create a paid workspace for Banking Hub - Invalid developer email passed

### ISSUE THREAD

**Issue by AlexanderNikiforovLineate** [Fiserv/Support#426]
Please 'choose a different type' above to go back and select 🐞 Bug report
Hello,

I have an access code to create a paid workspace for Banking Hub.
When I try I get an error "Invalid developer email passed".

Please help with this issue.

 
![image](https://github.com/Fiserv/Support/assets/124882232/0f1e5f65-eb01-4809-95dd-a48ff6e6bd06)

**Comment by sfiserv** [comment]
@AlexanderNikiforovLineate  is this happening in Production environment?

I am redirecting this issue to the BankingHub team so that they can help you in this matter.

**Comment by AjitR01** [comment]
Sent email to Lead Developer to try it out creating a paid workspace using lead developer associated with account (a.k.a. Fintech) will keep posted here.
