### ISSUE TITLE
Support for paid account

### ISSUE THREAD

**Issue by AlexanderNikiforovLineate** [Fiserv/Support#428]
Hello,

developer.fiserv.com offers '16 hours of initial consulting support (additional hours available separately)'  for Paid Developer Studio Connection subscription plan. 
I have an access code and can create a workspace with type Integration.
Does it mean that I have Paid Developer Studio Connection subscription?
If yes, how can I get paid consulting support ?

Thanks.

**Comment by sfiserv** [comment]
You have purchased the access code and subscripted to Banking hub paid subscription. Hence I am forwarding your queries/issues to the team in charge.

@tsegurajimen @bobburghardt

**Comment by AlexanderNikiforovLineate** [comment]
@sfiserv , hi. When we can expect an answer to this query? Thanks

**Comment by sfiserv** [comment]
I have assigned all your queries and issues created to Banking hub team. They should be help you out.

**Comment by AjitR01** [comment]
@AlexanderNikiforovLineate  
Fiserv does not provide support for free trial plans.  We recommend you review the documentation available, including the Getting Started information to answer basic questions.
With purchase of Developer Studio Connection subscription plans, Fiserv offers optional Technical Integration Services, including expert consulting assistance and guidance on developing your integration.  Contact your company’s administrator for more information.  
we have received you email regarding Technical Integration service and team will reach out / respond to your email. 
Appreciate it.
