### ISSUE TITLE
Test data in paid workspace (Banking Hub)

### ISSUE THREAD

**Issue by AlexanderNikiforovLineate** [Fiserv/Support#429]
Hello,
I'm using paid workspace for Banking Hub.
PartyIds that worked for free sandbox don't work for paid workspace.
Can you please provide a table with valid PartyId, AccountIds, and other data used in paid Banking Hub workspace?

Thank you.

![image](https://github.com/Fiserv/Support/assets/124882232/10fc8eb5-8363-4545-9d20-006a78258516)

**Comment by sfiserv** [comment]
@tsegurajimen @bobburghardt please help @AlexanderNikiforovLineate .

**Comment by AjitR01** [comment]
@AlexanderNikiforovLineate  Team will be sharing standard report include Balance Reference Journals for DDA, SDA, CDA and Loans via email to alexander.nikiforov@kore.com. Hope that will fix the issue.
