### ISSUE TITLE
Question about multiple recurrence rules in BankingHub

### ISSUE THREAD

**Issue by levan-lineate** [Fiserv/Support#431]
[Get Transfer List](https://developer.fiserv.com/product/BankingHub/api/?type=post&path=/xferservice/payments/transfers/secured/list&branch=main&version=11.0.0)  response schema shows that XferListRec.XferListInfo.RecurModel.RecurRule is an array. 

Could you please provide some information on how these rules are combined?

What are typical use cases for using multiple recurrence rules?

**Comment by sfiserv** [comment]
@tsegurajimen @bobburghardt
