### ISSUE TITLE
Spec Approval Email Flow Enhancement

### ISSUE THREAD

**Issue by kcaramat** [Fiserv/Support#433]
### Context

Spec Approval email flow should include a text box that allows a user to enter a request reason and the admin to provide a denied reason. Time can be booked to Cert PR22060823.

### Solution

Spec Approval email flow should include a text box that allows a user to enter a request reason and the admin to provide a denied reason. Time can be booked to Cert PR22060823.

### Alternatives

Spec Approval email flow should include a text box that allows a user to enter a request reason and the admin to provide a denied reason. Time can be booked to Cert PR22060823.

**Comment by sfiserv** [comment]
@kcaramat  can you please verify the email flow is implemented as per the requirements.

**Comment by kcaramat** [comment]
@sfiserv the requested functionality has not yet been implemented.
