### ISSUE TITLE
Preview links are not staying in preview branch 

### ISSUE THREAD

**Issue by MAFiserv** [Fiserv/Support#437]
### Product

Commerce Hub

### Page

Updates and alerts > preview releases 

### Description

While in the preview branch clicking on a link takes you back to the main branch 
Link ex: forced post: https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Release-Notes-Alerts/Preview.md&branch=preview

### Expected Behaviour

When you are in the preview branch you should stay in the preview branch

### Operating system

Windows 

### Browser

Google chrome

### Region

Production

**Comment by wwfiserv** [comment]
issue appears to be resolved, will keep an eye on it.

**Comment by wwfiserv** [comment]
Today I'm seeing instances of being in the Main (Active) branch and it navigating to the Preview branch

**Comment by sfiserv** [comment]
@MAFiserv  we have fixed the issue, can you please verify.
