### ISSUE TITLE
Request objects in GET methods of type Query

### ISSUE THREAD

**Issue by FranciscoCampos09** [Fiserv/Support#439]
### Product

Silvercore

### Page

api/?typw=get&path=/cards/cvv&branch=develop&version=1.0.0

### Description

Hi Team, We are missing many parameters in the portal for one of our APIS. Request objects in GET methods of type Query are not displayed

On Swagger
![image](https://github.com/Fiserv/Support/assets/120739273/57a5bc93-ae33-4714-872f-d308649583cb)

On Developer Portal
![image](https://github.com/Fiserv/Support/assets/120739273/b1e4a9b3-a515-4a78-9149-e0b11276a938)

Is this supported?

Can you help me please

Greetings

### Expected Behaviour

Show the reques body in the GET methods:

![image](https://github.com/Fiserv/Support/assets/120739273/57a5bc93-ae33-4714-872f-d308649583cb)

### Operating system

Windows 11 Enterprise 22H2

### Browser

Chrome 114.0.5735.134

**Comment by sfiserv** [comment]
tracking this ticket in https://firstdatateam.atlassian.net/browse/PORT-6950

**Comment by sfiserv** [comment]
@FranciscoCampos09  our team is still reviwing this issue. let me get an update on this.

**Comment by OZ-FS** [comment]
@FranciscoCampos09 DevStudio display information being provided in openspec.yaml.
Do I understand it correctly that the missing part is the description and examples for API parameters, not the parameters (name, in, required, type, format) themselves, correct?
URL query string is a string, it is possible to pass a json stringify object, but again as a string.

To display the parameter string as an object:

1.  parameter description field can be used with <br> tags. Please note: the whole description has to be inside single-quote:
          description: 'Estructura de campos para la solicitud de la API CVV.<br>{<br> "accountNumber": "9A21CA199726F942F2535D7E32CA1CB6",<br> "additional": 0,<br> "cardNumber": "112233",<br> "cardNumberM": "445566" <br>}'


1. add an example as part of the parameter schema as such:
      example: '{ "accountNumber": "9A21CA199726F942F2535D7E32CA1CB6", "additional": 0, "cardNumber": "112233", "cardNumberM": "445566" }'

I have edited reference/1.0.0/Cards.yaml
/cards/cvv GET **request** parameter with description and schema example that can be followed.

![Uploading Screenshot 2023-08-17 at 2.19.27 PM.png…]()

**Comment by OZ-FS** [comment]
<img width="922" alt="Screenshot 2023-08-17 at 2 19 27 PM" src="https://github.com/Fiserv/Support/assets/92183615/c26deb16-6338-49d8-a3ff-97280d380168">

**Comment by OZ-FS** [comment]
Anyhow according to security.stackexchange.com:
 **sensitive data should not be sent via a HTTP "GET" and should always be sent via "POST"**

**Comment by OZ-FS** [comment]
<img width="1557" alt="Screenshot 2023-08-17 at 2 25 36 PM" src="https://github.com/Fiserv/Support/assets/92183615/6ddf2528-95d5-4dae-92df-fe5710218a17">
<img width="1000" alt="Screenshot 2023-08-17 at 2 25 59 PM" src="https://github.com/Fiserv/Support/assets/92183615/3cafe627-a1cd-41f7-8abf-c3c9016d4ebf">

**Comment by OZ-FS** [comment]
Endpoint parameters are displayed in rows of two columns:

column 1: name, required, type, in

column 2: description, example

**_We do not parse object schema for parameters._**

**Comment by sfiserv** [comment]
@FranciscoCampos09  please review the feedback provided by our team member. Please close the ticket if you got a solution to your query.

**Comment by FranciscoCampos09** [comment]
Hi, we are working on the solution mentioned in the CVV example to display requests in GET methods. It is also coming up with a migration from GET to POST in a new version. Thanks for your support.
