### ISSUE TITLE
Inconsistency in field name and description of LoanAccountInfo.HomeMortgageDisclosure.PostAddr in PRM-AddLoan Request Schema

### ISSUE THREAD

**Issue by ndcalabrese** [Fiserv/Support#441]
In the PRM AddLoan Request Schema, in `LoanAccountInfo.HomeMortgageDisclosure.PostAddr`, should the `County` property be `Country`? Or should the description say 'county' instead?

https://github.com/Fiserv/banking-hub/blob/12b5aad980ea6d7f61817d47e49f8398f2333417/reference/11.0.0/Accounts/AcctService-11.0.0_PRM-Add_LOAN.yaml#L2360-L2363

**Comment by AjitR01** [comment]
@mjkuhlman1983 Please look into this issue.

**Comment by ndcalabrese** [comment]
Hi, is there an update for this issue?

**Comment by ndcalabrese** [comment]
Hi, is there an update for this issue?
