### ISSUE TITLE
Weird behavior of Core's Dropdown when switching from Active to Preview Branch and vice versa. 

### ISSUE THREAD

**Issue by tsegurajimen** [Fiserv/Support#442]
### Product

Banking Hub

### Page

https://developer.fiserv.com/product/BankingHub/api/?type=post&path=/acctservice/acctmgmt/accounts&branch=main&version=11.0.0

### Description

Core's dropdown is failing when switching from Active to Preview Branch and vice versa, multiple duplicate entries are displayed per each core.

![image](https://github.com/Fiserv/Support/assets/81706748/53c02c44-ebe9-4256-b70e-1709ddb43d47)

![image](https://github.com/Fiserv/Support/assets/81706748/fa23e0ad-b80d-4e44-a25e-400574165145)

Thanks in advance for checking! 

### Expected Behaviour

Core's dropdown should work as expected, displaying only the entries according the yamls linked in our tenant.json file.

### Operating system

Microsoft 64-bit operating system, x64-based processor

### Browser

Google Crome

**Comment by sfiserv** [comment]
Tracking this issue as part of jira https://firstdatateam.atlassian.net/browse/PORT-7026

**Comment by tsegurajimen** [comment]
@sfiserv now I'm not able to reproduce it either, not sure why is working fine now. The only change done by BH Team was to move Finxact APIs from Preview to Active, then that might has fixed the issue.

![image](https://github.com/Fiserv/Support/assets/81706748/1219c2e8-111c-454b-8d48-04777f7894f0)

**Comment by sfiserv** [comment]
So I am closing this ticket. if you see this issue please report again or reopen this ticket.
