### ISSUE TITLE
Exchange Product Category Revisement

### ISSUE THREAD

**Issue by up-t-j** [Fiserv/Support#443]
### Context

Hi, we would like to change the category of the Exchange product on dev studio - repo: https://github.com/Fiserv/exchange/

Please may we be moved to Merchant, with the Subgroup Enterprise. 
We would like the following tags as well: 
Region 
- North America
Channel Type 
- Card Present
- Card Not Present
Integration Type
- RESTful
Category
- Cards
- Payments
- Risk & Fraud

### Solution

Please may we be moved to Merchant, with the Subgroup Enterprise. 
We would like the following tags as well: 
Region 
- North America
Channel Type 
- Card Present
- Card Not Present
Integration Type
- RESTful
Category
- Cards
- Payments
- Risk & Fraud

### Alternatives

N.A

### Additional Context

N.A

### Region

Dev Studio Exchange

**Comment by TaniaS-fiserv** [comment]
JIRA ticket created for Dev Studio tracking purposes 
https://firstdatateam.atlassian.net/browse/PORT-7032

Please note any future updates to the ticket will be posted in this GitHub ticket.
Thanks!

**Comment by prakashthakuri** [comment]
this has been fixed and we are validating in upper env.

**Comment by up-t-j** [comment]
Hi @prakashthakuri  , Where can iIverify this please? 
I do not see the changes made on the QA environment yet https://qa-developer.fiserv.com/merchants
Thankyou

**Comment by sfiserv** [comment]
@up-t-j seems the changes were not completely implemented. We missed to change the Solution area and sub category  ( merchants) as per your request.
Our team will get this fixed and update you for your validation.

**Comment by sfiserv** [comment]
@up-t-j  the changes are completed and ready for your validation. As the deployments proceed, we will make changes to the tenant json file to update the solution type.

**Comment by up-t-j** [comment]
Thanks @sfiserv , this appears as expected on the QA environment now. Is any action needed from my side to get this into next prod deployment ?

**Comment by sfiserv** [comment]
This code will be available in production with Sprint 19's prod deployment.
