### ISSUE TITLE
Ability to select Free Trial Core 

### ISSUE THREAD

**Issue by Darrickloftus** [Fiserv/Support#444]
### Context

When creating a Free Workspace in BankingHub users have access to all available cores. As we add more and more products to these free workspaces, it will become necessary to add a selecting feature for the free workspace they create. We will also need the ability to add cores onto a workspace without the act of deleting and recreating the workspace. 

### Solution

A selector UI that would be added to the Free Workspace creation flow. Also the ability under the settings of the workspace to add additional free services to the Workspace. We have looks at a dropdown selector or checkboxes but would want UX involvements to create.  

### Alternatives

We have looked at dropdowns and check boxes but would want UX involvement in the creation of the artifact.

**Comment by sfiserv** [comment]
tracking the issue in https://firstdatateam.atlassian.net/browse/PORT-7161
