### ISSUE TITLE
Add additional button for paid plan support

### ISSUE THREAD

**Issue by Darrickloftus** [Fiserv/Support#445]
### Context

When a user gets a paid plan they aregiven access to a speceific area for support. We would want to enable a button giving the option to open a ticket through the paid plan channel through the Dev Studio 

### Solution

Enable a button for paid plan support. We will have groups vreated and routing rules designed by September and would like to have users the ability to get paid plan support through the DevStudio

### Alternatives

Ideally we would only like to show the option for paid plan support for users with paid plans

**Comment by sfiserv** [comment]
@Darrickloftus  is this the same request as raised by Thomas https://github.com/Fiserv/Support/issues/447

**Comment by sfiserv** [comment]
https://firstdatateam.atlassian.net/browse/PORT-7160 tracking the issue in jira.

**Comment by sfiserv** [comment]
seems a duplicate request hence closing this.
