### ISSUE TITLE
Issue with YAML file

### ISSUE THREAD

**Issue by CinthyaRivera** [Fiserv/Support#446]
I tried to added a new file to preview branch but it keep marking as an error cause identify that tags are missing but tags are on YAML:

1. Error
![image](https://github.com/Fiserv/Support/assets/111396588/e746f9d8-ffbe-4f66-b735-1a57a7b71da7)

2.  YAML with tags
![image](https://github.com/Fiserv/Support/assets/111396588/fa61c45a-33dd-4e67-83a4-362f2f43f4fe)

3. Config in tentant.jsom
![image](https://github.com/Fiserv/Support/assets/111396588/c91f770a-7d55-4da0-ab35-41d7ecd429c7)

Bonus: It's showing a category that doesn't exist on the config
![image](https://github.com/Fiserv/Support/assets/111396588/e3a3ce06-4b6a-40f9-8701-5d8cd808e4cc)

I need to show this on portal for this week release.

**Comment by sfiserv** [comment]
@asingh2023 can you please help out Cinthya in this matter.

**Comment by CinthyaRivera** [comment]
Hello, thanks for answer. This is not an issue anymore. I just let the ticket alive for research and avoid this can be an issue for other people
