### ISSUE TITLE
Add link to https://client360.fiservapps.com/Client360/login from Developer Studio for those with a purchased product

### ISSUE THREAD

**Issue by thomaspirone** [Fiserv/Support#447]
### Context

Add link to https://client360.fiservapps.com/Client360/login from Developer Studio for those with a purchased product.  

1.  Fiserv customers use Client360 to have their support requests routed to Fiserv groups. 
2.  Fiserv groups that own support of the Banking Hub Developer Studio Connection and systems connected to it such as ESF Communicator Open, etc. have signed up to receive support requests only from paying customers and only through Client360.
3.  Companies that buy Banking Hub Developer Studio Connection will be given instructions on how to log into Client360 directly. They do not need to open Developer Studio to submit a support request.
4. Developers in companies that bought a Banking Hub Developer Studio Connection may go to Developer Studio if they are experiencing an issue with an API response. They may see the Help link there. If that prominently visible link is the first thing they see and they use it to open a GitHub entry, the Fiserv groups that own support of the Banking Hub Developer Studio Connection and systems connected to it such as ESF Communicator Open, etc. are not going to respond.
 

### Solution

To fulfill the problem described in the Context section above, create a link for dedicated support that is as prominently displayed as the Help button that currently opens GitHub. See this confluence page for all design considerations and UX proposal https://bankconfluence.onefiserv.net/display/appmarket/Route+Banking+Hub+users+with+paid+subscriptions+away+from+GitHub

If you don't visually distinguish and direct those that have bought a product to Client360 instead of GitHub, support for paying customers will be delayed.

Support groups using Client360 will not want to answer emails, Microsoft Team texts, or answer phone calls from those that are monitoring GitHub. 

### Alternatives

.

### Additional Context

.

### Region

USA

**Comment by sfiserv** [comment]
tracking this issue in(https://firstdatateam.atlassian.net/browse/PORT-7127)

**Comment by sfiserv** [comment]
changes are ready to be verified in QA and stage env.
