### ISSUE TITLE
Looking for Bill Pay Service in Banking Hub

### ISSUE THREAD

**Issue by pcoulter** [Fiserv/Support#450]
### Context

I'm looking for a way to create payees and payments for consumer bank accounts.  I've been working mostly with Banking Hub.  Am I missing this API or does it not exist?

### Solution

API to create payees and schedule payments.

### Alternatives

Don't have one

### Region

US

**Comment by AjitR01** [comment]
@pcoulter  This service is not available as of today in Banking Hub.

**Comment by pcoulter** [comment]
@AjitR01 Is there another product outside of Banking Hub that would provide this functionality?  I'm specifically looking to work with Premiere Core, but if there's some add-on to Premiere that provides this, we'd consider purchasing that.

Thanks,
Pete
