### ISSUE TITLE
Need help with URL creation

### ISSUE THREAD

**Issue by f7wau03** [Fiserv/Support#452]
### Context

we have a scenario in the API explorer where a drop-down value should be selected in the API explore based on the link parameter. The documentation section has link which needs to point to the API explorer section with a dropdown value highlighted.

### Solution

The URL should have the ability to pre define a value to be selected in the drop down like having an extra parameter to mention the drop down value to be selected

### Alternatives

There is no alternative we can consider at this time

### Region

North America

**Comment by f7wau03** [comment]
@sfiserv the feature is requested for Connected Commerce (uCom) & Digital Disbursements

**Comment by sfiserv** [comment]
@f7wau03  going forward, we would appreciate if you could update the request with product details. It is difficult for our team to track the issue.

**Comment by acho-fiserv** [comment]
thanks for the suggestion.  this will be set as low priority and something we may consider in the future.

**Comment by paulmohljr** [comment]
@acho-fiserv How do we track from this ticket to prioritization? This would help in how we design pages going forward so I would think this feature to us isn't low priority
