### ISSUE TITLE
feat: Dark mode

### ISSUE THREAD

**Issue by michaelbrewer** [Fiserv/Support#46]
**Is your feature request related to a problem? Please describe.**

As a 2 am developer, i like to set dark mode everywhere

**Describe the solution you'd like**

When my computer is configured for night mode (with dark mode), i would expect websites to honor this preference.

**Describe alternatives you've considered**

There is extensions to generate a dark mode for site, but it never really works well.

**Comment by TaniaSarkar89** [comment]
Opened this JIRA ticket: https://firstdatateam.atlassian.net/browse/PORT-3285
