### ISSUE TITLE
Security Certificate for *.getbills.com is expired

### ISSUE THREAD

**Issue by vandorb12** [Fiserv/Support#465]
### Product

getbills.com

### Page

getbills.com

### Description

In Firefox, using any service that hooks into your service returns a SEC ERROR EXPIRED CERTIFICATE error. Going into further detail, Firefox states that "Peer's Certificate has expired." You have the option, at least in Firefox and Chrome, to Accept the Risk and continue to go on your merry way, however this is not the expected behavior for a secure bill transport to an end user or to another vendor.

![image](https://github.com/Fiserv/Support/assets/32138616/9108a4e6-2e0a-4b36-ac9e-c3ba66fa39d5)

To reproduce, you may go to the https://billdetail.getbills.com site, and you are presented the SEC ERROR EXPIRED CERTIFICATE error in Firefox, and a similarly worded error in Chrome. You can also go through a consumer banking bill pay platform that hooks in with getbills.com, and get the same results when trying to view a bill document.

Going deeper into the certificate, it is indeed expired, per screenshot:
![image](https://github.com/Fiserv/Support/assets/32138616/59f79df4-6a56-4cdd-9ea1-35f1e307d71b)

### Expected Behaviour

Your security certificate has expired has not successfully renewed. End users should not see this certificate error.

### Operating system

Win10, Debian 11

### Browser

Firefox 116, Chrome (latest)

### Region

United States

**Comment by vandorb12** [comment]
This issue was first noticed on 20230810 at 2100 PDT, and I have reported this issue to my banking institution to reach out to your support services as well. They were able to replicate this issue on multiple machines and networks.

**Comment by sfiserv** [comment]
@vandorb12  this github support is meant exclusive for Developer Studio.
https://developer.fiserv.com/
You will have to reach out to the appropriate support channel to log the bug.

**Comment by vandorb12** [comment]
Pleasantries,

The GitHub page was the logical conclusion of me trying to find the
appropriate support personnel to bring up this issue within a meaningful
amount of time that was outside of standard business hours.

Fiserv is not performing industry best practices of providing a
security.txt file or any form of direct contact to those who would be
managing the webserver infrastructure.

With that said, the issue appeared to resolve itself and being that this is
being reported in the wrong place, this issue may be closed without further
discussion.
