### ISSUE TITLE
Free/Trial Plan Provider Selection 

### ISSUE THREAD

**Issue by AjitR01** [Fiserv/Support#469]
### Context

As of today when user creates a free workspace in Banking Hub space, by default workspace & api credentials is created for all enabled providers.

### Solution

1. User should be able to select one Provider at a time while creating a Free Workspace in Banking Hub. 
2. Once free workspace is created, user should be able to add an additional provider once it is enabled on Developer.Fiserv.com a.k.a. https://developer.fiserv.com/workspace/64d13343185a02e5ca7a5b06/  without altering the API credentials.
3. Addition of each provider should be shown as Individual Line items under Credentials tab in workspace.
4. User should have capability to delete Individual Provider API credentials from the workspace.

### Alternatives

By default create API Credentials for all enabled Providers in Banking Hub space.

### Additional Context

![image](https://github.com/Fiserv/Support/assets/137955475/0f69f5fe-cf1f-4d35-a810-f1042ae42c5e)

### Region

https://developer.fiserv.com/workspace/

**Comment by sfiserv** [comment]
Tracking this issue in https://firstdatateam.atlassian.net/browse/PORT-7313

**Comment by sfiserv** [comment]
Closing this issue since Developer studio won't be working on this requirement.
