### ISSUE TITLE
Update summary content & plan description for Free trial Plan in Developer Studio Banking Hub Space

### ISSUE THREAD

**Issue by AjitR01** [Fiserv/Support#474]
### Context

As a Fintech Developer, when I am in signed into fiserv's Developer Studio

Also, when I create a workspace and navigate to my Banking Hub Workspace,

Then I must see the following details:
![image](https://github.com/Fiserv/Support/assets/137955475/8a3da9dc-8278-4d83-9a39-5dbc7e379bcf)

![image](https://github.com/Fiserv/Support/assets/137955475/7b79fb63-73d6-44dc-9d78-7c66b59705ab)

### Solution

Update specific line under get started content summary page to below  - 

**A monthly quota of 1,000 test API transactions, with up to 3 API transactions per minute**

Update Plan description to below -

**This plan includes 1,000 account processing core API transactions per month and 3 API transactions per minute across shared core environments.**

### Alternatives

N/A

**Comment by AjitR01** [comment]
Pass the new Product Bundle ID as part of request to DAC for workspace creation for free plan.

**Comment by sfiserv** [comment]
Tracking this requirement in Jira 
https://firstdatateam.atlassian.net/browse/PORT-7309

**Comment by anandrewfiserv** [comment]
Hi @AjitR01 , the summary page is currently controlled by us so I can change it, but the text in the API key is from the planDescription in the GET request.

**Comment by sfiserv** [comment]
@AjitR01 the changes are in the QA env ready to validate.
