### ISSUE TITLE
Remove additional resources link from API Explorer and add a link to navigate to resource page

### ISSUE THREAD

**Issue by AjitR01** [Fiserv/Support#477]
### Context

As of today the additional resource link i.e., Download API specifications & Download P[ostman collection in API explorer page is not functional.

### Solution

Remove the link under Api Explorer and give linnk to Resource page under Doucmentation i.e. https://qa-developerstudio.fiserv.com/product/BankingHub/docs/?path=docs/resources/resources.md&branch=develop
![image](https://github.com/Fiserv/Support/assets/137955475/1c3160c5-7e60-4636-a573-a271b9a0dfdb)

### Alternatives

N/A

**Comment by sfiserv** [comment]
@AjitR01 please validate the changes on QA env. we have implemented a new fix for download feature.
