### ISSUE TITLE
Feedback 

### ISSUE THREAD

**Issue by phaninv** [Fiserv/Support#480]
### Feedback

Hi,

Below is the feedback from the recent usage of Developer Studio of fiserv. The APIs are well organized and the availability of the postman collection helps in the making the calls easy with the provided documentation.

We will greatly appreciate if the APIs could provide some test data so it will accelerate the integration.

Thanks,
Phani

**Comment by sfiserv** [comment]
@phaninv thank you for the feedback. 
We would like to know which product's test data you were looking for. If you could please provide us the information we can help you in the integration.

**Comment by phaninv** [comment]
We are working on the Signature integration. (Banking Hub)
Use case:
Create Party, Update Party
Create SDA, Update SDA
Finding trouble creating SDA and CDA as it requires lot of data to be filled for the flags.
There is a mention of Product Specification Inquiry API to get data. I tried that and it is not returning the valid flags.
Please provide some test data for Party, SDA, CDA and Loan accounts for Signature Core
