### ISSUE TITLE
Migration of Zelle SDK from QA to Production environment

### ISSUE THREAD

**Issue by gowtham-fiserv** [Fiserv/Support#481]
We have completed and tested the ZelleSDK Page flow on the QA environment and found every thing working fine. We would like to migrate from QA to Production environment to be accessible by our FI's to download the Zelle SDK builds  and refer the supporting documents for the integration with their parent app.

**Please find the details below:**

Product Name : Zelle® Mobile SDK
Product link : https://qa-developerstudio.fiserv.com/product/ZelleMobileSDk/docs/?path=docs/supporting-documents/cordova.md&branch=develop
Repo Name : zelle-turnkey-solutions
Repo Link : https://github.com/Fiserv/zelle-turnkey-solutions

Please let us know if you required any details.

**Comment by sfiserv** [comment]
Tracking the issue in https://firstdatateam.atlassian.net/browse/PORT-7406
for sprint18
