### ISSUE TITLE
Example body from /v1/charges doesn't work

### ISSUE THREAD

**Issue by aoysgelt** [Fiserv/Support#483]
Hello, 

When using the example request in https://developer.fiserv.com/product/CommerceHub/api/?type=post&path=/payments/v1/charges&branch=main&version=1.4.0 and executing with my api key, merchant id, and terminal ID, I receive a "bad request" response message. Please review my request and response below.

Request:
```
curl --location 'https://cert.api.fiservapps.com/ch//payments/v1/charges' \
--header 'Client-Request-Id: Client-Request-Id' \
--header 'Api-Key: redacted' \
--header 'Accept-Language: Accept-Language' \
--header 'Auth-Token-Type: Auth-Token-Type' \
--header 'Message-Digest: Message-Digest' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--data '{
  "amount": {
    "total": 12.04,
    "currency": "USD"
  },
  "source": {
    "sourceType": "PaymentCard",
    "encryptionData": {
      "encryptionType": "RSA",
      "encryptionTarget": "MANUAL",
      "encryptionBlock": "=s3ZmiL1SSZC8QyBpj/Wn+VwpLDgp41IwstEHQS8u4EQJ....",
      "encryptionBlockFields": "card.cardData:16,card.nameOnCard:10,card.expirationMonth:2,card.expirationYear:4,card.securityCode:3",
      "keyId": "88000000022"
    }
  },
  "transactionInteraction": {
    "origin": "ECOM",
    "eciIndicator": "CHANNEL_ENCRYPTED",
    "posConditionCode": "CARD_NOT_PRESENT_ECOM"
  },
  "merchantDetails": {
    "merchantId": "redacted",
    "terminalId": "redacted"
  }
}'
```

Response:
`{
    "gatewayResponse": {
        "transactionProcessingDetails": {
            "apiTraceId": "e66a01d6878f4980b6821d9e0341f831",
            "clientRequestId": "Client-Request-Id"
        }
    },
    "error": [
        {
            "type": "APIM",
            "message": "Bad request."
        }
    ]
}`

**Comment by wwfiserv** [comment]
The payload is just an example you will need to still generate a valid encrypted payload using the multi-use public key or test using the PaymentCard using plain card data.
