### ISSUE TITLE
Urgent Bug Report Search Engine Issue Impacting API Search Functionality to Find a Specific API by VMX Service .

### ISSUE THREAD

**Issue by mohamed-jammal** [Fiserv/Support#485]
### Product

FirstVision - LATAM

### Page

Search

### Description

Dear Development Team,

I hope this message finds you well. I wanted to bring to your immediate attention a issue that I have identified while use the developer portal. It appears that the search engine is not functioning appropriately when attempting to locate a specific API by VMX Service: M.CMS.FLCN.MON.TRANSFER.INQ . I kindly request your prompt attention to address and rectify this bug to ensure the seamless functionality of our platform.

**Bug Description**:
When utilizing the search engine to locate a specific API, the results returned are inaccurate and often fail to provide the desired outcome. Users are experiencing difficulty in finding the desired API even when using accurate and specific search terms. This is significantly impacting the usability of our platform, as it hinders users from effectively accessing the APIs they need.

**Steps to Reproduce**:
Navigate to the search page on the platform's main page.
Enter a specific API name or related keywords.
The URL must be like: [Monetary Inquiry] (https://developer.fiserv.com/search?q=M.CMS.FLCN.MON.TRANSFER.INQ)
Observe the search results for accuracy and relevance.
**Actual Behavior**:
The search results often include irrelevant APIs or fail to include the desired API in the search results.

**Impact**:
This bug significantly impacts the usability and efficiency of our platform. Users rely on the search engine to quickly locate and access the APIs they require for their projects. The current issue causes frustration, delays, and inefficiencies in their workflow, which can lead to a negative user experience and potential loss of trust in our platform's functionality.

**Urgency**:
Given the critical nature of this bug and its impact on user experience, I strongly urge the development team to prioritize this issue. Swift action is needed to ensure that the search engine's functionality is restored to its expected state.

**Proposed Solution**:
To address this issue, I recommend the following steps be taken:

Conduct a thorough investigation to identify the root cause of the search engine's inaccuracies.
Review and adjust the search algorithm to improve the relevance and accuracy of search results.
Implement comprehensive testing to ensure that the search engine functions appropriately across a variety of search queries.

**Additional Information**:
If further information, logs, or testing results are required to diagnose and resolve this issue, please do not hesitate to reach out to me. I am fully committed to assisting in any way necessary to expedite the resolution process.

Thank you for your attention to this matter. Your efforts in swiftly addressing this bug are greatly appreciated and will undoubtedly contribute to the continued success of our platform.

Best Regards,

Mohamed Jammal
mohamed.jammal@fiserv.com

### Expected Behaviour

**Expected Behavior**:
The search engine should accurately retrieve relevant results based on the provided search query. Users should be able to find the desired API with reasonable ease, even when using specific terms or phrases:
[FirstVision - LATAM - Account - Monetary Inquire] (https://developer.fiserv.com/product/FirstVisionLATAM/api/?type=post&path=/account/v1/falconMonetaryInquiry&branch=preview&version=1.2.0)

### Operating system

Windows 10 Enterprise

### Browser

Microsoft Edge for Business Version 116.0.1938.62 (Official build) (64-bit)

### Region

Brasil

**Comment by mohamed-jammal** [comment]
![image](https://github.com/Fiserv/Support/assets/143200886/0005588b-37ba-42d6-878f-7613f52a7706)
![image](https://github.com/Fiserv/Support/assets/143200886/a1dd0eaa-efad-4dab-ae35-973b962cb129)

**Comment by sfiserv** [comment]
Tracking this issue in 
https://firstdatateam.atlassian.net/browse/PORT-8218

Once our team verify the issue and prioritize it per our workload

**Comment by OZ-FS** [comment]
Tested the issue in production:

<img width="1155" alt="Screenshot 2023-11-06 at 3 31 52 PM" src="https://github.com/Fiserv/Support/assets/92183615/fc40e3cb-4c77-4ae8-900b-640f37d02502">
<img width="936" alt="Screenshot 2023-11-06 at 3 34 12 PM" src="https://github.com/Fiserv/Support/assets/92183615/22ffd0d1-084b-4b85-8909-11dbea3d4490">

**Comment by OZ-FS** [comment]
the following fields are used in the search:

<img width="195" alt="Screenshot 2023-11-06 at 3 44 41 PM" src="https://github.com/Fiserv/Support/assets/92183615/3a6159b9-ccdd-4bd9-a265-bbcae965886f">

The search-ability of the API can be increased by adding tags:

<img width="810" alt="Screenshot 2023-11-06 at 3 38 43 PM" src="https://github.com/Fiserv/Support/assets/92183615/60b1b3d7-3525-44f8-878a-72dbaccd6ad0">
<img width="724" alt="Screenshot 2023-11-06 at 3 44 06 PM" src="https://github.com/Fiserv/Support/assets/92183615/3b09578b-25b8-469b-8541-66e2c0dba3c2">

**Comment by OZ-FS** [comment]
@mohamed-jammal please comment if that is sufficient

**Comment by OZ-FS** [comment]
search for **M.CMS.ACCTEMB.AUTHCRIT.UPD**

<img width="1087" alt="Screenshot 2023-11-07 at 3 01 19 PM" src="https://github.com/Fiserv/Support/assets/92183615/9fd0a8b1-e0b8-403b-b371-edcfdc01dfb7">

**Comment by OZ-FS** [comment]
search for **M.CMS.BALANCE.INQ**

<img width="1069" alt="Screenshot 2023-11-07 at 3 03 55 PM" src="https://github.com/Fiserv/Support/assets/92183615/c3b8de14-c890-4d68-b1ca-c5485b353dbe">

**Comment by OZ-FS** [comment]
Closing this issue as already fixed, working as expected.
