### ISSUE TITLE
Create new "Software Vendors" Solution Category for CardPointe and Fiserv ISV Products

### ISSUE THREAD

**Issue by KGroninger** [Fiserv/Support#486]
### Product

CardPointe

### Page

Home

### Description

As previously discussed with @acho-fiserv, the CardPointe product team requires a new Solution Category to position the specific integrations and documentation for our Integrated Software Vendor (ISV) Partner Program. These solutions are intended only for our software vendor partners and should be kept separate from similar Merchant and Enterprise offerings.

A clickable prototype of this proposed solution can be found here: [https://www.figma.com/proto/dDrA6Bo7FEKb8mA2mubdtM/Fiserv-Dev-Studio?node-id=1-2&scaling=scale-down&page-id=0%3A1&starting-point-node-id=1%3A2&t=bNiKAy8wmNJzIvTi-1](here).

Alternatively, this new Solution Category could be titles "Partners," with Software Vendors as the subordinate category, leaving room for other Partner types in the future, similarly to merchants.fiserv.com.

### Expected Behaviour

The Software Vendors solution category exists in the Developer Studio site navigation at the same level as "Merchants" and "Financial Institutions."

### Operating system

N/A

### Browser

N/A

**Comment by KGroninger** [comment]
@sfiserv, can we have an update on this request, or do you want to meet to discuss further?

**Comment by sfiserv** [comment]
Tracking this issue in https://firstdatateam.atlassian.net/browse/PORT-8219
Team need to have a discussion on this requirement.
