### ISSUE TITLE
Left-side navigation pane

### ISSUE THREAD

**Issue by fiservakshay** [Fiserv/Support#49]
# Reporting new issue for [NAME] (Tenant/Product)

**Page**
All pages of Open Banking

**Describe the bug**
Left-side navigation pane is visible on only 70% (approx.) of screen height. It should be visible on 100% of screen height.
**To Reproduce**
1. Click **Fanatical Institutions** tab

**Expected behavior**
Left-side navigation pane should be visible on 100% of screen height.
**Screenshots**
![image](https://user-images.githubusercontent.com/81968767/138654137-009ce4d1-56f5-4e65-9c22-0735047b7690.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 95.0.4638.54

**Tablet (please complete the following information):**
 n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by acho-fiserv** [comment]
Thanks @fiservakshay .  This is now fixed in the latest dev build.

**Comment by fiservakshay** [comment]
Thank you for fixing this issue!
