### ISSUE TITLE
Available features in Developer Studio "Learn more" links are not links

### ISSUE THREAD

**Issue by elibyrd** [Fiserv/Support#50]
# Reporting new issue for Developer Studio website

**Page**

- https://developer.fiserv.com/product/CommerceHub
- https://developer.fiserv.com/product/Reporting

**Describe the bug**
On the Merchants > Commerce Hub/Reporting pages, there is a "Available features in Developer Studio" heading. The cards under this heading each have a "Learn more" element that is styled like a link; however, these elements are not links and aren't interactable in any way.

**To Reproduce**
1. From the home page, click on the "Merchants" link in the main navigation.
2. In the left hand sidebar, click on "Commerce Hub" or "Reporting"
3. Scroll down to "Available features in Developer Studio"
4. On any of the cards under this heading, attempt to click on the "Learn more" element. Observe that clicking the element does not cause any new behavior.
5. Using developer tools, it is possible to observe that the element is not a link.

**Expected behavior**
The "Learn more" element should be a link that navigates the user to a page with more information on the selected card.

**Screenshots**
<img width="945" alt="dev studo learn more" src="https://user-images.githubusercontent.com/8714791/138723190-135a11e4-5303-4037-9a52-0c70704ee2bf.PNG">

**Desktop:**
 - Windows 10
 - Chrome
 - Version 95.0.4638.54 (Official Build) (64-bit)

**Tablet:**
 - Not tested

**Smartphone:**
 - Device: Google Pixel 5
 - OS: Android 11
 - Browser Chrome (stock)
 - Version 95.0.4638.50

**Additional context**
No console errors were visible after replicating this bug on Desktop.

**Comment by acho-fiserv** [comment]
we can close this since that feature has been disabled & will be reworked.
