### ISSUE TITLE
Preview Issue (White Screen)

### ISSUE THREAD

**Issue by wwfiserv** [Fiserv/Support#512]
### Product

Commerce Hub

### Page

All

### Description

When accessing a linked pages in the left navigation or documentation it intermittently doesn't load and only gives a white screen.

Example going to In-Person and clicking on Tap to Pay on iPhone Learn More link or clicking Tap to Pay on iPhone in the left nav. Hitting refresh it appears to try to load before going to the white screen again.

![image](https://github.com/Fiserv/Support/assets/75692745/5857d553-978c-4e4f-9753-063d717ba247)

https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Getting-Started/Getting-Started-InPerson.md&branch=preview

https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/In-Person/Integrations/Tap-to-Pay.md&branch=preview

### Expected Behaviour

Page should load

### Operating system

Windows

### Browser

Chrome, Edge

### Region

All

**Comment by sfiserv** [comment]
Tracking this issue as part of a previously raised bug.
https://firstdatateam.atlassian.net/browse/PORT-7359

**Comment by minh-pham1** [comment]
Hi William! There are apparently various `U+200b` characters (invisible whitespace character) hidden inside this document that is being parsed as headers. When the page attempts to parse them and add them to the table of content, it's throwing an error and rendering a blank page.

**Comment by wwfiserv** [comment]
@minh-pham1 this is occurring in all preview documentation not just this one, this was just the one I could get a consistency with. 

When you say whitespace are you saying it's due to invalid markdown or something the rendering engine is doing? The markdown is the same in all environments yet the blank pages are only occurring in Preview.

**Comment by minh-pham1** [comment]
Are the documents the same file just being pushed to different branches or does your team create the `develop` branch document then copy paste it into a new file on the `preview` branch? There just might be a zero width space that gets copied that comes from github somehow (this is just my theory, I'm not 100% sure why yet either).

Could you try to copy paste the markdown for `Tap-to-Pay.md` into a text editor that can remove all hidden characters and formatting (on Windows I use Notepad but then again, it might still be there) then paste it back onto the Github? At least according to this website (https://www.dcode.fr/zero-width-space) the preview version of the Tap-to-pay document somehow has 20 zero width spaces.

**Comment by minh-pham1** [comment]
Well for now, we have added if statement to filter out those zero-width spaces which should handle the majority of the issues. If they show up inside of other headers, I _think_ it should be ok, though we can keep tabs on it. But according to your development process, it shouldn't be an issue in the future hopefully.

The fix will be on Devstudio's QA environment next sprint. Please keep me updated if you happen to find another document that has this issue afterwards. We do have some document validation automation testing on our end too so perhaps that will also catch it.

**Comment by minh-pham1** [comment]
The fix is now on QA environment. Please let me know if you see any other issues about this ticket!

**Comment by wwfiserv** [comment]
Everything appears to be loading correctly.
