### ISSUE TITLE
Alphabetical Order in Left Nav

### ISSUE THREAD

**Issue by tsegurajimen** [Fiserv/Support#513]
### Product

Banking Hub

### Page

https://developer.fiserv.com/product/BankingHub?branch=main

### Description

Hi @sfiserv and Team,

We need your help because how APIs are sorted in the API Explorer Left Side Nav is not following the alphabetical order it used to follow, now they are displayed randomly with any specific order inside or each domain category.

![image](https://github.com/Fiserv/Support/assets/81706748/4896fd16-fd0e-4796-bd59-b3caf98fc7b0)

Thanks in advance!

### Expected Behaviour

APIs under API Explorer should follow alphabetical order.

### Operating system

Microsoft 64-bit operating system, x64-based processor

### Browser

Google Crome

**Comment by minh-pham1** [comment]
Hello @tsegurajimen!

The issue has been fixed on our dev environment. The issue with the sorting should be resolved in about 2 weeks, I'll be sure to update this ticket when it reaches QA environment where you can validate it.

Just some minor notes about issues that I found while cross-checking our data with your Github repository:
- In your `product-layout.yaml`, I noticed that you listed multiple documents under each `featuredFeatures.relatedDocs`. For the current moment, we only support **one** doc link for each of the Featured offerings card (which can be accessed when the user clicks the `Read documentation` button on the card on DevStudio). As such, we'll only read the first link you provide under `relatedDocs` for the `Read documentation` button. I just noticed that all of the offerings lead to Getting started (which might be the intended link, just wanted to mention it just in case).
- Under [Accounts/Reinvestment-Service](https://github.com/Fiserv/banking-hub/blob/develop/reference/11.0.0/Accounts/Reinvestment-Service-11.0.0_SIG.yaml), I noticed that various `x-proxy-name` are defined with an empty space at the start of the string (which may mess with the alphabetical ordering, both in the API explorer left nav and potentially on the Catalog page). Please fix those if possible.

Please let me know if you have any questions, thank you!

**Comment by sfiserv** [comment]
Please verify this issue is fixed. The issue should be available be in  QA to be verified.

**Comment by sfiserv** [comment]
Closing this issue as no issues reported on this fix.
