### ISSUE TITLE
Commerce Hub iFrame Integration Issue

### ISSUE THREAD

**Issue by yalahyane** [Fiserv/Support#517]
Hello,

I'm following the example here:  https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Online-Mobile-Digital/Secure-Data-Capture/iFrame-JS/iFrame-Request.md&branch=main to integrate with CommerceHub using iFrame.
The iFrame is showing, but when I enter a card and hit 'Pay', the 'Next' object in the snippet below returns undefined. Please note that I see in the console that the capture was successful. I just need a way to capture the result form the js after form submission.

form.loadPaymentForm("payment-saq-a-ep-form-div")
                .then((next) => {})
                .catch((error) => {});

**Comment by wwfiserv** [comment]
@yalahyane thank you for your inquiry, I have contacted our Dev teams to inquire about the response. I would also like to verify what client you are working with, as CH is for high volume Enterprise clients and may not be the product you need to integrate with.

**Comment by wwfiserv** [comment]
@yalahyane you would want to integrate with our JS or API solutions as the iFrame is hosted and generated by us there is no way to customize it.
