### ISSUE TITLE
Onboard a new tenant

### ISSUE THREAD

**Issue by PalanikumarAthinamilagi** [Fiserv/Support#518]
### Name of your product / tenant

Transfer Now

### Type of Tenant

- [X] Full service
- [ ] Doc only
- [ ] Link out

### Team Members

karthika.karunakaran,praveenkumarmurugesan,gokulanandraju,girijasardevi,nithyaselvansrikanth,palanikumarathinamilagi,veerahanumasuryakirangopisetty,allaiammalarjunan

### Bug Reporting

karthikakarunakaran,palanikumarathinamilagi,veerahanumasuryakirangopisetty,allaiammalarjunan

### Feedback Reporting

karthikakarunakaran,palanikumarathinamilagi,veerahanumasuryakirangopisetty

### Enhancement Reporting

karthikakarunakaran,palanikumarathinamilagi,veerahanumasuryakirangopisetty

### Internal tenant

No

### Product of Carat

No

### Merchants solution area

No

### Customer Segments for Merchants

- [ ] SMB
- [ ] Enterprise

### Financial Institutions solution area

Yes

### Customer Segments for Financial Instituitions

- [X] Bank
- [X] Credit Union
- [X] Large Financial Institution

### Fintech solution area

Yes

### Region of Operation

- [X] North America
- [ ] EMEA
- [ ] LATAM
- [ ] APAC

### RESTful

Yes

### SDK

Yes

### Industry

Banking and Financial Institutions

### Runbox

Yes

### Mock Sandbox

No

### Live Server

Yes

**Comment by sfiserv** [comment]
@PalanikumarAthinamilagi  Please update the on boarding form for the below changes.
Choose only one service type for your product.
It can be Full tenant (docs and APis) or Document only. Linkout tenant is a product who already has their Portal and user needs to be redirected to that external url.
Also you can have only one Server either Mock or Live.

Please make these changes to the form so that we prioritize the on boarding process in our upcoming sprint.

**Comment by sfiserv** [comment]
Tracking this issue in our jira board https://firstdatateam.atlassian.net/browse/PORT-7821

**Comment by PalanikumarAthinamilagi** [comment]
Updated above comment

**Comment by sfiserv** [comment]
Thanks. @PalanikumarAthinamilagi  we will priortize this sprint.

**Comment by sfiserv** [comment]
@PalanikumarAthinamilagi  your product is now ready to be verified on the QA env. Please verify and close the ticket if there are no issues.

**Comment by sfiserv** [comment]
Closing this ticket considering it as done.
