### ISSUE TITLE
 Wrong rendering of parameter field information

### ISSUE THREAD

**Issue by LucasOliveiraJacintho** [Fiserv/Support#519]
Developer Studios has a bug to render information from Parameter fields, below I describe the steps used for this statement:

Some services showed the same behavior, in this case I will use this service: 

[https://developer.fiserv.com/product/FirstVisionLATAM/api/?type=get&path=/customer/v1/cards&branch=main&version=1.2.0](url)

opening the link we can see the below result, the description and properties of the fields are without format.

![image](https://github.com/Fiserv/Support/assets/145802160/06567ba8-12bb-42f8-a2c6-4efde53d43d7)

Below a small part of code was selected, where we see that the document have the tag responsible to ending and skipping a line ( \n ), but above we can see that the Developer Studio isn't respecting it.

            `@Parameter(description = "* Min Length: 1\n" +
                    "* Max Length: 3\n" +
                    "\n" +
                    "Identification number of the organization associated with the account.\n" +
                    "\n" +
                    "VisionPLUS Service Data: AZXBQI-ORG", required = true, example = "998")
            @RequestHeader(value = "organizationNumber")
            @Range(min = 1, max = 999, message = "organizationNumber must be between 1 and 999")
            @NotNull(message = "organizationNumber may not be null.")
            Integer organizationNumber,

            @Parameter(description = "* Min Length: 19\n" +
                    "* Max Length: 19\n" +
                    "\n" +
                    "Customer number that identifies the customer record to which this account is assigned.\n\n" +
                    "A valid customer name and address must be on file for this account.\n" +
                    "\n" +
                    "The value must be filled with leading zeros so the length is equal to 19.\n" +
                    "\n" +
                    "VisionPLUS Service Data: AZXBQI-CUST-NBR", example = "000001234XXXXX56789", required = true)
            @RequestHeader(name = "customerNumber")
            @Size(min = 19, max = 19, message = "customerNumber must be 19 characters in length")
            @NotNull(message = "customerNumber may not be null.")
            String customerNumber,`

It is a small part of code was obtained from the VisionPlus Project in the API-Customer for the VMX Service M.CMS.CUST.NBR.INQ, L8V1, https://escmstash.1dc.com/projects/LAA/repos/visionplus-apis/browse

As a way of confirming that the code was written correctly, a yml file was generate for this application and the result was opened on Swagger editor, below is the result:

![image](https://github.com/Fiserv/Support/assets/145802160/87a4f319-b24d-450f-84aa-abe9d9a7c1f7)

In Swagger Editor the information (description and  properties) are rendered correctly.

**Comment by sfiserv** [comment]
@OZ-FS can you please look into this issue.

**Comment by OZ-FS** [comment]
Parameter description is placed in paragraph <p> tag where /n new lines are ignored, you might consider using <br> instead.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/br
<img width="893" alt="Screenshot 2023-09-26 at 9 52 04 PM" src="https://github.com/Fiserv/Support/assets/92183615/39833510-869e-45f0-8b67-d6328393f836">

For examples to show, **exaple:** has to be under **schema:**

**Comment by sfiserv** [comment]
@LucasOliveiraJacintho  were you able to work with the suggestions provided by our team member. 
If yes please close this ticket.

**Comment by sfiserv** [comment]
Closing this ticket since no comments/response from reporter.
