### ISSUE TITLE
Can't set a password

### ISSUE THREAD

**Issue by max-m-s** [Fiserv/Support#520]
### Page

https://developer.fiserv.com/

### Description

Can't set a password for a new account:
"Something went wrong, please try again"

### Expected Behaviour

New password is accepted and login completes

### Operating system

Windows 10

### Browser

Chrome

**Comment by sfiserv** [comment]
@max-m-s  are you still seeing this issue. Can you please send out the email you are using to login.
Please let us know.Sometimes there might be a lag from PingID.
