### ISSUE TITLE
Specification Portal Phase 1 Bugs

### ISSUE THREAD

**Issue by kcaramat** [Fiserv/Support#522]
### Product

Specification Portal

### Page

Specification Portal

### Description

Specification Portal Phase 1 Bugs:
1. When logging in, can’t access documentation initially. Need to refresh for docs to show.
2. Subscribed to Equinox page. Made an update to the Markdown Page and received the email notification but it referenced the GitHub path versus the page name.
3. Enabled doc notifications for P2PE_v2_PIM_Equinox_Luxe_85xx-RSA_v1.0.pdf. Made an update to the doc and received the email notification but it referenced the GitHub path versus the doc name.
4. 404 error received sporadically. Error goes away after refreshing or waiting a few minutes. 

### Expected Behaviour

Specification Portal Phase 1 Bugs:
1. When logging in, can’t access documentation initially. Need to refresh for docs to show.
2. Subscribed to Equinox page. Made an update to the Markdown Page and received the email notification but it referenced the GitHub path versus the page name.
3. Enabled doc notifications for P2PE_v2_PIM_Equinox_Luxe_85xx-RSA_v1.0.pdf. Made an update to the doc and received the email notification but it referenced the GitHub path versus the doc name.
4. 404 error received sporadically. Error goes away after refreshing or waiting a few minutes. 

### Operating system

N/A

### Browser

Google Chrome

**Comment by sfiserv** [comment]
Tracking ticket https://firstdatateam.atlassian.net/browse/PORT-7994

**Comment by kcaramat** [comment]
Reported issues have been resolved.
