### ISSUE TITLE
Specification Portal Bugs - Phase 2

### ISSUE THREAD

**Issue by kcaramat** [Fiserv/Support#523]
### Product

Specification Portal

### Page

Specification Portal

### Description

Phase 2 – Entitled Documents
1. Entitled docs should populate associated Product Name when requesting access.
2. When an elite doc access request is denied, brings me to a blank Dev Studio page.
3. User doesn’t receive an email when the request is denied.
4. When an elite doc access request is approved, brings me to a Dev Studio page that shows Status Pending Latest action Invalid Date. 
5. User doesn’t receive an email when the request is approved.
6. Still unable to access doc (Global_SingleMID_PFAC_File_Structure_v3.1.pdf) when the request is approved.
7. Approval / Deny Email - should mention file name as the Document Name and not the path.
8. Missing studio notification functionality for the entire flow.

### Expected Behaviour

Phase 2 – Entitled Documents
1. Entitled docs should populate associated Product Name when requesting access.
2. When an elite doc access request is denied, brings me to a blank Dev Studio page.
3. User doesn’t receive an email when the request is denied.
4. When an elite doc access request is approved, brings me to a Dev Studio page that shows Status Pending Latest action Invalid Date. 
5. User doesn’t receive an email when the request is approved.
6. Still unable to access doc (Global_SingleMID_PFAC_File_Structure_v3.1.pdf) when the request is approved.
7. Approval / Deny Email - should mention file name as the Document Name and not the path.
8. Missing studio notification functionality for the entire flow.

### Operating system

N/A

### Browser

Google Chrome

**Comment by sfiserv** [comment]
tracking these issue in https://firstdatateam.atlassian.net/browse/PORT-7995

**Comment by kcaramat** [comment]
Reported items have been resolved.
