### ISSUE TITLE
Example not showing correctly 

### ISSUE THREAD

**Issue by AnabelCristinaMoreira** [Fiserv/Support#524]
### Product

FirstVision LATAM

### Page

[Account Demographic Inquiry](https://developer.fiserv.com/product/FirstVisionLATAM/api/?type=post&path=/account/account-demographic&branch=main&version=1.2.0)
[Amount Against Rule Levels Validate](https://developer.fiserv.com/product/FirstVisionLATAM/api/?type=post&path=/account/organizationNumber/level-limits/validate-amount&branch=main&version=1.2.0)

### Description

When the field is integer type the example is not showing right.
![image](https://github.com/Fiserv/Support/assets/139910463/88711a8c-518d-4175-a272-0fdf18f26ec8)

This behavior should be fixed according to this old ticket: https://statics.teams.cdn.office.net/evergreen-assets/safelinks/1/atp-safelinks.html

Here we have a counter example: https://developer.fiserv.com/product/FirstVisionLATAM/api/?type=put&path=/customer/&branch=main&version=1.2.0
The field is integer and the example is being shown correctly:
<img width="347" alt="image" src="https://github.com/Fiserv/Support/assets/139910463/3b9e37e0-ab64-4003-a7b3-f81213cbc755">

### Expected Behaviour

Show "example: 0" as when the field type is a string:
![image](https://github.com/Fiserv/Support/assets/139910463/c001df89-3388-489c-8c59-155300e97cc0)

### Operating system

Windows

### Browser

Google Chrome

**Comment by minh-pham1** [comment]
Hello Anabel, could you fill out the sections for `Product` with your product name (such as `FirstVision LATAM`) and `Page` with the URLs (multiple examples if possible) of the API you're reporting the bug for?

**Comment by AnabelCristinaMoreira** [comment]
Sorry, done now. I also added a counter example.

**Comment by minh-pham1** [comment]
Sounds good, I found the issue and will push the fix to our dev environment for testing. Will let you know when it can be validated on QA environment (should be there in 2 weeks from now in case I somehow forget to update). Thanks for your help!

**Comment by minh-pham1** [comment]
Hello! I was trying to validate this but I couldn't find this field/example anymore. We did deploy to qa environment so it shouldn't be an issue anymore but if you happen to find another API with a similar issue on production, the same example should be fixed on qa environment. Please let me know if this is still broken anywhere!

**Comment by AnabelCristinaMoreira** [comment]
Hello!
I validated here and it looks like it is fixed!
In prod: 
![image](https://github.com/Fiserv/Support/assets/139910463/fdec8504-b5b1-4f53-a082-eeaa0d18171d)
In QA:
![image](https://github.com/Fiserv/Support/assets/139910463/9a10b1a5-afd1-40f6-bcde-3c4c051a3d78)

The endpoint is the [Fee Table Information Inquiry](https://developer.fiserv.com/product/FirstVisionLATAM/api/?type=get&path=/transactions/{feeTableNumber}/fee-table-information&branch=main&version=1.2.0).

Thank you for your help!
