### ISSUE TITLE
Identifire to highlight new changes

### ISSUE THREAD

**Issue by fiservakshay** [Fiserv/Support#526]
Hi Team,

Can we have a feature to highlight newly added sections in left navigation pane of Dev Studio?

For example, if we introduce a new navigation item under Documentation section a tag, say "New" should get added next to it. See reference screenshot below:
![image](https://github.com/Fiserv/Support/assets/81968767/229483f4-c274-4fb3-8824-dc6aa290d90f)

Once enabled the tag should stay activated for defined time frame (say 1 week) and after that auto disable.

This feature will improve visibility of any newly added documentation sections to end users and improve content consumption accordingly.

**Comment by fiservakshay** [comment]
Hi @sfiserv @TaniaS-fiserv 
Request you to please share your comment on above feature request for Dev Studio feasibility.

**Comment by sfiserv** [comment]
@fiservakshay Our team will review this ask in the upcoming planning. Updates regarding this will be posted in this ticket.
