### ISSUE TITLE
Update "Provider" text and dropdown styling

### ISSUE THREAD

**Issue by fiservakshay** [Fiserv/Support#527]
Hi Team,

We have received a feedback from lot of clients that they are missing to see this Provider dropdown under API documentation.
 
![image](https://github.com/Fiserv/Support/assets/81968767/b9690f7d-d26c-49bd-b13a-8af78899e14e)

In order to overcome this issue please apply the following changes:

- The font for 'Provider' dropdown be bold and/or match the text on the page, and the size needs to align as well.
- The value from the dropdown once selected should show in Orange, since its a Fiserv product
- Increase the width of the dropdown to accommodate at least 25 characters

CC: @RahulRavindra

**Comment by sfiserv** [comment]
@fiservakshay please check this is fixed and imlemented
<img width="290" alt="image" src="https://github.com/Fiserv/Support/assets/87097017/58d499f0-005f-4884-823e-043106acc743">
