### ISSUE TITLE
Magento 2 Extension for Commerce Hub Integration

### ISSUE THREAD

**Issue by hemant2586** [Fiserv/Support#528]
I need a Magento 2 module to integrate Commerce Hub with adobe commerce Magento 2 setup. Can you please help if you have a module already available or any third party who can provide it.

**Comment by wwfiserv** [comment]
This module is currently in development, I will verify with the Dev team on when it will be available for download. Once done the documentation will be updated accordingly. Also to make sure you are using the correct Fiserv gateway what client/merchant are you working with as Commerce Hub is designed specifically for Enterprise or high volume/dollar merchants.

**Comment by Laura021** [comment]
Hello! 
Any updates here?
Thanks!
