### ISSUE TITLE
Change CardPointe Tenant Product Name

### ISSUE THREAD

**Issue by KGroninger** [Fiserv/Support#529]
### Product

CardPointe

### Page

Home

### Description

Can we please rename our product name from CardPointe to CardPointe Integrated Payments? The URL should remain as CardPointe.

When I attempted to change the name in our tenant.json file, all of our documentation URLs became broken.

<img width="1428" alt="2023-10-06_11-04-30" src="https://github.com/Fiserv/Support/assets/129098650/0f1aae8c-72e6-4940-acc6-5a1563193cff">

### Expected Behaviour

Product display name is changed from CardPointe to CardPointe Integrated Payments

### Operating system

N/A

### Browser

N/A

**Comment by sfiserv** [comment]
@KGroninger  Product name change is a db change from Devstudio side and not from github.
We can use this ticket for as a requirement change ticket and prioritize this in the upcoming sprint.

**Comment by sfiserv** [comment]
trackin  this requirement in https://firstdatateam.atlassian.net/browse/PORT-8217

**Comment by sfiserv** [comment]
We have made the change in the QA enviornment. Closing this ticket as no issues were reported till now.
@KGroninger please let us know if you have any issues regarding this implementation
