### ISSUE TITLE
<TITLE> [TX ID: undefined]

### ISSUE THREAD

**Issue by TLeeBennett** [Fiserv/Support#532]
### Product

Forgot Password - one time code 

### Page

Login In Pop UP > Reset Password > receive one time pass code

### Description

Unable to process request
We are experiencing technical difficulties and hope to have them resolved soon. Please try again later.

### Expected Behaviour

I'm able to receive a one time passcode to login. 

### Operating system

Windows 10 Enterprise

### Browser

Version 118.0.5993.71 (Official Build) (64-bit)

**Comment by sfiserv** [comment]
@TLeeBennett are facing this issue on the Production environment.
The OTP for the password is sent out by Ping. Sometimes there is a lag to send out the OTP.
Please try out after sometime and let us know if yo u are still facing the problem.

**Comment by TLeeBennett** [comment]
I just tried it again and got the same error.

***@***.***


***@***.***

***@***.***
Trisha Lee Bennett (she/her) | AVP Enterprise Applications & PMO
Bay Federal Credit Union | ***@***.******@***.***> | d: 831.477.8412 | c: 408.835.4287

***@***.***<https://www.bayfed.com/money-market-advantage>

**Comment by sfiserv** [comment]
Just to confirm you are reporting this issue for Developer Studio https://developer.fiserv.com/

**Comment by sfiserv** [comment]
Since there is no response from the reporter of this issue, closing this ticket.
