### ISSUE TITLE
Get Document List (DocumentListInqOperAsync) - DocType not returning

### ISSUE THREAD

**Issue by Mohammad-BakerHill** [Fiserv/Support#533]
### Product

Banking Hub

### Page

Home -> Financial Institutions -> Banking Hub -> Get Document List

### Description

We are trying to get the Document Type Id using Get Document (DocumentListInqOperAsync) API with the endpoint “https://esfms-test.fiservapps.com/btat2/v9”, but the DocType field is always returning zero.  The API documentation states it should be populated with a value that comes from the imaging system.  In order to allow a client to import documents from the imaging system to ours, we need to know what the document type is in the imaging system.  
 
What is stopping the DocumentListInq request from returning what should be currently stored on the imaging system (the known unique document type).

![image](https://github.com/Fiserv/Support/assets/148146124/d0ec0e8b-398c-497c-8de1-51f6fc7f9c13)

### Expected Behaviour

DocType field returning value.

### Operating system

Windows

### Browser

Edge

**Comment by sfiserv** [comment]
no response from the BH team. hence closing this issue.
