### ISSUE TITLE
Deployment to production environment for Silvercore product  [Silvercore] [Stage & Prod]

### ISSUE THREAD

**Issue by FranciscoCampos09** [Fiserv/Support#537]
After the validation of the Silvercore product in the QA environment and it was found that it is already working stably, its first release to the productive environment is requested.

**Comment by sfiserv** [comment]
IN order to promote your product to higher environment, we need a github request for the same.
Closing this issue since the download postman is working as expected.

**Comment by FranciscoCampos09** [comment]
Ok, what's the process for generating the github request.

**Comment by sfiserv** [comment]
Sorry

**Comment by sfiserv** [comment]
the product is enabled in Prod. This was already communicated to the tenant and they had verified it.
<img width="800" alt="image" src="https://github.com/Fiserv/Support/assets/87097017/8b8863a3-dc48-4060-beb4-3690650b2ef1">
hence closing this issue.
