### ISSUE TITLE
Onboard a new tenant [Fraud Mitigation]

### ISSUE THREAD

**Issue by kongaravinatha** [Fiserv/Support#539]
### Name of your product / tenant

Fraud Mitigation

### Type of Tenant

- [X] Full service
- [ ] Doc only
- [ ] Link out

### Team Members

vinatha.kongara@fiserv.com , gary.byfield@fiserv.com

### Bug Reporting

gary.byfield@fiserv.com,vinatha.kongara@fiserv.com

### Feedback Reporting

gary.byfield@fiserv.com,vinatha.kongara@fiserv.com

### Enhancement Reporting

gary.byfield@fiserv.com,vinatha.kongara@fiserv.com

### Internal tenant

Yes

### Product of Carat

No

### Merchants solution area

Yes

### Customer Segments for Merchants

- [X] SMB
- [X] Enterprise

### Financial Institutions solution area

No

### Customer Segments for Financial Instituitions

- [ ] Bank
- [ ] Credit Union
- [ ] Large Financial Institution

### Fintech solution area

No

### Region of Operation

- [X] North America
- [ ] EMEA
- [ ] LATAM
- [ ] APAC

### RESTful

Yes

### SDK

Yes

### Runbox

Yes

### Mock Sandbox

No

### Live Server

No

**Comment by minh-pham1** [comment]
Hello @kongaravinatha!

Just one additional question while I work on onboarding you into our database. We have set of product tags called `Features` which will show up along with similar tags like `Region`, `Customer Segment`, etc.

It is not on the current onboarding menu (since it's not enabled on our UI yet) but I was wondering if you would like to add them now. Here are the options:

- Cards
- Payments
- Data & Analytics
- Risk & Fraud
- Core Banking
- Business Finance
- Banking as a Service

**Comment by kongaravinatha** [comment]
Hi Gary,

What features does suit us for our application “Fraud-Mitigation” ?

•              Cards
•              Payments
•              Data & Analytics
•              Risk & Fraud
•              Core Banking
•              Business Finance
•              Banking as a Service

Thanks
Vinatha Kongara (Alpharetta)
+1 408 775 2088

From: Minh Pham ***@***.***>
Date: Wednesday, October 25, 2023 at 5:22 PM
To: Fiserv/Support ***@***.***>
Cc: Kongara, Vinatha (Alpharetta) ***@***.***>, Mention ***@***.***>
Subject: Re: [Fiserv/Support] Onboard a new tenant [Fraud Mitigation] (Issue #539)

  ⚠ EXTERNAL MESSAGE – Think Before You Click


Hello @kongaravinatha<https://urldefense.com/v3/__https:/github.com/kongaravinatha__;!!P9vvK-4S!iA9PXBUxHJYOaCqSHv64x2EbmdHK2YGTbBeM6oEEZX_-j8GR3ibWZWo9JB_GSAk00bb-WgOtBk-HPipxwEGrTBWHXiHRaw$>!

Just one additional question while I work on onboarding you into our database. We have set of product tags called Features which will show up along with similar tags like Region, Customer Segment, etc.

It is not on the current onboarding menu (since it's not enabled on our UI yet) but I was wondering if you would like to add them now. Here are the options:

  *   Cards
  *   Payments
  *   Data & Analytics
  *   Risk & Fraud
  *   Core Banking
  *   Business Finance
  *   Banking as a Service

**Comment by kongaravinatha** [comment]
Hi Minh Pham,

Pls include Risk & Fraud for our app [Fraud-Mitigation]

Thanks
Vinatha Kongara (Alpharetta)
+1 408 775 2088

From: Kongara, Vinatha (Alpharetta) ***@***.***>
Date: Wednesday, October 25, 2023 at 5:25 PM
To: Fiserv/Support ***@***.***>, Fiserv/Support ***@***.***>, Byfield, Gary (Alpharetta) ***@***.***>
Subject: Re: [Fiserv/Support] Onboard a new tenant [Fraud Mitigation] (Issue #539)
Hi Gary,

What features does suit us for our application “Fraud-Mitigation” ?

•              Cards
•              Payments
•              Data & Analytics
•              Risk & Fraud
•              Core Banking
•              Business Finance
•              Banking as a Service

Thanks
Vinatha Kongara (Alpharetta)
+1 408 775 2088

From: Minh Pham ***@***.***>
Date: Wednesday, October 25, 2023 at 5:22 PM
To: Fiserv/Support ***@***.***>
Cc: Kongara, Vinatha (Alpharetta) ***@***.***>, Mention ***@***.***>
Subject: Re: [Fiserv/Support] Onboard a new tenant [Fraud Mitigation] (Issue #539)

  ⚠ EXTERNAL MESSAGE – Think Before You Click


Hello @kongaravinatha<https://urldefense.com/v3/__https:/github.com/kongaravinatha__;!!P9vvK-4S!iA9PXBUxHJYOaCqSHv64x2EbmdHK2YGTbBeM6oEEZX_-j8GR3ibWZWo9JB_GSAk00bb-WgOtBk-HPipxwEGrTBWHXiHRaw$>!

Just one additional question while I work on onboarding you into our database. We have set of product tags called Features which will show up along with similar tags like Region, Customer Segment, etc.

It is not on the current onboarding menu (since it's not enabled on our UI yet) but I was wondering if you would like to add them now. Here are the options:

  *   Cards
  *   Payments
  *   Data & Analytics
  *   Risk & Fraud
  *   Core Banking
  *   Business Finance
  *   Banking as a Service

**Comment by kongaravinatha** [comment]
@minh-pham1 
RIsk and Fraud would suit to our application [Fraud-Mitigation]

**Comment by minh-pham1** [comment]
I noticed that you mentioned that you have a runbox for your APIs but both `Mock sandbox` and `Live server` are false. Are you planning on having your APIs just have mock responses setup or sent to your live server?

**Comment by kongaravinatha** [comment]
Hi Pham,

If I select Mock Sandbox and Live Server as True, then do you guys [Devstudio] gives the mock data without hitting our actual URL in the backend ?

Thanks
Vinatha Kongara (Alpharetta)
+1 408 775 2088

From: Minh Pham ***@***.***>
Date: Thursday, October 26, 2023 at 2:27 PM
To: Fiserv/Support ***@***.***>
Cc: Kongara, Vinatha (Alpharetta) ***@***.***>, Mention ***@***.***>
Subject: Re: [Fiserv/Support] Onboard a new tenant [Fraud Mitigation] (Issue #539)

  ⚠ EXTERNAL MESSAGE – Think Before You Click


I noticed that you mentioned that you have a runbox for your APIs but both Mock sandbox and Live server are false. Are you planning on having your APIs just have mock responses setup or sent to your live server?

**Comment by minh-pham1** [comment]
Hello! For API runbox, we offer 2 options:

- Mock server: In the API documentation yaml, you will have to define sections for different response codes (i.e. `200` would have its own sub-section with return messages and fields). When a customer/developer clicks the Run Request button on the runbox in DevStudio, we will just parse the data you defined on the yaml regardless of what headers and body content they "send" in the request.
- Live server: We send whatever the example request header+body has to your live API endpoint and gets a direct response. There are parameters in your `tenant-config.yaml` that allows you to enable/disable users from editing the request parameters.

You will need to pick one or the other. Please let me know which one suits your need!

**Comment by kongaravinatha** [comment]
++ Gary

Thanks
Vinatha Kongara (Alpharetta)
+1 408 775 2088

From: Minh Pham ***@***.***>
Date: Thursday, October 26, 2023 at 2:53 PM
To: Fiserv/Support ***@***.***>
Cc: Kongara, Vinatha (Alpharetta) ***@***.***>, Mention ***@***.***>
Subject: Re: [Fiserv/Support] Onboard a new tenant [Fraud Mitigation] (Issue #539)

  ⚠ EXTERNAL MESSAGE – Think Before You Click


Hello! For API runbox, we offer 2 options:

  *   Mock server: In the API documentation yaml, you will have to define sections for different response codes (i.e. 200 would have its own sub-section with return messages and fields). When a customer/developer clicks the Run Request button on the runbox in DevStudio, we will just parse the data you defined on the yaml regardless of what headers and body content they "send" in the request.
  *   Live server: We send whatever the example request header+body has to your live API endpoint and gets a direct response. There are parameters in your tenant-config.yaml that allows you to enable/disable users from editing the request parameters.

You will need to pick one or the other. Please let me know which one suits your need!

**Comment by kongaravinatha** [comment]
Hi Minh,

Can you enable Mock Server as true for our product [Fraud Mitigation]

Thanks
Vinatha Kongara (Alpharetta)
+1 408 775 2088

From: Kongara, Vinatha (Alpharetta) ***@***.***>
Date: Thursday, October 26, 2023 at 2:55 PM
To: Fiserv/Support ***@***.***>, Fiserv/Support ***@***.***>, Byfield, Gary (Alpharetta) ***@***.***>
Cc: Mention ***@***.***>
Subject: Re: [Fiserv/Support] Onboard a new tenant [Fraud Mitigation] (Issue #539)
++ Gary

Thanks
Vinatha Kongara (Alpharetta)
+1 408 775 2088

From: Minh Pham ***@***.***>
Date: Thursday, October 26, 2023 at 2:53 PM
To: Fiserv/Support ***@***.***>
Cc: Kongara, Vinatha (Alpharetta) ***@***.***>, Mention ***@***.***>
Subject: Re: [Fiserv/Support] Onboard a new tenant [Fraud Mitigation] (Issue #539)

  ⚠ EXTERNAL MESSAGE – Think Before You Click


Hello! For API runbox, we offer 2 options:

  *   Mock server: In the API documentation yaml, you will have to define sections for different response codes (i.e. 200 would have its own sub-section with return messages and fields). When a customer/developer clicks the Run Request button on the runbox in DevStudio, we will just parse the data you defined on the yaml regardless of what headers and body content they "send" in the request.
  *   Live server: We send whatever the example request header+body has to your live API endpoint and gets a direct response. There are parameters in your tenant-config.yaml that allows you to enable/disable users from editing the request parameters.

You will need to pick one or the other. Please let me know which one suits your need!

**Comment by minh-pham1** [comment]
Hello! I have finished the DB changes on `dev` environment and your product is live on our environment. However, the page is not loading due to various `tenant.json`  issues (namely, a few fields are still missing their values or have placeholders such as `<FraudMitigation>` and `<github-id>`). 

Please review the `tenant.json`, `product-layout.yaml`, and any other docs/apis you might want to test out. and your product will be live on QA environment to validate on 11/6 as aforementioned! Thank you!

**Comment by sfiserv** [comment]
@kongaravinatha  please verify the changes are in QA environment. The product is a internal tenant as per the requirement.
Please close the ticket if there no issues.
For further product enhancement you will have to raise a separate github request.
