### ISSUE TITLE
List item rendering issue

### ISSUE THREAD

**Issue by fiservakshay** [Fiserv/Support#54]
# Reporting new issue for BankSolutions/Cards

**Page**
Field description documentation section under API Explorer

**Describe the bug**
Content added as list items in SwaggerHub is not being rendered correctly on Dev Studio portal. The same content looks as expected in SwaggerHub output. 

I have used the standard MarkDown code to document list items under description tag. (Please check the attached screenshots)
> ### Note
>
> This issue is occuring only for the descriptions of the API methods, meaning - the content added under the "description:" tag of API method (POST, PUT, DELTE, etc.).

**To Reproduce**
n/a

**Expected behavior**
List items should display correctly

**Screenshots**

**SwaggerHub Code and Output:**

![image](https://user-images.githubusercontent.com/81968767/139579202-9f946740-6e09-452d-95ea-4d92bb5d0ed4.png)
Screenshot 1:

**Dev Studio Output for the same SwaggerHub code:**

![image](https://user-images.githubusercontent.com/81968767/139579733-85a2eb5d-4b66-47ca-87f1-74c5ed3a2f1e.png)
Screenshot 2:

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: latest version

**Tablet (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by tsegurajimen** [comment]
Workaround implemented from our side to handle it.
