### ISSUE TITLE
Unable to fork the repo [Fraud-Mitigation] into my Github Account 

### ISSUE THREAD

**Issue by kongaravinatha** [Fiserv/Support#540]
### Context

pls enable to fork the repo [Fraud-Mitigation]
<img width="488" alt="image" src="https://github.com/Fiserv/Support/assets/84332702/76424de8-b933-4885-b6e5-9d92cc1db97a">

### Solution

Enable the permission to fork the repo [Fraud-Mitigation]

### Alternatives

I don't see any alternative.

**Comment by sfiserv** [comment]
@kongaravinatha I am closing this ticket since your issue is resolved and you are able to progress with your work on the repo.
