### ISSUE TITLE
Error that indicates preparation failed.

### ISSUE THREAD

**Issue by parasjoshisit** [Fiserv/Support#541]
### Product

Commerce Hub

### Page

iOS SDK API

### Description

Hi,

Getting error Error that indicates preparation failed. when calling the method **activateReader**.

What should I do next to make it work?

Thank you

### Expected Behaviour

It should activate the reader and I can go to make the transaction. 

### Operating system

iOS 17.0

### Browser

NA

### Region

India

**Comment by wwfiserv** [comment]
@parasjoshisit I have contacted our dev team to help determine the cause of the issues. To better assist you can you please provide the environment and client you are creating the integration for.

**Comment by wwfiserv** [comment]
@parasjoshisit our dev team came back and informed that there is no method ‘activateReader()’. The read me has been updated to clarify this.

**Comment by parasjoshisit** [comment]
Hi William,

Here is the link of the SDK for the iOS I am using.

https://github.com/Fiserv/TTPPackage

I am getting error on this initializeSession() method with the latest package so I used that activateReader() method. Kindly guide me which one I have to use here and how.

try await self.fiservTTPCardReader.initializeSession()

Thank you
Paras Joshi
[https://opengraph.githubassets.com/e7dad8d01c65c32b989d6ddfd92d04351d77fcd85e456a8f7f2f10e9a88eff81/Fiserv/TTPPackage]<https://github.com/Fiserv/TTPPackage>
GitHub - Fiserv/TTPPackage: Fiserv Tap To Pay Package iOS<https://github.com/Fiserv/TTPPackage>
Fiserv Tap To Pay Package iOS. Contribute to Fiserv/TTPPackage development by creating an account on GitHub.
github.com




________________________________

**Comment by wwfiserv** [comment]
@parasjoshisit initialize is the correct method, the SDK should work as is with not modification. You can try the sample app that we have created. For more information on integrating with Commerce Hub you can review the documentation in Developer Studio https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/In-Person/Integrations/Tap-to-Pay.md&branch=main

**Comment by parasjoshisit** [comment]
We're getting the same error in the same code too. Also, we're testing the app in India but the application will actually be used in the USA.
________________________________
