### ISSUE TITLE
Dark Theme Enahncements

### ISSUE THREAD

**Issue by wwfiserv** [Fiserv/Support#544]
### Context

Currently the dark theme doesn't accurately reflect/display per most guidelines like Microsoft, Google, Apple, W3. We need to ensure a better user experience by following those guidelines, this includes color choices, adaptive images, etc.

### Solution

- Some of the colors for the dark theme should be changed to be more inline with industry standards (example the tags and callout boxes are too bright).
- Some code blocks and text are hard to read in the dark theme
- Images should switch between a light (white) version and a dark (black/grey) version based on theme selected.

### Alternatives

n/a

### Additional Context

example the callout boxes are too light for a proper dark mode, these should be a darker greyscale version of the colors![42893fe3-3b7d-4138-9f0f-cb71b40ae542](https://github.com/Fiserv/Support/assets/75692745/9b193d2a-dd38-48d3-96c3-ea46446a1d6b)

There is also issues with the code elements using the dark background inside of a callout box not looking as clean
![5c94cfe1-adbc-46ed-8953-0d7dab83c816](https://github.com/Fiserv/Support/assets/75692745/c98dd3f5-03d0-4cf5-9f31-17d754c73ab3)

Text element in Digital Disbursements
![image](https://github.com/Fiserv/Support/assets/75692745/60e06bfb-b5fd-411b-b380-fd5a004dd57d)

White image on dark theme
![image](https://github.com/Fiserv/Support/assets/75692745/70c13bbc-ae39-412b-9d69-29d4a6df3b0e)

Here are examples from FIS Global and Adyen
![730c598b-04c9-46cf-8060-99b21e00905a](https://github.com/Fiserv/Support/assets/75692745/457fdb9b-a745-4ca4-9704-18e514ab1c13)
![9ba415a5-97ed-4497-94d9-e84b62e5edfc](https://github.com/Fiserv/Support/assets/75692745/3d535372-aabb-4f58-8ee7-ed391075ca1a)

I found these a good read
- https://accessibility.digital.gov/visual-design/color-and-contrast/
- https://www.figma.com/community/plugin/733159460536249875/A11y---Color-Contrast-Checker
- https://learn.microsoft.com/en-us/windows/apps/design/style/color
- https://learn.microsoft.com/en-us/windows/apps/design/style/color
- https://developer.apple.com/design/human-interface-guidelines/macos/visual-design/dark-mode/
- https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/dark-mode
- https://bootcamp.uxdesign.cc/a-hands-on-guide-for-creating-a-dark-mode-for-your-software-application-16261d22c8dd
- https://material.io/design/color/dark-theme.html#usage
- https://css-tricks.com/a-complete-guide-to-dark-mode-on-the-web/
- https://material.io/design/color/dark-theme.html#usage

**Comment by sfiserv** [comment]
Tracking this issue as part of https://github.com/Fiserv/Support/issues/545

**Comment by sfiserv** [comment]
this issue should be fixed as updates to dark mode are made.
<img width="1072" alt="image" src="https://github.com/Fiserv/Support/assets/87097017/fd22d371-7c50-4aa9-80e7-c684ee7efd43">
please verify.
