### ISSUE TITLE
Dark Mode Text appearing inconsistently 

### ISSUE THREAD

**Issue by Darrickloftus** [Fiserv/Support#545]
### Product

Banking Hub

### Page

Workspace Summary Page 

### Description

See attached screenshot

![image](https://github.com/Fiserv/Support/assets/139264371/8545f0b0-cb9b-439b-aef7-02a0ef7f40ca)

### Expected Behaviour

I believe the text should appear all white except the "UPGRADE NOW" hyperlink text. I will continue looking through the page and update ticket with any other locations with this error 

### Operating system

Windows 10

### Browser

EDGE

**Comment by Darrickloftus** [comment]
![image](https://github.com/Fiserv/Support/assets/139264371/a3e34d7f-b3ea-41aa-b0e5-d850bfe139a0)
Additional example

**Comment by sfiserv** [comment]
https://firstdatateam.atlassian.net/browse/PORT-9024

**Comment by sfiserv** [comment]
This issue is fixed. please verify the issue.
<img width="1263" alt="image" src="https://github.com/Fiserv/Support/assets/87097017/0572f5f8-84e0-42db-9c77-45796e21ddab">
