### ISSUE TITLE
One time passcode is not working

### ISSUE THREAD

**Issue by joeldewitt** [Fiserv/Support#548]
### Product

developer studio

### Page

password reset

### Description

When I attempt to reset password I see the following:
Unable to process request
We are experiencing technical difficulties and hope to have them resolved soon. Please try again later.

If the problem persists, report us the issue or check the status on Github

### Expected Behaviour

get an email with a one time passcode

### Operating system

windows

### Browser

chrome

### Region

USA

**Comment by sfiserv** [comment]
@joeldewitt  can please clarify in which environment you are seeing this is issue (is it production?)
Are you still unable to reset the password?

**Comment by joeldewitt** [comment]
https://developer.fiserv.com/

![image](https://github.com/Fiserv/Support/assets/146852664/d42b5e12-c5a1-479f-84da-0f0c50157a68)

**Comment by sfiserv** [comment]
Thank you for the screenshot. Can you please also provide us the email you used to login/create account. 
Is there any information provided on clicking  the "Review Issue" button.

**Comment by joeldewitt** [comment]
It appears I had my email incorrect (tranposed I and N).  Once I used correct email address all was fine.  Sorry for the confusion.
