### ISSUE TITLE
Description of API not displaying on the Dev Studio Portal

### ISSUE THREAD

**Issue by fiservakshay** [Fiserv/Support#55]
# Reporting new issue for BankSolutions/Cards

**Page**
Field description documentation section under API Explorer.

**Describe the bug**
Description of an API added under the "info:" tag is not being rendered on the Dev studio portal.
This description describes the overview of an API service and should be displayed on the final documentation on Dev Studio portal.

**To Reproduce**
Click any API method from the API Explorer tab.

**Expected behavior**
The description added under the "info:" tag should be displayed on the portal.

**Screenshots**
![image](https://user-images.githubusercontent.com/81968767/139580447-19af4a1c-372c-4617-a8a5-a76029b943ec.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 
 - Version: latest

**Tablet (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by tsegurajimen** [comment]
This ticket is no longer needed***
