### ISSUE TITLE
We need Fraud Mitigation Product to be Exposed Externally not Internally

### ISSUE THREAD

**Issue by kongaravinatha** [Fiserv/Support#550]
### Context

For now the Fraud Mitigation is exposed internally, but we need it to be exposed Externally same like Reporting APIs. Fraud Mitigation Product should be exposed Externally and its not for Internal Purpose.

<img width="469" alt="image" src="https://github.com/Fiserv/Support/assets/84332702/f09c751e-1abd-4ff5-a4c4-4bfda0b3d7b3">

### Solution

Exposing it Externally is the solution.

### Alternatives

Please make Fraud Mitigation exposed Externally, Not internally.

**Comment by sfiserv** [comment]
https://firstdatateam.atlassian.net/browse/PORT-8746 
Tracking this issue in the above jira.

**Comment by sfiserv** [comment]
@kongaravinatha please verify the changes in QA env for Fraud Mitigation - external not internal 
![image](https://github.com/Fiserv/Support/assets/87097017/8940bced-5fed-4b34-845a-b140c7fd46ce)
