### ISSUE TITLE
Search & Catalog - Verify Now product is not listing under products Category

### ISSUE THREAD

**Issue by gokulfiserv** [Fiserv/Support#553]
### Product

Verify Now

### Page

https://qa-developerstudio.fiserv.com/catalog

### Description

While Searching “Verify Now” in Catalog and Search Option we could find only Transfer Now product whereas Verify Now product is not listing.

### Expected Behaviour

While searching with Verify Now Keyword in Search and Catalog option Verify Now product should be listed.

### Operating system

Windows

### Browser

Google Chrome Version 119.0.6045.107

### Region

https://qa-developerstudio.fiserv.com/catalog

**Comment by sfiserv** [comment]
our team is working on fixing this issue. We will update you once it is available in QA

**Comment by gokulfiserv** [comment]
The is been working fine
