### ISSUE TITLE
Search & Catalog - Transfer Now - Specification Portal product from Merchant segment is listed under Financial Institutions

### ISSUE THREAD

**Issue by gokulfiserv** [Fiserv/Support#554]
### Product

Transfer Now

### Page

https://qa-developerstudio.fiserv.com/catalog

### Description

While Searching with Transfer Now keyword in Search & Catalog, Specification portal product from Merchant Segment is also listing.

### Expected Behaviour

While searching with Transfer Now Keyword in Search and Catalog option Transfer Now product should alone be listed.

### Operating system

Windows

### Browser

Google Chrome Version 119.0.6045.107

### Region

https://qa-developerstudio.fiserv.com/catalog

**Comment by sfiserv** [comment]
@gokulfiserv  we have the fix in deve env. it will be available for your team once our QA deployment is completed which should be tomorrow eod.

**Comment by gokulfiserv** [comment]
The is been working fine

**Comment by sfiserv** [comment]
Closing this issue since this is working fine as per @gokulfiserv .
