### ISSUE TITLE
PRODUCTION PORTAL: 'Download API specifications' option is not downloading latest swagger files. 

### ISSUE THREAD

**Issue by tarunfiserv** [Fiserv/Support#556]
### Product

FirstVisionAPAC

### Page

Home -> Financial Institutions -> FirstVision - APAC -> Change PIN

### Description

Hi Team,

When we click on 'Download API specifications' link on the page and download the swagger files from the page, the downloaded zip does not have the latest swagger files.
![Production_Download_issue](https://github.com/Fiserv/Support/assets/100914278/48f438e5-43b2-4824-ada6-4436f92ad872)

### Expected Behaviour

The downloaded zip file should have all the swagger's versions or the latest swagger files which in this case is 1.5.0.

### Operating system

Windows 10

### Browser

Google Chrome 119.0.6045.159

### Region

Production

**Comment by sfiserv** [comment]
@tarunfiserv  our team is investigating this issue as why the zip generator workflow got skipped in your last commit made to Main branch.
However the main branch is locked from last week which might restrict us to make any changes to the workflow.

**Comment by sfiserv** [comment]
The download api/spec files is fixed please verify 

<img width="1223" alt="image" src="https://github.com/Fiserv/Support/assets/87097017/582cea7e-3300-48f0-8977-b80e475ed5b7">

**Comment by tarunfiserv** [comment]
Verified the fix, it's working so closing the ticket for now.
