### ISSUE TITLE
Partial Capture giving timeout

### ISSUE THREAD

**Issue by osamafidamirza** [Fiserv/Support#557]
### Product

Commerce Hub

### Page

https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Resources/Guides/Split-Shipment.md&branch=main#tab-transactiondetails

### Description

Im trying to do Auth and Multiple/Partial Capture

accoding to the documentation 
this is the payload im trying to do Auth

```
{
    "source": {
        "sourceType": "PaymentCard",
        "card": {
            "cardData": "4400000000000008",
            "expirationMonth": "02",
            "expirationYear": "2035",
        }
    },
    "billingAddress": {
    "firstName": "John",
    "lastName": "Doe",
    "address": {
      "street": "112 Main St.",
      "city": "Atlanta",
      "stateOrProvince": "GA",
      "postalCode": "30301"
    }
  },
    "amount": {
        "total": 100,
        "currency": "USD"
    },
    "transactionDetails": {
        "captureFlag": false
    },
    "merchantDetails": {
        "terminalId": "myTerminalID",
        "merchantId": "myMerchantID"
    }
}
```

i get successful response but when i do split shipment for partial capture
using this payload
```
{
  "amount": {
    "total": 10,
    "currency": "USD"
  },
  "transactionDetails": {
    "captureFlag": true,
    "splitShipment": {
      "totalCount": 5,
      "finalShipment": true
    }
  },
  "merchantDetails":{
      "terminalId": "myTerminalID",
        "merchantId": "myMerchantID"
   },
  "referenceTransactionDetails": {
    "referenceTransactionId": "myTransactionID"
  }
}
```

i get TIMEOUT as a response

### Expected Behaviour

need to perform partial capture

### Operating system

through API's

### Browser

through API's

**Comment by osamafidamirza** [comment]
@wwfiserv @sfiserv any update

**Comment by wwfiserv** [comment]
@osamafidamirza sorry for the delay, have you tried sending the capture with the finalShipment: false as we don't have the transaction identified as a splitShipment yet and consider it a standard capture and don't' expect the splitShipment object.

**Comment by osamafidamirza** [comment]
@wwfiserv if I remove the whole splitShipment object from the request it works as a standard Capture. if I add the splitShipment object, the request goes TIMEOUT, weather finalShipment is true or false

**Comment by sfiserv** [comment]
@osamafidamirza  please connect with Wiiliam Wade and Mashood Ali for further discussion on this issues. here are their email addresses.
william.wade@fiserv.com
mashhood.ali@fiserv.com

I am closing this issue from github.
