### ISSUE TITLE
Need to delete User and registered email address in SnapPay portal

### ISSUE THREAD

**Issue by storerent** [Fiserv/Support#558]
### Product

SnapPay

### Page

the entire account for 3 email addresses is the bug

### Description

We’ve been trying to get this problem resolved since May 2023, but to no avail. We’ve attached the most recent emails from [donotreply@snappayglobal.com](mailto:donotreply@snappayglobal.com) to outdated emails of :

GPerrotto@Arhaus (needs deleted and User credentials removed)
CWooding@Arhaus (my email is within the correct StoreRent@ group; please delete CWooding address and User credentials)
APInvoices@Arhaus (only 1 lease 495877 is using this address; User and email address needs removed)

[SnapPay portal_8.pdf](https://github.com/Fiserv/Support/files/13395464/SnapPay.portal_8.pdf)
[SnapPay portal_1.pdf](https://github.com/Fiserv/Support/files/13395465/SnapPay.portal_1.pdf)
[SnapPay portal_2.pdf](https://github.com/Fiserv/Support/files/13395466/SnapPay.portal_2.pdf)
[SnapPay portal_3.pdf](https://github.com/Fiserv/Support/files/13395467/SnapPay.portal_3.pdf)
[SnapPay portal_4.pdf](https://github.com/Fiserv/Support/files/13395468/SnapPay.portal_4.pdf)
[SnapPay portal_5.pdf](https://github.com/Fiserv/Support/files/13395469/SnapPay.portal_5.pdf)
[SnapPay portal_6.pdf](https://github.com/Fiserv/Support/files/13395470/SnapPay.portal_6.pdf)
[SnapPay portal_7.pdf](https://github.com/Fiserv/Support/files/13395471/SnapPay.portal_7.pdf)

### Expected Behaviour

These 3 email addresses and Users should be deleted from the SnapPay portal immediately and permanently

### Operating system

windows 11

### Browser

Google Chrome; Version 119.0.6045.125 (Official Build) (64-bit)

### Region

United States

**Comment by sfiserv** [comment]
@storerent  are these emails/accounts created in Developer Portal.
This github is meant to support issue for https://developer.fiserv.com/

**Comment by storerent** [comment]
Good morning, I’ve never been on github.com nor Fiserv.com before this request; I use snappayglobal.com as a tenant to retrieve Rent invoices and have not been able to find any sort of Tech/Customer Support for this portal. They referenced Fiserv on their website, so I tried reaching out to see if they could help resolve my requests. I apologize if I’m not contacting the correct Support team.

Thank you for acknowledging my ticket and responding, regardless 😊



***@***.***
Cheryl Wooding, A/P Specialist
ARHAUS | Your Home
P: 440.439.7700 x3426
51 E. Hines Hill Road,
Boston Heights, OH 44236

ARHAUS CONFIDENTIALITY NOTICE: This transmission, and any documents, files or previous messages attached to it, may contain confidential information that is legally privileged. If you are not the intended recipient, or a person responsible for delivering it to the intended recipient, you are hereby notified that any disclosure, copying, printing, forwarding, distribution or use of any of the information contained in or attached to this message is STRICTLY PROHIBITED. If you have received this transmission in error, please immediately notify us by e-mail at ***@***.******@***.***> or by telephone at (866) 427 4287, and destroy the original transmission and its attachments without reading or saving them. Thank you.

**Comment by sfiserv** [comment]
@storerent since this issue is unrelated to DeveloperStudio application, I am closing this ticket.
