### ISSUE TITLE
API response returns Latin language data 

### ISSUE THREAD

**Issue by bkandhas** [Fiserv/Support#559]
### Product

VerifyNow

### Page

Home -> Financial Institutions -> VerifyNow -> Status/Outcome

### Description

We implement 3 API for VerifyNow. API response returns latin language data. We need english language data as response.

Steps to reproduce:
1. Open https://qa-developerstudio.fiserv.com/ 
2. Click "Who we serve" link.
3. Popup window appear
4. Navigate "Financial Institution" -> "see all financial institution"
5. In left pane, click "VerifyNow" menu.
6. Verify page will load
7. In left pane, click "VerifyNow service(widget flow)" -> "Status/Outcome" menu
8. In Right side window, click "Run Request" button for invoke API

Expected result:
Response data in English language

Actual result:
Response data in Latin language

### Expected Behaviour

Response data in English language

Screenshot:
<img width="959" alt="image" src="https://github.com/Fiserv/Support/assets/146924994/5d60f601-19b5-43ee-aa78-8a152ec51c3f">

### Operating system

Windows

### Browser

Google Chrome

**Comment by minh-pham1** [comment]
We are looking into this issue, however we did notice that if you change the response code in the Response area (via the dropdown), the English version does load properly for all the response codes. Will update as needed.

**Comment by sfiserv** [comment]
We have debugged the issue and have a possible resolution. We will update  you once the fix is ready for your verfication.

**Comment by minh-pham1** [comment]
Status update: Developer is actively working on debugging and fixing the issue. It is being tracked in https://firstdatateam.atlassian.net/browse/PORT-9049

Thank you for your patience!

**Comment by sfiserv** [comment]
@bkandhas our team has debugged this issue and found that you have to 
 fix 5 errors
![image](https://github.com/Fiserv/Support/assets/87097017/3d100790-52d4-45a0-8222-99a56d2528fb)

Your product has only one spec file and the response code is not available . Hence a response code is auto generated and the default language is Latin.
https://github.com/Fiserv/verifynow/blob/develop/reference/1.0.0/sample.yaml

**Comment by sfiserv** [comment]
we have communicated to the tenant the fixes to be done for this issue.
They need to fix the errors and add the appropriate response codes.
Closing this issue for now.
