### ISSUE TITLE
Summary of an API Method is not displaying

### ISSUE THREAD

**Issue by fiservakshay** [Fiserv/Support#56]
# Reporting new issue for BankSolutions/Cards

**Page**
Field description documentation section under API Explorer.

**Describe the bug**
Summary of an API method (POST, DELETE, PUT, etc) added under the "summary:" tag is not being rendered on the Dev studio portal.
Summary gives brief idea about the API method and it is a short version of the description of an API method. 

Please ignore this bug if you have intentionally disabled the Summary of an API method.

**To Reproduce**
Click any API method from the API Explorer tab.

**Expected behavior**
Summary should be displayed on the Dev Studio portal to give user a brief idea about the API method.

**Screenshots**
![image](https://user-images.githubusercontent.com/81968767/139580994-ac51547f-4f43-417f-aceb-f25c8c6ee96c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
- Browser: Chrome
- Version: latest

**Tablet (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by tsegurajimen** [comment]
This ticket is no longer needed.
