### ISSUE TITLE
Dev studio tabs are exceeding page

### ISSUE THREAD

**Issue by MAFiserv** [Fiserv/Support#560]
### Product

Commerce Hub

### Page

https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Online-Mobile-Digital/3D-Secure/3DS-Authentication.md&branch=preview#tab-merchantdetails

### Description

![Screenshot 2023-11-21 121054](https://github.com/Fiserv/Support/assets/137187052/10be742f-12bc-4b7f-9538-81e2acbd5f4e)

### Expected Behaviour

https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Online-Mobile-Digital/3D-Secure/3DS-Authentication.md&branch=preview#tab-merchantdetails

The tabs are exceeding the page. Before it would create a new row and add the tabs. Now it exceed the tab row and goes under the right nav. Also, when it's under the right nav you are unable to click on those tab to view. 

### Operating system

Windows 

### Browser

Google chrome

### Region

Preview

**Comment by OZ-FS** [comment]
Good catch, we've added overflow-hidden class to div containing tab links, so the excess of tab links will be hidden:

<img width="921" alt="Screenshot 2023-11-21 at 2 35 46 PM" src="https://github.com/Fiserv/Support/assets/92183615/96c8afeb-890b-4d2d-aea1-010bce248c22">

We propose for the excess tabs, the tabs exceeding the width of the document, to be positioned in the next tabs row.

**Comment by OZ-FS** [comment]
<img width="1328" alt="Screenshot 2023-11-21 at 11 58 00 PM" src="https://github.com/Fiserv/Support/assets/92183615/bebf5166-6779-4779-8acb-e0cde0128554">

**Comment by sfiserv** [comment]
This issue is fixed as part of https://firstdatateam.atlassian.net/browse/PORT-8766

**Comment by sfiserv** [comment]
Closing this ticket as no issues reported from the client.
