### ISSUE TITLE
Enable “TransferNow UI Widget” menu for Signed-In user alone.

### ISSUE THREAD

**Issue by bkandhas** [Fiserv/Support#561]
### Product

TransferNow

### Page

Home -> Financial Institutions -> Transfer Now -> TN UI Widget

### Description

As per requirement, we need to enable one of the TransferNow tenant menu (menu name “TransferNow UI Widget”) for Signed-In user alone. 
Could you please enable “TransferNow UI Widget” menu for Signed-In user.

Please find the url and navigation path for “TransferNow UI Widget” menu below.

URL : https://qa-developerstudio.fiserv.com/product/TransferNow/docs/?path=docs/getting-started/TN-UI-Widget/TN_Ui_Widget.md&branch=develop
Path : Home -> Financial Institutions -> Transfer Now -> TransferNow UI Widget

<img width="968" alt="image" src="https://github.com/Fiserv/Support/assets/146924994/a9cb4432-96cf-4487-91da-da64bdffb7c4">

### Expected Behaviour

“TransferNow UI Widget” menu enable for signed-in user alone.

### Operating system

Windows

### Browser

Google Chrome

**Comment by sfiserv** [comment]
@bkandhas currently we provide the feature where the product can be internal ( displayed only when fiserv user signs in). or external ( available to everyone.

The enhancement that you have asked is part of our gated content feature.
We are in middle of development process of the gated content which is currently not available for tenants

Please let us know if your product needs to be a internal tenant.

**Comment by sfiserv** [comment]
Closing this ticket since Transfer now is working toward integrating workspace on the ui.
https://github.com/Fiserv/Support/issues/590
