### ISSUE TITLE
Developer Studio logged user info details request

### ISSUE THREAD

**Issue by bkandhas** [Fiserv/Support#574]
### Product

TransferNow

### Page

Home -> Financial Institutions -> Transfer Now -> TN UI Widget

### Description

Need Developer Studio logged user info details. 
we have to share these dev studio logged user details to our API for access token

### Expected Behaviour

Logged user details need to share to API for access token.

### Operating system

windows

### Browser

Google Chrome

**Comment by sfiserv** [comment]
@bkandhas what is the information you are looking for ?

**Comment by sfiserv** [comment]
tracking this ask in https://firstdatateam.atlassian.net/browse/PORT-9025

**Comment by sfiserv** [comment]
Closing this ticket as your team has a new ask for workspace creation hence closing this ticket.
https://github.com/Fiserv/Support/issues/590
