### ISSUE TITLE
Deployment content and image not reflected in Verifynow devstudio portal

### ISSUE THREAD

**Issue by prabaharanthommai** [Fiserv/Support#575]
Deployment content and image not reflected in Verifynow devstudio portal

**Comment by minh-pham1** [comment]
Hello! Is this issue similar the issue seen in #576? If so, we do have an update in that issue, feel free to close this one as it is a duplicate.

If not, please provide more details and examples (i.e. what PR did you merge / content did you change, what page/env you're trying to view, where is the bug, etc.)
