### ISSUE TITLE
TransferNow : Uploaded Content not reflected

### ISSUE THREAD

**Issue by NithyaselvanSrikanth** [Fiserv/Support#576]
### Product

TransferNow

### Page

HomeFinancial Institutions>Transfer NowHow> to Sign-In to Developer Studio Portal to Access TransferNow Widget.

### Description

List of pages:
 1.HomeFinancial Institutions>Transfer Now>SSL Authentication
2.Home>Financial Institutions>Transfer Now>Error Handling / Error Codes
3.Home>Financial Institutions>Transfer Now>Fund Transfer Services
4.Home>Financial Institutions>Transfer Now>Fund Transfer Services>Transfer-Via Debit Cards

### Expected Behaviour

Content Should be reflected.

### Operating system

Windows Microsoft 365

### Browser

Google Chrome Version 119.0.6045.160 (Official Build) (64-bit)

**Comment by minh-pham1** [comment]
Hello @NithyaselvanSrikanth, we've identified and deployed a fix on our `dev` environment. It will move up to QA next week for validation. Thank you!

**Comment by sfiserv** [comment]
<img width="262" alt="image" src="https://github.com/Fiserv/Support/assets/87097017/72b43c73-9e41-4301-9295-1e561ed4137e">
Please verify if these are the changes you are looking for.

**Comment by NithyaselvanSrikanth** [comment]
The contents are reflecting @minh-pham1. Thanks for solving the issue.
