### ISSUE TITLE
Transfer Now Tenant to be changed as "TransferNow"

### ISSUE THREAD

**Issue by gokulfiserv** [Fiserv/Support#578]
### Product

TransferNow

### Page

Financial Institutions>TransferNow

### Description

There should not be any space between the word Transfer and Now.

### Expected Behaviour

Space should be removed between Transfer & Now; Name of the tenant should be "TransferNow" .

### Operating system

Windows

### Browser

Google Chrome Version 119.0.6045.200

### Region

QA

**Comment by sfiserv** [comment]
<img width="608" alt="image" src="https://github.com/Fiserv/Support/assets/87097017/a12e5b1a-8534-4ae5-95c9-cb7fb08496bd">
This is not a bug but an enhancement. The product name was provided by your team and it is reflected as per the request.

If you need to change the name we can do it in the upcoming sprints.

**Comment by gokulfiserv** [comment]
Yes, We do need the name to be Changed. If possible add ETA, this will be easy for us to track.

**Comment by sfiserv** [comment]
Tracking this as part of https://firstdatateam.atlassian.net/browse/PORT-9023

**Comment by minh-pham1** [comment]
Hello @gokulfiserv! The update has been made on our dev environment. Please make sure to update the `title` field on your Github `config/tenant.json` for the `develop` and `stage` branch. The change will be reflected on our QA environment next week. 

Just as a note, this change will also be reflected in the upcoming push to our stage environment.

**Comment by ManiBharathiNatarajan** [comment]
Hi @minh-pham1 Thank you for your guidance, TransferNow is reflecting as expected.
<img width="960" alt="image" src="https://github.com/Fiserv/Support/assets/153706962/499b121f-1ce5-43a6-82af-bd4bc49ef235">

**Comment by gokulfiserv** [comment]
Since informed earlier closing this issue.

**Comment by gokulfiserv** [comment]
Since informed earlier closing this issue.
