### ISSUE TITLE
Dev studio portal not loading getting network error

### ISSUE THREAD

**Issue by prabaharanthommai** [Fiserv/Support#580]
### Product

verify Now  & Transfer Now

### Page

product->verify Now

### Description

Dev studio portal not loading getting network error
<img width="939" alt="MicrosoftTeams-image (4)" src="https://github.com/Fiserv/Support/assets/145688917/89e2fa23-8579-4017-a52b-efffe742d21f">
<img width="922" alt="MicrosoftTeams-image (2)" src="https://github.com/Fiserv/Support/assets/145688917/b49adc16-6399-4504-b958-e4d457d649c0">

### Expected Behaviour

Dev studio portal not loading getting network error

### Operating system

windows

### Browser

google chromw

**Comment by sfiserv** [comment]
@prabaharanthommai this issue has been resolved. QA env is up and running. Hence closing the issue.
