### ISSUE TITLE
Onboard a new tenant

### ISSUE THREAD

**Issue by jaideepsahaf** [Fiserv/Support#581]
### Name of your product / tenant

UNIFIED MERCHANT MASTER

### Type of Tenant

- [x] Full service
- [ ] Doc only
- [ ] Link out

### Team Members

jaideepsahaf

### Bug Reporting

jaideepsahaf

### Feedback Reporting

jaideepsahaf

### Enhancement Reporting

jaideepsahaf

### Internal tenant

Yes

### Product of Carat

No

### Merchants solution area

Yes

### Customer Segments for Merchants

- [ ] SMB
- [ ] Enterprise

### Financial Institutions solution area

No

### Customer Segments for Financial Instituitions

- [ ] Bank
- [ ] Credit Union
- [ ] Large Financial Institution

### Fintech solution area

No

### Region of Operation

- [X] North America
- [ ] EMEA
- [ ] LATAM
- [ ] APAC

### RESTful

Yes

### SDK

No

### Runbox

Yes

### Mock Sandbox

Yes

### Live Server

Yes

**Comment by minh-pham1** [comment]
Looking into it

**Comment by sfiserv** [comment]
tracking this issue in https://firstdatateam.atlassian.net/browse/PORT-9026

**Comment by minh-pham1** [comment]
Hello @jaideepsahaf sorry for the delay! Before we onboard you onto our `dev` and subsequently `qa` environment I would like to verify a few details.

1. Name: Should your product name follow this exact capitalization?
2. Internal Tenant: Do you intend for your product to be only viewable by **logged in** Fiserv users on our DevStudio (i.e. a user must be logged in with their work email on the DevStudio website to view your product)?
3. Live Server: Are you looking to provide us with a live API endpoint that DevStudio users can hit? If not (you would only like to provide mocked responses through yaml definitions), that would be just the Mock Sandbox feature we provide.

Please reply to this thread and we can continue the onboarding process from there. Thank you!

**Comment by jaideepsahaf** [comment]
> Hello @jaideepsahaf sorry for the delay! Before we onboard you onto our `dev` and subsequently `qa` environment I would like to verify a few details.
> 
> 1. `Name`: Should your product name follow this exact capitalization? Is there any naming convention we need to follow?
> 2. `Internal Tenant`: Do you intend for your product to be only viewable by **logged in** Fiserv users on our DevStudio (i.e. a user must be logged in with their work email on the DevStudio website to view your product)? Yes its Internal only
> 3. `Live Server`: Are you looking to provide us with a live API endpoint that DevStudio users can hit? If not (you would only like to provide mocked responses through yaml definitions), that would be just the Mock Sandbox feature we provide. Do you provide support for GraphQL? As we have GraphQL API. How will that work?
> 
> Please reply to this thread and we can continue the onboarding process from there. Thank you!

**Comment by jaideepsahaf** [comment]
Hi Minh,

Any update on this?

**Comment by jaideepsahaf** [comment]
Hi Minh,

I have added comments to the ticket.
Can you please take a look?  And when can we expect the new tenant to be usable?
Please let me know.

Thanks,
Jaideep Saha
Manager Software Development II
GBS
Mobile: (647) 687-2802
Fiserv
World’s Most Innovative Companies 2022 | Fast Company
Fiserv<https://www.fiserv.com/?cid=link|fiservsignature|fiservlink||> | Join Our Team<https://www.careers.fiserv.com/?utm_source=outlook&utm_medium=email&utm_campaign=signature> | Twitter<https://twitter.com/fiserv> | LinkedIn<https://www.linkedin.com/company/fiserv/> | Facebook
<https://www.facebook.com/Fiserv/>
© 2022 Fiserv Inc. or its affiliates. Fiserv is a registered trademark of Fiserv Inc. Privacy Notice
<https://www.fiserv.com/en/about-fiserv/privacy-notice.html?cid=link|fiservsignature|privacypolicy||>Fast Company is a registered trademark of Mansueto Ventures LLC.

**Comment by minh-pham1** [comment]
Hello Jaideep,

Sorry for the late response, I was out on vacation for the last two weeks. However, I currently only see that you have posted a comment that quotes/replies to my inquiry but without any answer. Maybe something failed to parse but could you double check on this issue ticket to see whether your comment was added properly? Just as an example, I need a response such as

1. Name: "Yes, `UNIFIED MERCHANT MASTER` is correct" or "No, it should be `Unified Merchant Master`"
2. Internal Tenant: Yes/no.
3. Live Server: "Yes, here is the information for our live API server for users to send API requests to" or "No, we are only going to define mock APIs using the YAML, we will not be utilizing the Live Server feature"

Thanks,
Minh Pham

**Comment by jaideepsahaf** [comment]
Name: "Yes, UNIFIED MERCHANT MASTER is correct".
Internal Tenant: Yes.
Live Server: "We are not using Live Server now. Moreover we have a GraphQLAPI. in order for GraphQL Api to work with the live server, need your guidance.

**Comment by minh-pham1** [comment]
Ok, I'll get the tenant setup for you soon and will let you know when it'll be ready.

In regards to GraphQL, unfortunately our mock sandbox does not currently support that feature (we only mock REST APIs using yaml spec files). I do happen to know that it has been requested as an enhancement at some point but its implementation has not been discussed. I'll enable the Mock Sandbox feature for your tenant just in case.

**Comment by jaideepsahaf** [comment]
Hi Minh

Can  we expect it this week?

> Ok, I'll get the tenant setup for you soon and will let you know when it'll be ready.
> 
> In regards to GraphQL, unfortunately our mock sandbox does not currently support that feature (we only mock REST APIs using yaml spec files). I do happen to know that it has been requested as an enhancement at some point but its implementation has not been discussed. I'll enable the Mock Sandbox feature for your tenant just in case.

**Comment by minh-pham1** [comment]
Hello Jaideep, the onboarding scripts have been added to the code to be ran during our QA deployment (normally it would happen today but might get pushed to tomorrow due to the holiday and various planning calls+approvals).

Meanwhile, you can find your product's [github repository here](https://github.com/Fiserv/unified-merchant-master). Feel free to request access to the `unified-merchant-master` team to get Write permission to the repository. I'll be sure to update this issue when the QA deployment is complete and your product is available for viewing on DevStudio.

**Comment by sfiserv** [comment]
@jaideepsahaf  please validate the QA env and verify your product is on boarded as per your request.
 QA env credentials will be send out to you separately.
<img width="942" alt="image" src="https://github.com/Fiserv/Support/assets/87097017/421a72b0-2309-40c7-a4b8-07837ac2a45a">

**Comment by sfiserv** [comment]
Closing this issue as the on boarding is done and no issues reported by the tenant.
