### ISSUE TITLE
When we Click on Visit Our Support Page from TransferNow and VerifyNow Tenant, Constantly it redirects to Banking Hub Support

### ISSUE THREAD

**Issue by ManiBharathiNatarajan** [Fiserv/Support#589]
### Product

TransferNow and VerifyNow

### Page

Help->Visit Our Support Page

### Description

When we Click on Visit Our Support Page from the Help Button in TransferNow & VerifyNow tenant, it redirects to the Support page which specifically designed for Banking Hub Support.

https://github.com/Fiserv/Support/assets/153706962/882d689a-533d-4134-9b98-f417480f8eeb

### Expected Behaviour

When we Click on Visit Our Support Page from the Help Button in TransferNow & VerifyNow tenant, it should redirect to the Support page which specifically designed for TransferNow & VerifyNow tenant.

### Operating system

Windows

### Browser

Google Chrome Version 119.0.6045.200

### Region

QA

**Comment by sfiserv** [comment]
@ManiBharathiNatarajan based on your video you have clicked the Banking hub support card and this is redirecting you to the Banking support page which is the expected behavior.
The file the bug card is redirecting you to the correct github issue ticket.

Closing this ticket as this is working as expected.

**Comment by ManiBharathiNatarajan** [comment]
@sfiserv When we click on Visit Our Support link from either TransferNow or VerifyNow, it should redirect to the Specific Support page for TransferNow or VerifyNow, but in this case the redirection itself leads to the support page for Banking Hub.

https://github.com/Fiserv/Support/assets/153706962/13ca8980-e597-4c52-8634-6dd056cba0f7

![Screenshot 2023-12-19 114543](https://github.com/Fiserv/Support/assets/153706962/02b88dfe-fc10-45f1-b56a-12d17fde9010)

**Comment by sfiserv** [comment]
@ManiBharathiNatarajan please look carefully you are redirected to the general support page.You are focusing on the Banking hub card which is a temporary customize support page. 
Transfer Now tenant and all other tenant do not have this customized support page.
This is a expected behavior.
