### ISSUE TITLE
Content rendering issue with arrays

### ISSUE THREAD

**Issue by fiservakshay** [Fiserv/Support#59]
# Reporting new issue for OpenBanking/Cards

**Page**
API documentation page (under API Explorer) of Address Service.

**Describe the bug**
Field descriptions added in the YAML file are not being rendered in the API Explorer. This issue usually appears when the data-type of a field is array. Please refer the attached screenshot below for your ready reference.

![image](https://user-images.githubusercontent.com/81968767/141927356-5b52d957-6ed6-4f30-ba52-9888875f7890.png)

**To Reproduce**
Reference documentation link: https://dev-developerstudio.fiserv.com/product/OpenBankingCards/api/?type=post&path=/address

**Expected behavior**
All fields that are part of YAML file should display in the documentation section as well.

**Screenshots**
added

**Desktop (please complete the following information):**

**Tablet (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**
cc: @tsegurajimen @chrisnealonfiserv @brittaho

**Comment by jimmychen-fiserv** [comment]
Jira ticket: https://firstdatateam.atlassian.net/browse/PORT-2801

**Comment by tsegurajimen** [comment]
Now content seems to be displayed right:
![image](https://user-images.githubusercontent.com/81706748/146275898-e259fa1f-1017-4ee4-bd3c-560d61258439.png)

**Comment by acho-fiserv** [comment]
@fiservakshay is this confirmed done?  it says closed by it's not closed yet.

**Comment by fiservakshay** [comment]
> @fiservakshay is this confirmed done? it says closed by it's not closed yet.

Yes, this issue has been fixed. I thought it was closed already, closing it now.
