### ISSUE TITLE
Enable the Workspace for TransferNow tenant

### ISSUE THREAD

**Issue by bkandhas** [Fiserv/Support#590]
### Product

TransferNow

### Page

Workspace

### Description

Steps: 
1. Enable workspace for TransferNow tenant

<img width="960" alt="image" src="https://github.com/Fiserv/Support/assets/146924994/d67dcead-2200-4ef2-9e84-c2f5684464ac">

2. Provide us the following details to navigate to the Hosted URL.
            - API Key
            - API Secret
            - Firstname, Lastname, Email-Id of the Free user who logs in Dev Studio.

3. Hosted URL : **https://qa-ft.onefiserv.net/jsp/backoffice/tnAPI.jsp**

### Expected Behaviour

User should navigate to the hosted URL page which was developed by us. 

Screenshot of the hosted URL page.

<img width="299" alt="TNPage" src="https://github.com/Fiserv/Support/assets/146924994/093583ad-6052-412f-968c-2a77933bee1e">

### Operating system

Windows

### Browser

Google Chrome

**Comment by sfiserv** [comment]
Tracking this issue as part of https://firstdatateam.atlassian.net/browse/PORT-9025

Developer team will be evaluating the requirement and collaborating with transfer now team for the implementation of this ask.

**Comment by anandrewfiserv** [comment]
At first glance, we will have to agree on an encryption method to provide the users' information.

**Comment by bkandhas** [comment]
can you please kindly provide the encryption method which you are referring in Developer Studio
Looking forward for your kind reply.

**Comment by sfiserv** [comment]
This enhancement cannot be implemented. This integration is not possible hence closing this ticket.

**Comment by sfiserv** [comment]
Reopening this issue since we the ask from the team is to have separate workspace and not integrated with Banking hub as mentioned in github#616
