### ISSUE TITLE
Reset pwd throws an error in QA

### ISSUE THREAD

**Issue by ns9988** [Fiserv/Support#591]
### Product

Dev Studio

### Page

QA Login page

### Description

When I try to access forgot pwd link in QA it throws an error.

Steps
1. Go to https://qa-developerstudio.fiserv.com/financial-institutions
2. Signin->Reset pwd
3. Error Unable to process request
We are experiencing technical difficulties and hope to have them resolved soon. Please try again later.

If the problem persists, report us the issue or check the status on Github.

### Expected Behaviour

User should be able to get a reset pwd link and proceed.

### Operating system

Mac Os Ventura 13.5

### Browser

Chrome Version 120.0.6099.109

### Region

US-Pacific

**Comment by sfiserv** [comment]
closing this issue as the reset password is working in QA env.
