### ISSUE TITLE
Invalid TTP Access Token if terminalProfileId is not in UUID format

### ISSUE THREAD

**Issue by rholstad** [Fiserv/Support#598]
### Product

Commerce Hub

### Page

https://github.com/Fiserv/TTPPackage

### Description

While using the TTPPackage to perform a Tap to Pay on iPhone payment, the PaymentCardReader.linkAccount(using:) method fails if the token obtained from the FiservTTPTokenRequest was requested with a terminalProfileId that is not a UUID string. The readme says 

```
terminalProfileId: "3c00e000-a00e-2043-6d63-936859000002") /// Unique identifier for the terminal profile used to configure the kernels of the card reader and manage payment terminal behavior
```

but it does not mention that the `terminalProfileId` must be in a UUID string format. If you use a string that is not in this format, the FiservTTPTokenRequest is successful and an access token is obtained, but it cannot be decoded by Apple when linking the account:

```
Fail to decode the provided PSP token.
```

We have our own unique identifiers for each device that I tried to use for this property which is not in a UUID string format. Why does this property have to be formatted in this way?

### Expected Behaviour

Choice of `terminalProfileId` should not affect Apple's ability to decode the access token.

### Operating system

iOS 16.7.2

### Browser

iPhone

**Comment by rholstad** [comment]
Actually, it appears the `terminalProfileId` must be exactly `3c00e000-a009-a14f-5a63-cf156a000001`. Anything in UUID format will allow `PaymentCardReader.linkAccount(using:)` to succeed, but only this specific value will allow `PaymentCardReader.prepare(using:)` to succeed. If this value is specific to Fiserv, why is it editable?

**Comment by Rezi0110** [comment]
Hello Ryan, thank you for reporting this bug, I will be looping @fs-rich-tilt into this conversation to better help you with this bug.

**Comment by wwfiserv** [comment]
@Rezi0110 can you assign @fs-rich-tilt to the ticket it won't allow me.

**Comment by Rezi0110** [comment]
Sounds good, I will have it assigned.

**Comment by rholstad** [comment]
@fs-rich-tilt Do you have any feedback on this issue? We are nearing deployment of this feature.

**Comment by fs-rich-tilt** [comment]
Our release schedule for the repo is in line with other server side dependencies. The reported issue, which is not server related, will be addressed in the next release.
