### ISSUE TITLE
Align Account Processing core, Identity & EPOC Debit Cards Product description and Summary Content in DevStudio Banking Hub Free/Paid Plan Workspace

### ISSUE THREAD

**Issue by AjitR01** [Fiserv/Support#599]
### Context

Given Identity (a.k.a.) Onboard Advisor and EPOC Debit Cards services is enabled in Banking Hub, then we the product description for each provider as per their rate plan should be displayed in Banking Hub Free / Paid Plan workspace for consumer. 

### Solution

Align the provider product description format in Banking Hub Free / Paid plan Workspace based on the Information passed by downstream system. 

1. In below screenshot > the highlighted box in the pop up window, when user created a free workspace then based on the providers enable below product description should be added  

**Account Processing Core** : This plan includes 1,000 account processing core API transactions per month and 3 API transactions per minute across all shared core environments.
**Identity** : The free plan allows you to explore Identity Verification: KYC/KYB API transactions limited to 1 transaction per minute not to exceed 10 transaction per month.
**EPOC Debit Cards** : This plan includes 1,000 transactions per month and 3 API transactions per minute for consuming the Card Token service.

![image](https://github.com/Fiserv/Support/assets/137955475/550b82d1-5b19-4a6e-9879-628ab5587f5e)

2. Highlighted lines in Workspace Summary Content should be updated to below

- Access to a shared account processing core bank test environment, Identity services and EPOC Debit card services. 
- A key to access all account processing core APIs, Identity APIs and EPOC Debit Cards APIs. 

![image](https://github.com/Fiserv/Support/assets/137955475/b71048e7-3c26-47b6-9a1e-103af7bc82aa)

### Alternatives

N/A

**Comment by AjitR01** [comment]
@anandrewfiserv As discussed please review the ticket, FYI we are targeting this in Jan release so please add to your list and let me know if you have any questions.

**Comment by sfiserv** [comment]
@anandrewfiserv please let us know if this is fixed. please let us know the priority of this we can assign this to our team.

**Comment by anandrewfiserv** [comment]
This has been fixed.

**Comment by sfiserv** [comment]
As per @anandrewfiserv this enhancement has been implemented.
Hence closing this ticket as no issues were reported by the BH team.
