### ISSUE TITLE
Add Debit Logo field to view API key pop up window in Banking Hub free/Paid workspace

### ISSUE THREAD

**Issue by AjitR01** [Fiserv/Support#600]
### Context

Given EPOC debit cards is enabled, then we have to show the Debit Logo to consumer for consuming debit cards token api services 

### Solution

Add Debit Logo field as shown below in view API key window
![image](https://github.com/Fiserv/Support/assets/137955475/7e2a9663-bd55-4d54-abf3-c41d36878027)

### Alternatives

N/A

**Comment by AjitR01** [comment]
@anandrewfiserv FYI as we have EPOC Debit Cards services targeted for Jan release, please review the ticket and let me know if you have any questions.

**Comment by sfiserv** [comment]
@anandrewfiserv can you please let us know what was the priority decided for this requirement.

**Comment by anandrewfiserv** [comment]
![image (1)](https://github.com/Fiserv/Support/assets/90014155/58999c82-8138-4e2a-87f1-96d173f629f9)

from 
{
          EPOC: ['412412 (Finxact)', '3424124 (Premier)', '872763 (Signature)'],
          EPOD: ['123456 (Finxact)', '5435655 (Premier)', '134564 (Signature)'],
}

**Comment by sfiserv** [comment]
@AjitR01 @anandrewfiserv  is this implemented or is this still a requirement required for BH.

**Comment by anandrewfiserv** [comment]
There is a small aesthetic change left that I can take on anytime. I don't think there is a ticket for it yet.

**Comment by sfiserv** [comment]
This enhancement is promoted to Production. Hence closing the issue.
