### ISSUE TITLE
screen reader accessibility

### ISSUE THREAD

**Issue by fr5d** [Fiserv/Support#601]
### Context

Hi there a friend of mine works a job that uses your program and she is losing her sight and unfortunately there is little to no screen reader accessiblity built in. She is worried she will have to quit her job because of this. I hope you can help

### Solution

Implementation of screenreader accessibility for all major screen readers Jaws for windows, voice over for, NVDA, etc.

### Alternatives

n/a

**Comment by sfiserv** [comment]
@fr5d is there an issue you wanted to report for developer studio.
