### ISSUE TITLE
TransferNow - In TransferNow UI Widget Page, Functionality of Right-side menu is not correlating with the content.

### ISSUE THREAD

**Issue by Prav5314** [Fiserv/Support#602]
### Product

TransferNow

### Page

TransferNow->Documentation->TransferNow UI Widget->TN UI Rendering Options

### Description

In TransferNow UI Widget Page, Click TN UI Rendering Options - Functionality of Right-side menu is not correlating with the content.

### Expected Behaviour

If we scroll down in the Right-side menu it should correlate with the content in main page.

### Operating system

Windows

### Browser

Google Chrome Version 120.0.6099.200

### Region

QA

**Comment by sfiserv** [comment]
@Prav5314 the right doc tree is related to the headers on the same tab not the different tabs.
this is the expected behavior.
