### ISSUE TITLE
VerifyNow Product Description is not appearing on Products Catalog section in Financial Institutions Home page

### ISSUE THREAD

**Issue by ManiBharathiNatarajan** [Fiserv/Support#604]
### Product

VerifyNow

### Page

Financial Institutions Home Page

### Description

The Product Catalog section in Financial Institutions Home page fails to reflect the product description.

https://qa-developerstudio.fiserv.com/financial-institutions/bank 

<img width="960" alt="image" src="https://github.com/Fiserv/Support/assets/153706962/02d974c1-5eb6-4d45-8bff-175ef5d0081c">

### Expected Behaviour

The Product Catalog section in Financial Institutions Home page should reflect the product description.

### Operating system

Windows

### Browser

Google Chrome Version 120.0.6099.200

### Region

QA

**Comment by sfiserv** [comment]
@ManiBharathiNatarajan  please use https://qa-developer.fiserv.com/  not the qa-developerstudio.fiserv.com

please verify if the correct UI if your changes are getting reflected.

**Comment by ManiBharathiNatarajan** [comment]
Hi @sfiserv, Thanks for the immediate response, the issue pertains by using the above mentioned link also. https://qa-developer.fiserv.com/financial-institutions/bank

 <img width="960" alt="image" src="https://github.com/Fiserv/Support/assets/153706962/cb2b42cd-aeb8-4b59-9c9b-6efc987b2aae">

**Comment by ManiBharathiNatarajan** [comment]
Hi @sfiserv, as per the guidance by @minh-pham1 We have changed the context in config/tenant.json and it is reflected.

<img width="960" alt="image" src="https://github.com/Fiserv/Support/assets/153706962/85b01202-176e-40de-a15d-6d8f84bf8d2a">

Closing this issue since it is working as expected.
