### ISSUE TITLE
TransferNow Product Description is not appearing on Products Catalog section in Financial Institutions Home page

### ISSUE THREAD

**Issue by ManiBharathiNatarajan** [Fiserv/Support#605]
### Product

TransferNow

### Page

Financial Institutions Home Page

### Description

The Product Catalog section in Financial Institutions Home page fails to reflect the product description.

https://qa-developerstudio.fiserv.com/financial-institutions/bank

<img width="960" alt="image" src="https://github.com/Fiserv/Support/assets/153706962/e3caa173-0fed-44a3-aa3e-6f31e4d3ebae">

### Expected Behaviour

The Product Catalog section in Financial Institutions Home page should reflect the product description.

### Operating system

Windows

### Browser

Google Chrome Version 120.0.6099.200

### Region

QA

**Comment by sfiserv** [comment]
@ManiBharathiNatarajan please use https://qa-developer.fiserv.com/ not the qa-developerstudio.fiserv.com

please verify if the correct UI if your changes are getting reflected.

**Comment by ManiBharathiNatarajan** [comment]
Hi @sfiserv, the issue still pertains by using the above-mentioned link also.

<img width="960" alt="image" src="https://github.com/Fiserv/Support/assets/153706962/4ca62c69-a489-4cf1-91fe-53f6515b540f">

**Comment by minh-pham1** [comment]
I believe you'll have to change these fields in your github `config/tenant.json`:

```
"description": "transfer now description",
"longDescription": "transfer now long description"
```

**Comment by ManiBharathiNatarajan** [comment]
Hi @minh-pham1, Thank you for the response. will check with our Development team.

**Comment by ManiBharathiNatarajan** [comment]
Hi @minh-pham1 Thank for your guidance. The changes are reflected.

<img width="960" alt="image" src="https://github.com/Fiserv/Support/assets/153706962/1573752d-e811-47f5-a962-d3b0fd3eb5cb">

Closing this issue, since it is working as expected.
