### ISSUE TITLE
Onboard AI Center

### ISSUE THREAD

**Issue by russnicoletti** [Fiserv/Support#606]
### Name of your product / tenant

AI Center

### Type of Tenant

Doc only

### Team Members

acho-fiserv

### Bug Reporting

acho-fiserv

### Feedback Reporting

acho-fiserv

### Enhancement Reporting

acho-fiserv

### Internal tenant

Yes

### Product of Carat

No

### Merchants solution area

Yes

### Customer Segments for Merchants

- [ ] SMB
- [ ] Enterprise

### Financial Institutions solution area

No

### Customer Segments for Financial Instituitions

- [ ] Bank
- [ ] Credit Union
- [ ] Large Financial Institution

### Fintech solution area

No

### Region of Operation

- [X] North America
- [ ] EMEA
- [ ] LATAM
- [ ] APAC

### RESTful

No

### SDK

No

### Runbox

No

### Mock Sandbox

No

### Live Server

No

**Comment by minh-pham1** [comment]
Product has been onboarded to all 4 environments.
