### ISSUE TITLE
XML format does not support for VerifyNow API

### ISSUE THREAD

**Issue by bkandhas** [Fiserv/Support#607]
By default API explorer rendering request and response as JSON format.
We need to render Verify Now API(instant verification, ping, outcome) request and response type as XML format. 
So we configured content type as application/xml in API yaml file.
Post update content type, request and response not updated as XML format.
Please update XML format.

**Comment by sfiserv** [comment]
@bkandhas please update this issue if this is an bug or enhancement you are looking for.

**Comment by bkandhas** [comment]
We have configured content as application/xml openapi.yaml file but JSON format alone rendering in API explorer.
Please enable XML format in API explorer request data

**Comment by sfiserv** [comment]
@bkandhas  this will be a feature enhance our team needs to work on. We can prioritize this in the upcoming sprint 4.

**Comment by sfiserv** [comment]
Tracking this issue in sprint 5 as part of 
https://firstdatateam.atlassian.net/browse/PORT-10052

**Comment by bkandhas** [comment]
JSON API working as expected.So no need to configure XML format.
