### ISSUE TITLE
Integration with Fiserv DNA

### ISSUE THREAD

**Issue by BaranovskiyNE** [Fiserv/Support#608]
### Context

Hello, colleagues. 
We need to integrate our CRM system with Fiserv DNA. First of all, we need to receive contact and card information.
1. What Fiserv DNA's API can we use for it? Where can we find documentation?
2. Can we use Banking Hub to communicate with Fiserv DNA? (We see that it has the preview status).
3. How can we get test environment for such development?
4. Should we use DNACreator and create DNAApp to achieve that?

### Region

North America

**Comment by BaranovskiyNE** [comment]
@sfiserv, @eliascanaza, hello, can you help me with my question?

**Comment by sfiserv** [comment]
@BaranovskiyNE can you please check this with  navneet.seth@fiserv.com
He is the point of contact with Fiserv DNA. currently they have been inactive for a while. however please check with Navneet if he can help you out.

**Comment by BaranovskiyNE** [comment]
@sfiserv , thanks for your answer. I've tried to send email to navneet.seth@fiserv.com and received automatic answer that "Your message to avneet.seth@fiserv.com couldn't be delivered. avneet.seth wasn't found at fiserv.com." :((

**Comment by sfiserv** [comment]
@BaranovskiyNE  please check the email addres you have typed 
his email address is   navneet.seth@fiserv.com 
seems you have a typo in the email.
