### ISSUE TITLE
Onboard MTRG network token on Developer Portal

### ISSUE THREAD

**Issue by prashantkumarfiserv** [Fiserv/Support#609]
### Context

Expose network token api specs on Developer Portal Starting from QA UI region. Git repository already created. 
Repo URL: https://github.com/Fiserv/network-tokens/

### Solution

Expose network token api specs on Developer Portal Starting from QA UI region. Git repository already created. 
Repo URL: https://github.com/Fiserv/network-tokens/

build and deployment should be automated and merging changes on develop branch should expose changes to QA, merging to stage env should expose it to stage env.

Also provide access to this repo to following users:

prabanand.karunanithi@Fiserv.com
venkatsaichaitanya.callen@fiserv.com
[prashantkumar.tripathi@Fiserv.com](mailto:prashantkumar.tripathi@Fiserv.com)
[vinitkumar.singh@Fiserv.com](mailto:vinitkumar.singh@Fiserv.com)
[gopinathan.mani@Fiserv.com](mailto:gopinathan.mani@Fiserv.com)

### Alternatives

Expose network token api specs on Developer Portal Starting from QA UI region. Git repository already created. 
Repo URL: https://github.com/Fiserv/network-tokens/

### Region

QA

**Comment by prashantkumarfiserv** [comment]
@sfiserv Please let know the dates when this will get picked for implementation

**Comment by minh-pham1** [comment]
Hello Prashan, I have created the scripts and they are set to be ran along with our `qa` environment deployment on 01/29. @sfiserv will send out the Github team invite to the mentioned addresses later this week. Thank you!

**Comment by prashantkumarfiserv** [comment]
Hi Minh, is there a way to view  it on developer Portal before 29th?

**Comment by prashantkumarfiserv** [comment]
Hi Minh, I am not able to do any commit on this repo. Is commit permission provided?

**Comment by minh-pham1** [comment]
Hello Prashant, as per our process, we do not allow direct commits to any branch that is displayed on our DevStudio without a Pull Request. As such, you'll need to make your changes on a feature branch split from the branch you'd like to work on, then submit a PR to merge it into the `develop`, `preview`, `stage`, and/or `main`. This is to have accountability and change logs in the case of bad documents or other bugs due to faulty yamls, as well as allowing us to run various validators for the `tenant.json` and API references.

**Comment by prashantkumarfiserv** [comment]
Hi Minh, is this available on developer portal?

**Comment by minh-pham1** [comment]
Hello Prashant, we are actually in progress for our QA deployment as of the current moment. I'll be sure to update this ticket immediately as soon as we complete our deployment. Thank you for your patience!

**Comment by sfiserv** [comment]
@prashantkumarfiserv your product is enabled in QA env please use this url to verify.
 https://qa-developer.fiserv.com/

**Comment by sfiserv** [comment]
closing this issue as the product is on QA env and there is a request to promote this product to production.
