### ISSUE TITLE
Rename a tenant 

### ISSUE THREAD

**Issue by fiservakshay** [Fiserv/Support#61]
**Is your feature request related to a problem? Please describe.**
One tenant for documentation of Open Banking APIs.

**Describe the solution you'd like**

- Rename the existing "Open Banking Cards" tenant to "Integrated Banking"
- Remove/disable the following tenants that was created for other Open Banking domains:
  - Accountholder
  - Accounts and Transactions
  - Cards and Payments
  - Notifications and Preferences (@brittaho Please confirm if the Notification tenant also needs to be removed) 

![image](https://user-images.githubusercontent.com/81968767/142355247-1d78364f-b33f-47ae-9dfc-973035f11188.png)

Reason:
Earlier we had decided to use separate tenant for API documentation of each banking domain. But now the team has decided to merge all banking domain tenants into one single tenant.

**Describe alternatives you've considered**
n/a

**Additional context**

**Comment by brittaho** [comment]
@fiservakshay, this is to confirm that the "Notifications and Preferences" tenant needs to be removed as well. Related APIs need to show under Integrated Banking. Thank you!

**Comment by brittaho** [comment]
The renaming of the tenant to "Integrated Banking" needs to include a BETA label at the end.

**Comment by TaniaSarkar89** [comment]
'Open Banking Cards' has been renamed to 'Integrated Banking' and the rest of the Open Banking products have been removed from FI page as well. 
The 'Beta' will be added by our team later.
