### ISSUE TITLE
Download API specification not working.

### ISSUE THREAD

**Issue by shubhamKanse99** [Fiserv/Support#610]
### Product

firstvision-emea

### Page

API explorer -> Download API specifications button

### Description

Download API specifications button is not working, it is throwing below error. 

![image](https://github.com/Fiserv/Support/assets/117971606/6f5b6fcd-a357-4d3b-a6aa-41262e51d722)

### Expected Behaviour

Should download the yaml file with button click.

### Operating system

windows

### Browser

chrome

### Region

Production

**Comment by minh-pham1** [comment]
Hello Shubham, I believe that the API specs zip file is available for download on production now. It may have been some delay on our end to generate the zip file or cache it. Can you please verify whether this issue is already resolved on your end?

**Comment by shubhamKanse99** [comment]
Hi, 

It is not resolved. Still the same error.

**Comment by minh-pham1** [comment]
I see the problem, we'll attempt to fix it as soon as possible sorry for the delay!

In the mean time, do you need this zip urgently? I can send it to you.

**Comment by minh-pham1** [comment]
Quick update: It seems that another developer has already fixed this issue 2 weeks ago (hence I was having trouble replicating the issue on our `dev` environment despite seeing it on `production`). The change is already on our `qa` environment and will soon move up to `stage` and `prod`. Sorry about the inconvenience!

**Comment by shubhamKanse99** [comment]
okay thanks a lot.

**Comment by minh-pham1** [comment]
Hello Shubham, our production deployment has completed and I believe that the issue has been fixed. Thank you for your help and patience. Please feel free to validate and close this ticket if the issue has been resolved for you!

**Comment by shubhamKanse99** [comment]
Hi @minh-pham1, 

Thanks for your support, It is now working as expected.
