### ISSUE TITLE
uCom API Key

### ISSUE THREAD

**Issue by bmcfarlin** [Fiserv/Support#611]
Please send test (SANDBOX) API Key for uCom.

https://developer.fiserv.com/product/ConnectedCommerce/api/?type=get&path=/v1/geolocation/sites&branch=main&version=1.0.0

**Comment by sfiserv** [comment]
@bmcfarlin  can you please elaborate what exactly is your ask?
Please provide more information.

**Comment by sfiserv** [comment]
@bmcfarlin please open a proper request if your product needs to implement workspace for the Universal commerce product.
else please let us know what is the ask I can redirect you to the correct point of contact.
