### ISSUE TITLE
Need to promote our Fraud Mitigation product to both Stage and Production of Devstudio [Stage and Main Branch]

### ISSUE THREAD

**Issue by kongaravinatha** [Fiserv/Support#612]
### Context

Hi Devstudio team,

I am one of the resources working for FraudMitigation product for both Stage and production env of Devstudio and we are looking to see our product on Stage Devstudio and Production Devstudio for the upcoming next release on Feb 1st [As per devstudio release.] and also our product is on QA Devstudio also. Pls let me know if you need anything.

Following is the associated repo.
https://github.com/Fiserv/fraud-mitigation

pls let me know if you have any Questions.

### Solution

Exposing the Fraud Mitigation from QA to Stage and PROD Externally

### Alternatives

I don't think we need any thing as alternate solution.

**Comment by minh-pham1** [comment]
Hello Kongara! We were in the process of promoting your tenant to our production environment but noticed that your Github branch `main` has still not been properly configured hence we deactivated it. Please update your github branch and let us know and we'll slate you to reenable it at a future date.

**Comment by sfiserv** [comment]
@kongaravinatha   I have to close this issue as your product is already enabled in production. However based on your new requirement to disable your product on stage and Production please create a new request we can expedite it with our next prod release.
