### ISSUE TITLE
Sandbox MID submitted on 1/11

### ISSUE THREAD

**Issue by jamiedwyer** [Fiserv/Support#614]
### Page

Workspaces -> Credentials

### Description

I created a MID for my dev team to test with in the sandbox environment on Jan 11 but it still hasn't been approved.  The MID is 100008000307746.  Please let me know if there's a reason it hasn't been approved so we can address it and continue with our development & testing.  (I realize this isn't a bug, but I don't see where else to submit this or how to contact support about it.  Please let me know if there's a better way to contact support about this.)

### Expected Behaviour

n/a

### Operating system

n/a

### Browser

n/a

**Comment by sfiserv** [comment]
@jamiedwyer can we know the enviornment this is being tested.
We can check this issue with the team who actually handles the MIDs.

**Comment by jamiedwyer** [comment]
Thank you for your help.  This merchant account is a sandbox test merchant in the Fiserv Developer Studio.  I’ve included a screenshot showing the details below, but let me know if you have more questions and we’ll get back to you right away.

Thank you,
Jamie

***@***.***

**Comment by sfiserv** [comment]
@jamiedwyer  I have contacted the team who actually looks into this issue. Will keep you posted once I hear from them.

**Comment by jamiedwyer** [comment]
Hi Supriya,
I’m following up to check if you received an update on our sandbox MID.

Thank you!
Jamie

**Comment by sfiserv** [comment]
@jamiedwyer  we have connected with the team who works on the MIDs. They was a issue related to their workflow due to which the MIds were not getting approved.
However they have fixed the issue now. Please try creating another sandbox mid which should be approved.

**Comment by jamiedwyer** [comment]
Hi Supriya,
We created another sandbox MID on 2/13, but it still hasn’t been approved.  We also noticed these MIDs are being created as Card Not Present, which is not the case.  These would be used exclusively for Card Present transactions on Clover terminals.

Can you ask the team who works on the MIDs to help look into this and explain what is preventing us from moving forward?

Thanks again for your help.

Jamie

**Comment by sfiserv** [comment]
@jamiedwyer you can connect with the Market Place team on this, they would be able to help you on this issue.

Please contact   amisha.damani@fiserv.com  for further details.
I am closing this issue from github for now.
