### ISSUE TITLE
Acceptance Solutions - APAC Testing APIs returns empty data

### ISSUE THREAD

**Issue by t0e** [Fiserv/Support#615]
### Product

Acceptance Solutions - APAC

### Page

Features -> Cloud Based Integration -> Sale with Local Payment Method

### Description

All the APIs except login request are returning the empty data.

E.g. API: `https://www.uat.fdmerchantservices.com/boardinggateway/cloudpoidp/PosPush/standardNonOpiProcess`

Payload:
`{
    "resquest": {
"merchantDetails":{
      "ain":"2100000",
      "billerId":"14",
      "merchantId":"42298585547594",
      "terminalId":"85547596",
      "mrchCountryCode":"036",
      "siteId":"",
      "workStationId":""
   },
   "transactionDetails":{
      "functionCode":"00",
      "customerRefNumber":"2511202203112022031",
      "merchantRefNumber":"2511202203112022031120220311202203112022031121323",
      "transactionId":"202211250950162",
      "reqDate":"25112022",
      "reqTime":"144955",
      "originalTranDate":"",
      "originalTranTime":"",
      "authCode":"",
      "rrn":"",
      "tokenId":"",
      "invoiceNumber":"",
      "batchNo":"",
      "amexSeNumber":"",
      "posEntryMode":"",
      "walletType":"",
      "walletId":"",
      "schemeId":"",
      "cardLastNumber":"",
      "primaryId":"",
      "customerName":"",
      "offlineFlag":"",
      "aTC":"",
      "tVR":"",
      "appLabel":"",
      "aID":"",
      "panSeqNo":"",
      "schemeTranInfo":"",
      "isInternalCall":null,
      "authenticationMethod":null
   },
   "amounts":{
      "authAmount":"56.39",
      "mrchDiscountAmt":".10",
      "convFee":".10",
      "cgst":"",
      "igst":"",
      "sgst":"",
      "gst":".10",
      "totalAmount":"56.59",
      "tranCurrency":"036",
      "tip":""
   },
   "additionalParams":{
      "udf1":"23133",
      "udf2":"21313",
      "callbackURL":"",
      "paramList":[
         {
            "param":"23",
            "param_lit":"param1 key"
         },
         {
            "param":"54",
            "param_lit":"param 2 key"
         }
      ]
   }
    }
}`

Response
`{
    "response": {
        "merchantDetails": {
            "ain": "",
            "billerId": "",
            "merchantId": "",
            "terminalId": "",
            "mrchCountryCode": "",
            "siteId": "",
            "workStationId": ""
        },
        "txnStatus": {
            "respCode": "",
            "response": "",
            "respMsg": ""
        },
        "txnDetails": {
            "functionCode": null,
            "customerRefNumber": null,
            "merchantRefNumber": null,
            "transactionId": null,
            "reqDate": null,
            "reqTime": null,
            "originalTranDate": null,
            "originalTranTime": null,
            "authCode": null,
            "rrn": null,
            "tokenId": null,
            "invoiceNumber": null,
            "batchNo": null,
            "amexSeNumber": null,
            "posEntryMode": null,
            "walletType": null,
            "walletId": null,
            "schemeId": null,
            "cardLastNumber": null,
            "primaryId": null,
            "customerName": null,
            "offlineFlag": null,
            "aTC": null,
            "tVR": null,
            "appLabel": null,
            "aID": null,
            "panSeqNo": null,
            "schemeTranInfo": null,
            "isInternalCall": null,
            "authenticationMethod": null,
            "voidCNP": null
        },
        "amounts": {
            "authAmount": "",
            "mrchDiscountAmt": "",
            "convFee": "",
            "cgst": "",
            "igst": "",
            "sgst": "",
            "gst": "",
            "totalAmount": "",
            "tranCurrency": "",
            "tip": ""
        },
        "dccInfo": {
            "dccIndicator": "",
            "dccCurrency": "",
            "dccAmount": "",
            "dccExchangeRate": ""
        }
    }
}`

### Expected Behaviour

Should return the correct information to proceed to the next step.

### Operating system

MacOS

### Browser

Google Chrome Version 120.0.6099.200

### Region

APAC

**Comment by sfiserv** [comment]
@t0e please contact Tarun Mittal for this issue via his email tarun.mittal@fiserv.com to revive the correspondence on this issue.

I am closing this issue from github for now.
