### ISSUE TITLE
TransferNow API details integrate in BankingHub workspace

### ISSUE THREAD

**Issue by bkandhas** [Fiserv/Support#616]
### Product

TransferNow

### Page

Workspace

### Description

We requested new Workspace for TransferNow.
Ticket : https://github.com/Fiserv/Support/issues/590 - received comments from Supriya, this ticket going to take time to implement.
So is it possible to integrate TransferNow API details to BankingHub workspace.as an alternative option.
if possible, could you please provide timeline for this request.

### Expected Behaviour

TransferNow API details integrate in BankingHub workspace. 

### Operating system

Windows

### Browser

Google Chrome

**Comment by sfiserv** [comment]
This enhancement cannot be implemented. This integration is not possible hence closing this ticket.
