### ISSUE TITLE
Developer Studio - Who We Serve is Blank

### ISSUE THREAD

**Issue by fiservsodas** [Fiserv/Support#617]
Developer Studio - "Who We Serve" was showing Blank page no matter how many times we refresh and reload. Believe it is fixed now but would help to look at the matter if it is not yet reported.

**Comment by sfiserv** [comment]
@fiservsodas can you please let us know the environment you are trying to access.

If its QA env please use this url: 
https://qa-developer.fiserv.com/ 

I am assuming you are using the incorrect url.

**Comment by fiservsodas** [comment]
It was in production site. It has resolved since. It was the same for myself & Ram for a sometime.. Again, want to ensure it works fine now but given it happened multiple times want to make sure sopmeone knows the root cause (if there's one)

**Comment by sfiserv** [comment]
Thank you for bringing this to our attention. Team is aware of this issue and we are doing an RCA. on this.

**Comment by sfiserv** [comment]
We have a fix which will be promoted to production in our upcoming Production release.

**Comment by minh-pham1** [comment]
Hello @fiservsodas thank you for catching this bug! It is pretty hard to reproduce so we had a hard time replicating it as well. The fix is now in production so we'll be closing this ticket but if you do encounter it again, please feel free to reopen this ticket and let us know!
