### ISSUE TITLE
date formats in documentation do not match what I'm getting back in /account/v4/search

### ISSUE THREAD

**Issue by jameyoverton** [Fiserv/Support#618]
### Product

Developer Studio - Issuer Solutions - Servicing - Search - /account/v4/search

### Page

Issuer Solutions - Servicing - Search - /account/v4/search

### Description

https://pl-cat.test.coop.org:443/fs/account/v4/search

request -  The commented date formats are the formats specified in the documentation.

{
    "common": {
            "user": "CSGUI",
            "accountId": "any account Id"
    },
    "selectFields": [
        "EXPR_DT",                          //MMYY
        "FRAD_STGY_CHNG_DT",                //YYMMDD
        "LAST_ADDR_CHNG_DT",                //YYMMDD
        "LAST_CRDT_LINE_CHNG_DT",           //MMYY
        "LAST_NMN_DT",                      //YYMMDD
        "LAST_PLST_DT",                     //YYMMDD
        "LAST_STMT_DT",                     //YYMMDD
        "LAST_STTS_CODE_CHNG_DT",           //YYMMDD
        "LFTM_HIGH_BAL_UPDT_DT",            //YYYYMMDD
        "NEXT_PYMN_DUE_DT",                 //MM-DD-YY
        "OPEN_DT"                           //MMYY
    ],
    "limitFieldCount": false,
    "odsNaming": true
}

Response:  Notice the date formats don't match what the documentation says they should be.  

 "accounts": [
        {
            "selectedFields": {
                "LAST_NMN_DT": "2023-11-16",
                "LAST_STTS_CODE_CHNG_DT": "000000",
                "NEXT_PYMN_DUE_DT": "2024-02-12",
                "FRAD_STGY_CHNG_DT": "2022-10-18",
                "OPEN_DT": "2008-03",
                "LFTM_HIGH_BAL_UPDT_DT": "00000000",
                "ACCT_ID": "xxxxx",
                "LAST_CRDT_LINE_CHNG_DT": "2008-03",
                "LAST_PLST_DT": "2021-05-31",
                "EXPR_DT": "2024-07",
                "LAST_STMT_DT": "2024-01-18",
                "LAST_ADDR_CHNG_DT": "2007-04-27"
            },
            "accountIdentifier": "xxxx"
        }
    ]

### Expected Behaviour

I would expect the date formats returned to match what is in the documentation.   The documentation seems to match the date formats I see in ODS.  But the dates returned from this endpoint aren't the same format.   I've tried ODS naming and the long form naming convention.

### Operating system

not applicable to OS.   found in Postman

### Browser

not applicable to browser.  found in Postman

**Comment by sfiserv** [comment]
@jameyoverton please connect with @eliascanaza on his email address for further correspondence     elias.canaza@fiserv.com

I am closing this issue from github.
