### ISSUE TITLE
Commerce Hub IFrame Integration Error

### ISSUE THREAD

**Issue by yamilrevilla** [Fiserv/Support#619]
### Product

Commerce Hub

### Page

Home > Commerce HubSecure Data Capture - iFrame v2 Integration Guide

### Description

I can't access the javascript file for the IFrame integration described in the documentatio page: 

```html
<script src="https://commercehub-secure-data-capture.fiservapps.com/v2/saq-a.js"></script>
```

I'm getting a 403 unauthorized response code when I include that HTML in my website. When I paste that URL in my browser I'm getting this: 

```xml

  | <?xml version="1.0" encoding="UTF-8"?>
-- | --
  | <Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>RJ2M44J8M1NMC0MH</RequestId><HostId>WSE0Dqfym3H1Upa3d/AO5/gavB1jdOgd9wt/d7oIIgxAa0B0oHCmXp8ImhoJT6HPaMxAD9V0SsM=</HostId></Error>
```

Is this a broken link? Do we need special access in order to view/download this file/url? 

### Expected Behaviour

The javascript file should be fine to access it. 

### Operating system

macOS Sonoma 4.2.1 (23C71)

### Browser

Microsoft Edge Version 121.0.2277.83 (Official build) (arm64)

**Comment by MAFiserv** [comment]
Hi the link needs to be updated. I will be working on this update soon. Please use this link 
https://commercehub-secure-data-capture.fiservapps.com/0.11.0/saq-a.js

**Comment by sfiserv** [comment]
@yamilrevilla  please contact @MAFiserv using his email address for  further correspondence
mashhood.ali@fiserv.com
I am closing this issue from github.
