### ISSUE TITLE
Grouping in API Explorer

### ISSUE THREAD

**Issue by fiservakshay** [Fiserv/Support#62]
**Is your feature request related to a problem? Please describe.**
Unable to segregate the APIs basis their domain names under the API Explorer.

**Describe the solution you'd like**
We want to have a domain wise grouping of APIs under the API Explorer. This grouping will help the end-users to navigate to the APIs basis their domain name. Please refer the attached screenshot below:
![image](https://user-images.githubusercontent.com/81968767/142356098-a0f45016-9a9c-48de-ba1d-c2e728f579e6.png)

**Describe alternatives you've considered**
n/a

**Additional context**
cc: @brittaho @bobburghardt @tsegurajimen

**Comment by TaniaSarkar89** [comment]
The Grouping for 'Integrated Banking' has been updated and is now available on our dev env.

**Comment by tsegurajimen** [comment]
API Explorer grouping is now displayed in the right way:

![image](https://user-images.githubusercontent.com/81706748/148462552-a10abd93-e26f-4c69-be86-f73bc586eaa7.png)

Closing the issue.
