### ISSUE TITLE
Cannot download Commerce Hub Resources

### ISSUE THREAD

**Issue by rholstad** [Fiserv/Support#620]
### Product

Commerce Hub

### Page

Home > Merchants > Commerce Hub > Charges

### Description

There are two downloads under Additional Resources, neither of which work.

Download API specifications
Download Postman collection

In Chrome, the download fails with a "Site wasn't available" error. In Safari, the download completes with a 93 byte .zip file that is not able to be uncompressed.

### Expected Behaviour

Downloads should begin and finish successfully and the zip package should be valid.

### Operating system

macOS Sonoma 14.2.1

### Browser

Google Chrome 121.0.6167.85

**Comment by sfiserv** [comment]
@rholstad  we are awarer of this issue and the fix will be in the Production by this week.

I will update you about it in this issue.

**Comment by minh-pham1** [comment]
Hello @rholstad! This has been reported in #610 and the fix has been deployed to our production environment. We will close this ticket but await validation from the user who reported the other ticket. However, feel free to drop a comment there if you still see the issue on your end. Thank you!
