### ISSUE TITLE
Commerce Hub Bad Request souce.pinBlock must not be null

### ISSUE THREAD

**Issue by rholstad** [Fiserv/Support#621]
### Product

Commerce Hub

### Page

https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Resources/API-Documents/Payments/Charges.md&branch=main#tab-source

### Description

Since at least late last week, Commerce Hub Charge requests have been failing with the error
```json
[
 {
  "type": "GATEWAY",
  "field": "source.pinBlock",
  "code": "107",
  "message": "Must not be null"
 }
]
```

The [documentation](https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Resources/API-Documents/Payments/Charges.md&branch=main#tab-source) does not mention a source.pinBlock parameter. When sending source.pinBlock as an empty string, the error is
```json
[
 {
  "type": "GATEWAY",
  "field": "source.pinBlock",
  "code": "100",
  "message": "Invalid or Missing Field Data"
 }
]
```

When sending source.pinBlock as an integer, boolean, or non-empty string, the error is
```json
[
 {
  "type": "GATEWAY",
  "field": "source.pinBlock",
  "code": "101",
  "message": "Unknown field data in object"
 }
]
```

When sending source.pinBlock as an Object matching the example for [Payment EMV PIN Based Transactions](https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/In-Person/Encrypted-Payments/EMV.md&branch=main#tab-json_example-1), the error is again 
```json
[
 {
  "type": "GATEWAY",
  "field": "source.pinBlock",
  "code": "107",
  "message": "Must not be null"
 }
]
```

### Expected Behaviour

Charge request should be successful

### Operating system

iOS 17.1.2

### Browser

iPhone SE

**Comment by minh-pham1** [comment]
Hello @rholstad! Seems like the Commerce Hub team might have missed updating this in their documentation. I'll assign this ticket to the relevant point of contact and they can assist you further. Thank you!

**Comment by rholstad** [comment]
@minh-pham1 I opened an analogous [issue](https://github.com/Fiserv/TTPPackage/issues/2) on the Tap to Pay SDK GitHub where the Engineering team has been working this problem.
