### ISSUE TITLE
ISO File Size Issue & Compliance Issue

### ISSUE THREAD

**Issue by NMIAB** [Fiserv/Support#622]
### Page

Integrations

### Description

We have encountered a possible bug that is affecting multiple ISO clients and is a compliance issue. It appears that massive records are being provided for certain clients with some files having over 2 million records and including vendors that are **not** part of that ISO's/Merchants portfolio.

These file sizes are 100s MBs with some totaling 1TB in size that are being provided,  andcurrently expose merchant information that does not belong to the particular ISO. 

An example is a single funding report that is 762 mb in size.

These are FiServ Client Line Enterprise files for clients such as Bams. An additional listing of clients can be provided if required. 

### Expected Behaviour

Files provided by FiServ should include information **only** specific to the ISO.
These files should not be 100s of MB in size and in the past have been kb - single digit mb in size.

### Operating system

Windows OS

### Browser

Google Chrome

### Region

USA

**Comment by sfiserv** [comment]
@NMIAB this support is exclusive for Developer Studio users only. Please let us know if this is a issue related to https://developer.fiserv.com/
