### ISSUE TITLE
Need to update application mapping to new URL for QA, Stage, Preview and Prod

### ISSUE THREAD

**Issue by tarunfiserv** [Fiserv/Support#625]
### Context

Our application server has migrated to the new server and FQDN and the portal is still mapping to the old application server URL. 
**https://stage-developer.fiserv.com/product/FirstVisionAPAC?branch=stage** , All the API on this page are giving **Sandbox error** whenever user tries to trigger them.

![image](https://github.com/Fiserv/Support/assets/100914278/9fe81505-0735-43e3-b5da-230280c18aa3)

### Solution

Please change the existing URL configured in portal from (**stg34.visionplus.io**) to (**stg34b.visionplus.io**) in QA, Stage, preview and production environment for application [](https://stage-developer.fiserv.com/product/FirstVisionAPAC).  After this, all the request will come to our new server.

### Alternatives

No other alternative.

### Region

Production

**Comment by sfiserv** [comment]
@russnicoletti  can you please take a look into this issue and let us know can this be aligned for sprint4 or next sprint5.

**Comment by russnicoletti** [comment]
@sfiserv I will get it into s4

**Comment by russnicoletti** [comment]
@tarunfiserv Should it also be changed in the dev environment?

**Comment by russnicoletti** [comment]
@tarunfiserv Can you confirm that in the QA environment, the full url should be "https://stg34b.visionplus.io/apisit"?

**Comment by sfiserv** [comment]
The changes are currently deployed to dev env and will be in QA env by Tuesday Feb27,2024

**Comment by sfiserv** [comment]
@tarunfiserv  please verify the changes in QA env.

**Comment by sfiserv** [comment]
@tarunfiserv our team has found an issue with your certificate and you need to fix it asap.
The certificate of the FirstVisionAPAC live sandbox server has expired. Also, the Common Name refers to stg34.visionplus.io instead of stg34b.visionplus.io
![image](https://github.com/Fiserv/Support/assets/87097017/b388b888-6923-45c8-a64b-1a1f292db629)

**Comment by tarunfiserv** [comment]
> @tarunfiserv our team has found an issue with your certificate and you need to fix it asap. The certificate of the FirstVisionAPAC live sandbox server has expired. Also, the Common Name refers to stg34.visionplus.io instead of stg34b.visionplus.io ![image](https://private-user-images.githubusercontent.com/87097017/310667911-b388b888-6923-45c8-a64b-1a1f292db629.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NTMyMTIsIm5iZiI6MTcxMTk1MjkxMiwicGF0aCI6Ii84NzA5NzAxNy8zMTA2Njc5MTEtYjM4OGI4ODgtNjkyMy00NWM4LWE2NGItMWExZjI5MmRiNjI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDA2MjgzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyNmMwMzJhZjJkOGI4ZDJiZDFlMjk2OGNlYzJhZTVlNjU1YzIxMjRhNjNkNzVmNjJlYjQ1YmVjNTI1NWUyMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H7vdu7iQcSQ8A5QYoSW3ns_-Q1ZC4vlFEeb9Ept89ik)

ok will change the certificate.

**Comment by tarunfiserv** [comment]
> @tarunfiserv our team has found an issue with your certificate and you need to fix it asap. The certificate of the FirstVisionAPAC live sandbox server has expired. Also, the Common Name refers to stg34.visionplus.io instead of stg34b.visionplus.io ![image](https://private-user-images.githubusercontent.com/87097017/310667911-b388b888-6923-45c8-a64b-1a1f292db629.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NTMyMTIsIm5iZiI6MTcxMTk1MjkxMiwicGF0aCI6Ii84NzA5NzAxNy8zMTA2Njc5MTEtYjM4OGI4ODgtNjkyMy00NWM4LWE2NGItMWExZjI5MmRiNjI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDA2MjgzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyNmMwMzJhZjJkOGI4ZDJiZDFlMjk2OGNlYzJhZTVlNjU1YzIxMjRhNjNkNzVmNjJlYjQ1YmVjNTI1NWUyMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H7vdu7iQcSQ8A5QYoSW3ns_-Q1ZC4vlFEeb9Ept89ik)

@sfiserv : ok, we will update the certificate.

**Comment by russnicoletti** [comment]
This issue has been resolved, the sandbox url was updated in S4 2024
