### ISSUE TITLE
API support for XP2

### ISSUE THREAD

**Issue by spoc-c3po** [Fiserv/Support#629]
### Context

We are service integrators who work with mostly credit unions , to provide agent experience solutions.
We have enquiry about possibility of integration with Fiserv xp2. 
I am unable to find any relevant documentation for this . 

Does xp2 have api support and is there a separate documentation for it , im sorry if this is a primitive sort of question but any help will be greatly appreciated?

### Solution

Documentation or sandbox for XP2 api support

### Alternatives

Any other way to move forward with this request.

### Region

United States

**Comment by minh-pham1** [comment]
Hello @spoc-c3po! Unfortunately, it looks like the XP2 team has not reached out to us to upload their API and other documentation on our Developer Studio as of today. You'll have to find their official website and use their Contact channels to get this documentation as we don't have a point of contact we can provide for you in this case. We wish you the best of luck and hopefully we can provide better documentation and support for your integration in the future!
