### ISSUE TITLE
Onboard a new tenant

### ISSUE THREAD

**Issue by rajlenin77** [Fiserv/Support#631]
### Name of your product / tenant

Hallpass

### Type of Tenant

Doc only

### Team Members

rajlenin77

### Bug Reporting

rajlenin77

### Feedback Reporting

rajlenin77

### Enhancement Reporting

rajlenin77

### Internal tenant

Yes

### Product of Carat

No

### Merchants solution area

No

### Customer Segments for Merchants

- [ ] SMB
- [ ] Enterprise

### Financial Institutions solution area

No

### Customer Segments for Financial Instituitions

- [ ] Bank
- [ ] Credit Union
- [ ] Large Financial Institution

### Fintech solution area

No

### Region of Operation

- [ ] North America
- [ ] EMEA
- [ ] LATAM
- [ ] APAC

### RESTful

Yes

### SDK

No

### Runbox

No

### Mock Sandbox

Yes

### Live Server

No

**Comment by sfiserv** [comment]
@rajlenin77 
Can you please let us know under which category/solution does your product "HallPass" needs to be included as
Is it Merchants or Financial Institute 
If you need more information please check our production "https://developer.fiserv.com/"
Please provide us this solutions asap.

**Comment by minh-pham1** [comment]
Also, just double checking that you do intend to be an Internal Tenant that only people with accounts (such as internal Fiserv team members like Commerce Hub, Banking Hub, etc.) can see your documents _or_ do you want your product to be viewable by anyone who comes to Developer Studio?

**Comment by sfiserv** [comment]
@rajlenin77 
We are still waiting to hear from you about the category your product needs to be in. We need this info asap. else we won't be able to enable your product in QA env. If you miss this week's window you will have to wait 2 more weeks ( complete next sprint) to access your product in QA.

**Comment by sfiserv** [comment]
@rajlenin77 please verify the changes in QA environment.
https://qa-developer.fiserv.com/product/Hallpass?branch=develop
I will send out the credentials for QA env separately.
<img width="985" alt="image" src="https://github.com/Fiserv/Support/assets/87097017/f28a1cad-bea0-466c-828a-351d793a958d">

**Comment by minh-pham1** [comment]
Marking as complete due to inactivity and work being done on our side.
