### ISSUE TITLE
Cross Linking of Documentation on Dev Studio 

### ISSUE THREAD

**Issue by fiservakshay** [Fiserv/Support#632]
Hi Team,

We have a requirement to display API documentation on Banking Hub tenant, when .md and YAML files are available on different tenant. 

The requirement is to display few APIs of BillPay within Banking Hub API documentation. Additionally, we do not want to copy .md or YAML files into BankingHub's repo as we will not be in sync with latest changes in original file. 
We tried to achieve this through "config/document-explorer-definition.yaml" file, but looks like we can only link files within same GitHub repo. Is there any workaround to link .md or YAML files from another GitHub tenant?

**Comment by sfiserv** [comment]
@minh-pham1  can you please help our @fiservakshay

**Comment by minh-pham1** [comment]
Hello Akshay! Sorry for the delayed response. I also tried various approaches on my end but ultimately, the decision to only include existing files in a tenant's repository is to ensure security (no linking to external sites or other documents in the left nav, where users might not realize where it's redirecting).

However, if you would like this as a straight up enhancement (being able to define in the `DED` a link to a document and/or API yaml a link to another API on another tenant to display as if it were your own), please feel free to open a separate enhancement ticket with that request. The response for this ticket specifically is `no`, I do not have any easy workaround or method to have this functionality within our current architecture. At best, you can create an MD that has a brief description and has a hyperlink to the other tenant's documentation on DevStudio for now.

**Comment by sfiserv** [comment]
@fiservakshay please refer to the comments from @minh-pham1 and open a separate ticket for this enhancement.
