### ISSUE TITLE
want to check fiserv integration in ios app in test env

### ISSUE THREAD

**Issue by BanaganapalliSwathi** [Fiserv/Support#635]
### Context

i want integrate fiserv payment gateway in my application to check how this works in ios

### Solution

Can you please provide the proper document to follow

### Alternatives

N?A

### Region

india

**Comment by sfiserv** [comment]
@BanaganapalliSwathi  are you looking something on DeveloperStudio application or looking for https://merchants.fiserv.com/india/eCommerce/?_ga=2.5184881.335879646.1709358087-1127956789.1709146987

This support group for Developerstudio application.
