### ISSUE TITLE
Back Button in All Data Aggregation Page is disabled while navigating from TransferNow Tenant

### ISSUE THREAD

**Issue by ManiBharathiNatarajan** [Fiserv/Support#636]
### Product

TransferNow

### Page

TransferNow->Getting Started

### Description

While navigating from Getting Started page to All Data Aggregation page, Back Button is disabled.

The same issue persist in SSL Authentication page.

https://github.com/Fiserv/Support/assets/153706962/89d8acbc-e1ec-44ae-9844-3395bd0c0fee

### Expected Behaviour

Back Button in All Data Aggregation page should be enabled so that we can again redirect to Getting Started page in TransferNow

### Operating system

Windows

### Browser

Google Chrome Version 120.0.6099.200

### Region

QA

**Comment by sfiserv** [comment]
Our team is working to get this issue fixed. We will update this issue once it is ready for testing.
