### ISSUE TITLE
VerifyNow Getting Started page is automatically fetched under TransferNow Title while redirecting from "Instant (Risk Database) Verification" to TransferNow.

### ISSUE THREAD

**Issue by ManiBharathiNatarajan** [Fiserv/Support#637]
### Product

TransferNow

### Page

TransferNow->Getting Started

### Description

VerifyNow Getting Started page is automatically fetched under TransferNow Title while redirecting from "Instant (Risk Database) Verification" to TransferNow.

https://github.com/Fiserv/Support/assets/153706962/97b1140b-60f3-43c7-911c-3a84ff7f1c28

### Expected Behaviour

While redirecting from VerifyNow to TransferNow tenant it should fetch TransferNow Getting Started Page Content.

### Operating system

Windows

### Browser

Google Chrome Version 120.0.6099.200

### Region

QA

**Comment by sfiserv** [comment]
@ManiBharathiNatarajan  this issue related to the browser back button. Same issue as mentioned in 636.
We are already looking into this issue. hence closing this issue.
