### ISSUE TITLE
404 Error is thrown while returning back to TransferNow tenant from Instant (Risk Database) Verification 

### ISSUE THREAD

**Issue by ManiBharathiNatarajan** [Fiserv/Support#638]
### Product

TransferNow

### Page

TransferNow->TN Integration Guide-> SSL Authentication

### Description

404 Error is thrown while returning back to TransferNow tenant from Instant (Risk Database) Verification & User Workflow
[SSL.zip](https://github.com/Fiserv/Support/files/14448790/SSL.zip)

### Expected Behaviour

It Should return back to SSL Authentication Page

### Operating system

Windows

### Browser

Google Chrome Version 120.0.6099.200

### Region

QA

**Comment by sfiserv** [comment]
@ManiBharathiNatarajan  this is the same issue as mentioned in 636 hence closing this github. Please refrain from creating new github issues for the same issue.
