### ISSUE TITLE
Network Token QA Environment is not able to take changes from development branch

### ISSUE THREAD

**Issue by prashantkumarfiserv** [Fiserv/Support#640]
### Product

Network Token

### Page

https://qa-developerstudio.fiserv.com/product/NetworkTokens

### Description

Changes merge on development branch are not reflected on qa developer studio.

### Expected Behaviour

once changes are merged on development branch it should get reflected on qa developer studio within a day.

### Operating system

mac

### Browser

Chrome, Safari

**Comment by sfiserv** [comment]
@prashantkumarfiserv can you plesae verify if qa environment is working to reflect changes for your product.

**Comment by sfiserv** [comment]
Closing this ticket since no new issues were reported by the Tenant.
