### ISSUE TITLE
The Account Types glossary is missing "MMA" as an Account Type

### ISSUE THREAD

**Issue by muscal** [Fiserv/Support#642]
It seems the Account Type glossary is missing the MMA account type.

https://developer.fiserv.com/product/BankingHub/docs/?path=docs/api-glossary.md&branch=main#tab-account_types
<img width="1405" alt="image" src="https://github.com/Fiserv/Support/assets/14338652/ce58ae51-4a85-4c0a-9685-b5499294da5e">

Noticed it was missing because MMA is listed as a valid enum in the response body of some of the Account related API calls

<img width="1030" alt="image" src="https://github.com/Fiserv/Support/assets/14338652/ca55540b-77f7-4428-a56d-96d7ecbdad95">

**Comment by sfiserv** [comment]
@muscal  please contact the Akshay Talekar ( akshay.talekar@fiserv.com)
Rahul Ravindra ( rahul.ravindra@fiserv.com)  and Gulnaz from Banking Hub team who manage the documents to be updated.
There is no changes that need to be done from Developer Studio.
