### ISSUE TITLE
Stage portal of FirstVision APAC is not showing API in API explorer.

### ISSUE THREAD

**Issue by tarunfiserv** [Fiserv/Support#644]
### Product

FirstVisionAPAC

### Page

All Financial Institutions -> FirstVisionAPAC -> API explorer

### Description

We are getting below error on stage portal while loading API Explorer page.
![image](https://github.com/Fiserv/Support/assets/100914278/ff0c0d0e-8a9a-47cd-9592-1dc7f9e29014)

Please check and fix. 

### Expected Behaviour

The API explorer should show all the API under version no. 1.9.0.

### Operating system

Windows 10

### Browser

Google Chrome 119.0.6045.159

### Region

Stage

**Comment by minh-pham1** [comment]
Hello @tarunfiserv! Thank you for bringing this issue to our attention. It seems that our elasticsearch index was out of date and didn't quite auto-update yet. I requested a manually reindexing and I do see your APIs populating on our `stage` environment now. Please validate and close the ticket if the issue has been resolved. Thank you!

**Comment by minh-pham1** [comment]
Marking as complete due to inactivity and work being done on our side.
