### ISSUE TITLE
Invalid Account Set Up Error - Charges API

### ISSUE THREAD

**Issue by pmaniyath** [Fiserv/Support#646]
### Product

Commerce Hub

### Page

API > Payments > Charges

### Description

 We are creating an API for charges request from Dot net core. We used below details for testing 

URL : https://cert.api.fiservapps.com/ch/payments/v1/charges
Method : POST
Request Content : 

{
        "amount": {
        "total": 12.04,
        "currency": "USD"
         },
         "source": {
        "sourceType": "PaymentCard",
        "card": {
             "cardData": "4005550000000019",
             "expirationMonth": "02",
             "expirationYear": "2035"
           }
         },
         "transactionDetails": {
        "captureFlag": true,
        "merchantInvoiceNumber": "123456789012"
         },
         "transactionInteraction": {
        "origin": "ECOM",
        "eciIndicator": "CHANNEL_ENCRYPTED",
        "posConditionCode": "CARD_NOT_PRESENT_ECOM"
         },
         "merchantDetails": {
        "terminalId": "10000001",
        "merchantId": "100008000003683"
         }
        }

This one always returns :  {"type":"GATEWAY","code":"200","message":"Invalid account setup"}

Other services including credentials and transaction-inquiry is working . Is there anything needs to be taken care with account settings ? Any solution or pointers would help us.

API-KEY Used : A8ROqJST3PX21zcbSOIsRzOTz6CEPJG6
API-SECRET : 3XxrXY1NK9AgJez9G0k5wCAkNOUXyBzS2qAKKNTphAf

Features Selected for account : 
Data as a Service: Return Optimizer
Data as a Service: Enhanced Data
Payments
Payments: Value Added Services

### Expected Behaviour

201 . Payment created .

### Operating system

Windows 10 Enterprise 64-bit

### Browser

Version 122.0.6261.129 (Official Build) (64-bit)

### Region

Asia , India

**Comment by minh-pham1** [comment]
Hello @wwfiserv! Could you take a look at this ticket and connect with them as necessary? Thank you.

**Comment by wwfiserv** [comment]
@pmaniyath can you try these test cards https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Resources/Guides/Testing/Test-Scripts/Test-Scripts.md&branch=main

**Comment by pmaniyath** [comment]
@wwfiserv still facing the same issue with above test cards.

**Comment by wwfiserv** [comment]
@pmaniyath is this for a sandbox account, cert e2e or production merchant account?

**Comment by pmaniyath** [comment]
@wwfiserv this is for sandbox account
