### ISSUE TITLE
Link and Images are not loaded in Transfernow and Verifynow tenant

### ISSUE THREAD

**Issue by bkandhas** [Fiserv/Support#647]
### Product

TransferNow, Veriynow

### Page

Home -> Financial Institutions -> Transfer Now

### Description

Both Transfernow and Verifynow tenant, images and links not working.

### Expected Behaviour

Images and Links should work

### Operating system

Windows

### Browser

Google Chrome

**Comment by bkandhas** [comment]
<img width="941" alt="image" src="https://github.com/Fiserv/Support/assets/146924994/132d5ef0-024b-402b-89a8-cd8e49b891b9">

**Comment by minh-pham1** [comment]
Hello @bkandhas! We purposefully do not support rendering and parsing URLs for images. If you would like to use images, please make sure to upload them to your `assets` folder (as I see you've already done) and referencing them using tree format (i.e. in `docs/verifynow-account-verification-method.md` you would want to use `../assets/images/<image_name>.png` and for `docs/getting-started/know-our-standard-api-structure.md` you would want to use `../../assets/images/<image_name>.png`).

Please give this change a try and let us know if you still encounter any issues. Thank you!

**Comment by minh-pham1** [comment]
Hello! After some additional investigation, we believe that one of our configuration change may have blocked the browser from being able to render images. We have reverted this change and images should load again. Apologies for the inconvenience! You can continue to render images using any of the previous methods as usual and disregard my earlier comment.

**Comment by ManiBharathiNatarajan** [comment]
Hi @minh-pham1, In TransferNow & VerifyNow tenant still some of the functionalities like tab, scrolling from left to right & vice versa, collapsible designs are also not working. Can you pl check it again from your end.

<img width="717" alt="image" src="https://github.com/Fiserv/Support/assets/153706962/901b3062-63bb-468b-a32f-e81dd61254a7">
<img width="791" alt="image" src="https://github.com/Fiserv/Support/assets/153706962/1515b9b7-e08e-4b20-b91e-a1b938722d29">
<img width="770" alt="image" src="https://github.com/Fiserv/Support/assets/153706962/9acefe29-0932-4993-a045-4f50e15c3245">
<img width="712" alt="image" src="https://github.com/Fiserv/Support/assets/153706962/1fa5c373-46c7-482a-80b5-18394ed1d8db">

**Comment by minh-pham1** [comment]
Hello @ManiBharathiNatarajan! I believe that these are 2 different bugs other than the original issue. For the sake of documentation and process, could you kindly close this issue (regarding the images not working) and create two separate bugs with the screenshots you provided and URLs to their respective pages? It'll make it easier for me to divide and assign with to the developers that can investigate and follow-up with you.

- Doc functionalities not working: Card scrolling and collapsible text labels (you mentioned `Tabs` which I'm assuming is the cards scrolling?)
- Doc URL redirection throwing 404

Thank you for your help!

**Comment by ManiBharathiNatarajan** [comment]
Hi @minh-pham1 Still some of the images are not rendering in TransferNow tenant. Can you pl check?

<img width="960" alt="image" src="https://github.com/Fiserv/Support/assets/153706962/24df0f53-2026-4c46-bd04-841e29ae6903">

**Comment by ManiBharathiNatarajan** [comment]
Hi @minh-pham1 I have created two new issues & tagged here for your reference.
https://github.com/Fiserv/Support/issues/651 & https://github.com/Fiserv/Support/issues/652

**Comment by minh-pham1** [comment]
> Hi @minh-pham1 Still some of the images are not rendering in TransferNow tenant. Can you pl check?

Hello Mani!

It seems there is an issue when attempting parse img src using the file tree pattern ... Could you kindly update images to use either of these 2 formats?
- `src="raw"`: Get the full github filepath to fetch from raw
  - ex: https://github.com/Fiserv/transfer-now/blob/0407246361c8c36dc0c9fac40664a1e7c07a570d/docs/debit-card-transaction.md?plain=1#L32
-  `![<alt_text>]("../../assets/images")`: Use the relative tree path with this MD formatting
  - ex: https://github.com/Fiserv/transfer-now/blob/develop/docs/getting-started/resp-webdesign.md

**Comment by minh-pham1** [comment]
> Hi @minh-pham1 I have created two new issues & tagged here for your reference. #651 & #652

Perfect, I'll be sure to get them assigned to the appropriate team members and send updates on the respective tickets as they progress. Thank you so much for your help.

**Comment by minh-pham1** [comment]
Marking as complete due to inactivity and issue having been fixed.
