### ISSUE TITLE
Example added in SwaggerHub file is not reflecting on Portal

### ISSUE THREAD

**Issue by fiservakshay** [Fiserv/Support#65]
# Reporting new issue for Integrated Banking

**Page**
 Parameters tab under API Explorer section.
API documentation link: https://dev-developerstudio.fiserv.com/product/IntegratedBanking/api/?type=put&path=/credits

**Describe the bug**
A sample JSON code added under the **example:** tag in SwaggerHub file is not reflecting on Dave Studio portal. The same example is displaying fine on SwaggerHub output. 

Please refer the attached image for your reference.
![image](https://user-images.githubusercontent.com/81968767/143849448-fdbc0a72-9214-4c08-9838-a1c4c175f53c.png)

**To Reproduce**
Go to: https://dev-developerstudio.fiserv.com/product/IntegratedBanking/api/?type=put&path=/credits

**Expected behavior**
Example added in SwaggerHub file should display on Dev Studio portal.

CC: @tsegurajimen @brittaho

**Comment by tsegurajimen** [comment]
Work session with Tania - fixed by changing our code (adding examples under schema instead the parameter directly)

**Comment by tsegurajimen** [comment]
Example for EFX Header looks good now in dev environment pending to be displayed in PROD accordingly: 
![image](https://user-images.githubusercontent.com/81706748/148462233-7a4ee38d-c5ed-4d68-b52d-a0eb99bc0011.png)
Closing the issue.
