### ISSUE TITLE
Doc functionalities not working: Card scrolling, Tab and collapsible text labels in TransferNow and VerifyNow

### ISSUE THREAD

**Issue by ManiBharathiNatarajan** [Fiserv/Support#651]
### Product

TransferNow and VerifyNow

### Page

TransferNow and VerifyNow

### Description

Doc functionalities not working: Card scrolling, Tab and collapsible text labels in the entire TN & VN tenant.

[VerifyNowTenant.zip](https://github.com/Fiserv/Support/files/14742848/VerifyNowTenant.zip)
[TransferNowTenant.zip](https://github.com/Fiserv/Support/files/14742937/TransferNowTenant.zip)

### Expected Behaviour

If we click the dots below the image it should load the respective content
<img width="960" alt="image" src="https://github.com/Fiserv/Support/assets/153706962/c24f92a2-c433-4aee-82a0-5217b52bbfc9">

If we click the + button it should expand
<img width="960" alt="image" src="https://github.com/Fiserv/Support/assets/153706962/af7db717-ef16-4e29-bea2-5f7478510394">

### Operating system

Windows

### Browser

Google Chrome Version 120.0.6099.200

### Region

QA

**Comment by minh-pham1** [comment]
Hello! We are actively working on a fix and are tracking it as part of https://firstdatateam.atlassian.net/browse/PORT-10348. Thank you for your patience.

**Comment by minh-pham1** [comment]
This issue has been fixed on our `dev` environment and will be moving up following our regular deployment schedule. Thank you for your cooperation!

**Comment by minh-pham1** [comment]
Quick update: The fix has been pushed to our `qa` environment and will be on `stage` tomorrow after deployment.

**Comment by minh-pham1** [comment]
Quick update: The fix has been pushed to our `stage` environment!

**Comment by minh-pham1** [comment]
Production deployment has been completed and the issue should now be fixed. Please verify! Thank you for your patience.
