### ISSUE TITLE
Doc URL redirection throwing 404: Navigating from TransferNow to VerifyNow

### ISSUE THREAD

**Issue by ManiBharathiNatarajan** [Fiserv/Support#652]
### Product

TransferNow

### Page

TransferNow>Getting Started

### Description

All the URL's throwing 404 Error, While Navigating from TransferNow to VerifyNow tenant.
[navigationfromTNtoVN.zip](https://github.com/Fiserv/Support/files/14743082/navigationfromTNtoVN.zip)

### Expected Behaviour

It should navigate to the respective destination.

### Operating system

Windows

### Browser

Google Chrome Version 120.0.6099.200

### Region

QA

**Comment by minh-pham1** [comment]
Hello @ManiBharathiNatarajan! I believe this issue should be fixed. Please validate and let us know if you're still encountering it.

Please note that on `stage` and `prod` environment, the link for [Instant (Risk Database) Verification](https://developer.fiserv.com/product/VerifyNow/docs/?path=docs/verifynow-account-verification-method/instant-verification.md&branch=develop) includes a hard coded `&branch=develop` which will cause issues. To avoid this, please do not include the URL branch parameter.
