### ISSUE TITLE
Onboard a new tenant

### ISSUE THREAD

**Issue by mhaar-finact** [Fiserv/Support#653]
### Name of your product / tenant

CashFlow Central

### Type of Tenant

Doc only

### Team Members

mhaar-finact, DHunnewell

### Bug Reporting

mhaar-finact, DHunnewell

### Feedback Reporting

mhaar-finact, DHunnewell

### Enhancement Reporting

mhaar-finact, DHunnewell

### Internal tenant

No

### Product of Carat

No

### Merchants solution area

No

### Customer Segments for Merchants

- [ ] SMB
- [ ] Enterprise

### Financial Institutions solution area

Yes

### Customer Segments for Financial Instituitions

- [X] Bank
- [X] Credit Union
- [X] Large Financial Institution

### Fintech solution area

Yes

### Region of Operation

- [X] North America
- [ ] EMEA
- [ ] LATAM
- [ ] APAC

### RESTful

Yes

### SDK

No

### Industry

Banking, Small Business

### Runbox

Yes

### Mock Sandbox

Yes

### Live Server

No

**Comment by minh-pham1** [comment]
Hello @mhaar-finact! 

Work for this ticket is being tracked under https://firstdatateam.atlassian.net/browse/PORT-10431 and should be live on our `qa` environment 2 weeks from today (deployment will be completed by 4/8 barring any unexpected issues). 

Credentials to access our `qa` environment and the invite to get Write access for your product's Github repository will be sent separately. Thank you!

**Comment by minh-pham1** [comment]
Just double checking, you do want to be listed as a `Doc only` product correct? I.e you do not need a runbox to mock any APIs nor provide any API specification files?

Just wanted to make sure, it's not a blocker but we noticed that you did mark `Runbox` and `Mock sandbox` as `true`.

**Comment by mhaar-finact** [comment]
Per our conversation, sounds like this needs to be a full sandbox - but also seems like there is an issue within documentation.

<img width="787" alt="image" src="https://github.com/Fiserv/Support/assets/98828569/b04c3c31-cb46-43d1-9c1e-32a393592ec8">

**Comment by mhaar-finact** [comment]
Can we please take the repo private that was created?  This product is under development and requires NDA / proprietary info that I'd like to have not open to the world (we will be using gated content).

**Comment by minh-pham1** [comment]
Product has been onboarded onto `dev` and `qa` environments. Closing ticket as complete, please feel free to reopen as needed. Thank you!
