### ISSUE TITLE
Enable ConnectPay in Stage

### ISSUE THREAD

**Issue by paulmohljr** [Fiserv/Support#655]
### Context

Need to Enable ConnectPay Repo in Stage

### Solution

Enable ConnectPay in Stage

### Alternatives

None

### Additional Context

Github code is already there 

### Region

US

**Comment by minh-pham1** [comment]
Hello @paulmohljr! We generally keep our `stage` and `prod` environments in sync as much as possible. Essentially, you can treat `stage` as a 1 week promotion period. If you would like to proceed, please make sure your Github branches `stage` and `main` are both up to date/synced with your `develop` and has all the documents and configs you need to be promoted!

If this is not the intended process you would like, please let us know and we can discuss in further details.

**Comment by paulmohljr** [comment]
Understood. When can I expect Connectpay to be available in stage-developer.fiserv.com? Currently, it is not enabled for me to do a pass-thru to prepare for the production launch

**Comment by minh-pham1** [comment]
Hello @paulmohljr! Sorry I must have missed this comment, you can expect to see it live on our `stage` environment this Thursday (4/18)

**Comment by minh-pham1** [comment]
Closing ticket as product has been promoted to `stage`. Please feel free to reopen the ticket as needed. Thank you!
