### ISSUE TITLE
Pull request not completed

### ISSUE THREAD

**Issue by bkandhas** [Fiserv/Support#656]
### Product

TransferNow

### Page

Pull Request

### Description

I have created merge request and validation not completed.
PR Request : https://github.com/Fiserv/transfer-now/pull/517

### Expected Behaviour

Validation should complete.

### Operating system

Windows

### Browser

Google Chrome

**Comment by russnicoletti** [comment]
Hello @bkandhas, sometimes the PR validators don't get invoked by GitHub. Can you try making one more change to the PR (for example, adding a space to the end of a line)? This will hopefully cause the validators to be run.

**Comment by minh-pham1** [comment]
Hello @bkandhas! Apologies for the issue with the validators, we had a brief issue with our github workflow that has since been fixed. I've reran the validators for you so you should now be able to merge.

**Comment by minh-pham1** [comment]
Marking as complete due to inactivity and issue seeming to be resolved.
