### ISSUE TITLE
Pull Request Not Completed

### ISSUE THREAD

**Issue by MalathiL15** [Fiserv/Support#657]
### Product

VerifyNow

### Page

Pull Request

### Description

I have created merge request and validation not completed.
PR Request: https://github.com/Fiserv/verifynow/pull/403

### Expected Behaviour

Validation should complete

### Operating system

windows

### Browser

Google Chrome

**Comment by minh-pham1** [comment]
Hello @MalathiL15! Apologies for the issue with the validators, we had a brief issue with our github workflow that has since been fixed. I've reran the validators for you though there does seem to be an issue with your `openapi.yml` so please take a look and resolve at your convenience. Thank you!

**Comment by minh-pham1** [comment]
Marking as complete due to inactivity and issue seeming to be resolved.
