### ISSUE TITLE
Subscription Email Notification

### ISSUE THREAD

**Issue by kcaramat** [Fiserv/Support#658]
### Product

Specification Portal

### Page

Specification Portal

### Description

I made an update to the Offsite Specification file and markdown page in GitHub. Notifications are enabled on but I didn't receive a Subscription Notification. Attached is an example of a past Subscription Notification received. 
[Developer Studio from Fiserv - Subscription Notification.pdf](https://github.com/Fiserv/Support/files/14779567/Developer.Studio.from.Fiserv.-.Subscription.Notification.pdf)

### Expected Behaviour

A Subscription Notification should be received when an update is made to the file or page.

### Operating system

N/A

### Browser

Google Chrome

**Comment by minh-pham1** [comment]
Just for clarification, are these the notifications you are referring to?

![Screenshot 2024-03-27 at 11 24 34 AM](https://github.com/Fiserv/Support/assets/114534554/ce0ba1ef-9d0b-45ca-8d13-6d8ec016db18)
![Screenshot 2024-03-27 at 11 24 45 AM](https://github.com/Fiserv/Support/assets/114534554/288a9e9b-4bb0-4cec-a493-44bbd039eea8)

**Comment by kcaramat** [comment]
No, I'm referring to the attached example Developer Studio from Fiserv - Subscription Notification.pdf document I uploaded to the ticket.

**Comment by minh-pham1** [comment]
I'm trying to confirm the functionality that you expect to trigger this behavior. But it sounds like that this is the Notifications you are referring to. I'll assign the ticket to a developer soon, thank you.

**Comment by yanyan-cathy** [comment]
A ticket is created for this issue https://firstdatateam.atlassian.net/browse/PORT-10481, thanks!
