### ISSUE TITLE
Updated File Versions and the My Documents section

### ISSUE THREAD

**Issue by kcaramat** [Fiserv/Support#659]
### Product

Specification Portal

### Page

Workspace - My Document Section

### Description

When a old file is replaced with an updated version, the old file still shows under My Documents. Since the old file was deleted, the user will receive an error if they attempt to download from the My Documents section.

### Expected Behaviour

If the file still exists in Git Hub allow the user to download. If it was deleted they should be prompted that this is an old version of the file that is no longer available. 

### Operating system

N/A

### Browser

Google Chrome

**Comment by yanyan-cathy** [comment]
A ticket is created https://firstdatateam.atlassian.net/browse/PORT-10482 for this issue, thanks!

**Comment by jimtie** [comment]
We may need to add 2 more columns:
- Status (show if the file still available or removed)
- A link to go to the MD page
