### ISSUE TITLE
Inaccurate Breadcrumb Trail 

### ISSUE THREAD

**Issue by fiservakshay** [Fiserv/Support#66]
# Reporting new issue for Integrated Banking

**Page**
Any documentation or API Explorer page.

**Describe the bug**
A breadcrumb trail is not showing the complete path of the active page. It just shows the title of active page inside the Integrated Banking, rather than showing the exact location of the page as per the left-nav pane.
Please refer to the following screenshots for your ready reference.

**Example 1:** Documentation section
![image](https://user-images.githubusercontent.com/81968767/144789541-77ea0f8e-e104-441d-8253-d92b6accba0c.png)

**Example 2:** API Explorer section
![image](https://user-images.githubusercontent.com/81968767/144790056-6611d221-2e79-43e4-ab0d-3b900f9bba59.png)

**To Reproduce**
Go to any documentation or API Explorer page of Integrated Banking tenant.

**Expected behavior**
A breadcrumb trail should show the complete path of the active page (as per the left-nav pane) so that user can understand the exact location of the page.

cc: @tsegurajimen @brittaho 

@brittaho I have marked the priority/severity to Medium, please add a comment for Alvin, if you want this issue to be addressed before the beta launch.

**Comment by tsegurajimen** [comment]
In addition is important to mention that we want the Domain to be displayed in each of the APIs, as it follows the breadcrumb trail:
In that case for example we want it to appear as : Cards then Card Service and then the name of the API. (CardAdd for example)
![image](https://user-images.githubusercontent.com/81706748/145257204-f3803f48-8df0-4696-8e68-6fe5a6df0cd1.png)
Thanks in advance!

**Comment by jimmychen-fiserv** [comment]
According to NN group, breadcrumb should only include real pages and no category name. Which means each item in the trail should be clickable and link to a real page. We will review it again in the next month, although we believe what we have is the best solution so far.

https://www.nngroup.com/articles/breadcrumbs/

**Comment by fiservakshay** [comment]
> According to NN group, breadcrumb should only include real pages and no category name. Which means each item in the trail should be clickable and link to a real page. We will review it again in the next month, although we believe what we have is the best solution so far.
> 
> https://www.nngroup.com/articles/breadcrumbs/

Ah, got it! It make sense to have only clickable items in breadcrumb.

Actually, our major concern was - when user clicks a hyperlink and redirected to a new page in the same window, it's hard to guess the exact location of that page in left-side nav pane. And we thought the complete breadcrumb trail will do the work here.

I was wondering if we could able to highlight the active topic in the left-side nav pane even if opened through a hyperlink. Presently, if you click a hyperlink, a new page opens in the same window and the left-side nav pane doesn't change. 
This alternative solution will also address the issue.

For example, if I click a hyperlink from one of the topic from Documentation section, which redirects me to the API in API Explorer. And as you can see in below screenshot it is hard to guess where that API is located in the left-nav pane.

![image](https://user-images.githubusercontent.com/81968767/150282595-9e2ce718-1408-46b6-a112-f6b2ced94963.png)


CC: @acho-fiserv

**Comment by tsegurajimen** [comment]
@jimmychen-fiserv Do you status of this one?

**Comment by jimmychen-fiserv** [comment]
Thank you for the feedback. We have a ticket for this problem and will work on it in this sprint. Here is the link for your reference: https://firstdatateam.atlassian.net/browse/PORT-2702. Thanks

**Comment by tsegurajimen** [comment]
Moving this ticket to sprint 6

**Comment by tsegurajimen** [comment]
Hi @jimmychen-fiserv please let us know if you have any update on this ticket please! 

cc: @fiservakshay

**Comment by jimmychen-fiserv** [comment]
@tsegurajimen This has been moved to Sprint-7. Will enable the left nav expanded when open a new Doc or API explorer link.

**Comment by tsegurajimen** [comment]
Great thanks a lot @jimmychen-fiserv!

**Comment by tsegurajimen** [comment]
Hi @jimmychen-fiserv do you have any update on this ticket?

**Comment by jimmychen-fiserv** [comment]
@tsegurajimen Yes! Just checked with our developer. Now if you open an URL, the left nav will be expanded and the list item is highlighted. Ex: https://dev-developerstudio.fiserv.com/product/BankingHub/api/?type=post&path=/cards

**Comment by tsegurajimen** [comment]
This looks just great! Please find some screenshots below where we can see left nav is expanded as expected:

https://dev-developerstudio.fiserv.com/product/BankingHub/api/?type=post&path=/address
![image](https://user-images.githubusercontent.com/81706748/162031828-a3dd9f90-e56f-45a2-b559-61026445f6b8.png)

https://dev-developerstudio.fiserv.com/product/BankingHub/docs/?path=docs/banks-and-CU/bank-servicing.md
![image](https://user-images.githubusercontent.com/81706748/162031906-84da779a-9691-4583-99ec-246cc232b8f8.png)

Thanks a lot @jimmychen-fiserv
