### ISSUE TITLE
Sorting - My Document Section

### ISSUE THREAD

**Issue by kcaramat** [Fiserv/Support#660]
### Product

Specification Portal

### Page

My Document Section

### Description

The documents within the My Document Section are sorted in a random order.

### Expected Behaviour

They should be sorted Newest to Oldest by the last downloaded date.

### Operating system

N/A

### Browser

Google Chrome

**Comment by minh-pham1** [comment]
Can you provide a screenshot? The documents you mention require access requests which our developers may not be able to replicate otherwise.

**Comment by kcaramat** [comment]
Attached is the screenshot.

![My Documents_Last Downloaded Sorting](https://github.com/Fiserv/Support/assets/101660924/f76e4fcc-1c04-4939-9930-6151d68529be)

**Comment by minh-pham1** [comment]
Default seems to be ascending alphabetical order (requestFile is last because lower case `r` is considered farther down the alphabet). You can change the sorting by clicking on the corresponding column header.

Unless you're requesting for an enhancement to change the default filter to be by `Last Downloaded` column then please update the description  and issue label for clarity as we sort it out for our developer to fix. Thank you!

**Comment by yanyan-cathy** [comment]
Yes, I have checked this issue too. Currently, the files are sorted by docName in ascending order by default, please let me know if you would like to change it, thanks!

**Comment by kcaramat** [comment]
If it could be changed to sort newest to oldest based on the Last Downloaded column.

Thank you,

Kristina Caramat
Program Manager
Client Certification
Office: 754.320.7941

Fiserv
World’s Most Admired Companies™ 2024 | Fortune® Magazine
Join us at Forum 2024 | September 29–October 1 <https://www.fiserv.com/en/forum.html?cid=link|outlook|forum2024||emailsignature>
Fiserv<https://www.fiserv.com/?cid=link|fiservsignature|fiservlink||> | Join Our Team<https://www.careers.fiserv.com/?utm_source=outlook&utm_medium=email&utm_campaign=signature> | LinkedIn<https://www.linkedin.com/company/fiserv/> | Facebook | Instagram
<https://www.facebook.com/Fiserv/>
©2024 Fiserv Inc. or its affiliates. Fiserv is a registered trademark of Fiserv Inc. Privacy Notice
<https://www.fiserv.com/en/about-fiserv/privacy-notice.html?cid=link|fiservsignature|privacypolicy||>From Fortune. ©2024 Fortune Media IP Limited. All rights reserved. Used under license.

**Comment by yanyan-cathy** [comment]
the change is made and available on Dev now, thanks
