### ISSUE TITLE
Report a Bug Flow

### ISSUE THREAD

**Issue by kcaramat** [Fiserv/Support#661]
### Product

Specification Portal

### Page

Specification Portal

### Description

Tested the 'Report a Bug' flow when a file is missing in GitHub and received an email of the issue needing to be addressed versus a C360 ticket as originally discussed. 

### Expected Behaviour

A C360 notification would be created needing to be addressed via a ticket versus email. 

### Operating system

N/A

### Browser

Google Chrome

**Comment by yanyan-cathy** [comment]
The c360 feature is still under development, please keep using the Github to report the bug for now. I will give you updates once the C360 feature is available to use, thank you!
