### ISSUE TITLE
Document Updates Link Notifcation

### ISSUE THREAD

**Issue by kcaramat** [Fiserv/Support#663]
### Product

Specification Portal

### Page

Specification Portal

### Description

Under Account -> Notifications -> Document Updates -> Link within the notification. The notification says 'leaving Developer Studio' but the link takes you back to another Dev Studio Page.

### Expected Behaviour

Verbiage should be updated to remove leaving Developer
![Untitled picture](https://github.com/Fiserv/Support/assets/101660924/07e32c11-89b2-45fe-8793-eeb5302e0c1a)
 Studio.

### Operating system

N/A

### Browser

Google Chrome

**Comment by yanyan-cathy** [comment]
A ticket https://firstdatateam.atlassian.net/browse/PORT-10488 is created for this issue, thanks!

**Comment by yanyan-cathy** [comment]
implementation is done, the change is in DEV env now, thank you!
