### ISSUE TITLE
Release Notes in Banking Hub Error

### ISSUE THREAD

**Issue by fiservsodas** [Fiserv/Support#665]
Release Notes in Banking Hub does not navigate or show any data across any quarter. The page does not have any data.

**Comment by minh-pham1** [comment]
Hello! I do see that there are various release notes published on our Developer Studio such as [this one](https://developer.fiserv.com/product/BankingHub/docs/?path=docs/release-notes/ESF%20Release%20Notes%202023.3.md&branch=main). However, I'm not entirely sure what the issue you are referring to is.

Could you provide more details, description, URLs, and/or screenshots to further help us investigate this issue?

**Comment by fiservsodas** [comment]
Please navigate the Release Notes tabs in Banking Hub and you will know what I am talking about.

**Comment by minh-pham1** [comment]
Unfortunately, I'm still not entirely sure what the issue you're referring to is precisely. I can see two potential questions:

1. `2023_Q2` and `2024_Q1` have "Information is not available": This is controlled by the Banking Hub team, I can ask them to update as needed.
2. Core tabs such as `Premier`, `Precision`, `Signature`, etc. cannot be viewed on each Release Note: This is a bug whose fix is being hotfixed up to stage within this week (and will be going out as part of our `production` deployment barring any other issues or unforeseen circumstances).

If neither of these questions are what you're referring to, please let me know and I'll see what I can find out.

https://github.com/Fiserv/Support/assets/114534554/a1762467-c0c3-4170-a21f-afdec2595e8a
