### ISSUE TITLE
Tabs are not working on Dev Studio 

### ISSUE THREAD

**Issue by MAFiserv** [Fiserv/Support#668]
### Product

Commerce Hub

### Page

The tabs are not working on Dev Studio  Ex https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Online-Mobile-Digital/3D-Secure/3DS-Request.md

### Description

The tabs are not working on Dev Studio 
Ex https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Online-Mobile-Digital/3D-Secure/3DS-Request.md

### Expected Behaviour

The tabs are not working on Dev Studio, when clicking on tab it should show the fields however it is not and just loading 
Ex https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Online-Mobile-Digital/3D-Secure/3DS-Request.md

### Operating system

Windows

### Browser

Chrome 

### Region

US

**Comment by minh-pham1** [comment]
Hello @MAFiserv, thanks for letting us know. We have a duplicate bug issue under !651 which is being actively tracked and updated. Please refer there for any updates, sorry for the inconvenience!
