### ISSUE TITLE
Promote Global Currency Solution to Stage and Production

### ISSUE THREAD

**Issue by prashantkumarfiserv** [Fiserv/Support#669]
### Context

Global Currency Solution is available on QA. Please promote it to stage and production.
Repository: https://github.com/Fiserv/global-currency-solutions

### Solution

Global Currency Solution is available on QA. Please promote it to stage and production.
Repository: https://github.com/Fiserv/global-currency-solutions

### Alternatives

Global Currency Solution is available on QA. Please promote it to stage and production.
Repository: https://github.com/Fiserv/global-currency-solutions

**Comment by minh-pham1** [comment]
Hello @prashantkumarfiserv! I've assigned it to a developer and the script will be made this sprint, tracked under https://firstdatateam.atlassian.net/browse/PORT-10760. Please expect to see your product on `stage` and `prod` on 5/2 and 5/9 respectively. 

As a note, please make sure to update your Github branches `stage` and `main` with the latest code and documents to ensure a smooth promotion. If `tenant.json` is missing the proper configurations and information, this may result in your product failing to be added during our `stage`/`prod` release and potentially requiring us to disable it.

**Comment by minh-pham1** [comment]
Hello! We have promoted your product to `prod`. We did see that you did not push any updated configs/documents onto your Github `main` branch and did it this time but please take a moment to validate that everything there is as you expect. Thank you!

**Comment by prashantkumarfiserv** [comment]
@minh-pham1  I am not able to see this on production as of now. Is there any change in prod date?

**Comment by minh-pham1** [comment]
Hello @prashantkumarfiserv! Sorry about the delay, we have actually started our Gitlab migration process and in conjunction with a hackathon we were hosting we had decided to not promote our sprint code to `prod`.

However, as you may have seen in the Status update channel on Teams, we are going to be moving to our new `prod` system which does have the code to onboard your product onto `prod`. After the URL is updated and site is validated, I'll be sure to double check to see whether your product is properly showing.

Apologies for the gap in communication!

**Comment by prashantkumarfiserv** [comment]
Hi @minh-pham1 . No issues. Please keep me updated with the new dates.

**Comment by minh-pham1** [comment]
My apologies, it seems like that code deployment has been deferred once again to realign our schedule and do thorough testing of our new `production` environment after the migration. I was told we have a tentative deployment date of next Thursday on 5/28 but I'll get back to this ticket when I have a for-sure date. Sorry about the extended delay!

**Comment by prashantkumarfiserv** [comment]
@minh-pham1 Is code promoted on Production, i can't find it on developer studio

**Comment by prashantkumarfiserv** [comment]
@minh-pham1  We have committed to the client 5/28 but still it is not available.

**Comment by minh-pham1** [comment]
Closing as the product has now been promoted to `Stage` and `Production`, apologies for the delay!
