### ISSUE TITLE
Search-result content rendering issue

### ISSUE THREAD

**Issue by fiservakshay** [Fiserv/Support#67]
# Reporting new issue for Integrated Banking

**Page**
Search result page

**Describe the bug**
Search result shows the summary and description of an API when searched using the API name.
The **summary** is a short description of an API, whereas the **description** is a little elaborated version. Therefore summary and description in combined shows the duplicate information and may confuse the end-user.
Please refer the below attached screenshot:

![image](https://user-images.githubusercontent.com/81968767/144858787-d0852318-732b-4708-9fe8-a1eb5cc4ff82.png)

**PS:** Summary of an API is also not being rendered in the API documentation. Here's the link of bug that I had filed earlier:
https://github.com/Fiserv/Support/issues/56

**To Reproduce**
Search any API Name of Integrated banking, for example: Cards, Party, 

**Expected behavior**
The search result of an API should display only description of an API.

**Additional context**
cc: @tsegurajimen @brittaho

**Comment by tsegurajimen** [comment]
In addition is important to mention that the Search feature returns weird content like the following:
![image](https://user-images.githubusercontent.com/81706748/144917081-fdcea77f-bb25-4111-8047-63efc9cadc75.png)
Also we found that some documentation that was hided from our menu is being returned as a result of the search, (documentation that we don't want to display yet but still stored in our GitHub repository) please find an example bellow:
![image](https://user-images.githubusercontent.com/81706748/144917429-8d21dc85-efc1-438a-a6c5-7aa7aeab0604.png)
Thanks in advance for your help!

**Comment by tsegurajimen** [comment]
Hided (Not displayed) files were removed from the GitHub repository to don't be displayed in the search and summary tag was removed from our APIs while the issue is fixed.

**Comment by tsegurajimen** [comment]
In addition Accountholder description is not accurate according the domain description that is in place:
https://developer.fiserv.com/search/?q=party  
![image](https://user-images.githubusercontent.com/81706748/146416057-d15e6e65-f790-4252-bf2d-cf855244c8c8.png)

**Comment by rajeshb15** [comment]
Discussed with Alvin Cho and Tania Sarkar, 
1. The Dev Studio search engine examines all of the words in every stored document(API or Doc or Product) as it tries to match search criteria (full-text search). 
2. The search result description will be extracted from the search record with high matching score part of record against to given search criteria. 
3. But when user clicks on a search result, user will be redirected to a full record/page and we are not going to remove parts of search result description. The end result will be same as #2.

**Comment by tsegurajimen** [comment]
Workaround implemented from our side to handle it.
