### ISSUE TITLE
Tabs collapse when selecting on the right nav. 

### ISSUE THREAD

**Issue by MAFiserv** [Fiserv/Support#675]
### Product

Commerce Hub

### Page

All

### Description

Tabs are collapsing when selecting on the right navigation.

https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Resources/Guides/Authorizations/Auth-Optimization.md&branch=preview

Collpased link:
https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Resources/Guides/Authorizations/Auth-Optimization.md&branch=preview#request-variables

![Screenshot (16)](https://github.com/Fiserv/Support/assets/137187052/44f66dfd-abde-4727-803e-f0af2c1e2cad)

### Expected Behaviour

When clicking on the tabs it should not collapse.

### Operating system

All

### Browser

Google Chrome

**Comment by minh-pham1** [comment]
Hello @MAFiserv! Thanks for reporting this issue. I've assigned https://firstdatateam.atlassian.net/browse/PORT-10834 to a team member for next sprint (since we are already approaching the end of this one).

**Comment by wwfiserv** [comment]
@minh-pham1 are we setting up a process for production down scenarios like this and the prior bug where the tabs themselves stopped working (there were a few last year as well that I recall). These are critical and client impacting meaning they can not use the content with these bugs and should be resolved ASAP (in some cases in less than 24 hours). It does not look good upon Fiserv nor instill confidence in our clients if they can't access documentation properly for 2+ weeks going on a Sprint cycle.

**Comment by minh-pham1** [comment]
Hello William, as with any bugs we do go through a triage and determine Severity to determine impact and whether the issue should be a hotfix candidate. Generally we do try to not hotfix `production` but we do try to accelerate it by hotfixing to `qa` and `stage` with code from a sprint or two prior, shortening the time to usually 1 week before the fix comes to production for Sev 1 and 2 issues.

For this issue in particular, the developer has been informed of its priority and have an MR in. I'll of course bring up the severity to the code review and Alvin for final decision about hotfixing. Sorry for the inconvenience! I'll be sure to update this ticket again soon.

**Comment by wwfiserv** [comment]
Appears to be fixed
