### ISSUE TITLE
Internal APIs

### ISSUE THREAD

**Issue by CinthyaRivera** [Fiserv/Support#678]
### Context

- For a product we have APIs or functionalities that are for internal use by Fiserv.
- For the same product we have APIS or functionalities that are Public and private to which the Fiserv developer must have access.

### Solution

- Limiting access to the APIS and their information by profile to have all the APIS information in one place and not in different portals as now.

### Alternatives

Allow internal access

### Region

LATAM

**Comment by CinthyaRivera** [comment]
@minh-pham1  Is there any update related this issue?

**Comment by minh-pham1** [comment]
Hello Cinthya! Sorry we missed this issue, mayhaps I thought it was in a Teams channel somewhere. With regards to this we currently do not have plans for filtering/privatizing internal vs public APIs. As far as I'm aware, we are working with Specification Portal on a feature involving file access requests per user for various file types (doc, pdf, zip, etc.) which you _could_ utilize to attach links for API spec/postman collection with access control.

However, if you're thinking of an API explorer where certain APIs are listed only when a user is logged in (similar to how some of our products are internal and hidden until logged in), then please let us know and we can look into how feasible it is.

Just as a personal opinion/thought: A solution that involves unique access level for each user is very hard and requires a lot of architecture which we would have to discuss for a while. However just having internal (logged in) vs external (not logged in) system may be acceptable and could be done more quickly. Not sure if that's what you'd be looking for though.
