### ISSUE TITLE
Search Tags and Enhanced Tag Functionality

### ISSUE THREAD

**Issue by wwfiserv** [Fiserv/Support#679]
### Context

Currently search tags are coded to the tenant and all documents have the same tags, these are not useful from a navigation and usage perspective. Original Ticket https://github.com/Fiserv/Support/issues/337 and prior request on tag filtering https://github.com/Fiserv/Support/issues/146

### Solution

There should be a default set of tags that relate to the search options/filters. Then additionally the tags on the individual articles should be used to override or add to the default tags when available.

### Alternatives

n/a

### Additional Context

Similarly when you click on the tag in the search or in the article it should being a set of search results containing that tag.

**Comment by minh-pham1** [comment]
Will raise a ticket with our Alvin and our design team about the official design decision.

**Comment by wwfiserv** [comment]
Refresh due to stale bot
