### ISSUE TITLE
Right-side menu pane is not in sync with the active content

### ISSUE THREAD

**Issue by fiservakshay** [Fiserv/Support#68]
# Reporting new issue for Integrated Banking

**Page**
Any page under the **Documentation** section

**Describe the bug**
The active section ( or header name) is not in sync with the highlighted section name in the right-side menu pane. Moreover, clicking the  section name in the right-side menu pane does not redirect to the exact location in the document. Please check any document of Integrated Banking section to view this behavior. 

Reference screenshot:
![image](https://user-images.githubusercontent.com/81968767/145023004-cc476124-ad94-4aaf-b333-94b456b84d96.png)

**To Reproduce**
Open any page within the Documentation section of Integrated Banking.
Ref link:
https://dev-developerstudio.fiserv.com/product/IntegratedBanking/docs/?path=docs/getting-started/before-you-start.md

**Expected behavior**
* The name of active section should be highlighted in the right-side menu pane 
* Clicking the section name link in the right-side menu pane should redirect to the exact location 

cc: @tsegurajimen @brittaho

**Comment by tsegurajimen** [comment]
This issue seems to be solved when code was moved to stage, but it persist in Dev environment.
