### ISSUE TITLE
Breadcrumb and Default Article/URL Navigation

### ISSUE THREAD

**Issue by wwfiserv** [Fiserv/Support#680]
### Context

When navigating documentation it should provide reliable bread crumbs based on organization structure. Similarly if navigating through the URL so clients don't get a 404. See original ticket https://github.com/Fiserv/Support/issues/413

### Solution

Breadcrumbs Navigation
Example from the 3-D Secure landing page https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Online-Mobile-Digital/3D-Secure/3DSecure.md when you navigate to another article (example https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Online-Mobile-Digital/3D-Secure/3DS-Request.md&branch=main) the root directory/path doesn't show in the breadcrumbs

![image](https://github.com/Fiserv/Support/assets/75692745/f577c000-d1f6-46bd-82ae-7230e937a069)

Path Navigation
Need a way to define a default md article in a path, example if you remove the 3DS-Request.md from the path to go back to the root it goes to a 404 instead of the defined landing page (i.e. https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Online-Mobile-Digital/3D-Secure/3DSecure.md).

This information should be pulled from the directory structure in GitHub

![image](https://github.com/Fiserv/Support/assets/75692745/80a45f95-cbc2-4a2f-b41a-c74654bd3d9b)

### Additional Context

See Adyen as an example https://docs.adyen.com/online-payments/3d-secure, you have a breadcrumb that relates to their directory structure.

![image](https://github.com/Fiserv/Support/assets/75692745/e07a09d6-0116-4ea4-8216-a56fc44c4f97)

Additionally if you remove the specific article from the URL 3d-secure you are navigated to the root article as well.

**Comment by minh-pham1** [comment]
Ticket created for next sprint, sorry about the delay!
