### ISSUE TITLE
Undocumented error code: 695 "Invalid/Missing Encryption Data".

### ISSUE THREAD

**Issue by jozuenoon** [Fiserv/Support#683]
### Product

CommerceHub

### Page

CommerceHub -> ErrorResponseCodes

### Description

The code 695 is not documented (Invalid/Missing Encryption Data). Apart from that is it actionable? How can we resolve it? We encounter the error while running Charges, "PaymentToken" in the Sandbox environment with payload derived from API explorer.

### Expected Behaviour

The documented actionable error code (explanation how to fix it).

### Operating system

.

### Browser

.

**Comment by minh-pham1** [comment]
Hello! Sorry about the delay, somehow this ticket slipped under our radar. Is this still an issue? We can connect you to a CommerceHub representative if needed.

**Comment by minh-pham1** [comment]
Closing due to no response
