### ISSUE TITLE
Missing field in schema for referenceTransactionDetails.referenceTransactionType in OpenAPI specification.

### ISSUE THREAD

**Issue by jozuenoon** [Fiserv/Support#685]
### Product

CommerceHub

### Page

CommerceHub -> Payments -> Refunds

### Description

I've noticed that the OpenAPI schema is missing the field referenceTransactionDetails.referenceTransactionType despite it being present on this [page](https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Resources/Master-Data/Reference-Transaction-Details.md&branch=main#tab-referencetransactiondetails) and in examples.

I initially found it on this [page](https://developer.fiserv.com/product/CommerceHub/api/?type=post&path=/payments/v1/refunds&branch=main&version=1.6.0).

### Expected Behaviour

Documented field referenceTransactionDetails.referenceTransactionType in OpenAPI specification.

### Operating system

.

### Browser

.

**Comment by wwfiserv** [comment]
@jozuenoon this was a legacy field, Commerce Hub not orchestrates that information internally for the client. Thanks for bringing it to our attention we will update the documentation.

**Comment by wwfiserv** [comment]
@jozuenoon thank you for brining this to our attention, it seems that during a merge request they were overridden in the YAML. We will update the API Explorer ASAP.

**Comment by jozuenoon** [comment]
Just a note that this field still appears in example:

![image](https://github.com/Fiserv/Support/assets/18538487/789b6232-4d73-4b2b-b075-7f1c08b48491)

**Comment by wwfiserv** [comment]
@jozuenoon big thanks again for that, we will remove all references from the YAML.
