### ISSUE TITLE
Preview API Explorer Links Don't Work in Docs

### ISSUE THREAD

**Issue by wwfiserv** [Fiserv/Support#686]
### Product

Commerce Hub

### Page

All

### Description

The API Explorer Links in our documentation doesn't work in the Preview branch, but work fine in the Active (Main) branch.

### Expected Behaviour

When clicking the link in Preview should link to the Preview version of the API Explorer.

Example under See Also and Try It Now button
https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Resources/API-Documents/Payments/Charges.md&branch=main
https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Resources/API-Documents/Payments/Charges.md&branch=preview

### Operating system

Windwos

### Browser

All

### Region

All

**Comment by russnicoletti** [comment]
Hi @wwfiserv, it looks to me that these two documents you mention are the same in the main and preview branches. Can you check? Based on my investigations, the feature of retrieving documents per branch is working as expected.

**Comment by wwfiserv** [comment]
@russnicoletti the issue isn't that the documents aren't the same, it's when you click on any link to the API Explorer (Try it Now button, or API Explorer in the See Also section), in production it properly goes to the branch in the API Explorer, in preview it tries to navigate (you can see it in the URL bar) but then redirects to the CH Product page.
