### ISSUE TITLE
Undocumented error code: 894 "Referenced transaction identifier is associated with more than one transaction".

### ISSUE THREAD

**Issue by jozuenoon** [Fiserv/Support#687]
### Product

CommerceHub

### Page

CommerceHub -> ErrorResponseCodes

### Description

We have encountered an issue with error code 894, which is not currently documented. The error message associated with this code is "Referenced transaction identifier is associated with more than one transaction." This occurred while using the Refund endpoint in the Sandbox environment, with payload data derived from the API explorer.

1. Could we add documentation for error code 894?
2. Is there a known workaround or fix for this issue where a transaction identifier references multiple transactions or other example allowing to get a valid response from Sandbox?

Payload to reproduce:
```json
{
  "amount": {
    "currency": "USD",
    "total": 12.04
  },
  "merchantDetails": {
    "merchantId": "<edited_value_from_sandbox>",
    "terminalId": "<edited_value_from_sandbox>"
  },
  "referenceTransactionDetails": {
    "referenceMerchantTransactionId": "ac81864d7c9d1ff8b5aa6e98db"
  },
  "transactionDetails": {
    "merchantInvoiceNumber": "123456789012"
  }
}
```

### Expected Behaviour

The documented actionable error code (explanation how to fix it or work around in Sandbox).

### Operating system

.

### Browser

.

**Comment by minh-pham1** [comment]
Hello! Sorry about the delay, somehow this ticket slipped under our radar. Is this still an issue? We can connect you to a CommerceHub representative if needed.

**Comment by minh-pham1** [comment]
Closing ticket as there is no response
