### ISSUE TITLE
Field amount.total is represented as string in examples.

### ISSUE THREAD

**Issue by jozuenoon** [Fiserv/Support#688]
### Product

CommerceHub

### Page

CommerceHub -> Charges

### Description

In some examples amount.total is represented as a string:

![image](https://github.com/Fiserv/Support/assets/18538487/e9184b1c-5e76-49ec-909a-11de0d7f5cdd)

### Expected Behaviour

Examples reflect the correct schema.

### Operating system

.

### Browser

.

**Comment by russnicoletti** [comment]
Hello @jozuenoon, I see in the spec the `CreateDigitalGiftCardRequest` and the `PaymentCardActivateCardRequest` examples use `'12.04'` instead of `12.04`. However, I also see that the `/payments/v1/charges` path doesn't use those examples. Can you provide the example for which the `total` appears as a string?

**Comment by jozuenoon** [comment]
@russnicoletti  See the screenshot attached above, [page link](https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Resources/API-Documents/Payments/Charges.md&branch=main#tab-request).

Other examples which I found:
1. [refunds tagged](https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Resources/API-Documents/Payments/Refund-Tagged.md&branch=main)
2. [auth and capture](https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Resources/API-Documents/Payments/Refund-Auth-Capture.md&branch=main)
3. [Response to inquiry](https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Resources/API-Documents/Payments/Inquiry.md&branch=main#tab-response) paymentReceipt.approvedAmount.total
