### ISSUE TITLE
Broken example / Out of date documentation

### ISSUE THREAD

**Issue by wesfincher** [Fiserv/Support#689]
Following the example provided for the JS Integration Guide and using either the Cert or Prod link
[Payment Form Example:](https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Online-Mobile-Digital/Secure-Data-Capture/Payment-JS/JS-Request.md&branch=main#payment-form-example) 

I receive the following error: 
`Uncaught TypeError: commercehub.FiservSaqAEp is not a constructor`

Is this documentation up to date?  Can you please clarify usage if so?  Please and thank you.

**Comment by wesfincher** [comment]
When trying to access the JS library directly, I receive the following payload response:

`{
    "gatewayResponse": {
        "transactionProcessingDetails": {
            "apiTraceId": "abc7a5e465ad4004a6071817f4a2a59c",
            "clientRequestId": ""
        }
    },
    "error": [
        {
            "type": "APIM",
            "message": "ApiKey and/or Authentication supplied are invalid."
        }
    ]
}`

**Comment by wesfincher** [comment]
@TaniaS-fiserv @sfiserv @acho-fiserv @srija-fiserv - How do I get some resolution or visibility on this?

**Comment by sfiserv** [comment]
@wesfincher the documents are updated/managed by the respective Product team in this case Commerce hub team. I am adding the contact information for Commerce Hub team who can help you in this case.
@wwfiserv  - William Wade  ( william.wade.fiserv.com)

**Comment by wesfincher** [comment]
Thank you @sfiserv - I appreciate your help! 

@wwfiserv - It seems that a GET to the JS SDK routes through an API Gateway. The API Gateway appears to be attempting to authenticate the request but, seeing no authentication / whitelist for my host (localhost for now), returns a 401 Unauthorized with the aforementioned payload.  Can you assist?

**Comment by wwfiserv** [comment]
@wesfincher have you performed the Credentials request in Step 1 https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Online-Mobile-Digital/Secure-Data-Capture/Payment-JS/JS-Request.md&branch=main, you should be able to make this call with the shared API credentials from you account login dashboard, or from a dedicated MID created for sandbox mock https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Resources/Guides/Dev-Studio/Key-Management.md&branch=main

**Comment by wesfincher** [comment]
@wwfiserv - Yes I can successfully complete a credentials request.  However, nothing in the documentation for the Payment-JS integration mentions using anything from that response in the GET for the JS SDK.  Do I include the AuthToken in the query string to load that JS library?  How do I authenticate that request to load the JS library?

**Comment by wesfincher** [comment]
@wwfiserv - Here's our web app's request as captured from Chrome and the failed response:

![image](https://github.com/Fiserv/Support/assets/6493678/e8f825d4-cb75-4e82-ad27-169d5bbf25c5)

I've even tried loading the SDK after our Credentials request, but the call still fails:

![image](https://github.com/Fiserv/Support/assets/6493678/b9372447-3f7b-4be3-a414-2f1d1af9f49f)

**Comment by wwfiserv** [comment]
Yes the credentials are required you can see it in the Payment Form example

https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Online-Mobile-Digital/Secure-Data-Capture/Payment-JS/JS-Request.md&branch=main#authentication-credentials

```javascript
const authorization = 'ACCESS_TOKEN';
const apiKey = 'API_KEY';
const formConfig = {
    "merchantId": 'MERCHANT_ID',
    "publicKey": 'PUBLIC_KEY',
    "asymmetricEncryptionAlgorithm": 'ASYMETRIC_ENCRYPTION_ALGORITHM',
    "keyId": 'KEY_ID'
};
```

```html
<html>
    <head>
        <meta charset="utf-8">
        <script id="commercehub" src="https://cert.api.fiservapps.com/ch/js/v1/commercehub-client-sdk.js"></script>
    </head>
    <body>
        <div id="payment-saq-a-ep-form-div"></div>
        <script>
            const authorization = '50e56404-4595-41b0-a5e7-44b9e4e6569b';
            const apiKey = '1951fe5b30e34cdaad758b8874140872';
            const formConfig = {
                "merchantId": '100008000003683',
                "publicKey": 'MIIBIjANBgkqhkiG9w0BAQEFA....',
                "symmetricEncryptionAlgorithm": 'AES_GCM',
                "asymmetricEncryptionAlgorithm": 'RSA',
                "keyId": 'cc33a193-92b9-4663-ad66-3ddfd8984ded'
            };
            const form = new commercehub.FiservSaqAEp(formConfig, authorization, apiKey);
            form.loadPaymentForm("payment-saq-a-ep-form-div")
                .then((next) => {})
                .catch((error) => {});
        </script>
    </body>
</html>
```

**Comment by wesfincher** [comment]
@wwfiserv  - Sorry if I'm being unclear.  Is this the GET 'request' that is failing:

`<script id="commercehub" src="https://cert.api.fiservapps.com/ch/js/v1/commercehub-client-sdk.js"></script>`

**Comment by wwfiserv** [comment]
@wesfincher yes authentication is still required.

I do want to also ensure you are using the correct integration method, we recommend using our SAQ A iFrame integration specifically v2 https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Online-Mobile-Digital/Secure-Data-Capture/Secure-Data-Capture.md&branch=main and not JS.

If you are unable to use iFrames and need the SAQ A-EP JS integration, I would suggest postponing development under the current v1 version of our JS as it is being replaced with v2. We will have the documentation available sometime next month.

**Comment by wesfincher** [comment]
@wwfiserv - I will investigate the iFrame solution.  

In the meantime, how would one authenticate the loading of this script file? 

`<script id="commercehub" src="https://cert.api.fiservapps.com/ch/js/v1/commercehub-client-sdk.js"></script>`

**Comment by wesfincher** [comment]
@wwfiserv  - I've tried flipping my integration to use the iFrame solution however am now getting the following error after my call to `createPaymentForm`.

Refused to frame 'https://commercehub-secure-data-capture.fiservapps.com/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".

Can you PLEASE help?  We are being forced to migrate from Payeezy 4 months earlier than anticipated.  We are awaiting being officially assigned an implementation resource but the process is painstakingly slow.  Any and all help is incredibly appreciated!

**Comment by wwfiserv** [comment]
@wesfincher we will need a list of hostnames to whitelist for access.

**Comment by wesfincher** [comment]
May I please email you?  I have multiple applications and environments to implement.  What other information will you need along the way?

**Comment by wwfiserv** [comment]
@wesfincher unfortunately I am not integration support and only handle the management documentation of our content and answer simple questions. by directing to the respective articles.

It would be best to contact the merchant's account manager to have them submit an integration request and get assigned a certification analyst. They would be able to assist with coding and manually adding your hostnames to the whitelist.

**Comment by NikitaBG** [comment]
> @wesfincher unfortunately I am not integration support and only handle the management documentation of our content and answer simple questions. by directing to the respective articles.
> 
> It would be best to contact the merchant's account manager to have them submit an integration request and get assigned a certification analyst. They would be able to assist with coding and manually adding your hostnames to the whitelist.

Hi @wesfincher , I have same issue and this is answer is the solution I'm looking for. But I cannot find any email I can mail to fix this. Can you give me someone I can email to fix it?

**Comment by wesfincher** [comment]
We are forced to go through our assigned integration /cert analyst after contacting our account rep. Unfortunately, there's nothing to be done without being onboarded.
