### ISSUE TITLE
Financial Institutions Section - Content Update for Betta Lunch

### ISSUE THREAD

**Issue by tsegurajimen** [Fiserv/Support#69]
# Reporting new issue for Financial Institution  and integrated Banking pages
 
**Page**
https://dev-developer.fiserv.com/financial-institutions
https://dev-developer.fiserv.com/product/IntegratedBanking

**Describe the bug**
Financial Institutions: Due to the code is hard-coded we need your help to updated he content as follows:
![image](https://user-images.githubusercontent.com/81706748/145261916-a5455042-f459-4f3f-9bde-36f457c947f8.png)

Integrated Banking: Inside of Integrated Banking "Who is it for" box is missing, we need it to be in place:
Also in the same page in the Self-service section, the "Generate Credentials" box needs to have an red "X" symbol instead of a green check
![image](https://user-images.githubusercontent.com/81706748/145262225-280cc347-2cdb-4bfb-9747-400a1cfd8b97.png)

**To Reproduce**
Click on following links:
https://dev-developer.fiserv.com/financial-institutions
https://dev-developer.fiserv.com/product/IntegratedBanking

**Expected behavior**
Content updated as expected.

Adding following team members for notifications:
--> @fiservakshay @brittaho @JaneRemus @bobburghardt

**Comment by tsegurajimen** [comment]
Please your help updating this section in the home page https://dev-developer.fiserv.com/ as well accordingly: 
![image](https://user-images.githubusercontent.com/81706748/145271743-bd1f7435-9077-4d03-a8e4-e108853cdc21.png)
Thanks in advance!

**Comment by tsegurajimen** [comment]
Content is being updated on the fly by @TaniaSarkar89 and team, according latest updates

**Comment by tsegurajimen** [comment]
Please your help updating the Integrated Baking name to Banking Hub:

![image](https://user-images.githubusercontent.com/81706748/148433970-17b2f815-4f65-4524-aeee-3f7ca5af8076.png)

![image](https://user-images.githubusercontent.com/81706748/148434052-968b6103-5939-4f29-bfad-250549617efc.png)

![image](https://user-images.githubusercontent.com/81706748/148434079-5e07b7cc-b710-417f-afcf-ad2fb1c6a92a.png)

![image](https://user-images.githubusercontent.com/81706748/148434170-3836aa32-051f-40d3-93c0-c0794ba8bdfa.png)

Thanks in advance!

**Comment by tsegurajimen** [comment]
Same renaming needed in our GitHub Repo from Cards to Banking Hub:
![image](https://user-images.githubusercontent.com/81706748/148436899-976ad627-c371-4bb0-82cc-823b732526f7.png)
Thanks!

**Comment by TaniaSarkar89** [comment]
Closing this ticket since content of FI and IB pages have been already updated.
