### ISSUE TITLE
Specifications Tenant Name Update

### ISSUE THREAD

**Issue by kcaramat** [Fiserv/Support#692]
### Context

Requesting Specifications Tenant Name be updated to Direct Platform Specifications. 

### Solution

Requesting Specifications Tenant Name be updated to Direct Platform Specifications. 

### Alternatives

Tenant Name Direct Platform Specs would be an option too depending on any length restrictions.

**Comment by yanyan-cathy** [comment]
ticket is created and will work on the change, thanks. https://firstdatateam.atlassian.net/jira/software/c/projects/PORT/boards/568?assignee=712020%3Ab0dbd80b-6795-4cb0-ad16-45f8f77e3523&selectedIssue=PORT-10999

**Comment by yanyan-cathy** [comment]
change is done, thanks
