### ISSUE TITLE
Required {keyId} path parameter for 3ds endpoints.

### ISSUE THREAD

**Issue by jozuenoon** [Fiserv/Support#693]
### Product

CommerceHub

### Page

Commerce Hub > 3-D Secure Authentication

### Description

In the parameters section API Explorer lists {keyId} as a path parameter, however, the endpoint path does not include any interpolated element. I can see keyId in the request body so I guess it should be removed from OpenAPI required parameters.

![image](https://github.com/Fiserv/Support/assets/18538487/81566af4-db7a-4888-a928-2313ae61fdec)

1. https://developer.fiserv.com/product/CommerceHub/api/?type=post&path=/payments-vas/v1/3ds/authenticate&branch=main&version=1.6.0
2. https://developer.fiserv.com/product/CommerceHub/api/?type=post&path=/payments-vas/v1/3ds/device-data-initialize&branch=main&version=1.6.0
3. https://developer.fiserv.com/product/CommerceHub/api/?type=post&path=/payments-vas/v1/3ds/verify&branch=main&version=1.6.0

### Expected Behaviour

Consistent use of keyId parameter.

### Operating system

.

### Browser

.

**Comment by russnicoletti** [comment]
@wwfiserv It seems the  3-D Secure Authentication endpoint, and some others, have an extraneous path parameter, `KeyIdParam`. Can you check?

**Comment by wwfiserv** [comment]
@jozuenoon thank you for bringing this to our attention, we actually just discovered this in an audit of our YAML and will be fixing it during out next subversion release.
