### ISSUE TITLE
Onboard a new tenant

### ISSUE THREAD

**Issue by Michaelondot** [Fiserv/Support#695]
### Name of your product / tenant

Enrichment as a Service

### Type of Tenant

Full service

### Team Members

michaelondot, loganathanchandran

### Bug Reporting

michaelondot, loganathanchandran

### Feedback Reporting

michaelondot, loganathanchandran

### Enhancement Reporting

michaelondot, loganathanchandran

### Internal tenant

No

### Product of Carat

No

### Merchants solution area

No

### Customer Segments for Merchants

- [ ] SMB
- [ ] Enterprise

### Financial Institutions solution area

Yes

### Customer Segments for Financial Instituitions

- [X] Bank
- [X] Credit Union
- [X] Large Financial Institution

### Fintech solution area

Yes

### Region of Operation

- [X] North America
- [ ] EMEA
- [ ] LATAM
- [ ] APAC

### RESTful

Yes

### SDK

Yes

### Industry

Banking, Card Services, Fintech, Data Analytics and Insight, Transaction Processing and Enrichment

### Runbox

Yes

### Mock Sandbox

Yes

### Live Server

Yes

**Comment by srija-fiserv** [comment]
Tracking this issue as a part of this ticket: https://firstdatateam.atlassian.net/browse/PORT-11104

**Comment by srija-fiserv** [comment]
@Michaelondot Are you looking to provide us with a live API endpoint that DevStudio users can hit? If not (you would only like to provide mocked responses through yaml definitions), that would be just the Mock Sandbox feature we provide.

**Comment by Michaelondot** [comment]
> @Michaelondot Are you looking to provide us with a live API endpoint that DevStudio users can hit? If not (you would only like to provide mocked responses through yaml definitions), that would be just the Mock Sandbox feature we provide.

We definitely need mock server from Dev Studio for sure. In the future, is it possible to set up like this: (1) mock (dev studio); (2) live sandbox (hosted by us); production (hosted by us). (1) and (2) are the same or different, right now?

**Comment by srija-fiserv** [comment]
Mock is different than live. If it was a live server, then you would have to provide a live server and our team would have to coordinate with you to set it up. The servers must also be the same across all environments. Hope this helps.

**Comment by minh-pham1** [comment]
Your product has been onboarded to our `qa` environment. Please feel free to validate and add content at your pace. Thank you!
