### ISSUE TITLE
Specification Portal Admin Update

### ISSUE THREAD

**Issue by kcaramat** [Fiserv/Support#696]
### Context

Please add Soumava Chowdhury<soumava.chowdhury@Fiserv.com>and Sumit Ghosh <sumit.ghosh@Fiserv.com> as admins to receive the approval notifications for Elite documents.

### Solution

Please add Soumava Chowdhury<soumava.chowdhury@Fiserv.com>and Sumit Ghosh <sumit.ghosh@Fiserv.com> as admins to receive the approval notifications for Elite documents.

### Alternatives

Please add Soumava Chowdhury<soumava.chowdhury@Fiserv.com>and Sumit Ghosh <sumit.ghosh@Fiserv.com> as admins to receive the approval notifications for Elite documents.

**Comment by yanyan-cathy** [comment]
They are added as admin in QA ENV,  would you like to add them as admins in the DEV ENV too?

**Comment by yanyan-cathy** [comment]
https://firstdatateam.atlassian.net/browse/PORT-11120 is created for this issue, thank you!

**Comment by yanyan-cathy** [comment]
the change is done on the DEV now, thanks
