### ISSUE TITLE
Dev Studio Notifications Section

### ISSUE THREAD

**Issue by kcaramat** [Fiserv/Support#697]
### Page

https://dev-developer.fiserv.com/account/notifications

### Description

When all notifications are selected under the Notifications Section, and 'Mark as Read' or 'Mark as Unread' is selected there is a delay for the notifications to be updated.

### Expected Behaviour

When all notifications are selected under the Notifications Section, and 'Mark as Read' or 'Mark as Unread' is selected there shouldn't be a delay for the notifications to be updated.

### Operating system

Windows

### Browser

Chrome

**Comment by yanyan-cathy** [comment]
Hi, thank you for contacting us. A ticket is created to fix this bug https://firstdatateam.atlassian.net/browse/PORT-11129, we will give you an update once it is done.

**Comment by minh-pham1** [comment]
Issue has been fixed and pushed to `qa` environment. Please feel free to validate and reopen the ticket if the issue persists.
