### ISSUE TITLE
Cannot use JavaScript SDK

### ISSUE THREAD

**Issue by ternstyle** [Fiserv/Support#698]
### Product

Commerce Hub

### Page

Custom Checkout Page

### Description

I'm attempting to include the following script in the <head> of my site:
https://cert.api.fiservapps.com/ch/js/v1/commercehub-client-sdk.js

Like so:
<script src="https://cert.api.fiservapps.com/ch/js/v1/commercehub-client-sdk.js?ver=1715176715" id="ics-payment-commercehub-sdk-js"></script>

However I continue to get the following error:
{
                "gatewayResponse":{
                    "transactionProcessingDetails":{
                        "apiTraceId":"6278fab1e2f14387a5b30167402b4bb3",
                        "clientRequestId":""
                    }
             },
                 "error":[
                     {
                         "type":"APIM",
                         "message":"ApiKey and/or Authentication supplied are invalid."
                     }
                 ]
             }
          
I cannot find anything in the documentation indicating that I must include an API key when including this script or how to include the API key.

### Expected Behaviour

The script would load.

### Operating system

MacOS

### Browser

Google Chrome 124.0.6367.119

**Comment by ternstyle** [comment]
@TaniaS-fiserv @sfiserv @acho-fiserv @srija-fiserv

**Comment by yanyan-cathy** [comment]
Thank you for contacting us. Could you please specify the API you used and the version of it?

**Comment by yanyan-cathy** [comment]
@wwfiserv could you please take a look at this as well? thank you!

**Comment by ternstyle** [comment]
Team, right now I'm simply trying to diagnose why I am not able to include the JavaScript SDK to begin working with the API:
https://cert.api.fiservapps.com/ch/js/v1/commercehub-client-sdk.js

I am receiving a 401 Not Authorized error.

**Comment by ternstyle** [comment]
@wwfiserv

**Comment by ternstyle** [comment]
@TaniaS-fiserv @sfiserv @acho-fiserv @srija-fiserv @yanyan-cathy

I'm just trying to include a JavaScript file just as your documentation lays out here:
https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Online-Mobile-Digital/Secure-Data-Capture/Payment-JS/JS-Request.md&branch=main

Is there no support for the CommerceHub API?

**Comment by ternstyle** [comment]
@wwfiserv

**Comment by ternstyle** [comment]
@wwfiserv, problems with the iFrame solution as well. I can't load the form field and continue to recieve the following error:
Refused to frame 'https://commercehub-secure-data-capture.fiservapps.com/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".

Looks like there is a policy on the URL attempted to be loaded in the field iFrames that won't allow it to be loaded as an iFrame.

**Comment by wwfiserv** [comment]
@ternstyle You will need to contact your merchant services account manager and they can work with the implementation team to have your site whitelisted.

**Comment by wwfiserv** [comment]
@ternstyle yes we have a documentation update that is going in along with the JS solution, you can see them by switching to our Preview branch in the top left corner, https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Online-Mobile-Digital/Secure-Data-Capture/iFrame-JS/iFrame-Request.md&branch=preview

**Comment by ternstyle** [comment]
@wwfiserv, I see that. Thank you. I do not see a way to contact my account representative, however. I set up the sandbox account but there is no support option to reach an account rep.

**Comment by wwfiserv** [comment]
@ternstyle the account representative should be the one associated with the merchant account and the contact information should be found on the top of the merchant statement. Unfortunately we don't have access to merchant accounts, but you may be able to contact the general customer service number who may be able to connect you to the account manager. https://merchants.fiserv.com/en-us/contact/contact-support/ You will need your merchant's account info like MID and other security details to have them access the account.

**Comment by ternstyle** [comment]
@wwfiserv, there is no merchant statement for a sandbox account and on contact information anywhere in the portal. I'll do what I can with the link you provided. As of right now, it is a multi-week process to include either a JavaScript file or to render an iFrame in development. Are there any plans to make this process easier? I don't mean to speak out of turn but I've never worked with an API before where there was no documentation outlining the process for a script inclusion and where I had to go through multiple weeks of support to end up needing to call a support line so that I could include an SDK in a development environment.

**Comment by wwfiserv** [comment]
@ternstyle Are you working with a Fiserv merchant/business? This is who would need to reach out to their representative.

The self-service functionality is intended for our direct API and not our SDKs, but will be enhanced to support our Secure Data Capture integrations in the future. As Commerce Hub is a new product we are still developing our Sandbox features, and the majority of our developers are working with their merchant services to get a dedicated cert MID created (which requires a live merchant account).

I will forward your concerns to the product family who is developing this feature.

**Comment by ternstyle** [comment]
@wwfiserv, Thank you.

I created a developer/sandbox account here: https://developer.fiserv.com/

There is no mention in the documentation of needing a production account to use the sandbox features. Can you please advise on how to set up a production merchant account? There is no way to add this on via the developer account and no obvious way to do this from the website.

It doesn't feel intuitive to me that I should have to do this to include a sandbox script in a development site. Developer studio does not make mention of a production account here:
https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Getting-Started/Getting-Started-Dev-Portal.md&branch=preview

**Comment by wwfiserv** [comment]
@ternstyle Sorry for the confusion, what I meant is that as a developer you would need to be working with a merchant, who would most likely have a production account (and if not would be working with Fiserv already to onboard). They would then be working with one of our implementation analysts to assist with setup and coding issues.

The signup is to allow access to your sandbox credentials, which are used for our Direct APIs, however it doesn't currently have the option to add your URLs to the whitelist required for our SDKs. This is only possible currently by having the account manager for the merchant account you are working to integrate with contact the implementation team, who can manually add them.

Unfortunately we needed to get our new v2 SDKs built in a quicker timeline than our Developer Studio team, which has left this gap in self-service. I have raised the concern, and hopefully we will be able to get it added in the next few Sprints. Until then the only option is to have the merchant's account manager submit an implementation request.

**Comment by ternstyle** [comment]
@wwfiserv, thank you for explaining the issue and scope of the problem. Thank you as well for elevating the concern. I'll see what I can do about connection to a single merchant's account, as we're developing a solution at scale and will have 10s or 100s of merchants using the application we're building to replace Payeezy. 

Happy sprinting.

**Comment by wwfiserv** [comment]
@ternstyle also just want to add, CH is designed for high volume or high dollar Enterprise accounts think Home Depot or Exxon, so I'm not sure if this would be the correct integration. Our Small/Medium business clients are normally directed to integrate with Clover. If you were directed to use CH, I would specifically contact the merchant who instructed you so you can talk to their account representative, as they may have a reason for the direction.

**Comment by minh-pham1** [comment]
Support has been completed and issue seems to be answered. Thank you William!
