### ISSUE TITLE
Broken rightTimePayment RPC documentation links

### ISSUE THREAD

**Issue by lukasschwab** [Fiserv/Support#699]
Links to `RIGHT_TIME_PAYMENT RPC` and `REVERSE_RIGHT_TIME_PAYMENT RPC` documentation seem broken on the respective Issuer Solutions documentation pages:

| Docs page | Broken link |
| ----------- | -----------| 
| https://developer.fiserv.com/product/IssuerSolutions/api/?type=post&path=/payments/v2/rightTimePayment&branch=main&version=1.0.0 | https://documentation.fiserv.com/bundle/Open-Data-Streams/page/00A_ODS_HC/05ODS_AUTHrpcs/05ODS_AUTHrpcs.xhtml#index_49559 |
| https://developer.fiserv.com/product/IssuerSolutions/api/?type=post&path=/payments/v2/reverseRightTimePayment&branch=main&version=1.0.0 | https://documentation.fiserv.com/bundle/Open-Data-Streams/page/00A_ODS_HC/05ODS_AUTHrpcs/05ODS_AUTHrpcs.xhtml#index_29169 |

Both links lead to 404 Not Found pages.

Thanks for any help — would love to read more.

Lukas

**Comment by yanyan-cathy** [comment]
Hello, thank you for contacting us. I  was able to be redirect to the correct page without any issue. Please try these links again and let us know if the links work for you now. 

![image](https://github.com/Fiserv/Support/assets/145809701/13ef4475-965a-48ac-be8f-09a759044d68)
![image](https://github.com/Fiserv/Support/assets/145809701/6105936f-9795-4b60-ac1c-bdac4afd94c7)

**Comment by lukasschwab** [comment]
The redirect to auth works fine. These links are broken _after logging in as a client_ with my Client 360 credentials.

**Comment by eliascanaza** [comment]
Hi @lukasschwab we are facing some issues in documentation, our team is working to fix this issue, but for now you can use this link instead  https://documentation.fiserv.com/bundle/ODS/resource/ODS.pdf

**Comment by minh-pham1** [comment]
Documentation has been provided and updated by team responsible for product. Please feel free to reopen this product or contact the Commerce Hub team directly for further assistance!
