### ISSUE TITLE
Spec Portal Group ID Removal

### ISSUE THREAD

**Issue by kcaramat** [Fiserv/Support#700]
### Context

Group IDs DATAWIRE_NAMS and DATAWIRE_SECURE_TRANSPORT_XML_SOAP_SRS_INTERFACES_FOR_RAPID_CONNECT can be removed from the Spec Portal Group ID list. It's no longer in use.

### Solution

Group IDs DATAWIRE_NAMS and DATAWIRE_SECURE_TRANSPORT_XML_SOAP_SRS_INTERFACES_FOR_RAPID_CONNECT can be removed from the Spec Portal Group ID list. It's no longer in use.

### Alternatives

Group IDs DATAWIRE_NAMS and DATAWIRE_SECURE_TRANSPORT_XML_SOAP_SRS_INTERFACES_FOR_RAPID_CONNECT can be removed from the Spec Portal Group ID list. It's no longer in use.

**Comment by yanyan-cathy** [comment]
Hi, thank you for contacting us. A ticket is created to remove these groups https://firstdatateam.atlassian.net/browse/PORT-11171. We will keep you updated once it is done.

**Comment by yanyan-cathy** [comment]
The implementation is done, thank you.
