### ISSUE TITLE
Looks like the Link is broke with 404 [https://developer.fiserv.com/product/FraudMitigation/docs/datareqs.md]

### ISSUE THREAD

**Issue by kongaravinatha** [Fiserv/Support#701]
### Product

Fraud Mitigation

### Page

https://developer.fiserv.com/product/FraudMitigation/docs/datareqs.md

### Description

This is previously working. looks like some thing went wrong. 

### Expected Behaviour

the page has to render with the document datareqs.md

### Operating system

macOS

### Browser

Google chrome

### Region

In Prod region [Atlanta]

**Comment by yanyan-cathy** [comment]
Hi, thank you for contacting us. I noticed that the page URL is missing the branch.  Please try this full URL https://developer.fiserv.com/product/FraudMitigation/docs/?path=docs/datareqs.md&branch=main to access the datareqs.md and let us know if it works for you.

**Comment by kongaravinatha** [comment]
Thanks for your response. I have fixed the link too. Can I know the coming production deployment date pls ?

**Comment by yanyan-cathy** [comment]
You are welcome! For the next production deployment, currently It is scheduled on 5/23

**Comment by kongaravinatha** [comment]
@yanyan-cathy 
I fixed the link in stage and prod too on last friday. But it didnot get reflected in stage yet. Can you pls check on this ? and get back to me ?

**Comment by yanyan-cathy** [comment]
Hi, I could find the datareqs.md file through https://stage-developer.fiserv.com/product/FraudMitigation/docs/?path=docs/datareqs.md&branch=stage in state env. Is this the link you are referring to?

**Comment by kongaravinatha** [comment]
Yes and I gave the path as : [attributes](../docs/datareqs.md). but the attributes link is not loading, is the path incorrect ?

**Comment by kongaravinatha** [comment]
[attributes] ------> (../docs/datareqs.md)

**Comment by minh-pham1** [comment]
Hi @kongaravinatha, you'll want to indicate a path such as `[attributes](?path=docs/datareqs.md)` instead

**Comment by kongaravinatha** [comment]
@minh-pham1  how much it will take time to reflect the change in stage once I push the link change ?

**Comment by minh-pham1** [comment]
Since it's a simple document/md change, it should be updated within 1 hour or less.

**Comment by kongaravinatha** [comment]
let me try adjusting it and get back to you after making the change

**Comment by kongaravinatha** [comment]
@minh-pham1 
If I push my changes to MAIN branch, then they will be reflected to production ?

**Comment by minh-pham1** [comment]
Yes

**Comment by OZ-FS** [comment]
https://developer.fiserv.com/product/FraudMitigation/docs/?path=docs/datareqs.md&branch=main
https://github.com/Fiserv/fraud-mitigation/blob/develop/docs/datareqs.md

**Comment by minh-pham1** [comment]
I see that the suggested fix has been applied on Github and appears to be functional. Closing the ticket as completed, please feel free to reopen or open a new Issue as needed!
