### ISSUE TITLE
Rename tenant 'Vision' to 'Vision Next' in non-prod

### ISSUE THREAD

**Issue by chunglam65** [Fiserv/Support#702]
### Context

I would like 'Vision' renamed to 'Vision Next' with a 'TM' trademakr symbol at the end if possible?

### Solution

replace 'Vision' as the tenant and left hand selection. Also, change YAML references

### Alternatives

n/a

### Region

EMEA - Global

**Comment by OZ-FS** [comment]
Will give an update on the timeline by the end of today.

**Comment by OZ-FS** [comment]
https://firstdatateam.atlassian.net/browse/PORT-11277 is created for next sprint June 03-14.
We will notify on issue status change.

**Comment by minh-pham1** [comment]
Just as a note, this will only show on the main product page as the header, but not changed on Github or in the URL. Is that acceptable?

**Comment by chunglam65** [comment]
Can you cut&paste the link/  urls for me to have a look please? Like to see what they are called

Regards


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by minh-pham1** [comment]
Hello! It'll remain as it is currently:
`https://dev-developer.fiserv.com/product/Vision` and `https://qa-developer.fiserv.com/product/Vision`

The only things that would change are solution browser left navigation, Catalog page entry, and Product page title.

![Solution left navigation](https://github.com/Fiserv/Support/assets/114534554/5e44b8d6-e8b0-44c1-a239-92ba7e8257c4)
![Catalog page](https://github.com/Fiserv/Support/assets/114534554/52a
528c3-399d-420c-81da-59e8a6a26dd5)
![Product page](https://github.com/Fiserv/Support/assets/114534554/c622144b-1c21-4fe8-8249-3e8c6dc129b4)

**Comment by chunglam65** [comment]
Can I ask why?

When we changed from “Helix” to "Vision", everything was changed to Vision including the URL as is now. So what's the reason why they can't be changed for VisionNext?

Regards


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by minh-pham1** [comment]
If you would also like to change the URL, we can do that. However, it won't contain the trademark symbol. The new URL will be `https://qa-developer.fiserv.com/product/VisionNext`.

Is this what you would like to proceed with?

**Comment by chunglam65** [comment]
Yes please :) thank you

Regards


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by minh-pham1** [comment]
Hello @chunglam65! QA deployment has been completed and your product has been renamed! Please validate and feel free to close this ticket once the request has been validated. Thank you!
