### ISSUE TITLE
Assistance Needed in Obtaining Pay by Bank SDK

### ISSUE THREAD

**Issue by harshitha-2909** [Fiserv/Support#703]
### Context

I am currently working on integrating the Pay by Bank service into our application. However, I am unable to locate the Universal Binary (.framework file) required for the integration on the Fiserv Developer Portal.

Could you please guide me on how to obtain the necessary SDK files? If there is a direct link or any specific steps I need to follow, I would greatly appreciate your assistance.

### Solution

I am currently working on integrating the Pay by Bank service into our application. However, I am unable to locate the Universal Binary (.framework file) required for the integration on the Fiserv Developer Portal.

Could you please guide me on how to obtain the necessary SDK files? If there is a direct link or any specific steps I need to follow, I would greatly appreciate your assistance.

### Alternatives

I am currently working on integrating the Pay by Bank service into our application. However, I am unable to locate the Universal Binary (.framework file) required for the integration on the Fiserv Developer Portal.

Could you please guide me on how to obtain the necessary SDK files? If there is a direct link or any specific steps I need to follow, I would greatly appreciate your assistance.

### Region

ohio

**Comment by minh-pham1** [comment]
HI @paulmohljr! Could you assist with pointing them toward the right documentation and/or point of contact for inquiry?
