### ISSUE TITLE
Product XDpreview convert into a full-service tenant with API spec and the mock sandbox feature,

### ISSUE THREAD

**Issue by sbollina-finact** [Fiserv/Support#704]
### Context

Product XDpreview convert into a full-service tenant with API spec and the mock sandbox feature,

### Solution

Product XDpreview convert into a full-service tenant with API spec and the mock sandbox feature,

### Alternatives

Product XDpreview convert into a full-service tenant with API spec and the mock sandbox feature,

**Comment by minh-pham1** [comment]
Completed and validated on `dev` environment. Deployment is scheduled to QA in 2 weeks on Monday 6/17 as per deployment schedule.

**Comment by minh-pham1** [comment]
API sandbox feature has already been enabled on our `qa` environment so please feel free to update your API yamls and validate your changes there. Apologies for the delay with the update!
