### ISSUE TITLE
Discriminator feature is not behaving the same way as Redoc or Swagger UI - Can some one please help

### ISSUE THREAD

**Issue by sbairagyaFiserv** [Fiserv/Support#705]
### Page

API spec

### Description

improperly displaying nested field level discriminator/oneOf/anyOf objects which are displayed correctly when using standard Redoc/Swagger-UI. This is how the UI shows up in Developer Studio:
![image](https://github.com/Fiserv/Support/assets/169327569/1d16ecc9-e2fb-4942-a863-3cab3b0e47d7)

The legalEntityTypeCode has a oneOf mapping in the specification with multiple .
 
When viewed in Redoc UI, we get the below representation:
![image](https://github.com/Fiserv/Support/assets/169327569/b3a8e60e-c7b5-457c-a7e7-e192922a1df8)

And in Swagger-UI:
![image](https://github.com/Fiserv/Support/assets/169327569/4c7ae34a-cf68-42ed-a20c-b03522f24ee0)

### Expected Behaviour

See description.

### Operating system

Any

### Browser

Chrome and Safari

### Region

USA

**Comment by OZ-FS** [comment]
Please provide additional information: what is the product name; what is the API path/type.

**Comment by sbairagyaFiserv** [comment]
> Please provide additional information: what is the product name; what is the API path/type.

Product Name: Unified Merchant Master
Any of example:
API Path:  Inquiry -->getMerchant --> provider : UMM


Corresponding YAML File:  [reference/1.0.0/Merchants/Inquiry/Inquiry_1.0.0_UMM.yaml](https://github.com/Fiserv/unified-merchant-master/blob/develop/reference/1.0.0/Merchants/Inquiry/Inquiry_1.0.0_UMM.yaml)


Discriminator example: 
same API Path - Provider UMM)_TEST
[reference/1.0.0/Merchants/Inquiry/Inquiry_1.0.0_UMM_TEST.yaml](https://github.com/Fiserv/unified-merchant-master/blob/develop/reference/1.0.0/Merchants/Inquiry/Inquiry_1.0.0_UMM_TEST.yaml)

**Comment by OZ-FS** [comment]
we currently do not support anyof, will ask product about supporting anyOf type in schema.

**Comment by sbairagyaFiserv** [comment]
> we currently do not support anyof, will ask product about supporting anyOf type in schema.

Did you decide on this? Or suggest another approach.

**Comment by OZ-FS** [comment]
Currently we support allOf & oneOf.
We plan to add support for anyOf in Q3.

**Comment by wwfiserv** [comment]
@OZ-FS we have a similar request open here that hasn't been assigned https://github.com/Fiserv/Support/issues/684
