### ISSUE TITLE
The default value for the required query parameter is not  passed in the first attempt

### ISSUE THREAD

**Issue by AwaneeshSrivastava** [Fiserv/Support#71]
# Reporting new issue for [DeveloperPortal] (FirstVision-APAC)

**Page**
FIrstVisionAPAC ==> AccountManagement ==> InquireAccountDetails

**Describe the bug**
The default value for the required query parameter is not  passed in the first attempt.  Need to re-type the same value in order to pass the information in the request.

**To Reproduce**
1. Go to FirstVisionAPAC-> AccountManagement -> InquireAccountDetails
2. Click on 'Run'
3. Click the cURL button.  
4. See that the request message doesn't have the query parameter populated 

**Expected behavior**
The default value of the required query parameter must passed in the request.

**Comment by TaniaSarkar89** [comment]
Hi @AwaneeshSrivastava this issue has been fixed in Dev studio. You can verify it from DEV and QA env.

**Comment by AwaneeshSrivastava** [comment]
Thanks @TaniaSarkar89  this issue is now resolved.
