### ISSUE TITLE
No OrgId for DNA 

### ISSUE THREAD

**Issue by shockney** [Fiserv/Support#710]
### Product

Banking Hub

### Page

Workpaces

### Description

Under Credentials it says DNA OrgId coming soon. How soon?

### Expected Behaviour

An OrgId is available for DNA.

### Operating system

Mac Senoma 14.5

### Browser

Chrome Version 125.0.6422.77 (Official Build) (arm64)

**Comment by shockney** [comment]
Can I get an update on this issue?

**Comment by minh-pham1** [comment]
Hello @shockney! Really sorry for the lack of communication. I believe that the DNA Fiserv team has not yet integrated with our Developer Studio hence the lack of documentation or information. We hope you found the correct point of contact and resources for your inquiry. Again, really sorry about the lapse in response.
