### ISSUE TITLE
Access Feature Request

### ISSUE THREAD

**Issue by kcaramat** [Fiserv/Support#712]
### Context

Requesting functionality so admins have the ability to revoke access, if needed, after it was initially approved. 

### Solution

Requesting functionality so admins have the ability to revoke access, if needed, after it was initially approved. 

### Alternatives

Requesting functionality so admins have the ability to revoke access, if needed, after it was initially approved.

**Comment by russnicoletti** [comment]
Hello @kcaramat, the team is evaluating your request
