### ISSUE TITLE
Need to add approver 

### ISSUE THREAD

**Issue by paulmohljr** [Fiserv/Support#713]
### Context

Need to add pull request approver to pay-by-bank project. User to be provisioned is aanoopfiserv

### Solution

Add additional pull request approver in any pull request

### Alternatives

None

### Region

US

**Comment by minh-pham1** [comment]
Hello Paul, that user has not been added to the pay-by-bank github team. It would be difficult for them to approve PRs. Please review the members under https://github.com/orgs/Fiserv/teams/connect-pay and let us know if you would like to remove or add any members before we setup aanoopfiserv as a codeowner.

For now, I made a PR on your repo with the necessary change. However, I won't enforce the rule until this is sorted out.

**Comment by paulmohljr** [comment]
Hey this user is in the fiserv project as seen from the image below
![Screenshot 2024-06-14 at 1 36 37 PM](https://github.com/Fiserv/Support/assets/82846075/622a1d92-d8ea-4b99-adba-fc1fa2e763ff)

**Comment by minh-pham1** [comment]
Hm, I see. I guess they probably had write permission at some point and made a commit but might have been revoked due to inactivity. I'll reinvite them into the `pay-by-bank` Github Teams to provide them Write permission again.
