### ISSUE TITLE
Carat Payments, powered by Fiserv Commerce Hub Magento extension is not working

### ISSUE THREAD

**Issue by nitin-havaldar** [Fiserv/Support#715]
### Product

Commerce Hub

### Page

Magento Admin Panel

### Description

We have recently purchased the Carat Payment Extension powered by Fiserv Commerce Hub from https://commercemarketplace.adobe.com/paradoxlabs-carat.html#product.info.details.support, after installing this extension, we have tried placing an order from the Magento admin & noticed the attached error & it is not proceeding further.

Please find the attached screenshot where the credentials are correct.
<img width="964" alt="image" src="https://github.com/Fiserv/Support/assets/43532414/243ed8de-c28a-4449-aa6d-4623673bdd2e">

Please find the attached screenshot about the error in detail
<img width="1556" alt="Screenshot 2024-06-03 at 4 07 24 PM (1)" src="https://github.com/Fiserv/Support/assets/43532414/973654b9-6c05-4cf4-9ae5-6274e8d53f18">

We have contacted the vendor of this extension i.e paradoxlabs, but they have informed us to contact Fiserv Commerce Hub as the issue is appearing from their iFrame.

I have replicated the same issue on the Magento Native 2.4.5-P8 version & still error is coming from the below JS file https://cert.api.fiservapps.com/ch/payments-vas/v1/card-form/assets/main.83d49f311c7ea057.js

### Expected Behaviour

Extension should work without any errors

### Operating system

macOS Ventura 13.6.7

### Browser

Google Chrome Version 125.0.6422.142 (Official Build) (x86_64)

**Comment by minh-pham1** [comment]
Hello! Redirecting this inquiry to @wwfiserv as this is outside of our jurisdiction.

**Comment by wwfiserv** [comment]
@nitin-havaldar sorry for the delay, unfortunately paradoxlabs didn't work with our implementation team, so we have no way to know how they integrated. Additionally it appears they are using our older v1 of our implementation which we will be sunsetting in favor of v2. Currently it appears the way credentialing is setup isn't working, you will need to contact the merchant account representative who can open an implementation ticket to have a set of API credentials manually created for cert.
