### ISSUE TITLE
Postman Collection for Commerce Hub is broken. 

### ISSUE THREAD

**Issue by darronj** [Fiserv/Support#716]
### Product

Commerce Hub

### Page

Home -> Merchants -> Commerce Hub -> Postman Collection

### Description

https://developer.fiserv.com/product/CommerceHub/docs/?path=assets/postman/Test.postman_collection.json&branch=main

the json presented on the page for a postman collection is invalid. I spent a long time trying to "fix" it after copying/pasting but to no avail. This has caused delays in getting to UAT for our team. 

### Expected Behaviour

I expect to be able to download the JSON and load it into postman and get cracking on some API development.

### Operating system

macOS 14.5 (23F79)

### Browser

Google Chrome

**Comment by wwfiserv** [comment]
Thank you for bringing this to our attention, we are currently in the process of creating our Postman Collections. We will be removing the invalid links until this work is completed.

**Comment by minh-pham1** [comment]
Closing issue as Postman collection have been removed from download. Please follow Commerce Hub status and news channel for any news regarding this.

For William, please feel free to reopen or just add a comment on this Issue in the future should you finish creating the collection and enable downloading again for full closure.
