### ISSUE TITLE
URL Not Updating to Preview or Main

### ISSUE THREAD

**Issue by wwfiserv** [Fiserv/Support#718]
### Product

Commerce Hub

### Page

All

### Description

When changing from the Active (Main) branch to the Preview the URL isn't updating. Or when changing from Preview to Active (Main).

Does not impact the main Product page or API Explorer only the documentation pages.

### Expected Behavior

The URL should update to &branch=preview or &branch=main

### Operating system

Windows

### Browser

Edge, Chrome

### Region

Production

**Comment by minh-pham1** [comment]
Hi William! Strange bug indeed. A quick check shows that this is a purely cosmetic bug (the document still gets refetched and the Network tab indicate that it is making the call to fetch the document on the branch being switched to. Accessing via URL with the branch URL query parameter also fetches the right document version.

However, I will make a Jira ticket to properly fix this cosmetic issue and have the engineer double check the functionality just in case. Thank you for catching it!

**Comment by minh-pham1** [comment]
This has been fixed actually, I forgot to update. Thanks for pointing it out again!
