### ISSUE TITLE
Onboard AI Assistant

### ISSUE THREAD

**Issue by russnicoletti** [Fiserv/Support#720]
### Name of your product / tenant

AIAssistant

### Type of Tenant

Doc only

### Team Members

tri.nugroho@fiserv.com, vidushi.gupta@fiserv.com

### Bug Reporting

tri.nugroho@fiserv.com, vidushi.gupta@fiserv.com

### Feedback Reporting

tri.nugroho@fiserv.com, vidushi.gupta@fiserv.com

### Enhancement Reporting

tri.nugroho@fiserv.com, vidushi.gupta@fiserv.com

### Internal tenant

Yes

### Product of Carat

No

### Merchants solution area

No

### Customer Segments for Merchants

- [ ] SMB
- [ ] Enterprise

### Financial Institutions solution area

No

### Customer Segments for Financial Instituitions

- [ ] Bank
- [ ] Credit Union
- [ ] Large Financial Institution

### Fintech solution area

No

### Region of Operation

- [ ] North America
- [ ] EMEA
- [ ] LATAM
- [ ] APAC

### RESTful

No

### SDK

No

### Runbox

No

### Mock Sandbox

Yes

### Live Server

No

**Comment by minh-pham1** [comment]
Tenant onboarded to `qa` environment.
