### ISSUE TITLE
Enhance Validator with the Ability to Link to Specific Documentation or External Links

### ISSUE THREAD

**Issue by wwfiserv** [Fiserv/Support#722]
### Context

Enhance the validator when verifying the md files are available in the document-explorer-definition.yaml that it allows the instance/branch or external links, for example I want to link directly to the preview release notes so clients don't have to toggle the active/preview to see them link: docs/Release-Notes-Alerts/Preview.md&branch=preview

### Solution

Allow linking to branches and links in the YAML for the left navigation bar

### Alternatives

The ability for specific documents to automatically switch branches

### Additional Context

See PR https://github.com/Fiserv/Commerce-Hub/pull/1167

**Comment by minh-pham1** [comment]
Hello William, the change has been completed! Please feel free to utilize branch versioning in the DED file now.

Please note that we do not support linking to external links or other tenants via the document-explorer at the current moment. The left-nav is intended for navigation of content within the product, linking to other products or external pages should be more descriptive inside a markdown to let the user understand when/why they're being redirected to another product.

**Comment by wwfiserv** [comment]
@minh-pham1 looks like there is an issue, it allows the branch to be added however it still tries to add the &branch=main again even though it's already defining a branch

https://developer.fiserv.com/product/CommerceHub/docs/?path=docs/Release-Notes-Alerts/Preview.md&branch=preview**&branch=main**

**Comment by minh-pham1** [comment]
Ah, so that could be why we previously did not allow this functionality. Let me see if a developer can take a look at that functionality this sprint.

**Comment by minh-pham1** [comment]
Validator has been updated a while back, apologies for the lack of update.
