### ISSUE TITLE
Onboard APIM as a new tenant

### ISSUE THREAD

**Issue by rk-fiserv** [Fiserv/Support#723]
### Name of your product / tenant

APIM

### Type of Tenant

Full service

### Team Members

ravikiran.muvva@fiserv.com, veneela.nagabandi@fiserv.com

### Bug Reporting

ravikiran.muvva@fiserv.com, veneela.nagabandi@fiserv.com

### Feedback Reporting

ravikiran.muvva@fiserv.com,karthikreddy.kunduru@fiserv.com

### Enhancement Reporting

ravikiran.muvva@fiserv.com,karthikreddy.kunduru@fiserv.com

### Internal tenant

Yes

### Product of Carat

No

### Merchants solution area

No

### Customer Segments for Merchants

- [ ] SMB
- [ ] Enterprise

### Financial Institutions solution area

No

### Customer Segments for Financial Instituitions

- [ ] Bank
- [ ] Credit Union
- [ ] Large Financial Institution

### Fintech solution area

No

### Region of Operation

- [X] North America
- [X] EMEA
- [X] LATAM
- [X] APAC

### RESTful

Yes

### SDK

No

### Runbox

Yes

### Mock Sandbox

Yes

### Live Server

No

**Comment by sfiserv** [comment]
@minh-pham1  assigning this issue to you to onboard the tenant.

**Comment by minh-pham1** [comment]
Tenant has been fully onboarded and promoted up to `qa` environment. Please feel free to validate, update content via Github, and reopen or open a new ticket if any issue arises. Thank you!
