### ISSUE TITLE
Incorrect default value for Timestamp header parameter 

### ISSUE THREAD

**Issue by russnicoletti** [Fiserv/Support#726]
### Product

Commerce Hub

### Page

API Explorer

### Description

The default value for the `Timestamp` header parameter in the Commerce Hub API specs is `{{time}}`. Because the `Timestamp` type is `integer`, the default value is in violation of the schema causing a failure when the APIs are run in the Developer Studio sandbox.

### Expected Behaviour

The default value for the `Timestamp` header parameter should be an integer.

### Operating system

MacOs

### Browser

Chrome

**Comment by russnicoletti** [comment]
@wwfiserv Can you take a look at this? Thanks.

**Comment by wwfiserv** [comment]
@russnicoletti I'll work on that with the next version, it was changed to facilitate a proper automated Postman Collection to be created, but as we are manually making them, it's not needed. The original plan was to reenable the ability to modify those fields again.
