### ISSUE TITLE
I can't see the elements of the API explorer

### ISSUE THREAD

**Issue by lucasfiserv1** [Fiserv/Support#729]
### Product

Silvercore

### Page

API Explorer

### Description

Hi, when I want to deploy the API explorer (version 2.0.0) in production it gives me that error and it also doesn't show me the structure of the API explorer, but this doesn't happen when I want to see version 1.0.0

<img width="491" alt="Capture-Api-Exporer-Error" src="https://github.com/user-attachments/assets/d3eec9df-8cda-4716-86ab-ae826151cea9">

### Expected Behaviour

This is a screenshot of an expected behavior, the example I took from QA. You should see the API explorer tree structure.

<img width="366" alt="Capture-Expected-Behaviour" src="https://github.com/user-attachments/assets/0995aca7-ec7b-43e5-be61-98c17a09667f">

### Operating system

Windows 10

### Browser

Google Chrome 127.0.6533.74

**Comment by russnicoletti** [comment]
Hi @lucasfiserv1, this appears to be an intermittent problem related to refreshing the APIs. It's working as expected when I tried just now. Please try again. Thanks.

**Comment by lucasfiserv1** [comment]
Hi, you're right, I see it ok now. Thanks!
