### ISSUE TITLE
EFX Header links are opened in an additional blank page

### ISSUE THREAD

**Issue by tsegurajimen** [Fiserv/Support#73]
# Reporting new issue for Integrated Banking - Getting Started Section

**Page**
https://developer.fiserv.com/product/IntegratedBanking/docs/?path=docs/getting-started/before-you-start.md#know-our-standard-api-structure

**Describe the bug**
When accessing Integrated Banking/Getting Started/Before You Start, links to EFX Header are opened in an additional page but not displaying any content and the content is being currently displayed in the main page page correctly.

![image](https://user-images.githubusercontent.com/81706748/146426325-066fb13b-e840-4162-a190-0047b09665f5.png)

![image](https://user-images.githubusercontent.com/81706748/146427116-1204b152-f1e2-48e2-848c-ae8b44a51255.png)

**Expected behavior**
Open the EFX Header content in the same main page.

Adding for notification:

@fiservakshay @brittaho

**Comment by fiservakshay** [comment]
Also, for the links with target set to "_blank" are getting opened in the same page as well. Such links should open only in a new tab.

**Note:** This issue is occuring only for the internal links (links within the GitHub repo) and external links are working fine.

Code snippet for ref:
![image](https://user-images.githubusercontent.com/81968767/146490526-8b651226-1685-4caa-b711-7fd11c24deea.png)

**Comment by anandrewfiserv** [comment]
@fiservakshay Hi Akshay, we currently don't support opening internal doc pages in a new tab.

If you really require this functionality, could you open a feature request? Otherwise, removing the target="_blank" will only open the link in the same tab.

Thank you.

**Comment by fiservakshay** [comment]
> @fiservakshay Hi Akshay, we currently don't support opening internal doc pages in a new tab.
> 
> If you really require this functionality, could you open a feature request? Otherwise, removing the target="_blank" will only open the link in the same tab.
> 
> Thank you.

@anandrewfiserv Thanks for responding. I will discuss this with the team and if everyone agrees to have this functionality then will open a feature request.

**Comment by anandrewfiserv** [comment]
Thanks, I will close this ticket.
