### ISSUE TITLE
Promote CardPointe tenant from Stage to Main

### ISSUE THREAD

**Issue by KGroninger** [Fiserv/Support#730]
Please assist with promoting the CardPointe tenant repo (https://github.com/Fiserv/card-pointe) from Stage to Main as soon as possible.

We have a hard deadline from Fiserv CRM to decomission our current developer site before September 5, 2024.

Please reach out to me directly with any questions.

**Comment by minh-pham1** [comment]
Hello! I have assigned the ticket to a developer. We will update the status of it here.

**Comment by minh-pham1** [comment]
The backend scripts have been created and your product will be promoted to Developer Studio `stage` and `production` on 8/22 and 8/29 respectively barring any delays or issues we may find. I'll update this ticket as those dates roll around.

In the mean time, please be sure to update your `stage` and `main` branches on Github with the proper version and information for the `config`, `reference`, and `docs` for your products. Thank you!
