### ISSUE TITLE
Onboard a new tenant

### ISSUE THREAD

**Issue by lyle-morris** [Fiserv/Support#733]
### Name of your product / tenant

Pixel

### Type of Tenant

Doc only

### Team Members

lyle-morris-fiserv, JonghoLeeFiserv

### Bug Reporting

lyle-morris-fiserv, JonghoLeeFiserv

### Feedback Reporting

lyle-morris-fiserv, JonghoLeeFiserv

### Enhancement Reporting

lyle-morris-fiserv, JonghoLeeFiserv

### Internal tenant

No

### Product of Carat

No

### Merchants solution area

No

### Customer Segments for Merchants

- [ ] SMB
- [ ] Enterprise

### Financial Institutions solution area

No

### Customer Segments for Financial Instituitions

- [ ] Bank
- [ ] Credit Union
- [ ] Large Financial Institution

### Fintech solution area

No

### Region of Operation

- [ ] North America
- [ ] EMEA
- [ ] LATAM
- [ ] APAC

### RESTful

No

### SDK

No

### Runbox

No

### Mock Sandbox

No

### Live Server

No

**Comment by minh-pham1** [comment]
Hello! Your Github repository has been created and is accessible at https://github.com/Fiserv/pixel for those listed under your list of `Team Members`.

It will be onboarded to our Developer Studio `qa` environment in 2 weeks. I'll leave a comment here once deployment is complete. Thank you!

**Comment by minh-pham1** [comment]
Product has been onboarded up to `qa` environment.
