### ISSUE TITLE
change to make BackOffice external and available to everyone (including non-logged in user).

### ISSUE THREAD

**Issue by kranthiale** [Fiserv/Support#735]
### Context

change to make BackOffice external and available to everyone (including non-logged in user).

BackOffice developerstudio is not accessible to some of external users even after registering with aperia email
 https://developer.fiserv.com/product/BackOffice?branch=main
 they were able to access at some point but recently they have lost the access,

As per MInh request submitting this request to expand make BackOffice available to everyone
 

### Solution

change to make BackOffice external and available to everyone (including non-logged in user).

### Alternatives

change to make BackOffice external and available to everyone (including non-logged in user).

### Additional Context

BackOffice

### Region

prod

**Comment by minh-pham1** [comment]
Hello! A developer has added the change and validated it on our `dev` environment. Based on our deployment schedule, the range will be on qa, stage, and prod on 8/23, 9/5 and 9/12 respectively barring any delays or other changes. Thank you!

**Comment by minh-pham1** [comment]
Hello! BackOffice is now an external product available for everyone on production as of now. Please feel free to validate but I'll just close the ticket as it is a straight forward request and implementation. If any issues or concerns arise, please open a new Github ticket or Teams thread. Thank you!
