### ISSUE TITLE
Onboard a new tenant - Managed PayFac

### ISSUE THREAD

**Issue by acho-fiserv** [Fiserv/Support#737]
### Name of your product / tenant

Managed PayFac

### Type of Tenant

Full service

### Team Members

acho-fiserv

### Bug Reporting

acho-fiserv

### Feedback Reporting

acho-fiserv

### Enhancement Reporting

acho-fiserv

### Internal tenant

No

### Product of Carat

No

### Merchants solution area

Yes

### Customer Segments for Merchants

- [X] SMB
- [X] Enterprise

### Financial Institutions solution area

No

### Customer Segments for Financial Instituitions

- [ ] Bank
- [ ] Credit Union
- [ ] Large Financial Institution

### Fintech solution area

Yes

### Region of Operation

- [X] North America
- [ ] EMEA
- [ ] LATAM
- [ ] APAC

### RESTful

Yes

### SDK

No

### Runbox

No

### Mock Sandbox

Yes

### Live Server

No

**Comment by acho-fiserv** [comment]
capabilities:  payments -> omnichannel & value added services.

**Comment by minh-pham1** [comment]
Product has been onboarded to `qa` environment.
