### ISSUE TITLE
Catalyst API Onboarding for Internal Usage

### ISSUE THREAD

**Issue by peter-fiserv** [Fiserv/Support#738]
### Name of your product / tenant

Catalyst API for Internal Usage

### Type of Tenant

Full service

### Team Members

peter-fiserv

### Bug Reporting

peter-fiserv

### Feedback Reporting

peter-fiserv

### Enhancement Reporting

peter-fiserv

### Internal tenant

Yes

### Product of Carat

No

### Merchants solution area

Yes

### Customer Segments for Merchants

- [X] SMB
- [ ] Enterprise

### Financial Institutions solution area

No

### Customer Segments for Financial Instituitions

- [ ] Bank
- [ ] Credit Union
- [ ] Large Financial Institution

### Fintech solution area

No

### Region of Operation

- [X] North America
- [ ] EMEA
- [ ] LATAM
- [ ] APAC

### RESTful

Yes

### SDK

No

### Industry

sales 
marketing

### Runbox

Yes

### Mock Sandbox

Yes

### Live Server

No

**Comment by peter-fiserv** [comment]
is QA ready yet?

**Comment by minh-pham1** [comment]
Hello! Apologies for the lack of update, yes your product is available on qa environment. Please feel free to validate at your convenience.

**Comment by minh-pham1** [comment]
Closing as there seem to be no issue with the onboarding.
