### ISSUE TITLE
Catalyst API Onboarding for External Usage

### ISSUE THREAD

**Issue by peter-fiserv** [Fiserv/Support#739]
### Name of your product / tenant

Catalyst API for External Usage

### Type of Tenant

Full service

### Team Members

peter-fiserv

### Bug Reporting

peter-fiserv

### Feedback Reporting

peter-fiserv

### Enhancement Reporting

peter-fiserv

### Internal tenant

No

### Product of Carat

No

### Merchants solution area

Yes

### Customer Segments for Merchants

- [X] SMB
- [ ] Enterprise

### Financial Institutions solution area

No

### Customer Segments for Financial Instituitions

- [ ] Bank
- [ ] Credit Union
- [ ] Large Financial Institution

### Fintech solution area

No

### Region of Operation

- [X] North America
- [ ] EMEA
- [ ] LATAM
- [ ] APAC

### RESTful

Yes

### SDK

No

### Industry

sales 
marketing

### Runbox

Yes

### Mock Sandbox

Yes

### Live Server

No

**Comment by russnicoletti** [comment]
Hi @peter-fiserv, can you explain the use-case for having two repositories, one for internal usage and one for external? Are there different APIs in each case, one set of APIs for internal usage and another set of APIs for external usage?

**Comment by peter-fiserv** [comment]
Yes that is correct.


From: Russ Nicoletti ***@***.***>
Date: Monday, August 26, 2024 at 7:39 PM
To: Fiserv/Support ***@***.***>
Cc: Norr, Peter (Berkeley Heights) ***@***.***>, Mention ***@***.***>
Subject: Re: [Fiserv/Support] Catalyst API Onboarding for External Usage (Issue #739)

  ⚠ EXTERNAL MESSAGE – Think Before You Click


Hi @peter-fiserv<https://urldefense.com/v3/__https:/github.com/peter-fiserv__;!!P9vvK-4S!hKZfAV6ITcaPEgvX1Kvud7fWEt10nXLhHyrq2z9xFvNs3vrGI9jHM1vOaaQBlFe1R26cqL0-cY_EaMVuhhdb__6qiQ$>, can you explain the use-case for having two repositories, one for internal usage and one for external? Are there different APIs in each case, one set of APIs for internal usage and another set of APIs for external usage?

**Comment by minh-pham1** [comment]
Hi @peter-fiserv!

Just wanted to clarify and confirm that these settings will be ok. As per your request we'll create two repos, one that is always accessible (external) and one that can only be accessible after logging in with a Fiserv email (Internal). You will have to personally manage both github repos individually once you're been onboarded. The configs are as detailed below:

External:
- DevStudio URL: `https://qa-developer.fiserv.com/product/CatalystAPI`
- DevStudio display name: `Catalyst API`
- Github: `https://github.com/Fiserv/catalyst-api` - Public repo

Internal:
- DevStudio URL: `https://qa-developer.fiserv.com/product/CatalystAPIInternal`
- DevStudio display name: `Catalyst API` + red internal tag
- Github: `https://github.com/Fiserv/catalyst-api-internal` - Private repo

Please let me know if this is acceptable or whether you would like any modifications.

**Comment by minh-pham1** [comment]
Also, two more pieces of information that we had not gotten a chance to add to the form:
1. Do any of these `Capability` tag(s) apply to your product
![Screenshot 2024-08-27 at 12 17 59 PM](https://github.com/user-attachments/assets/7ed5f8cb-88f4-47d3-976c-a003b18e6470)
2. Do you have a point of contact for sales and would you like DevStudio to setup a communication pathway for you? If so, please let us know the name and email address of this person.

**Comment by peter-fiserv** [comment]
1.  No
  2.  You can refer to Arnold Lam ***@***.******@***.***>)

From: Minh Pham ***@***.***>
Date: Tuesday, August 27, 2024 at 3:20 PM
To: Fiserv/Support ***@***.***>
Cc: Norr, Peter (Berkeley Heights) ***@***.***>, Mention ***@***.***>
Subject: Re: [Fiserv/Support] Catalyst API Onboarding for External Usage (Issue #739)

  ⚠ EXTERNAL MESSAGE – Think Before You Click


Also, two more pieces of information that we had not gotten a chance to add to the form:

  1.  Do any of these Capability tag(s) apply to your product
Screenshot.2024-08-27.at.12.17.59.PM.png (view on web)<https://urldefense.com/v3/__https:/github.com/user-attachments/assets/7ed5f8cb-88f4-47d3-976c-a003b18e6470__;!!P9vvK-4S!nqkNAgeltJlp0DqLBgu7h8xtDiS8LBQ3jikdPZvre4HzjR_Uu-2m9Pa9rZt7gG1j5Z2LHUWfCXwWB7riGGTlyg74JQ$>
  2.  Do you have a point of contact for sales and would you like DevStudio to setup a communication pathway for you? If so, please let us know the name and email address of this person.

**Comment by peter-fiserv** [comment]
Actually let’s use

Catalyst Team ***@***.******@***.***>)


From: Norr, Peter (Berkeley Heights) ***@***.***>
Date: Tuesday, August 27, 2024 at 5:23 PM
To: Fiserv/Support ***@***.***>, Fiserv/Support ***@***.***>
Cc: Mention ***@***.***>
Subject: Re: [Fiserv/Support] Catalyst API Onboarding for External Usage (Issue #739)

  1.  No
  2.  You can refer to Arnold Lam ***@***.******@***.***>)

From: Minh Pham ***@***.***>
Date: Tuesday, August 27, 2024 at 3:20 PM
To: Fiserv/Support ***@***.***>
Cc: Norr, Peter (Berkeley Heights) ***@***.***>, Mention ***@***.***>
Subject: Re: [Fiserv/Support] Catalyst API Onboarding for External Usage (Issue #739)

  ⚠ EXTERNAL MESSAGE – Think Before You Click


Also, two more pieces of information that we had not gotten a chance to add to the form:

  1.  Do any of these Capability tag(s) apply to your product
Screenshot.2024-08-27.at.12.17.59.PM.png (view on web)<https://urldefense.com/v3/__https:/github.com/user-attachments/assets/7ed5f8cb-88f4-47d3-976c-a003b18e6470__;!!P9vvK-4S!nqkNAgeltJlp0DqLBgu7h8xtDiS8LBQ3jikdPZvre4HzjR_Uu-2m9Pa9rZt7gG1j5Z2LHUWfCXwWB7riGGTlyg74JQ$>
  2.  Do you have a point of contact for sales and would you like DevStudio to setup a communication pathway for you? If so, please let us know the name and email address of this person.

**Comment by peter-fiserv** [comment]
Most likely yes but I doubt they have github accounts yet…

Can we add later?

Peter


From: Minh Pham ***@***.***>
Date: Tuesday, August 27, 2024 at 5:27 PM
To: Fiserv/Support ***@***.***>
Cc: Norr, Peter (Berkeley Heights) ***@***.***>, Mention ***@***.***>
Subject: Re: [Fiserv/Support] Catalyst API Onboarding for External Usage (Issue #739)

  ⚠ EXTERNAL MESSAGE – Think Before You Click


Sounds good, thank you.

Lastly, do you have a list of people who needs Write access to both of these Github repos other than yourself?

**Comment by minh-pham1** [comment]
Invitation has been sent to you, please feel free to accept to get write access to these repos whenever convenient. A developer will be assigned to create our backend script and you will be onboarded to `qa-developer.fiserv.com` in about 2 weeks. Thank you!

https://github.com/Fiserv/catalyst-api
https://github.com/Fiserv/catalyst-api-internal

**Comment by minh-pham1** [comment]
Hi Peter, unfortunately it seems like communication between Outlook and Github might be missing out on some pieces of information (especially with email address censoring and I edited some comments) so if you can double check the thread on Github it would be helpful. Thanks!

**Comment by peter-fiserv** [comment]
ya emails are all masked.

Do you have a point of contact for sales and would you like DevStudio to setup a communication pathway for you? If so, please let us know the name and email address of this person.

yes lets use Catalyst Team (catalyst@clover.com)

**Comment by peter-fiserv** [comment]
is dev available yet?
https://dev-developerstudio.fiserv.com/

**Comment by minh-pham1** [comment]
Hello Peter, unfortunately `dev` environment is only available for our Developer Studio team to test new features. You'll have to wait until next week for your product to show up on `qa-developer.fiserv.com`

**Comment by peter-fiserv** [comment]
is QA ready yet?

**Comment by minh-pham1** [comment]
Closing as there seem to be no issue with the onboarding.
