### ISSUE TITLE
Rename Integrated Banking to Banking Hub

### ISSUE THREAD

**Issue by tsegurajimen** [Fiserv/Support#74]
@acho-fiserv and Team, please your help updating the Integrated Baking name to Banking Hub:

![image](https://user-images.githubusercontent.com/81706748/148608455-858ce386-0ac6-43e8-912c-1d856e115922.png)

https://dev-developer.fiserv.com/financial-institutions

![image](https://user-images.githubusercontent.com/81706748/148608554-0a033659-1532-4f13-a86e-b942a17e0773.png)

https://dev-developer.fiserv.com/product/IntegratedBanking

![image](https://user-images.githubusercontent.com/81706748/148608588-a2bc765f-efb9-4c56-ac86-5bd55ba2231e.png)

Also please change the filters and pointers from Integrated Banking to Banking Hub>

![image](https://user-images.githubusercontent.com/81706748/148608649-d6c6eadb-f02f-405a-9f8c-69f78338d244.png)

https://dev-developer.fiserv.com/search/

![image](https://user-images.githubusercontent.com/81706748/148608716-c0805ddd-898e-41c5-9024-edde832355c7.png)

GitHub Repository name must be changed accordinly:

https://github.com/Fiserv/Banking-Product-Cards

![image](https://user-images.githubusercontent.com/81706748/148608793-a86994ff-6e92-44a4-8ceb-35135d173b72.png)

Thanks in advance!

**Comment by TaniaSarkar89** [comment]
@tsegurajimen @fiservakshay 'Integrated Banking' has been renamed to 'Banking Hub'. Kindly update the references of 'Integrated banking' in all markdowns and config files. 
Also the new Github repo is : https://github.com/Fiserv/banking-hub

**Comment by tsegurajimen** [comment]
Thank a lot! We have changed the markdown files as well accordingly.
We just found an issue in the "All APIs" and "Search" Pages:
As you can see some of our APIs still displayed as part of Integrated Banking instead of Banking Hub. 
https://dev-developer.fiserv.com/apis
![image](https://user-images.githubusercontent.com/81706748/149024554-38a0b937-7918-4ae2-a15d-abfc7ed1a557.png)
https://dev-developer.fiserv.com/search/?q=party
![image](https://user-images.githubusercontent.com/81706748/149024768-60a575f6-b766-48ae-90f7-3f9102c8f6f0.png)
Can you please check?
Thanks!

**Comment by tsegurajimen** [comment]
Issue was fixed and APIs are now displayed as expected.
Thanks a lot!
![image](https://user-images.githubusercontent.com/81706748/149036180-2c74dde9-68fb-4afc-b193-b2d01400674d.png)
![image](https://user-images.githubusercontent.com/81706748/149036198-f52eada4-321a-423a-8cc2-9d6d731b835a.png)
