### ISSUE TITLE
Download API Specifications HyperLink is not downloading all the Yamls

### ISSUE THREAD

**Issue by kongaravinatha** [Fiserv/Support#749]
### Product

Fraud Mitigation

### Page

https://dev-developer.fiserv.com/product/FraudMitigation/api/?type=post&path=/{gatewayName}/post-evaluate/clientID/{clientID}&branch=develop&version=1.0.0

### Description

For one of the our Products on Devstudio : Fraud Mitigation :

I have 3 yaml namely :

ATO
Enhanced Data
Fraud mitigation
When I download the API specification, I am getting the document with 1 yaml including only EnhancedData and Fraud Mitigation but missing ATO.

The yaml should include all the 3 yamls, EnhancedData + ATO + FraudMitigation

### Expected Behaviour

The yaml should include all the 3 yamls, EnhancedData + ATO + FraudMitigation

### Operating system

macOS

### Browser

Google chrome

### Region

Dev, QA, Stage and PROD

**Comment by minh-pham1** [comment]
It seems that your new API spec files are failing the validators but we weren't properly blocking your merge requests. Please check again as you need to resolve this issue. Sorry about the inconvenience, not sure why your repository was missing this validator requirement.
<img width="778" alt="Screenshot 2024-09-25 at 2 46 29 PM" src="https://github.com/user-attachments/assets/0fc662d6-38a4-4ab0-a958-fdfce71a9fb6">

**Comment by kongaravinatha** [comment]
@minh-pham1 

I am unable to merge the PR since I am failing with one validation : 

![image](https://github.com/user-attachments/assets/d54cf2bb-8095-40e1-9961-9cf7edd429d6)

But I have the product description

![image](https://github.com/user-attachments/assets/162ac83f-082b-436a-b944-12292f688eb8)

**Comment by OZ-FS** [comment]
the product description must be 112 characters or less.

**Comment by OZ-FS** [comment]
there is only one fraud-mitigation/reference/1.0.0/openapi.yaml file
