### ISSUE TITLE
Hyperlinks to open in a new tab

### ISSUE THREAD

**Issue by fiservakshay** [Fiserv/Support#75]
**Is your feature request related to a problem? Please describe.**

Hyperlinks with target set to "_blank" are getting opened in the same window as well. Such links should open only in a new tab.
I have used standard HTML anchor tag to document hyperlinks which I want to open in new tab. Please refer the sample anchor tag structure below:
` Text text text text <a href="mylink.com" target="_blank" title="Click to open"> Link Text </a> `

> #### Note
>
> This issue is occuring only for the internal links (docs within the GitHub repo) and external links are working fine.

**Describe the solution you'd like**
Anchor tags with target set to "_blank" should open in a new tab.

**Describe alternatives you've considered**
The target document can be opened as a popup window covering 90-95% of screen area. 

**Additional context**
n/a

cc: @tsegurajimen @anandrewfiserv

**Comment by anandrewfiserv** [comment]
Hi @fiservakshay, I am working on this issue.

The links that were set to open in a new tab before are not set to open in a new tab anymore. Are there links in the tenant I can use to test with? 

Thank you.

**Comment by anandrewfiserv** [comment]
@fiservakshay This has been resolved, please test if you can and close this ticket. Thank you.

**Comment by fiservakshay** [comment]
> @fiservakshay This has been resolved, please test if you can and close this ticket. Thank you.

I just tested it. The link is opening in a new tab but also getting opened in the same window as well.

**Comment by fiservakshay** [comment]
> Hi @fiservakshay, I am working on this issue.
> 
> The links that were set to open in a new tab before are not set to open in a new tab anymore. Are there links in the tenant I can use to test with?
> 
> Thank you.

Ohh I literally missed this comment. sorry for that. Here's the link for your reference:
https://dev-developerstudio.fiserv.com/product/BankingHub/api/?type=put&path=/clientDefinedFields
(Select **Update Client Defined Field** API)

![image](https://user-images.githubusercontent.com/81968767/151519541-a76ceede-8844-4e4b-9f10-12ad37b629ee.png)

**Comment by tsegurajimen** [comment]
Hi @anandrewfiserv we are changing this link as it was because of today's release to stage.
We'll change it back to open it in a new page on Monday so can test again.

Thanks!
cc: @fiservakshay

**Comment by anandrewfiserv** [comment]
@fiservakshay @tsegurajimen I forgot to mention that the fix is only available on the dev env currently. It will be pushed to the upper envs in the coming weeks.

**Comment by tsegurajimen** [comment]
Moving this ticket to next Sprint 6

**Comment by anandrewfiserv** [comment]
@tsegurajimen Is this still an issue? I thought it was fixed.

**Comment by tsegurajimen** [comment]
Hi @anandrewfiserv , let me check @fiservakshay was the one working on it but let me verify and close the issue.

**Comment by tsegurajimen** [comment]
Correct, this issue is now fixed, Hyperlinks with target="_blank" are opened in a new page as expected, thanks a lot!

![image](https://user-images.githubusercontent.com/81706748/157974337-eab37988-27b5-4ddc-9228-c2c11c222b38.png)

**Comment by tsegurajimen** [comment]
Hi @anandrewfiserv could you please help me checking this link that we are adding in the Add Account Hold https://dev-developer.fiserv.com/product/BankingHub/api/?type=post&path=/accountHolds, in the following line: **To view the core specific implementation notes, [click here](https://dev-developer.fiserv.com/product/BankingHub/docs/?path=docs/implementation-notes/AcctHoldMod_Tabs_Test2.md).**

It seems that the link is open in a new page but also in the current page at the same time.

The link was defined as follows:

<a href="../docs/?path=docs/implementation-notes/AcctHoldMod_Tabs_Test2.md" target="_blank" title="Click to open" >click here</a>

**Comment by tsegurajimen** [comment]
![image](https://user-images.githubusercontent.com/81706748/159575791-3b9f485f-c10e-454b-b226-1b7c264b11fc.png)

**Comment by anandrewfiserv** [comment]
I'll create a ticket for it

**Comment by anandrewfiserv** [comment]
@tsegurajimen Hi, I fixed the issue but all of the links you provided above are not set to open in a new tab (with target set to _blank). If you could change them back as you would like and test them that would be great, thank you.

**Comment by tsegurajimen** [comment]
Thanks a lot @anandrewfiserv ! We removed those links do to PROD release, but I'll put them back in place, test again and let you know.

Thanks again!

**Comment by tsegurajimen** [comment]
Thank you @anandrewfiserv I've test again and the target=Blank links are now opened in a new tab as expected.
![Uploading image.png…]()
