### ISSUE TITLE
Environment specific Server URLs are not rendered properly on the CURL

### ISSUE THREAD

**Issue by kongaravinatha** [Fiserv/Support#752]
### Context

Product
Fraud Mitigation

Page
https://developer.fiserv.com/product/FraudMitigation/docs/datareqs.md

Description
Hi Devstudio team,

This is regarding the Product: Fraud Mitigation :

We have 3 servers URLs in all our yamls as below:

For example : One of the yaml contains below
servers:

url: https://connect-qa.fiservapis.com/fvas-mitigation-v1/
description: QA external endpoint

url: https://connect-dev.fiservapis.com/fvas-mitigation-v1/
description: DEV external endpoint

url: https://connect-uat.fiservapis.com/fvas-mitigation-v1/
description: Stage/CAT external endpoint

When I check the CURL command in all the Envs, I always see only QA URL.
We need to see Dev URL in Dev Environment, QA URL in QA Envrionment, Stage URL in STAGE Environment.

### Solution

We need to see Dev URL in Dev Environment, QA URL in QA Envrionment, Stage URL in STAGE Environment.
I am assuming we can have different yamls for dev, qa, stage and prod. and we will render that yaml or we can have placeholders in yaml which will pick the server URL using that place holder

### Alternatives

---

### Region

Dev, QA, Stage and PROD

**Comment by OZ-FS** [comment]
https://enterprise-jira.onefiserv.net/browse/TFDS-2515
Feature request from GitHub Support: add server dropdown to Code Snippet editor

**Comment by minh-pham1** [comment]
Hello! Sorry for the delay, our developers have been busy with some work before the freeze and could not get around to this enhancement request. We have some working code and will validate it on our `dev` environment before it gets deployed to `qa` next week. Apologies for the lack of communication and patience!

Just as a note, in the dropdown we'll display the `description` and the server will be populated as expected in the code snippet.

**Comment by minh-pham1** [comment]
Enhancement has been pushed to QA and validated to be properly working in the `Code Snippet` as requested. If there are any other issues or suggestions, please feel free to open a new ticket or conversation on Microsoft Teams with a link to this issue. Thank you!
