### ISSUE TITLE
Promote Unified Merchant Master (UMM) tenant from Develop to Stage

### ISSUE THREAD

**Issue by pratim-ghosh** [Fiserv/Support#754]
Please assist in promoting Unified Merchant Master tenant [repo](https://github.com/Fiserv/unified-merchant-master) from `develop` to `stage`

ℹ All the OAS3 specification files have `branch=develop` - do we remove them when promoting to higher environments?

Please reach out to @ashyamsukha @sbairagyaFiserv @jaideepsahaf for further questions

**Comment by OZ-FS** [comment]
Created an issue for next sprint Oct 7-18, 2024.
https://enterprise-jira.onefiserv.net/browse/TFDS-2575

**Comment by OZ-FS** [comment]
Would you like to add 
- customer-segment tags. Selection for merchants/payments: [ SMB (small medium business ), Enterprise]. 
- capability tags. Selection for merchants/payments: [ Analytics, Boarding & Management, Disbursements, Omni-Channel
, Value Added Services]
More than one tag is OK. Tags make Product searchable by tags.

**Comment by OZ-FS** [comment]
The jira ticket TFDS-2575 is done.
Product UNIFIEDMERCHANTMASTER will be in Stage environment as part of S21 deployment on 2024-Oct-31.

**Comment by OZ-FS** [comment]
To which region does the product belong? 

  "tags": [
    "Asia Pacific",
    "Europe, the Middle East, and Africa",
    "Latin America",
    "North America"
  ],

**Comment by minh-pham1** [comment]
@ashyamsukha @sbairagyaFiserv @jaideepsahaf 

Your product has been promoted to `stage`. Please validate and we'll close this ticket as complete if there are no issues. Just as a note, our `stage` and `prod` environments are synced so please validate your content and merge up to main ASAP.

> ℹ All the OAS3 specification files have `branch=develop` - do we remove them when promoting to higher environments?

With regards to this unanswered question, please remove mentions of `&branch=develop` from all your doc links. Our UI will automatically fill in the branch name per environment.

**Comment by minh-pham1** [comment]
Product has been promoted up to `production` and validated on our end to be visible with no outstanding issues. Please feel free to validate your doc and API content. If there are any issues, you are free to update your own Github repository at any time and the update will reflect shortly. For other concerns or questions, please feel free to open another Github issue ticket or contact us on Teams in the `Feedback and Channel!`. Thank you!
