### ISSUE TITLE
SiTef Sales App Sample Code

### ISSUE THREAD

**Issue by Fiserv-Okamura** [Fiserv/Support#756]
### Name of your product / tenant

SiTef Sales App

### Short Description of Tenant

SiTef Sales App is the payment app for Clover Devices in LATAM.

### Type of Tenant

Doc only

### Team Members

marcos.okamura@fiserv.com,leo.ueda@fiserv.com,ivamhenrique.zanottimarques@fiserv.com

### Bug Reporting

marcos.okamura@fiserv.com,leo.ueda@fiserv.com,ivamhenrique.zanottimarques@fiserv.com

### Feedback Reporting

marcos.okamura@fiserv.com,leo.ueda@fiserv.com,ivamhenrique.zanottimarques@fiserv.com

### Enhancement Reporting

marcos.okamura@fiserv.com,leo.ueda@fiserv.com,ivamhenrique.zanottimarques@fiserv.com

### Internal tenant

No

### Product of Carat

No

### Payments solution area

Yes

### Customer Segments for Payments

SMB and Enterprise

### Capabilities for Payments

Payment app for Clover LATAM

### Banking solution area

No

### Fintech solution area

No

### Region of Operation

LATAM

### Runbox

No

### Mock Sandbox

No

### Live Server

No

### Sales Contact

No

**Comment by russnicoletti** [comment]
https://enterprise-jira.onefiserv.net/browse/TFDS-2772

**Comment by russnicoletti** [comment]
@Fiserv-Okamura I see that you have not specified a Region of Operation, although you have described the product as being for LATAM. It would be good to provide a Region of Operation to help customers find your app in Developer Studio.

Also, you have specified the product should be in the Banking solution area and not in the Payment solution area. Based on the description, it seems more appropriate to be in the  Payment solution area. Do you agree? If so, you can choose from the following for the Customer segments for Payments: SMB or Enterprise. Lastly, if the product is in the  Payment solution area, I recommend adding "Value Added Services" to Capabilities for Payments. 

You can't edit the form. You can simply respond in this issue and we will make any adjustments to the product configuration.

**Comment by russnicoletti** [comment]
Hello @Fiserv-Okamura, thanks for updating the form. Regarding Capabilities for Payments, there is a pre-defined list of capabilities tenants can choose from. They are: 'Analytics', 'Boarding & Management', 'Disbursements', 'Omni-Channel', 'Value Added Services'. Would you like your produce associated with any of these capabilties?

**Comment by Fiserv-Okamura** [comment]
Hello @russnicoletti , please associate with "Value Added Services"

Thank you!

**Comment by minh-pham1** [comment]
Closing issue as tenant has been onboarded and no further inquiries have been added. Please feel free to open a new ticket or reach out on our Teams channel at `Feedback and Help!` if you have any more questions!
