### ISSUE TITLE
Workspace

### ISSUE THREAD

**Issue by CinthyaRivera** [Fiserv/Support#758]
### Context

I want to create a workspace for First Vision - LATAM so I can manage product integrations and projects, but my product is not shown in the list:
![image](https://github.com/user-attachments/assets/f832e8b5-cb54-4b53-8bcd-5d8dff406935)

### Solution

I need your help to add my product to Workspace

### Alternatives

I have consider use another product but I don't want to use it incorrectly to perform my testing

### Region

LATAM

**Comment by Rezi0110** [comment]
Hello Cinthya,

 Workspace integration is a whole integration, and will require a few weeks of implementation, please attend the Partner Planning call and speak with Developer Studio's Product Manager to request this feature.
