### ISSUE TITLE
Response to Developers 

### ISSUE THREAD

**Issue by BRENLOVE** [Fiserv/Support#759]
### Name of your product / tenant

COMMERCE/ UCom

### Short Description of Tenant

I am having trouble respondig to the email support. I can open the response 

### Type of Tenant

Full service

### Team Members

brenda.reynolds@lovelysmealplan.com

### Bug Reporting

brenda.reynolds@lovelysmealplan.com

### Feedback Reporting

brenda.reynolds@lovelysmealplan.com

### Enhancement Reporting

brenda.reynolds@lovelysmealplan.com

### Internal tenant

Yes

### Product of Carat

No

### Payments solution area

Yes

### Banking solution area

Yes

### Fintech solution area

Yes

### Runbox

Yes

### Mock Sandbox

Yes

### Live Server

Yes

### Sales Contact

Yes

### Sales Contact Information

Email: #brenda.reynolds@lovelysmealplan.com 

I cant opent the Inquires from the developer about questions. It always goes to a page thats not active.

![Screenshot 2024-10-16 5 06 19 PM](https://github.com/user-attachments/assets/a23b87b6-c7db-4585-baf8-e512a7b6498a)
![Screenshot 2024-10-16 5 06 05 PM](https://github.com/user-attachments/assets/585c0a7d-99a6-48b8-ab6a-e18217b05d6c)

**Comment by russnicoletti** [comment]
Hello @BRENLOVE, to respond to the inquiry, reply to the email you receive. Your reply will be added to the support ticket. Please let me know if you have any other questions.
