### ISSUE TITLE
Fiserv Keying and Linking

### ISSUE THREAD

**Issue by SujoyBhandari-Fiserv** [Fiserv/Support#762]
### Name of your product / tenant

Fiserv Keying and Linking

### Short Description of Tenant

API to get the Fiserv Consumer ID and details for any Consumer

### Type of Tenant

Full Service

### Team Members

SujoyBhandari-Fiserv

### Bug Reporting

SujoyBhandari-Fiserv

### Feedback Reporting

SujoyBhandari-Fiserv

### Enhancement Reporting

SujoyBhandari-Fiserv

### Internal tenant

Yes

### Product of Carat

No

### Payments solution area

Yes

### Customer Segments for Payments

Enterprise

### Capabilities for Payments

Value Added Services

### Banking solution area

No

### Fintech solution area

Yes

### Region of Operation

North America

### Runbox

Yes

### Mock Sandbox

Yes

### Live Server

Yes

### Sales Contact

No

**Comment by russnicoletti** [comment]
Hello @SujoyBhandari-Fiserv, our onboarding form allows for the selection of "Fintech solution area" even though Developer Studio no longer uses that information. Instead, we use "Payments solutions area" and "Banking solutions area". In other words, is your tenant in the payments solutions area and/or in the banking solutions area? Your tenant should be in one or the other solutions area otherwise it will be difficult for users to find the tenant in Developer Studio.

If your tenant is in the Payments solution area, you can choose from the following for the Customer segments for Payments: SMB or Enterprise, and you can choose one of more for the Capabilities for payments: Analytics,
Boarding & Management, Disbursements, Omni-Channel, Value Added Services. 

If your tenant is in the Banking solution area, you can choose from the following for the Customer segments for Banking: Bank, Credit Union, Large Financial Industry, and for Capabilities for banking you can choose one or more from: Banking as a Service, Issuing, Licensing, Financial Data Management.

My guess from your description is your tenant is in the Payments solutions area. So perhaps your tenant is the in SMB and Enterprise customer segment and has the Value Added Services payments capability? That's only a guess. Please let me know if I can help further with the categorization of your tenant. Thanks.

**Comment by SujoyBhandari-Fiserv** [comment]
Hi @russnicoletti - We are from Data Commerce Solution under Prasanna Dhore. We deal with data both from Banking and Payments. If I need to choose only from these two option, Then we can go ahead with your suggestion.

Payment: Enterprise, Capability: Value Added Services

Thanks,
Sujoy Bhandari

**Comment by SujoyBhandari-Fiserv** [comment]
@russnicoletti - I have updated the main ticket to mark it as Payment

**Comment by minh-pham1** [comment]
Hello! We'll pick up this ticket and configure the github repo next week as we are closing out the sprint and finalizing our changes for `qa` environment deployment. As such you can expect to be deployed onto our `qa` environment on 11/18 (though you can start to edit your Github repository much sooner). We'll keep you updated here. Thank you!

**Comment by minh-pham1** [comment]
With regards to Live Server, this option indicates that you would like to provide your own mock sandbox server for users to test API calls against. Is this correct? If so, please provide the endpoint and any authentication required.

**Comment by minh-pham1** [comment]
Your Github is available at https://github.com/Fiserv/fiserv-keying-and-linking. Please give us an update for the mock sandbox feature whenever possible so we can finalize our backend script and get you deployed to `dev` and `qa` environments.

**Comment by SujoyBhandari-Fiserv** [comment]
Thank you so much @minh-pham1 . I have some questions regarding Developer's Studio - API Setup. Sent an meeting invite for tomorrow.

**Comment by SujoyBhandari-Fiserv** [comment]
Hi @minh-pham1 - Thank you for your time today. I have updated the Tenant Type as "Full Service". Please find below Endpoints.

For QA:
Host: https://az-p-cert-spring-apps-int-knl-queryapi-devstudio.private.azuremicroservices.io
End Point #1 : https://az-p-cert-spring-apps-int-knl-queryapi-devstudio.private.azuremicroservices.io/QueryAPI/getConsumerByPII
End Point #2: https://az-p-cert-spring-apps-int-knl-queryapi-devstudio.private.azuremicroservices.io/QueryAPI/lookupByCardNo

For Prod:
Host: https://az-n-spring-verification-app-knl-queryapi.private.azuremicroservices.io
End Point #1: https://az-n-spring-verification-app-knl-queryapi.private.azuremicroservices.io/QueryAPI/getConsumerByPII
End Point #2: https://az-n-spring-verification-app-knl-queryapi.private.azuremicroservices.io/QueryAPI/lookupByCardNo

Please let us know if firewall is required to be open.

**Comment by minh-pham1** [comment]
Onboarding to `dev` seems to be successful. We'll work with DevOps team to deploy to `qa` for your team to access ASAP

**Comment by minh-pham1** [comment]
Hello! Your product has been onboarded to the `qa` environment at https://qa-developer.fiserv.com/product/FiservKeyingandLinking

Please feel free to validate and we'll close this ticket if there are no issues. You can open a different Github Issue ticket once you are ready to be promoted to the higher environments. Thank you for integrating with us!

**Comment by SujoyBhandari-Fiserv** [comment]
Thanks @minh-pham1 . I am receiving the permission error while trying to commit changes in develop branch. Please help.

00:14:00.271: [fiserv-keying-and-linking] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false push --progress --porcelain origin refs/heads/develop:develop
remote: Permission to Fiserv/fiserv-keying-and-linking.git denied to SujoyBhandari-Fiserv.
fatal: unable to access 'https://github.com/Fiserv/fiserv-keying-and-linking/': The requested URL returned error: 403
00:14:08.473: [fiserv-keying-and-linking] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false push --progress --porcelain origin refs/heads/develop:develop
remote: Permission to Fiserv/fiserv-keying-and-linking.git denied to SujoyBhandari-Fiserv.
fatal: unable to access 'https://github.com/Fiserv/fiserv-keying-and-linking/': The requested URL returned error: 403

**Comment by minh-pham1** [comment]
Direct pushes are not allowed. You'll need to make a PR from a feature branch to push to `develop`, `stage`, and `main` (our prod)

**Comment by SujoyBhandari-Fiserv** [comment]
Facing the below issue while trying to create a branch. Please help. 

10:15:03.686: [fiserv-keying-and-linking-2] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false push --progress --porcelain origin refs/heads/FEATURE-ISSUE-762:refs/heads/FEATURE-ISSUE-762 --set-upstream
remote: Permission to Fiserv/fiserv-keying-and-linking.git denied to SujoyBhandari-Fiserv.
fatal: unable to access 'https://github.com/Fiserv/fiserv-keying-and-linking/': The requested URL returned error: 403
10:15:13.550: [fiserv-keying-and-linking-2] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false push --progress --porcelain origin refs/heads/FEATURE-ISSUE-762:refs/heads/FEATURE-ISSUE-762 --set-upstream
remote: Permission to Fiserv/fiserv-keying-and-linking.git denied to SujoyBhandari-Fiserv.
fatal: unable to access 'https://github.com/Fiserv/fiserv-keying-and-linking/': The requested URL returned error: 403

**Comment by russnicoletti** [comment]
Hi @SujoyBhandari-Fiserv, @minh-pham1 invited you to join the GitHub team for your repo. You should have received an email with the GitHub invitation. Please let us know if you have received the invitation and if you have accepted it.  Thanks.

**Comment by SujoyBhandari-Fiserv** [comment]
Hi @russnicoletti - I have just accepted the Invite

**Comment by russnicoletti** [comment]
I see you are now a member of the GitHub team. Are you now able to push your feature branch to your repo?

**Comment by SujoyBhandari-Fiserv** [comment]
Still facing the same issue. Do I need to re-clone the repo?

13:29:09.178: [fiserv-keying-and-linking] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false push --progress --porcelain origin refs/heads/FEATURE/PR-ISSUE-762:refs/heads/FEATURE/PR-ISSUE-762 --set-upstream
remote: Permission to Fiserv/fiserv-keying-and-linking.git denied to SujoyBhandari-Fiserv.
fatal: unable to access 'https://github.com/Fiserv/fiserv-keying-and-linking/': The requested URL returned error: 403
13:29:16.007: [fiserv-keying-and-linking] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false push --progress --porcelain origin refs/heads/FEATURE/PR-ISSUE-762:refs/heads/FEATURE/PR-ISSUE-762 --set-upstream
remote: Permission to Fiserv/fiserv-keying-and-linking.git denied to SujoyBhandari-Fiserv.
fatal: unable to access 'https://github.com/Fiserv/fiserv-keying-and-linking/': The requested URL returned error: 403

**Comment by minh-pham1** [comment]
https://stackoverflow.com/questions/7438313/pushing-to-git-returning-error-code-403-fatal-http-request-failed

This quick search regarding 403 error mentions it might be https vs ssh issue. I would delete and re-clone to double check. Maybe check your SSH token (if you haven't already made one and pasted it into Github already). Not sure, your user has all the proper permissions so it just seems like an issue with authenticating with Github that we can't really fix on our end.

**Comment by SujoyBhandari-Fiserv** [comment]
Thanks. Re-cloning worked. I have pushed the code to https://github.com/Fiserv/fiserv-keying-and-linking/tree/FEATURE-ISSUE-762

**Comment by minh-pham1** [comment]
Developer Studio automatically fetches markdown documents from github, so any `.md` files you update for documentation purposes will automatically get reflected on their respective environment without too much of a delay.

For API spec files, it'll be reindexed by elasticsearch (and available) once every 2 hours.

I don't particularly need to review your PRs, you can just merge them if validators pass and see the changes. I will note that in your document tree (which composes the left-hand navigation for the Documentation on DevStudio) you have listed a file at `docs/use-cases.md` which doesn't seem to exist. Might want to look at that. Otherwise it looks fine.

**Comment by SujoyBhandari-Fiserv** [comment]
Thank you so much @minh-pham1 . I have been able to push and test one of the API successfully. I have one observation. In API Spec, I have mentioned default value of INCLUDE_CONSUMER_DETAILS as true. But in the Developer Studio, It is coming as false in Request. Please help. Let me know if I should close this issue and open new one.

**Comment by minh-pham1** [comment]
Hm interesting ... Could you try to pass the value as a string instead (like `example: 'true'`) I'm not entirely sure and will have to check with the dev that implemented the API Explorer.

**Comment by minh-pham1** [comment]
I'll close this issue as the onboarding process is complete and there seems to be no issues pertaining to creating docs or anything related to access. Please feel free to use our Teams `Feedback and Help!` channel or create more Github issue tickets if you have any other questions or concerns. Thank you!
