### ISSUE TITLE
Access to Digital payouts

### ISSUE THREAD

**Issue by prashantkumarfiserv** [Fiserv/Support#770]
### Context

Please provide write access to [vmaridu-fiserv](https://github.com/vmaridu-fiserv). 
Email: venkatasrinivasa.maridu@fiserv.com
Repo: https://github.com/Fiserv/digital-disbursements

### Solution

Please provide write access to [vmaridu-fiserv](https://github.com/vmaridu-fiserv). 
Email: venkatasrinivasa.maridu@fiserv.com
Repo: https://github.com/Fiserv/digital-disbursements

### Alternatives

Please provide write access to [vmaridu-fiserv](https://github.com/vmaridu-fiserv). 
Email: venkatasrinivasa.maridu@fiserv.com
Repo: https://github.com/Fiserv/digital-disbursements

### Region

ALL Env

**Comment by minh-pham1** [comment]
Invitation sent.
