### ISSUE TITLE
Rename request inside postman collection

### ISSUE THREAD

**Issue by lucasfiserv1** [Fiserv/Support#772]
### Context

Hi! When I download the postman collection, all the requests have the API description as their name (see image captura-postman.png) and I want the request to have the name of the API as its title (see green arrow captura-devstudio.png). I understand that collections are created automatically.
![captura-devstudio](https://github.com/user-attachments/assets/bbf874ce-09cd-4580-9746-738db1665ea4)
<img width="258" alt="captura-postman" src="https://github.com/user-attachments/assets/23a8f3fc-e81d-4363-a0fd-f2f2b4786cd5">

### Solution

I want the request to have the name of the API as its title. In this example it would be called "Block Fees"

### Alternatives

I want the request to have the name of the API as its title. In this example it would be called "Block Fees"

**Comment by minh-pham1** [comment]
Fix has been added. The API names in the postman collection should now match our left navigation (i.e. using the spec's `x-proxy-name` field)

**Comment by russnicoletti** [comment]
@lucasfiserv1 The next time you update your APIs, the generated postman file will contain API names will match the names in the API explorer (`x-proxy-name` field)
