### ISSUE TITLE
Requesting to add new host for "Fiserv Keying and Linking"

### ISSUE THREAD

**Issue by SujoyBhandari-Fiserv** [Fiserv/Support#773]
### Context

We are planning to use our CERT Host / Endpoint in place of the DEV Host or Endpoint currently being used. Please add the CERT host in the repository.

Host to be added - https://az-p-cert-spring-apps-int-knl-queryapi-devstudio.private.azuremicroservices.io

### Solution

Host to be added - https://az-p-cert-spring-apps-int-knl-queryapi-devstudio.private.azuremicroservices.io

### Alternatives

NA

**Comment by minh-pham1** [comment]
Assigning ticket to an engineer

**Comment by minh-pham1** [comment]
Closing this ticket as the work has been completed + hotfixed up to the `qa` environment and the team has been informed.
