### ISSUE TITLE
Support Markdown Style Formatting for Spec File Endpoint Descriptions

### ISSUE THREAD

**Issue by KGroninger** [Fiserv/Support#779]
### Context

Today, no styling is supported for API endpoint descriptions within the API Explorer. This makes it difficult to provide detailed descriptions of API endpoint functions, and because formatting is not supported, we also cannot hyperlink out to other pages for detailed descriptions.

The Description section should allow the same formatting as supported for request and response parameters, including line breaks, itemized lists, bold/italic text, and hyperlinks. 

### Solution

The API endpoint description supports the same markdown content formatting as the request/response params.

### Alternatives

N/A

**Comment by minh-pham1** [comment]
We don't process yaml files with markdown syntax, however basic HTML tags should still work.

**Comment by KGroninger** [comment]
@minh-pham1 we currently use a mix of markdown and html styling in the parameter descriptions in the spec file, and both work (for example, here we have the code html tag, but it also works if we use the markdown syntax wrapping content in backticks (`) instead.

For example:

![secureexemption spec file](https://github.com/user-attachments/assets/91751cb0-aa7b-412e-be76-dcdff5c6bcef)
![secureexemption ui](https://github.com/user-attachments/assets/74914ff9-763b-44fa-94a4-75230f72cab9)

**Comment by KGroninger** [comment]
@minh-pham1 I experimented with HTML formatting in the endpoint/path description, and yeah it seems like all of the formatting I was looking for works well in HTML, so I think we can close this ticket.
