### ISSUE TITLE
Access request for Network Token

### ISSUE THREAD

**Issue by prashantkumarfiserv** [Fiserv/Support#783]
### Context

Please provide write access to repo (https://github.com/Fiserv/network-tokens) to following users
VinitSingh01
vinitkumar.singh@fiserv.com 
vmanduri
venkata.manduri@fiserv.com

### Solution

Please provide write access to repo (https://github.com/Fiserv/network-tokens) to following users
VinitSingh01
vinitkumar.singh@fiserv.com 
vmanduri
venkata.manduri@fiserv.com

### Alternatives

Please provide write access to repo (https://github.com/Fiserv/network-tokens) to following users
VinitSingh01
vinitkumar.singh@fiserv.com 
vmanduri
venkata.manduri@fiserv.com

### Region

ALL Env

**Comment by minh-pham1** [comment]
Closing as invitation has been accepted and team member has gotten access.
