### ISSUE TITLE
The Default Response payload generated after clicking Run button is incorrect

### ISSUE THREAD

**Issue by anamayjmacabuhay** [Fiserv/Support#79]
# Reporting new issue for [Ana Macabuhay] (AllData Aggregation)

**Page**
All the APIs under API Explorer of AllData Aggregation page

**Describe the bug**
The Default Response payload generated after clicking Run button is incorrect; it is generating the WorkingSample payload instead. This happens in all the APIs of AllData Aggregation.

**To Reproduce**
Note: for this, we'll be using the getAccountDetails API as an example scenario

1. Go to 'https://qa-developerstudio.fiserv.com/product/AllDataAggregation/api/?type=post&path=/WealthManagementWeb/ws/AccountDataInq/getAccountDetails'
2. Click 'Response' and take note of the payload.
3. Click 'Request' then click 'Run' button in the run box.
4. See the Default Response payload generated is not the same with the Default Response payload displayed before clicking Run button.

Optional steps:
1. Select 'getAccountDetails' from the dropdown menu of the run box then click Run button.
2. See that the generated Response payload for getAccountDetails is the same with the generated Response payload for Default.

**Expected behavior**
The Default Response payload generated after clicking Run button should be the same with the Default Response payload that is displayed before clicking the Run button.

**Screenshots**
Before clicking the Run button:
![image](https://user-images.githubusercontent.com/95615056/150569135-c55bee18-4cab-4ed6-9581-7effba3bd6c3.png)

After clicking the Run button:
![image](https://user-images.githubusercontent.com/95615056/150569174-39741d2d-0a26-4733-bbf9-4e120926ae99.png)

Response payload of getAccountDetails after clicking the Run button:
![image](https://user-images.githubusercontent.com/95615056/150569245-cdc787b6-1ee4-4b88-9e49-852af523b5e4.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 97.0.4692.71

**Tablet (please complete the following information):**
Not tested on tablet

**Smartphone (please complete the following information):**
Not tested on smartphone

**Additional context**
This happens with various values within the different APIs.

**Comment by anamayjmacabuhay** [comment]
Hello team, I've edited the bug for more clarity about the issue. Hoping it will help. Thanks!

**Comment by OZ-FS** [comment]
We had the same issue with AllData openapi.yaml file in December 2021.
Stoplight shows 634 errors with openapi.yaml file.
Mainly value - type mismatch

<img width="785" alt="Screen Shot 2022-01-27 at 06 00 25" src="https://user-images.githubusercontent.com/92183615/151376787-06ca97e5-d21a-489a-8c0b-7a07f7dc62ce.png">
.
<img width="1404" alt="Screen Shot 2022-01-27 at 05 59 29" src="https://user-images.githubusercontent.com/92183615/151376816-6a8f8ad7-8f3c-49ad-815b-8c961e14f65a.png">

**Comment by anamayjmacabuhay** [comment]
> We had the same issue with AllData openapi.yaml file in December 2021. Stoplight shows 634 errors with openapi.yaml file. Mainly value - type mismatch
> 
> <img alt="Screen Shot 2022-01-27 at 06 00 25" width="785" src="https://user-images.githubusercontent.com/92183615/151376787-06ca97e5-d21a-489a-8c0b-7a07f7dc62ce.png">
> 
> .
> <img alt="Screen Shot 2022-01-27 at 05 59 29" width="1404" src="https://user-images.githubusercontent.com/92183615/151376816-6a8f8ad7-8f3c-49ad-815b-8c961e14f65a.png">

Hi Olga, can you kindly give us more clarity with what our next step/s should be given your comments above? Thanks! @OZ-FS

**Comment by TaniaSarkar89** [comment]
Created JIRA ticket: https://firstdatateam.atlassian.net/browse/PORT-3270

**Comment by OZ-FS** [comment]
@anamayjmacabuhay, apparently it is all done.
<img width="841" alt="Screen Shot 2022-01-31 at 14 58 34" src="https://user-images.githubusercontent.com/92183615/151887370-1c55d643-1835-4211-af86-e4aea3660798.png">

**Comment by anamayjmacabuhay** [comment]
@OZ-FS Just re-checked it in Dev Studio and this issue persists.

**Comment by OZ-FS** [comment]
JIRA issue https://firstdatateam.atlassian.net/browse/PORT-3281 is still being worked on.
