### ISSUE TITLE
Field descriptions are being displayed as "N/A" in portal

### ISSUE THREAD

**Issue by fiservakshay** [Fiserv/Support#81]
# Reporting new issue for Banking Hub

**Page**
API Explorer documentation of recently added services.

Ref link: https://dev-developerstudio.fiserv.com/product/BankingHub/api/?type=post&path=/enumtable/secured

**Describe the bug**
Some field descriptions are being displayed as "N/A" in Dev Studio, despite the descriptions of such fields are added in SwaggerHub and available in the ref YAML file on GitHub.

Please refer the YAML file which has the description added but for the same field Dev Studio shows "N/A"
![image](https://user-images.githubusercontent.com/81968767/151356987-c8daf97d-c911-4617-a593-f50c16838795.png)

Dev Studio output for this field description:
![image](https://user-images.githubusercontent.com/81968767/151357167-be9816ff-f4b5-4034-a589-7720a8092d9b.png)

**To Reproduce**
N/A

**Expected behavior**
All descriptions added in SwaggerHub file should be displayed in the portal. 

PS: We were not facing this issue in earlier releases. 

cc: @tsegurajimen

**Comment by tsegurajimen** [comment]
Descriptions are now in place, any N/A description is displayed in any of the Banking Hub Services/APIs:

![image](https://user-images.githubusercontent.com/81706748/151851362-8beb66f3-1a6e-429f-a66e-ec1aa02706d4.png)

Thanks for your help!!

cc: @fiservakshay
