### ISSUE TITLE
Unable to expand the dropdowns of Collateral Service

### ISSUE THREAD

**Issue by fiservakshay** [Fiserv/Support#82]
# Reporting new issue for Banking Hub

**Page**
Documentation of  **Add Collateral**  and **Update Collateral** APIs in API Explorer.

Ref Link: https://dev-developerstudio.fiserv.com/product/BankingHub/api/?type=post&path=/collateral

**Describe the bug**
Field dropdowns are not expanding on click in Request Schema of  **Add Collateral**  and **Update Collateral** APIs. However, the field dropdowns in Response Schema is working as expected.

![image](https://user-images.githubusercontent.com/81968767/151490383-2ba305b9-dfc4-406e-9454-c09fb79fb1e4.png)

**To Reproduce**
Ref Link: https://dev-developerstudio.fiserv.com/product/BankingHub/api/?type=post&path=/collateral

**Expected behavior**
The field dropdowns should expand on click.

cc: @tsegurajimen

**Comment by fiservakshay** [comment]
Update:
For **Get Collateral** API, field dropdowns are working in Request Schema but not in Response Schema.

**Comment by TaniaSarkar89** [comment]
Opened a JIRA tickt for this issue: https://firstdatateam.atlassian.net/browse/PORT-3270

**Comment by tsegurajimen** [comment]
Dropdowns are working as expected now. Thanks a lot!
![image](https://user-images.githubusercontent.com/81706748/155618159-12fda767-345e-40f6-93a0-af6d16f42c49.png)
