### ISSUE TITLE
When provided, response examples should be displayed similar to request examples - Multiple response examples are included in YAML for both AccessOne and BackOffice tenants.  Swagger editor shows the examples, but they are not displayed in Developer Studio.  This needs to be fixed and would be a nice enhancement to have. 

### ISSUE THREAD

**Issue by jpfries** [Fiserv/Support#83]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by TaniaSarkar89** [comment]
Linked JIRA ticket : https://firstdatateam.atlassian.net/browse/PORT-4302

**Comment by sfiserv** [comment]
This is an on going implementation in progress, moving this issue to milestone 13.

**Comment by sfiserv** [comment]
The Jira linked for this issue has been completed and hence closing this issue

**Comment by jpfries** [comment]
Can i get a status on where we are with my request that was opened in January?

**Comment by anandrewfiserv** [comment]
John, you and I discussed and decided to pursue a mock server which would indirectly solve this problem, and @TaniaSarkar89 is working on the mock server for AccessOne at the moment.

**Comment by sfiserv** [comment]
Linking the Jira for this issue
https://firstdatateam.atlassian.net/browse/PORT-4446

**Comment by sfiserv** [comment]
The UI implementation will be done in the next sprint and the tracking ticket for the same is 
https://firstdatateam.atlassian.net/browse/PORT-4900
