### ISSUE TITLE
First Data - Auto redirect back to shop

### ISSUE THREAD

**Issue by eyalgrossdev** [Fiserv/Support#84]
**Is your feature request related to a problem? Please describe.**

I would like to know if it is possible to force the First Data gateway to automatically redirect back to our site (Return to shop) after a successful payment? If so, is this triggered via a parameter we send in the initial request to the gateway or is it an option that can be enabled on the account?

**Describe the solution you'd like**

Have the ability to auto redirect back to shop after successful payment in First Data.

**Comment by acho-fiserv** [comment]
Hi @eyalgrossdev , thanks for reaching out.  Can you provide me with more details?  Which gateway are you talking about?  IPG?

**Comment by acho-fiserv** [comment]
closing for now as there is no response
