### ISSUE TITLE
Core Level Addition into the API Explorer

### ISSUE THREAD

**Issue by tsegurajimen** [Fiserv/Support#89]
Hi Team,

As discussed in our Banking Hub Weekly meeting there is a need to include a new Core Level in the API Explorer for Banking Hub.

While we wait until the analysis of the best solution of how it will be handled, @acho-fiserv suggested that at the tenant.json config file could include a Core Level at the API Explorer, which will help us to address the issue while we have a solution in place. 

![image](https://user-images.githubusercontent.com/81706748/153258114-c65007fb-2edb-40f8-ae0e-9e7b5a2dcd03.png)

The idea is to have the Core Level the before the domains level, then we'll have the Service Level and the APIs, as we have them today.

**Core Level - _To be added in the config file_**
    Domain Level - Handled by the x-child-product-name tag in each API Spec
         Service Level - Handled by the x-group-name-name tag in each API Spec
               API Level - Handled by the x-proxy-name tag in each API Spec

For now we need Standard and Premier Core Levels in place, but we'll need to have additional Core Levels for Signature, Cleartouch and other cores soon.

Please find a mockup below:
![image](https://user-images.githubusercontent.com/81706748/153257640-1c50e86e-88d2-4172-b7a3-be2726b49209.png)

Let us know if you have any question or concern about it.

Regards!

**Comment by TaniaSarkar89** [comment]
Opened JIRA ticket: https://firstdatateam.atlassian.net/browse/PORT-3607

**Comment by tsegurajimen** [comment]
Hi @TaniaSarkar89 ,

We need to adjust this requirement a little bit to fulfill our Banking Hub Tenant needs, please find the details below:

As we requested, the idea is to have an additional level to address the Core Name (Standard/Premier/Signature...), but we also need a nested level inside of it to address a classification we are missing for our APIs.

So then we need Level 1 (Core) + Level 2 (Essentials/Classic) controlled by the config file, then the domains level, Service Level and the APIs, as we have today.

**Level 1** - (Core Level) **To be added/controlled in the config file**
**Level 2** - (Essentials/Classic) **To be added/controlled in the config file**
Domain Level - Handled by the x-child-product-name tag in each API Spec
Service Level - Handled by the x-group-name-name tag in each API Spec
API Level - Handled by the x-proxy-name tag in each API Spec

Is important to mention that we need to have the ability to manage the addition of Levels 1 and 2 when we want to start displaying them in the UI, Level 1 according the cores we need to display (6) and Level 2 related to the Essentials or Classic APIs classification. 

Please find a mockup below:

![image](https://user-images.githubusercontent.com/81706748/156613892-262d75c4-a624-43d3-bafd-a3f579e27ceb.png)

![image](https://user-images.githubusercontent.com/81706748/156613519-049d3d41-bad2-4e18-8405-d717e5dd267c.png)

Let us know if you have any question.

Regards,

**Comment by TaniaSarkar89** [comment]
Opened JIRA ticket:
1. https://firstdatateam.atlassian.net/browse/PORT-3610
2. https://firstdatateam.atlassian.net/browse/PORT-3678

**Comment by tsegurajimen** [comment]
This ticket is no longer needed due to the Banking Hub team will handle the Core differences thru Implementation Notes and correlation per core samples and Rq/Rs schemas displayed in the API Explorer _(Other ticket is open to support this capability)_
