### ISSUE TITLE
Next API Button failing to move to next API Group

### ISSUE THREAD

**Issue by tsegurajimen** [Fiserv/Support#90]
Hi Team,

Please your help with the **Next API** button, it is not working when you are looking at the last API in one service and you want to move to the next API in the next service according the dropdown in the left side.

Please look at the example below where we are in the Update Address API, then clicking on the Next API button we should move to the Add Party API, and instead of it we are taking randomly to the Get Card Account Relationship API.

![image](https://user-images.githubusercontent.com/81706748/153260431-c22c5dd1-7517-44e5-b42a-82a5d4812be6.png)

![image](https://user-images.githubusercontent.com/81706748/153260828-2088329e-d2dc-4a75-9a23-0d6c4b506bf9.png)

Thanks in advance!

**Comment by TaniaSarkar89** [comment]
Opened this JIRA ticket : https://firstdatateam.atlassian.net/browse/PORT-3418

**Comment by TaniaSarkar89** [comment]
Hi @tsegurajimen we have addressed this issue. Kindly verify it at your end.
However, please note that the Left navigation in the API explorer does not open up automatically (yet). We would be addressing the "API tree expansion" issue in upcoming sprints.

**Comment by tsegurajimen** [comment]
Issue is now solved, Next API button is working as expected! Thanks a lot!
