### ISSUE TITLE
Field displaying incorrect in Parameters for all the API's

### ISSUE THREAD

**Issue by palanikumarfiserv** [Fiserv/Support#92]
First Vision APAC

Page
All the API's under parameter section (This issue is happening for all the apis in Parameter section for (header, query and path fields) )

1. maxLength of the field is not displaying in dev studio (swagger file  maxLength: 19.0) but not dislaying in dev studio
2.  Example values displaying incorrectly, value provided in swagger ( example: 0001000010000510481) but displaying incorrectly as  (1000010000510481)

To Reproduce
1. Go to any Api
2. Click on  Parameter
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/91948280/153817054-6685984d-5e14-40c4-b269-5640c9efac49.png)

![image](https://user-images.githubusercontent.com/91948280/153817194-86fe9435-6890-4e7a-b9b9-d2a023fdc237.png)

**Comment by TaniaSarkar89** [comment]
@palanikumarfiserv: Please enclose the string data types in quotes (' ') and let us know if you are still facing the issue.

**Comment by palanikumarfiserv** [comment]
@TaniaSarkar89  thanks, will follow as you mentioned.
