### ISSUE TITLE
Date Format and Date displaying incorrectly  

### ISSUE THREAD

**Issue by palanikumarfiserv** [Fiserv/Support#93]
Date Format and Date displaying incorrectly  (First Vision Apac)

*Page
https://dev-developerstudio.fiserv.com/product/FirstVisionAPAC/api/?type=put&path=/v1/accounts/{accountNumber}/directDebit
First Vision APAC >> API Explorer >> Account Management >> Update Accounts Direct Debit  >> Request Schema

1. Date format displaying incorrect for (ddPaymentExpiryDate and ddPaymentStartDate) (Expected format 00/00/0000) displaying format(00-00-000)
2. Date value displaying incorrect (ddPaymentExpiryDate and ddPaymentStartDate) Actual date (04/11/2021, 04/10/2021) displaying (2021-04-10, 2021-04-09)
3) Update Pricing Control Api displays date correctly.  for this Api **"format: date"** attribute is provided.

**To Reproduce**
1. Go to 'FirstVisioin(Apac) >> Api Explorer >> Account Management >> Update Accounts Direct Debit.'
2. Click on 'Request Schema'
3.  See error

**Screenshots**
![image](https://user-images.githubusercontent.com/91948280/153823078-a6e8fe5b-8ed3-472c-8672-1e414e841703.png)
![image](https://user-images.githubusercontent.com/91948280/153823334-f0274ed3-027d-4f87-9ed6-4666213bd719.png)

**Comment by TaniaSarkar89** [comment]
@palanikumarfiserv : Please enclose the string data types in quotes (' ') and let us know if you are still facing the issue.

**Comment by palanikumarfiserv** [comment]
@TaniaSarkar89 closing this defect
