### ISSUE TITLE
Displaying value as string for the given examples (0, "") in Request Body

### ISSUE THREAD

**Issue by palanikumarfiserv** [Fiserv/Support#94]
Displaying value as string for the given examples (0, "") in Request Body FirstVision Apac

**Page**
All the apis having request body (PUT and POST) types

**Describe the bug**
Displays value as string for the given **example value as (0, 0000 or "")**
This defect is for all the Apis in Request body(Ex, Update Spend Limit, Update Accounts Direct Debit, Update Customer Demographic)

**To Reproduce**
1. Go to 'First Vision Apac >> Api Explorer >>(Account Mgmt, Card Mgmt, Cust Mgmt)
2. Click on (Update Accounts Direct Debit, Update Spend Limit, Update Customer Demographic)
4. See error in Request Body

**Screenshots**
![image](https://user-images.githubusercontent.com/91948280/153832903-0f01a4db-e807-4206-8bdb-a293ef8d2938.png)
![image](https://user-images.githubusercontent.com/91948280/153832943-08521988-89ef-4818-90f0-661e864b29e1.png)
![image](https://user-images.githubusercontent.com/91948280/153833032-dfe8b1fe-7b9e-48d6-8e0b-0b7fc0215223.png)
![image](https://user-images.githubusercontent.com/91948280/153833059-c74f058e-4629-4207-bb9d-45dac78c2bb0.png)
![image](https://user-images.githubusercontent.com/91948280/153833093-b3f46c73-8c6a-446f-81d1-1f7ea9beb6ec.png)
![image](https://user-images.githubusercontent.com/91948280/153833107-9c59929a-47de-4aff-9539-657375355015.png)

**Comment by rajeshb15** [comment]
Issue has been fixed and its working as expected in DEV env.
<img width="1658" alt="image" src="https://user-images.githubusercontent.com/80118847/154744950-0bbf380f-ab1b-4ea5-9941-df86d21601b7.png">
<img width="1658" alt="image" src="https://user-images.githubusercontent.com/80118847/154745027-de71ebcb-c92c-4d23-85cd-451211418407.png">
@TaniaSarkar89 @palanikumarfiserv

**Comment by palanikumarfiserv** [comment]
@TaniaSarkar89, Validated the issue working as expected.
