### ISSUE TITLE
Request Body left side 0's ignored

### ISSUE THREAD

**Issue by palanikumarfiserv** [Fiserv/Support#95]
Request Body left side 0's ignored (First Vision Apac)

**Page**
This is issue is for all the apis having Request Body (PUT and POST)

**Describe the bug**
1.  Left side zero's are ignored actual value in swagger file (example: 0000000001000000057 Actual Value) displayed value as  (1000000057)

**To Reproduce**
1. Go to 'First Vision APAC  >> API Explorer'
2. Click on ' API having request body'

**Screenshots**
![image](https://user-images.githubusercontent.com/91948280/153836452-838c268a-6cf5-4f2b-8f9a-905692b3c553.png)
![image](https://user-images.githubusercontent.com/91948280/153836470-f5c9a48f-b908-40de-9b42-0aad140d1354.png)
![image](https://user-images.githubusercontent.com/91948280/153836503-9e0c0b63-d47a-499f-870d-d112ea2eb7c2.png)
![image](https://user-images.githubusercontent.com/91948280/153836528-1f4c94ab-9b01-43fa-a585-338ae1289c12.png)

**Comment by TaniaSarkar89** [comment]
@palanikumarfiserv : Please enclose the string data types in quotes (' ') and let us know if you are still facing the issue.

**Comment by palanikumarfiserv** [comment]
Thanks Tania. will follow as mentioned if any issue will raise defect.
