### ISSUE TITLE
Maximum Minimum and Default attribute not displaying for Parameter, Request body and Response Body

### ISSUE THREAD

**Issue by palanikumarfiserv** [Fiserv/Support#96]
# Maximum and Minimum attribute not displaying for Parameter, Request body and Response Body (FirstVision APAC)

**Page**
This issue occurs for all the API's in Parameter, Request body and Response Body

**Describe the bug**
maximum, minimum and default attributes not displaying for  Parameter, Request body and Response Body 

**To Reproduce**
1. Go to 'First Visioin APAC >> API Explorer >> (Account Mgmt, Cust Mgmt, Card Mgmt)
2. Click on 'Request Schema, Parameter, Response Body'

Screenshot
![image](https://user-images.githubusercontent.com/91948280/153843998-462cab5c-e9b0-47fe-aca5-21f2f5e10448.png)

**Comment by jimmychen-fiserv** [comment]
Bug has been fixed. PR is already created and waiting for merge.
