### ISSUE TITLE
Response Schema Not Loading for some GET API's

### ISSUE THREAD

**Issue by palanikumarfiserv** [Fiserv/Support#98]
# Response Schema Not Loading for some GET API's (First Vision APAC)

**Page**
Inquire Statement Details
Inquire Account Details
List billed Transaction

**Describe the bug**
Response Schema page not loading.

**To Reproduce**
1. Go to 'First Vision APAC'
2. Click on 'Inquire Statement Detail >> Response schema'
3. See error

**Expected behavior**
Page should be able to load properly with description

**Screenshots**
![image](https://user-images.githubusercontent.com/91948280/154521288-accaaf7a-24c1-40c6-a4c6-16ffea4c7156.png)
![image](https://user-images.githubusercontent.com/91948280/154521373-23391f6f-5675-497a-9c11-46dc96a53593.png)

**Comment by TaniaSarkar89** [comment]
@palanikumarfiserv this issue has been resolved. Kindly validate the same.

**Comment by palanikumarfiserv** [comment]
Working as expected, hence closing this defect
