### ISSUE TITLE
allOf code is not being displayed in the Request/Response Schema - General Issue in all Banking Hub APIs

### ISSUE THREAD

**Issue by tsegurajimen** [Fiserv/Support#99]
Hi Team,

We just realized that the **allOf** code issue that we were facing at the beginning of the project last year, is back again, causing that all elements (objects/fields) in our code that are located under an **allOf** keywords in each API yaml specification, are not displayed at all in the Request/Response schema in the Developer Portal.

**This is a general issue that is affecting all Banking Hub APIs where allOf keyword is present in the code.**

The issue is present in the Dev and Stage Environments and it is also in **PROD.**

Some of the APIs failing are:

Accountholder:
  Party Service
	  **Add Party Request**
  Party Account Relationship Service
	  **Get Party Account Relationship Response**
  Party Parties Service
	  **Get Party to Party Relationship Response**

Please find a comparison below between our Add Party Request Default Schema and the one displayed in the portal:

_Our SwaggerHub Request Default:_ **(Bold elements represent the ones missing)**
{
  "OvrdAutoAckInd": true,
  "OvrdExceptionData": {
    "OverrideException": [
      {
        "SubjectRole": "string",
        "SubjectIdent": "string",
        "OvrdExceptionCode": "string",
        "OvrdElement": {
          "Path": "string",
          "ServerPath": "string",
          "Value": "string"
        }
      }
    ]
  },
  "PersonPartyInfo": {
    **"PartyPref": {
      "Language": "string"
    },
    "EstablishedDt": "2021-11-20",
    "OriginatingBranch": "string",
    "ResponsibleBranch": "string",
    "CreditRisk": [
      {
        "RiskCategory": "string",
        "InternalScore": "string"
      }
    ],
    "RelationshipMgr": [
      {
        "RelationshipMgrIdent": "string",
        "RelationshipRole": "Officer"
      }
    ],
    "OEDCode": "string",
    "ClientDefinedData": [
      {
        "DataClassType": "string",
        "DataIdent": "string",
        "DataType": "string",
        "Value": "string",
        "DataLength": 0,
        "ExpDt": "2021-11-20",
        "Desc": "string",
        "RequiredFlag": true,
        "SearchFlag": true,
        "GroupNum": "string"
      }
    ],
    "PartyType": "string",
    "TaxDataInfo": {
      "TaxIdentType": "None",
      "TaxIdent": "123456789",
      "TaxIdentVerified": true,
      "TaxIdentVerifiedDt": "2021-11-20",
      "TaxIdentVerifiedAttempts": 0,
      "OtherTaxIdent": "string",
      "BNotice1Dt": "2021-11-20",
      "BNotice2Dt": "2021-11-20",
      "ForeignTaxData": {
        "ForeignTaxForms": "None",
        "IncomeCode": "st",
        "TaxRate": 0,
        "RecipientCode": "st",
        "ExemptionCode": "st",
        "RecipientStateProv": "string",
        "RecipientCountryCode": {
          "CountryCodeSource": "string",
          "CountryCodeValue": "string",
          "CountryCodeValueEnumDesc": "string"
        },
        "RecipientResidenceCountry": {
          "CountryCodeSource": "string",
          "CountryCodeValue": "string",
          "CountryCodeValueEnumDesc": "string"
        },
        "RecipientPostalCode": "string",
        "ForeignWithholdingType": "string",
        "Chapter3Status": "string",
        "Chapter4FATCAStatus": "string",
        "RecipientGIIN": "string",
        "W8FormType": "string",
        "ForeignCertDt": "2021-11-20",
        "ForeignExpDt": "2021-11-20"
      },
      "LastActivityDt": "2022-02-17",
      "HandlingCode": "string",
      "HandlingCodeEnumDesc": "string",
      "DeliverNoticesOption": "string"
    },
    "DisclosureData": [
      {
        "DisclosureDt": "2021-11-20",
        "DisclosureAckType": "string"
      }
    ],
    "NAICS": [
      "string"
    ],
    "WithholdingOption": "string",
    "Retention": true,
    "SecretData": [
      {
        "SecretIdent": "string",
        "SecretValue": "string"
      }
    ],
    "ExemptOFAC": true,
    "PartyOpenMethod": "string",
    "TelebancPswd": "string",
    "RiskRanking": "string",
    "Reminder": [
      {
        "ReminderCategory": "string",
        "ReminderInd": true
      }
    ],
    "TaxExempt": "string",
    "PersonData": {
      "Contact": [
        {
          "PhoneNum": {
            "PhoneType": "string",
            "PhoneTypeEnumDesc": "string",
            "Phone": "string",
            "PreferredPhone": true,
            "PhoneDesc": "string"
          },
          "PostAddr": {
            "OpenDt": "2021-11-20",
            "AddressIdent": "string",
            "AddrUse": "string",
            "AddrUseEnumDesc": "string",
            "AddrFormatType": "Label",
            "Addr1": "string",
            "Addr2": "string",
            "City": "string",
            "StateProv": "string",
            "PostalCode": "string",
            "CountryCode": {
              "CountryCodeSource": "string",
              "CountryCodeValue": "string",
              "CountryCodeValueEnumDesc": "string"
            },
            "AddrType": "Primary",
            "TimeFrame": {
              "StartDt": "2021-01-31T23:59:59.999",
              "EndDt": "2021-01-31T23:59:59.999"
            },
            "Retention": true,
            "CensusTract": "string",
            "CensusBlock": "string",
            "ForeignFlag": true,
            "HandlingCode": "string",
            "HandlingCodeOption": "StatementsNoticesChecks",
            "MSACode": 0
          },
          "Email": {
            "EmailIdent": "string",
            "EmailType": "string",
            "EmailAddr": "string",
            "PreferredEmail": true
          },
          "WebAddr": {
            "WebAddrIdent": 0,
            "WebAddrType": "string",
            "WebAddrLink": "string"
          }
        }
      ],
      "IssuedIdent": [
        {
          "IssuedIdentType": "string",
          "IssuedIdentTypeEnumDesc": "string",
          "IssuedIdentId": "string",
          "IssuedIdentValue": "3762849726",
          "Issuer": "string",
          "IssuerEnumDesc": "string",
          "IssueDt": "2021-01-31T23:59:59.999",
          "ExpDt": {}
        }
      ],**
      "PersonName": [
        {
          "NameType": "Primary",
          "NameIdent": "string",
          "FullName": "string",
          "FamilyName": "string",
          "GivenName": "string",
          "MiddleName": "string",
          "NamePrefix": "string",
          "NameSuffix": "string",
          "LegalName": "string",
          "NameFormat": "None"
        }
      ]
    },
    "BirthDt": "2021-11-20",
    "Gender": "Male",
    "ImmigrationStat": "string",
    "Race": "string"
  },
  "OrgPartyInfo": {
    **"PartyPref": {
      "Language": "string"
    },
    "EstablishedDt": "2021-11-20",
    "OriginatingBranch": "string",
    "ResponsibleBranch": "string",
    "CreditRisk": [
      {
        "RiskCategory": "string",
        "InternalScore": "string"
      }
    ],
    "RelationshipMgr": [
      {
        "RelationshipMgrIdent": "string",
        "RelationshipRole": "Officer"
      }
    ],
    "OEDCode": "string",
    "ClientDefinedData": [
      {
        "DataClassType": "string",
        "DataIdent": "string",
        "DataType": "string",
        "Value": "string",
        "DataLength": 0,
        "ExpDt": "2021-11-20",
        "Desc": "string",
        "RequiredFlag": true,
        "SearchFlag": true,
        "GroupNum": "string"
      }
    ],
    "PartyType": "string",
    "TaxDataInfo": {
      "TaxIdentType": "None",
      "TaxIdent": "123456789",
      "TaxIdentVerified": true,
      "TaxIdentVerifiedDt": "2021-11-20",
      "TaxIdentVerifiedAttempts": 0,
      "OtherTaxIdent": "string",
      "BNotice1Dt": "2021-11-20",
      "BNotice2Dt": "2021-11-20",
      "ForeignTaxData": {
        "ForeignTaxForms": "None",
        "IncomeCode": "st",
        "TaxRate": 0,
        "RecipientCode": "st",
        "ExemptionCode": "st",
        "RecipientStateProv": "string",
        "RecipientCountryCode": {
          "CountryCodeSource": "string",
          "CountryCodeValue": "string",
          "CountryCodeValueEnumDesc": "string"
        },
        "RecipientResidenceCountry": {
          "CountryCodeSource": "string",
          "CountryCodeValue": "string",
          "CountryCodeValueEnumDesc": "string"
        },
        "RecipientPostalCode": "string",
        "ForeignWithholdingType": "string",
        "Chapter3Status": "string",
        "Chapter4FATCAStatus": "string",
        "RecipientGIIN": "string",
        "W8FormType": "string",
        "ForeignCertDt": "2021-11-20",
        "ForeignExpDt": "2021-11-20"
      },
      "LastActivityDt": "2022-02-17",
      "HandlingCode": "string",
      "HandlingCodeEnumDesc": "string",
      "DeliverNoticesOption": "string"
    },
    "DisclosureData": [
      {
        "DisclosureDt": "2021-11-20",
        "DisclosureAckType": "string"
      }
    ],
    "NAICS": [
      "string"
    ],
    "WithholdingOption": "string",
    "Retention": true,
    "SecretData": [
      {
        "SecretIdent": "string",
        "SecretValue": "string"
      }
    ],
    "ExemptOFAC": true,
    "PartyOpenMethod": "string",
    "TelebancPswd": "string",
    "RiskRanking": "string",
    "Reminder": [
      {
        "ReminderCategory": "string",
        "ReminderInd": true
      }
    ],
    "TaxExempt": "string",
    "OrgData": {
      "Contact": [
        {
          "PhoneNum": {
            "PhoneType": "string",
            "PhoneTypeEnumDesc": "string",
            "Phone": "string",
            "PreferredPhone": true,
            "PhoneDesc": "string"
          },
          "PostAddr": {
            "OpenDt": "2021-11-20",
            "AddressIdent": "string",
            "AddrUse": "string",
            "AddrUseEnumDesc": "string",
            "AddrFormatType": "Label",
            "Addr1": "string",
            "Addr2": "string",
            "City": "string",
            "StateProv": "string",
            "PostalCode": "string",
            "CountryCode": {
              "CountryCodeSource": "string",
              "CountryCodeValue": "string",
              "CountryCodeValueEnumDesc": "string"
            },
            "AddrType": "Primary",
            "TimeFrame": {
              "StartDt": "2021-01-31T23:59:59.999",
              "EndDt": "2021-01-31T23:59:59.999"
            },
            "Retention": true,
            "CensusTract": "string",
            "CensusBlock": "string",
            "ForeignFlag": true,
            "HandlingCode": "string",
            "HandlingCodeOption": "StatementsNoticesChecks",
            "MSACode": 0
          },
          "Email": {
            "EmailIdent": "string",
            "EmailType": "string",
            "EmailAddr": "string",
            "PreferredEmail": true
          },
          "WebAddr": {
            "WebAddrIdent": 0,
            "WebAddrType": "string",
            "WebAddrLink": "string"
          }
        }
      ],
      "IssuedIdent": [
        {
          "IssuedIdentType": "string",
          "IssuedIdentTypeEnumDesc": "string",
          "IssuedIdentId": "string",
          "IssuedIdentValue": "3762849726",
          "Issuer": "string",
          "IssuerEnumDesc": "string",
          "IssueDt": "2021-01-31T23:59:59.999",
          "ExpDt": {}
        }
      ],**
      "OrgName": [
        {
          "NameType": "Primary",
          "NameIdent": "string",
          "Name": "string",
          "LegalName": "string",
          "NameFormat": "None"
        }
      ]
    }
  }
}

_Dev Portal Request Default:_
{
  "Status": {
    "Id": "string",
    "StatusCode": "string",
    "StatusDesc": "string",
    "Severity": "string",
    "SvcProviderName": "string",
    "ServerStatusCode": "string",
    "ServerStatusDesc": "string",
    "OvrdExceptionInd": true,
    "SubjectRole": "string",
    "SubjectElement": [
      {
        "Path": "string",
        "ServerPath": "string",
        "Value": "string"
      }
    ],
    "ContentHTML": "string",
    "AdditionalStatus": [
      {
        "StatusCode": "string",
        "StatusDesc": "string",
        "Severity": "string",
        "SvcProviderName": "string",
        "ServerStatusCode": "string",
        "ServerStatusDesc": "string",
        "OvrdExceptionInd": true,
        "SubjectElement": [
          {
            "Path": "string",
            "ServerPath": "string",
            "Value": "string"
          }
        ]
      }
    ]
  },
  "PartyStatusRec": {
    "PartyKeys": {
      "PartyId": "string"
    },
    "PartyStatus": {
      "PartyStatusCode": "string",
      "EffDt": "2021-01-31T23:59:59.999Z"
    }
  }
}

Thanks in advance for your help!

cc: @fiservakshay @bobburghardt

**Comment by tsegurajimen** [comment]
Hi Team,

After the fix pushed to Dev this morning we still missing some fields into each object that was called by an allOf key, please take a look of the sample below:

![image](https://user-images.githubusercontent.com/81706748/154756151-4f2b7130-c24c-42d4-bbc5-5b55ade87f5d.png)

In this particular case, **RecipientCountryCode** has an allOf: **CountryCodeType**, then **CountryCodeType** has following properties:

> CountryCodeSource
> CountryCodeValue
**> CountryCodeValueEnumDesc**

But just the last one is missing***

Please let us know if you need any additional detail.

Thanks in advance!

**Comment by tsegurajimen** [comment]
**Note**: Left side is our SwaggerHub default view and right side is DEV default view of PartyAdd API.
https://dev-developerstudio.fiserv.com/product/BankingHub/api/?type=post&path=/parties

**Comment by tsegurajimen** [comment]
Issue is now solved thanks a lot @TaniaSarkar89 code under allOf keys is displayed correctly again.
![image](https://user-images.githubusercontent.com/81706748/155814588-46ad492a-b6f7-45ba-9b76-a47a89864057.png)

**Comment by TaniaSarkar89** [comment]
Opening another JIRA ticket to address this issue: https://firstdatateam.atlassian.net/browse/PORT-3729

**Comment by tsegurajimen** [comment]
Issue was fixed in Dev, pending to be validated on the next release to PROD on March 31st.
![image](https://user-images.githubusercontent.com/81706748/159572968-1edc8d8b-a4a7-4196-ade2-91bef8eff522.png)
